### ISSUE TITLE
Fetch MarketCap historically

### ISSUE THREAD

**Issue by dvirginz** [ranaroussi/yfinance#1008]
Using the provided code we can fetch one of the following data points

1) The current MarketCap
2) Historical data of Open High Low Close and Volume

```
msft = yf.Ticker("MSFT")
msft.info['marketCap']
msft.history()
```

Can we somehow can historical information of the marketcap?

Thanks.

**Comment by ValueRaider** [comment]
Does Yahoo website provide this? yfinance is just an API wrapper

**Comment by ProgrammingDao** [comment]
The MarketCap history doesn't seem to be available on yahoo finance and if you wanted to build the MarketCap history from the history of the stock prices, you would also need the history of outstanding shares. You can maybe assume constant number of outstanding shares over a short recent period and multiply it by your stock price history to get your market cap numbers.

**Comment by dvirginz** [comment]
Yes, unfortunately, as you know, this is not a fair assumption

**Comment by ValueRaider** [comment]
I'm reopening this because I have a solution: branch `feature/share-count` will provide you a few years of high-fidelity share count (mix of daily/weekly). Combine with price for marketCap.

If you want to try now and give feedback, [this discussion](https://github.com/ranaroussi/yfinance/discussions/1080) explains how to download.

**Comment by ValueRaider** [comment]
`Ticker.get_shares_full()` is your friend.

**Comment by liuxj2016** [comment]
> `Ticker.get_shares_full()` is your friend

It seems that sometimes get_shares_full() give wrong results. For example, get_shares_full() outputs two different shares of MSFT on 20240501

**Comment by ValueRaider** [comment]
I don't understand the data oddities in that API call, I discovered it by accident.

**Comment by kcbsbo** [comment]
> > `Ticker.get_shares_full()` is your friend
> 
> It seems that sometimes get_shares_full() give wrong results. For example, get_shares_full() outputs two different shares of MSFT on 20240501

Yes, the data has a lot of noise. How are you handling this issue now?
