### ISSUE TITLE
Different result for same input depending on computer's timezone

### ISSUE THREAD

**Issue by fritzel56** [ranaroussi/yfinance#1010]
First, thank you for yfinance, really enjoy using it.

### Versions:
yfinance version == 0.1.70
python version == 3.7.3

### Issue Summary:
I've found an edge case where the data returned by `yfinance.download` will vary for a fixed input depending on the timezone of the machine running the code. I've only noticed this in one specific instance which is where a dividend was issued the day before the start date being passed in the download command.

#### Example:

Start date: `2021-09-01`
Dividend Issue Date: `2021-08-31`

#### Code to run:

```python
import yfinance as yf
yf.download('VLB.TO', start='2021-09-01', end='2021-09-03', actions=True)
```

#### Timezone determined by:

```python
import datetime
datetime.datetime.now().astimezone().tzinfo
```

#### Outputs:

Run the code on a machine with a timezone of Eastern Daylight Time. You get the expected result:

```
            Open 	High 	Low 	Close 	Adj Close 	Volume 	Dividends 	Stock Splits
Date 								
2021-09-01 	27.600000 	27.700001 	27.559999 	27.700001 	27.700001 	4600 	0 	0
2021-09-02 	27.670000 	27.700001 	27.639999 	27.700001 	27.700001 	2200 	0 	0
```

Run the code on a machine with a timezone of UTC, you get an extra row with partial data:

```
            Open 	High 	Low 	Close 	Adj Close 	Volume 	Dividends 	Stock Splits
Date
2021-08-31 NaN NaN NaN NaN NaN NaN 0.072 0
2021-09-01 	27.600000 	27.700001 	27.559999 	27.700001 	27.700001 	4600 	0 	0
2021-09-02 	27.670000 	27.700001 	27.639999 	27.700001 	27.700001 	2200 	0 	0
```

### Issue:

Results in two issues:
1. The first row returned when run on the UTC machine is from the day before the start day which can result in issues with the user's code.
2. The first row returned when run on the UTC machine is incomplete (the NaNs are misleading as there was stock traded that day) which can cause issues for the user's code.

I think ideally yfinance would return a consistent result for a consistent input. As it is, the end user can easily implement a cutoff themselves:

```python
start_date = '2021-09-01'
ex_df = yf.download('VLB.TO', start=start_date, end='2021-09-03', actions=True)
ex_df = ex_df.loc[ex_df.index >= start_date]
```

### Cause:

It seems the issue stems from [here](https://github.com/ranaroussi/yfinance/blob/fc0f97926ef6a960dc8e6649dc74d06c1840195b/yfinance/base.py#L123). Time uses the local timezone for the calculation. As a result, `2021-09-01 UTC` is being converted to `2021-08-31 20:00:00 Eastern Daylight Time`. It seems that this doesn't catch any of the market activity but does catch the dividend activity.

**Comment by ValueRaider** [comment]
This is easy to fix by using timezone of the relevant stock exchange.

Suppose though `start=datetime(2022, 1, 1, 12, 0)` - which timezone should that be? Not clear if user is looking at their own clock, or if means exchange timezone. I'm leaning towards using exchange tz again.

**Comment by ValueRaider** [comment]
I've pushed a fix to my fork: https://github.com/ValueRaider/yfinance/tree/fix/timezone

You'll have to play with `sys.path.insert` to load this over PIP. Give it a play.

**Comment by ValueRaider** [comment]
Fix now in PIP, solves issue.

**Comment by fritzel56** [comment]
Tested it today and it worked perfectly. Thanks again!
