### ISSUE TITLE
Quarterly data displayed is older if Tickers object used instead of Ticker object

### ISSUE THREAD

**Issue by hrpomrx** [ranaroussi/yfinance#1011]
Example AAWW:

As of today 5/31

Using yf.Tickers, the most recent quarterly balance sheet (using .quarterly_balancesheet) is 12/31/2021
.calendar shows Earnings Date as 2022-02-16 to 2022-02-21

Using yf.Ticker, the most recent quarterly balance sheet (using .quarterly_balancesheet) is 03/31/2022
.calendar shows Earnings Date as 2022-08-03 to 2022-08-08

**Comment by hrpomrx** [comment]
Update - it appears that even yf.Ticker does the same, randomly. Sometimes you get the latest quarter, sometimes not.

**Comment by ajgringo619** [comment]
Can you explain exactly what's required to review PRs? I have the time, just not sure if I have the necessary expertise.

**Comment by ValueRaider** [comment]
> Can you explain exactly what's required to review PRs? I have the time, just not sure if I have the necessary expertise.

https://github.com/yfinance-fork-team/yfinance/discussions/12#discussioncomment-3646693

**Comment by hrpomrx** [comment]
> @hrpomrx I'm asking around for volunteers to help maintain a replacement fork of yfinance, seeing as Ran has abandoned it. The core issue is only Ran can merge, so solution is a team of maintainers. Can you assist, even if only reviewing PRs?

I could probably assist from time to time on a limited basis. However I consider this package useful only for price data and not much else as Yahoo! is either behind on or limiting access to fundamental data. I’m not aware of any sites that would be good sources of freely-available reliable fundamental quarterly data other than maybe EDGAR which seems somewhat  convoluted to parse. Welcome to ideas though!

**Comment by ValueRaider** [comment]
That's fine, most changes I want are in pricing data (surprisingly lots of issues). I don't really use the fundamentals side.

If you really are interested, then give this a read: https://github.com/yfinance-fork-team/yfinance-x/discussions/12 . I'll send an invite.

**Comment by ajgringo619** [comment]
> > Can you explain exactly what's required to review PRs? I have the time, just not sure if I have the necessary expertise.
> 
> [yfinance-fork-team#12 (comment)](https://github.com/yfinance-fork-team/yfinance-x/discussions/12#discussioncomment-3646693)

This just might work. It will give me an actual reason to keep up my development VMs. Let me know when you're ready to roll this out.

Question, though - what about the Arch package? Will we need to create a new PKGBUILD in the AUR?

**Comment by ValueRaider** [comment]
@ajgringo619 I'm already rolling out, just starting slow with 2 PRs. If neither are relevant/interesting to you then maybe browse through [these issues](https://github.com/ranaroussi/yfinance/pulls) for one you like, probably most will be merged in eventually. Or start a Discussion.

Arch Linux - no we don't, I'll just contact that package owner and they can update script.

**Comment by ajgringo619** [comment]
I'm getting my feet wet as we speak. If nothing else, my knowledge of python should grow significantly.
