### ISSUE TITLE
Get earnings date historics

### ISSUE THREAD

**Issue by nono-london** [ranaroussi/yfinance#1013]
Hi, 
I couldn't find a way to access earnings date history for a given ticker.
It would be great if could be added to the library.
Data seem to be easyly accessible:

`
web_request = requests.get(url='https://finance.yahoo.com/calendar/earnings?symbol=TD.TO',headers=headers)

web_tables = pd.read_html( web_request.text)

print(web_tables[0])
`
Thanks!

**Comment by rickturner2001** [comment]
Hey @nono-london  there are many ways to get access to upcoming and previous earning dates. Check this out.

```
import yfinance as yf

ticker = yf.Ticker("MSFT")

# Upcoming earnings 
ticker.calendar.loc['Earnings Date']

# Previous earnings (quarterly)
ticker.get_earnings(freq="quarterly")

# Previous earnings (yearly)
ticker.get_earnings(freq="yearly")
```

I hope this helps!

**Comment by nono-london** [comment]
Rick Tx for your message. When I used quaterly, i seem to be receiving only the last year, the Yahoo dataset is much bigger in term of quarters history:
yfinance:
![image](https://user-images.githubusercontent.com/7720585/173204455-7c310767-c2dc-4395-be38-4b09c36aac66.png)
yahoo using requests and url above:
![image](https://user-images.githubusercontent.com/7720585/173204516-d6449e9f-b818-4e78-b2e3-3ab714cfe3ad.png)

I have created my own function, but seems like it could be easily added to the package.

**Comment by rickturner2001** [comment]
Yes, I totally agree with you. I sent a Pull request yesterday, let's see if they merge it. Nice catch!

https://github.com/ranaroussi/yfinance/pull/1014

**Comment by nono-london** [comment]
tx a lot

**Comment by ValueRaider** [comment]
You should add a class variable `TickerBase._earnings_history` for caching the table, as done with most other properties.

**Comment by ValueRaider** [comment]
Also I think you should make the EPS columns float type (currently they are str), and the 'Earnings Date' column should be date type (I can help with timezones if you get stuck).

**Comment by nono-london** [comment]
on my function i created a new function for date, as I wasn't sure if 'Earnings Date' was always coming in the same timezone -EST in my case but didn't test for german stocks for instance, but yeah agreed, would be great to have all in datetime UTC for instance. and relevant types for other columns

**Comment by nono-london** [comment]
actually just checked for Candian name (initial URL), and timezone varries EST/EDT, as well there are multiple pages to loop through, so slithly more complicated to implement properly

**Comment by ValueRaider** [comment]
I'm thinking ignore the timezone entirely and replace "AM/PM" with "pre/post", still in a new column.

**Comment by nono-london** [comment]
AM/PM doesn't necesarrily means PRE/POST, there is the actual time after, which is quite good to have if you look at minute/tick data. Also depending of timezone PM, could become AM.
So far I have only seen 2 different timezones: EST and EDT, and seen results only for Canada and USA. German tickers don't seem to get any results..

**Comment by ValueRaider** [comment]
Ah, I missed that. Having time solves decision then - datetime with timezone, one column. @rickturner2001 I recommend using ZoneInfo not tzinfo, Python has finally fixed it's timezone handling.

**Comment by ValueRaider** [comment]
Now the page issue. That is easy, just loop over 'offsets' and append/concat tables together:

```
        offset = 0
        size = 100 # YF will cap at 100, don't go higher
        df = None
        while True:
            url = "{}/calendar/earnings?symbol={}&offset={}&size={}".format(_ROOT_URL_, self.ticker, offset, size)
            offset += size
```

**Comment by rickturner2001** [comment]
@ValueRaider Great suggestions, thank you for pointing this issues out.

**Comment by rickturner2001** [comment]
@ValueRaider  I was able to convert both EPS columns to float and replaced "-" characters with nan. Would you please explain to me the nature of the while loop in the sippet above? Thanks a lot.

**Comment by nono-london** [comment]
@rickturner2001, @ValueRaider was just answering to my comment: purpose is to handle nulple pages, as he mentioned, yahoo provide results by pages/offets of 100 results, so hilw loop allow you to iterate through the pages. you will need to handle error on the last page/no more results available. best and tx

**Comment by ValueRaider** [comment]
I was just showing the url syntax to use. You can figure out the rest.

**Comment by nono-london** [comment]
Hi, @ValueRaider, tx very much.
I can't access the attribute: 'earning_dates' of Ticker, but I am not sure I am doing this right. 

In google colab i install your git as follow:
`!pip install git+https://github.com/ValueRaider/yfinance.git`

Then when running example on your link, once i get to:
`!pip install git+https://github.com/ValueRaider/yfinance.git`

I get this error message:
![image](https://user-images.githubusercontent.com/7720585/173958359-bcebd748-ffac-4a9c-b778-03e002e71978.png)

has the earnings_date bit pushed in github, or should i use another link to get access to that specific branch (I am not used to this part of github of development, so sorry in advance if anwser if obvious). best

**Comment by nono-london** [comment]
@ValueRaider , this looks great: timezones seem to be working perfectly on the names I tested and all data are being picked up.

Only thing would be to handle error when no data are available (mainly european/asian names i guess), could return None or an empty df with expected columns ("EPS Estimate",  "Reported EPS",  "Surprise(%)") and index "Earnings Date". Not sure what is the pattern you usually use for these.
As well, for the Surprise column, do you prefer (%) unit or 0.01 unit (ie divide by 100)?
Tx a lot
best

**Comment by ValueRaider** [comment]
Useful feedback, I've incorporated it all.

**Comment by ValueRaider** [comment]
@nono-london This is now in main branch and has filtered through to PIP, looks good!

@ranaroussi You can close this.

**Comment by nono-london** [comment]
I see you added future earnings dates/estimates which complete nicely the dataset!

I have noticed that for German stocks, there are now some data returned but there seem to be some duplicates (date, hours)
Not sure, how you got those, would be good to have only the last updated data per quarter/date, see results for VOW3 (VW Pref shares):
![image](https://user-images.githubusercontent.com/7720585/174121513-9555cdac-377b-4495-921d-a9e6e8789ba9.png)

Tx & best

**Comment by nono-london** [comment]
Hi @ValueRaider, seems like may not worth pushing further for the symbols that are partially handled by Yahoo.
I have noticed that there seem to be a duplicate function/attr "earnings_history" and "earnings_dates". The former seem to return the raw data from yahoo while the later handles dates/numbers etc.
Not sure that was done in purpose, so just in case.
best and tx for evrything

![image](https://user-images.githubusercontent.com/7720585/175048456-0eb68ed1-ff06-4e03-914f-670900575d25.png)

**Comment by ValueRaider** [comment]
That's a Q for @ranaroussi , not sure why he merged both PRs for this issue.

**Comment by nono-london** [comment]
@ValueRaider tx,
as well, just tried the following on PyCharm and was asked to pip install 

```
html5lib
bs4

```
not sure they are already part of the current requirements, I beleive  it is needed by pandas to read html tables):

code that triggered request:

```
import yfinance as yf

tickers = yf.Tickers('msft aapl goog')
print(tickers.tickers['MSFT'].earnings_dates)
```
Error is:

error in _parser_dispatch
![image](https://user-images.githubusercontent.com/7720585/175084628-0de349f9-6487-48f8-8f3e-3a27fea9a10f.png)

**Comment by ValueRaider** [comment]
`read_html` was already present in `yfinance`. E.g. try accessing anything in `Ticker.info[]`

**Comment by nono-london** [comment]
@ValueRaider, It may not be read_html then, but I've tried with a new env, and code above only works if I pip install manually  "html5lib" and "bs4", which do not seem to be install when you pip yfinance.

**Comment by ValueRaider** [comment]
What happens when you access info?

**Comment by nono-london** [comment]
access_info works but earnings_dates doesn't
that is on Pycharm, Python 3.7.9
