### ISSUE TITLE
Options not giving any result for Indian stocks

### ISSUE THREAD

**Issue by theNerd96** [ranaroussi/yfinance#1018]
```
import yfinance as yf

itc = yf.Ticker("ITC.NS")

print(itc.options)
```
It gives () as a result, tried with HDFCBANK.NS also but getting same result.

**Comment by ValueRaider** [comment]
yfinance only returns what Yahoo has: https://finance.yahoo.com/quote/ITC.NS/options?p=ITC.NS

Yahoo doesn't show options data for these tickers
