### ISSUE TITLE
Bulk download info

### ISSUE THREAD

**Issue by klar-C** [ranaroussi/yfinance#1020]
Hi - 

Is it possible to bulk download the info object for multiple tickers (with threads as in the yf.download function)?

Right now it seems that there is a delayed load each time I'm executing the info command - so loading the info of many tickers takes a long time.

import yfinance as yf
tickers = yf.Tickers('msft aapl goog')
tickers.tickers['AAPL'].info # takes 4 seconds
tickers.tickers['goog'].info # takes 4 seconds again

Any help would be appreciated.

**Comment by ValueRaider** [comment]
Use `session` to cache data, see README

**Comment by ValueRaider** [comment]
@klar-C If that solves your issue can you close this.

**Comment by klar-C** [comment]
Yes - solved. Thank you!
