### ISSUE TITLE
Futures index does not return Saturday and Sunday data

### ISSUE THREAD

**Issue by amichae2** [ranaroussi/yfinance#1021]
There are futures indexes that trade on Saturday and Sunday that are tracked by Yahoo Finance. These indexes are denoted with tickers such as:

ES=F is ^GSPC futures
RTY=F is Russell 2000 futures
MNQ=F is NASDAQ futures

The yfinance package does not return the Saturday and Sunday values for these kinds of tickers. I've been looking for where in the yfinance code the Saturday and Sunday values are dropped but I can't find it. Perhaps the data is not returned in the first place.

**Comment by ValueRaider** [comment]
Maybe Yahoo simply isn't returning the data? Easy to check, just edit code to print out the data that yfinance receives.

**Comment by amichae2** [comment]
I did. It's not returning it. I am trying to figure out where the data is stored on the yahoo finance web page because it is showing on the actual web page accessed through a web browser. I could be wrong about this though. I would say my programming skills are between novice and intermediate.

**Comment by ValueRaider** [comment]
Try different intervals

**Comment by ValueRaider** [comment]
1h interval returns Sunday data.

Please show screenshot or url to Yahoo showing Sunday daily data because I don't see it.

**Comment by amichae2** [comment]
I figured it out. The dates being returned are off. For instance; 5/19/22 (Thursday) is being recorded in the day 5/20/22 (Friday). So Sunday is being recorded as Monday in the dataframe.

**Comment by ValueRaider** [comment]
Ah, timezones. I think I've fixed that but need a guinea pig to test it. Can you volunteer?
Grab my fork: https://github.com/ValueRaider/yfinance/tree/fix/timezone
And load like:
```
import sys
sys.path.insert(0,"path/to/my/yfinance")
...
```

**Comment by amichae2** [comment]
Okay, one sec

**Comment by amichae2** [comment]
Maybe yahoo has code that is fixing this bug on the user side instead of the server side because this would only happen for a few securities

**Comment by ValueRaider** [comment]
I'm getting a match between Yahoo and yfinance for May 23rd. Are you sure you're loading the fork?

**Comment by amichae2** [comment]
I used pip install git+https://github.com/ValueRaider/yfinance.git#egg=yfinance to install it, I believe this is correct. I will try installing it under a different name to make sure it isn't using a cached version

**Comment by amichae2** [comment]
Oh, sorry about that, thank you for being patient, one sec

**Comment by amichae2** [comment]
I am still getting the original repo when I go to the link. What is the .git link for the new repo?

**Comment by ValueRaider** [comment]
*sigh*

The fix is in a **branch** in my fork. The url goes direct to it, you can't miss it.

**Comment by amichae2** [comment]
I'm on this page: https://github.com/ValueRaider/yfinance/tree/fix/timezone and I go to the drop down menu named code and get the .git link https://github.com/ValueRaider/yfinance.git but that isn't the correct link.

**Comment by ValueRaider** [comment]
Yes it is. You download the repository, then switch to the branch.

**Comment by amichae2** [comment]
Its not working for me. I am still getting the 20th and 23rd instead of the 19th and 22nd.

**Comment by ValueRaider** [comment]
I need to be convinced that you are loading my branch. Run this:

```
...
import yfinance as yf
if "site-packages" in yf.__path__[0]:
	print("Not loading forked repository, but: "+yf.__path__[0])
	quit()

import os
f = open(os.path.join(yf.__path__[0], "base.py"), 'r').read().find("cache_lookup_tkr_tz")
if f == -1:
	print("Not loading my fork")

df = yf.Ticker("ES=F").history(start="2022-05-19",end="2022-05-20", interval="1d")
print(df[["Close"]]) # If date doesn't have time then not my branch
```

**Comment by ValueRaider** [comment]
Yahoo doesn't have weekend data.
