### ISSUE TITLE
Did yahoo stop carrying historic earnings

### ISSUE THREAD

**Issue by deadlyisking** [ranaroussi/yfinance#1025]
Noticed historic earnings no longer updates eps/reported past mid last year. WUI looks the same so assuming they no longer update...?

**Comment by ValueRaider** [comment]
WUI doesn't exist anymore, it got acquired.

**Comment by ValueRaider** [comment]
@ranaroussi Can close this

**Comment by deadlyisking** [comment]
Thanks. Free data so I'll work with what I have. Excellent library.
