### ISSUE TITLE
earnings_dates

### ISSUE THREAD

**Issue by shamit0228** [ranaroussi/yfinance#1027]
*** READ BEFORE POSTING ***

earnings_dates don't seem to work when I try from PyCharm IDE. Please see attached image for code and log
![2022-07-09_21-37-04](https://user-images.githubusercontent.com/109007654/178128073-06082909-bebd-493c-8c08-f061edd62b7b.jpg)
.

**Comment by ajgringo619** [comment]
OK, I tried this on my **EndeavourOS** (Linux) system and **Windows 10** system, both running Pycharm 2022.1.3, python 3.10.5, yfinance version 0.1.72. Both work as expected, so I'd bet that it's the older **yfinance** module that's to blame.

**Comment by ValueRaider** [comment]
It's a new feature so you need latest version 1.7.2
