### ISSUE TITLE
regularMarketPrice does not change

### ISSUE THREAD

**Issue by Cmdrd** [ranaroussi/yfinance#1034]
Having an issue where when I query any ticker, I seem to get a cached response for regularMarketPrice, or for any info associated with a ticker. Only for brief instances do I get up to date data, but the vast majority of the time I get stale data. Is there some sort of request limit or something that I may be hitting that could be resulting in this?

Have updated to the latest version 0.1.74.

**Comment by Cmdrd** [comment]
I'm trying with re-initializing the object as well as using a new object and it doesn't seem to be resolving the issue.

**Comment by Cmdrd** [comment]
Even running on different systems is showing the exact same values. Pulling the SPY ticker on 3 different systems for example has been outputting 378.83 all day.

**Comment by ValueRaider** [comment]
Post code that reproduces the bug. Might be an error in your code.

**Comment by Cmdrd** [comment]
` import yfinance as yf
spy_ticker = yf.Ticker('SPY')
print(spy_ticker.info['regularMarketPrice']`

I have other systems running more complex queries but this is all that I'm using to validate across systems right now.

**Comment by Cmdrd** [comment]
Looks like the close for July 13 was 378.83. Problem was that it was working fine yesterday and for about a half hour period from 10:00-10:30 EST. but other than that today it's been stuck at that value. Is there any sort of debugging I can do on the yfinance module to see what may be happening?

**Comment by ValueRaider** [comment]
Debug? I normally just edit the code directly. 2 options:
- edit code where PIP installs
- git clone and use `sys.path.insert` to override PIP

**Comment by Cmdrd** [comment]
Was more about increase logging verbosity of the package, but I'll give that a go and try to figure out why it's stuck pulling market data from after-hours July 13. Thanks!

**Comment by Cmdrd** [comment]
Started randomly working properly again. Going to keep tabs on this but I have a suspicion that Yahoo finance is doing some sort of cached data return. There's no bug that I'm finding in yfinance, but after going through and debugging the request and going through the entire path of receiving data, the data that Yahoo Finance is returning is in fact this old data. Let me know if there is any more information that I can provide, otherwise if this keeps happening I may have to use another solution to fetch this data.

**Comment by ValueRaider** [comment]
Are you accessing `info` many times, both in absolute terms and relative to other attributes e.g. price history? Maybe Yahoo caches in this situation.

**Comment by Cmdrd** [comment]
That definitely could be it. I'm going to cut down on these requests a lot here and see if that resolves it. Would make sense if that is the issue. Does requesting a specific attribute such as `regularMarketPrice` have the same request impact that a general `info` request does? If so that could be causing it and I will rework my code to reuse data better to cut down on requests.

**Comment by ValueRaider** [comment]
`info` is simply a dict. Filled on the first access, but never updated (have to create new Ticker object for "update").

If you're after latest price you shouldn't be using `info` at all, use `history`/`download` instead. `info` is best for balance sheet etc.
