### ISSUE TITLE
Discrepancy Between yf.download & yf.Ticker().history()

### ISSUE THREAD

**Issue by keg5038** [ranaroussi/yfinance#1036]
I am looking at Wheat Futures data (ticker=ZWZ22.CBT) & getting a discrepancy when running the following:

`yf.Ticker("ZWZ22.CBT").history(interval="1d",period="10d").tail(30)`

Returns data including today's trading day 2022-07-18.

Comparing this to: 
`yf.download('ZWZ22.CBT')
`
Which doesn't include 2022-07-18. The last day is 2022-07-15.

Why is there this discrepancy?

**Comment by ValueRaider** [comment]
`yfinance` doesn't handle timezones well, so often returned data is off by one day. Except when `period` is specified, then Yahoo handles the timezones.

I have a branch that should fix this but needs volunteers to test before I merge. See https://github.com/ranaroussi/yfinance/issues/954#issuecomment-1182558587

**Comment by ValueRaider** [comment]
Click the link.

**Comment by ValueRaider** [comment]
This should be solved in recent releases.
