### ISSUE TITLE
yf.download giving error

### ISSUE THREAD

**Issue by dinabhagat** [ranaroussi/yfinance#1039]
yf.download(tickers='TSLA', period="1h", interval="1m")['Close'] is giving below error in one Azure region and does not work in East us2 region.

1 Failed download:
- TSLA: No data found for this date range, symbol may be delisted

**Comment by ValueRaider** [comment]
If you execute at different time of day does it succeed?

**Comment by ValueRaider** [comment]
Were you running a LOT of calls and maybe triggered Yahoo spam limiting? Does the code work now?
