### ISSUE TITLE
yf.download hangs when no data returned for valid ticker

### ISSUE THREAD

**Issue by bma-diy** [ranaroussi/yfinance#1047]
I am downloading QQQ data every 20-45 seconds (variation is due to a rate limit I set) during market hours using the function: 

`yf.download(tickers=['QQQ'],period='3d',interval='1d')`

I average about 800-1300 API calls throughout the market day. I have an issue where about once a day, the download hangs. It can hang for as short as 20 minutes, or as long several hours.

The issue occurs when yf.download can't seem to find the data for the ticker symbol even though I inputted a valid Ticker. It's a rare situation but unfortunately can't be recreated using an invalid ticker. Using an invalid ticker does not produce a hang, only a valid ticker when no data is returned causes the script to hang. 

This is the error I get:

```
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- QQQ: No data found for this date range, symbol may be delisted
```
This seems to occur in less than 1% of API calls, the problem is, when it happens, it causes a very long hang.

**My ask is**: Is there a way to add a timeout so that if a valid ticker glitches and returns no data it times out quickly and moves on?

**Comment by ValueRaider** [comment]
What happens if you use `yf.Ticker("QQQ").history()` instead? Might solve the hanging problem, and instead fail immediately (because you're probably triggering Yahoo spam limiting)

**Comment by bma-diy** [comment]
Thanks, I'll try yf.Ticker and see if there are any improvements.

**Comment by bma-diy** [comment]
It looks like switching to yf.Ticker is better. I hit a hang where it could not find QQQ data and it timed out within a minute and continued on.

**Comment by ValueRaider** [comment]
Hi again. I noticed your timeout question - yes there is a way, use the `timeout=<seconds>` argument. Also recent releases should have solved the original hang problem.

Let me know current status of issue.

**Comment by tvaknin** [comment]
I have the recent release, still got the hang problem when using yf.download. I cannot use Ticker as I need many tickers. 
I will try to add timeout and update.
