### ISSUE TITLE
earnings_dates timezone issue

### ISSUE THREAD

**Issue by tylercap17** [ranaroussi/yfinance#1053]
When calling earnings_dates for a UK-listed stock, I am shown the below timezone error.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/81055821/185829382-bbc9707b-b42c-4600-869f-ff4a2499207d.png">

**Comment by ValueRaider** [comment]
What's the ticker?

**Comment by ValueRaider** [comment]
Those tickers are not listed in Yahoo.

**Comment by tylercap17** [comment]
Oh I see. I guess the tickers are RQIH.L and HUW.L. I will need to try if those work. This is not an issue then, but perhaps a different error message would be helpful if the ticker is wrong. Thanks again.
