### ISSUE TITLE
Problems with getting news data

### ISSUE THREAD

**Issue by ming-afk** [ranaroussi/yfinance#1054]
Hello yfinance community, 

Thanks for checking. Rather than an issue, my post is more like a consultation. First of all, thank you for bringing us yfinance to analyze financial data. It is been used heavily in my team to extract stock data and perform asset allocation.

Recently, we started a task on analyzing stock-specific news sentiments, which requires us to get news articles from Yahoo Finance. We noticed that the yahoofinance api consistently returns **8 news articles** by investigating the **Ticker().get_news()** method. However, we have no idea based on **what criteria** were the 8 articles retrieve. This is important to us as by manually checking these articles, we find some news are very relevant, while others only touch on the ticker we are looking at. 

If this is out of the scope of this community, could you point me to some resources where I can learn about the implementation or behaviors of the yahoofinance api? Thank you

**Comment by ValueRaider** [comment]
This appears to be the original PR, give it a read: https://github.com/ranaroussi/yfinance/issues/837

You may have to get someone on team to experiment with query URL parameters then submit a fix/improvement.

**Comment by ming-afk** [comment]
Hello @ValueRaider . Thanks for the reply. But I'm actually wondering how does yfinance api give the relevant news, not how the crawler in yfinance process the query. I know this is not related to what yfinance is doing, that's also why I asked if there are other resources I can look to. Tks

**Comment by ValueRaider** [comment]
That link describes the parameters available on the API. yfinance does not crawl nor process. `get_news` is basically just a web request.

No official Yahoo API documentation unfortunately, everything in yfinance was coded by reverse-engineering website - clicking buttons, intercepting requests, experimenting with parameters.

**Comment by ming-afk** [comment]
I see. Well thank you so much. These information are valuable. I indeed learned something from this.

**Comment by ValueRaider** [comment]
Next time inspect the source code first.
