### ISSUE TITLE
Is there a way to get more than the last 4 quarterly financial data?

### ISSUE THREAD

**Issue by HoneyJamFinance** [ranaroussi/yfinance#1055]
First of all, thank you for the amazing package. Yfinance is just amazing 👍 

The most beautiful thing about coding, imo, is automation and yfinance is absolutely amazing for that purpose. However, for some data, like quarterly financial data or yearly financial, I could only get up to the last 4 quarters or years. If I could get all the available financial data, it would be really convenient to conduct any financial analysis just with yfinance package.

If this feature is already available, please let me know how and if you know any other alternative please share it with me too.

Thanks

**Comment by ValueRaider** [comment]
Where does Yahoo website have more than 4 periods?

**Comment by sooheon** [comment]
Looks like #776 has been merged, but still seeing 4 quarters -- how can I see the 5th?
