### ISSUE TITLE
Why use print instead of log?

### ISSUE THREAD

**Issue by patrick-solving-problems** [ranaroussi/yfinance#1059]
This is not a bug. But we use yfinance in our project and I'd like to configure the logging outcome printed to my console.
If everything was done with logging instead of print, I could change the log level.

So do you mind if I create a PR to use log instead of print?
Or is there a good reason to go with print?

**Comment by ValueRaider** [comment]
Good idea, but good luck getting the PR merged in, Ran has effectively abandoned this project.

I'm a heavy user too (see the PRs), what do you think about setting up a fork together?

**Comment by patrick-solving-problems** [comment]
I would be interested. But I don't know if I have the time and the knowledge to do a good job maintaining such a project.

**Comment by ValueRaider** [comment]
Patrick, a lot has changed since my last comment. I can merge PRs and Ran is pushing to PIP, so you can go ahead with your idea.
