### ISSUE TITLE
Regarding recommendation stock that are strong buy

### ISSUE THREAD

**Issue by bpkapkar** [ranaroussi/yfinance#1060]
Hello, 

Is there any possibility to get the list of stocks that are strong buy with any of the function for NSE(India) stock instead of iterating each stock and finding its recommendation. Is there any optimize way to do so as it take huge time to process and get output.

Example code:

nifty_500=["3MINDIA","ABB","POWERINDIA","ACC","AIAENG","APLAPOLLO","AUBANK","AARTIDRUGS","AARTIIND"]  # example stock name 
recommendation_Key=[]
for i in nifty_500:
    try:
        stock = yf.Ticker(i+".NS")
        recommendation_Key.append(stock.info["recommendationKey"])
        print(f'{i} recommendationKey {stock.info["recommendationKey"]}')
    except:
            pass 

![image](https://user-images.githubusercontent.com/49440262/190009411-af6ba630-a746-463e-b73e-f155728a721c.png)

**Comment by ValueRaider** [comment]
I have a PR pending that speedups `info` access - https://github.com/ranaroussi/yfinance/pull/1048

But as you may have noticed, there are a lot of PRs waiting for Ran to merge, so looks like Ran has abandoned project. And no one else can merge. To solve, I'm setting up a fork with multiple collaborators, are you interested in joining?

**Comment by bpkapkar** [comment]
Thanks for replying. I have checked yfinance-cache repo, I could not see the things that have raised concern about it . I could see some merges and commits has happened to this project by ran, So I am not sure whether Ran has abandoned project. Yeah if something great we can do and contribute to community, I can review and check. Let me know how we can collaborate.

**Comment by bpkapkar** [comment]
I have closed by mistake ,reopening it.

Thanks for replying. I have checked yfinance-cache repo, I could not see the things that have raised concern about it . I could see some merges and commits has happened to this project by ran, So I am not sure whether Ran has abandoned project. Yeah if something great we can do and contribute to community, I can review and check. Let me know how we can collaborate.

**Comment by ValueRaider** [comment]
I never referenced yfinance-cache so don't understand why you checked it. I said check the README.

**Comment by bpkapkar** [comment]
Actually there was comment regarding yfinance caching  so thought you are referring that, I have checked readme as well. but couldn't even see the things that have raised concern about it. So what could be things and thought to get faster responses. Anything you have in mind.

**Comment by bpkapkar** [comment]
I have closed by mistake ,reopening it.

**Comment by ValueRaider** [comment]
Ctrl+F "session"

**Comment by bpkapkar** [comment]
Thanks for help. I went deeper into modules , by using utils directly I could get the data that I want faster. Below is the code that I have used it get desired value.
Example:
stock_name="TCS"
url= f"https://finance.yahoo.com/quote/{stock_name}.NS"
        stock = yf.utils.get_json(url,None, None)
        stock["financialData"]["recommendationKey"]
