### ISSUE TITLE
yfinance info logo_url value problem

### ISSUE THREAD

**Issue by Hcevahir34** [ranaroussi/yfinance#1062]
Hi,

I try to get logos from yfinance but while ticker is 'ARCLK.IS',  logo_url value is empty.

I hope someone get update 'logo_url' value with 'https://logo.clearbit.com/arcelik.com.tr'

Thanks for helps,

code:

ticker = yf.Ticker('ARCLK.IS')
inf = ticker.info
print(inf)

output:

logo_url': ''

**Comment by Jossan84** [comment]
Hi. Today I made a pull request, that I think fix this problem

**Comment by ValueRaider** [comment]
Thanks Jossan, this will go out in next release.
