### ISSUE TITLE
yfinance download(...) function returns either pandas Series or DataFrame

### ISSUE THREAD

**Issue by AndreiKeino** [ranaroussi/yfinance#1063]
...

**Comment by ValueRaider** [comment]
download() is actually returning a Dataframe in both cases. You are then accessing a single column 'Close', you are creating the problem.

**Comment by AndreiKeino** [comment]
Thank you, but I mean that I've told. I though It should be clear from the code. In first case  yf.download(tickers)['Close'] is Dataframe, in the second case - Series. So, there is no uniform access to Close/High/Low/Adj Close/Volume data.

**Comment by ValueRaider** [comment]
Your entitled attitude is not helping. yfinance is OSS - you have not paid for it, and no one is being paid to contribute. You are free to contribute.

**Comment by AndreiKeino** [comment]
I don't think your attitude is better than mine. Thank you for reply anyway.

**Comment by AndreiKeino** [comment]
Thank you very much for your support)

**Comment by AndreiKeino** [comment]
As I see, there is no support on this issue. I close it.
