### ISSUE TITLE
same query, different results

### ISSUE THREAD

**Issue by mreous714** [ranaroussi/yfinance#1065]
Hi ranaroussi,

Firstly, thanks for yfinance. It's been helpful in the past.

I noticed an interesting bug today. Running the same query (below) in two different instances produced differing values. They were run simultaneously on colab notebooks.

_yf.Ticker('AMZN').info.get('marketCap')_

yields...

- Notebook A: 63221071872
- Notebook B: 1269986230272 (correct)

Notebook A is calling the data as part of a list of tickers whereas B is just 'AMZN'.  In Notebook A, I double-checked the code and ran the query just for 'AMZN' (as above) and kept pulling 63221071872.

Any ideas what's going wrong here?

Thanks

**Comment by ValueRaider** [comment]
Is marketCap the only difference in info? If there's a *lot* of differences then indicates Yahoo returned bad data.

**Comment by mreous714** [comment]
good point. here's a list of the differences when pulling .info

There are 84 fields of the 158 that are different

|index|a|b|
|---|---|---|
|targetLowPrice|104|110|
|targetMedianPrice|170|172|
|earningsGrowth|||
|numberOfAnalystOpinions|51|48|
|targetMeanPrice|169\.37|171\.18|
|recommendationMean|1\.8|1\.7|
|isEsgPopulated|true|false|
|underlyingSymbol||NaN|
|underlyingExchangeSymbol||NaN|
|headSymbol||NaN|
|uuid|261fd26b-0151-3813-b0d0-97e4ed4c6505|NaN|
|annualHoldingsTurnover|||
|enterpriseToRevenue|3\.029|2\.761|
|beta3Year|||
|enterpriseToEbitda|27\.968|25\.497|
|52WeekChange||-0\.27699292|
|morningStarRiskRating|||
|forwardEps|70\.96|2\.31|
|revenueQuarterlyGrowth|||
|sharesOutstanding|507148000|10187599872|
|fundInceptionDate|||
|annualReportExpenseRatio|||
|totalAssets|||
|bookValue|205|12\.904|
|sharesShort|81630928|71375116|
|sharesPercentSharesOut|0\.008|0\.0069999998|
|fundFamily|||
|heldPercentInstitutions|0\.60442|0\.59828997|
|trailingEps|52\.562|1\.09|
|lastDividendValue|||
|SandP52WeekChange||-0\.122783005|
|priceToBook|0\.5960488|9\.469157|
|heldPercentInsiders|0\.09864|0\.09859|
|yield|||
|shortRatio|1\.18|1\.4|
|sharesShortPreviousMonthDate|1655251200|1659052800|
|floatShares|9171244349|9172874358|
|beta|1\.246487|1\.3332|
|enterpriseValue|1471660556288|1341667278848|
|threeYearAverageReturn|||
|lastSplitDate|936230400|1654473600|
|lastSplitFactor|2:1|20:1|
|legalType|||
|morningStarOverallRating|||
|earningsQuarterlyGrowth|||
|priceToSalesTrailing12Months|0\.12753275|2\.5618806|
|dateShortInterest|1657843200|1661904000|
|pegRatio|7\.17|34\.08|
|ytdReturn|||
|forwardPE|1\.7219561|52\.896107|
|lastCapGain|||
|shortPercentOfFloat|0\.0092|0\.008|
|sharesShortPriorMonth|112243921|67798677|
|category|||
|fiveYearAverageReturn|||
|trailingAnnualDividendYield||0|
|volume24Hr|||
|navPrice|||
|trailingAnnualDividendRate||0|
|expireDate|||
|algorithm|||
|dividendRate|||
|exDividendDate|||
|circulatingSupply|||
|startDate|||
|trailingPE|2\.3246832|112\.100914|
|regularMarketVolume|47645938|47543613|
|lastMarket|||
|maxSupply|||
|openInterest|||
|marketCap|61968416768|1244822896640|
|volumeAllCurrencies|||
|strikePrice|||
|askSize|1000|800|
|volume|47645938|47543613|
|fromCurrency|||
|fiveYearAvgDividendYield|||
|dividendYield|||
|bidSize|900|1200|
|lastDividendDate|NaN||
|impliedSharesOutstanding|NaN|0|
|toCurrency|NaN||
|coinMarketCapLink|NaN||
|trailingPegRatio|NaN|4\.9641|

**Comment by ValueRaider** [comment]
colab must be caching the bad data, can you clear it?

**Comment by mreous714** [comment]
re-ran it today, still bogus data in notebook A.

Is it a thing for yahoo to spam bad data to clients?

**Comment by ValueRaider** [comment]
Only time I've encountered this is when I am spamming Yahoo (looping over many tickers). But after some time AFK a repeat query returns good data. So it is odd for you to still be getting bad data, unless your notebook is spamming.

Are you spamming?

**Comment by mreous714** [comment]
I don't believe I am spamming. I am running through a list of the same 30 tickers each time I test notebook A. I'll give your suggestion a shot though. Thanks!

**Comment by ValueRaider** [comment]
Actually, before you use that code can you try using latest main instead? It has optimised `info` creation, might help. Instructions: https://github.com/yfinance-fork-team/yfinance-x/discussions/14

**Comment by ValueRaider** [comment]
Since my last response those fixes have been pushed into PIP. Can you try latest release?

**Comment by eabase** [comment]
@mreous714 Please provide a working code snippet we can use to reproduce your issue.

**Comment by mreous714** [comment]
stepped away from this project for a bit due to the issues I have been having. tried again today and same issue.

table=pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')

df = table[0]
stocks=list(df.loc[:100,'Symbol'])
stocks.sort()

universe_data = dict.fromkeys(stocks)

shares_keys = ['sharesOutstanding','floatShares','marketCap','regularMarketPreviousClose','regularMarketVolume']

for x in stocks:
  temp_stock = yf.Ticker(x)
  shares_val=[temp_stock.info.get(key) for key in shares_keys]
  
  universe_data[x] = dict(list(zip(shares_keys,shares_val)))


universe_data['AMZN']
yf.Ticker('AMZN').info.get('sharesOutstanding')

**Comment by mreous714** [comment]
I should add I pip installed the latest yfinance version via colabs

_Successfully installed requests-2.28.1 yfinance-0.1.89_

**Comment by ValueRaider** [comment]
Yahoo does not like many requests for `info[]`, a loop of 100 will trigger them. I don't know why they return bad data instead of just blocking you (temporarily).

Try a combination of `Ticker.history()` and `Ticker.shares`. If that helps, then try experimental `Ticker.shares_full()` for up-to-date share count (see #1133).
