### ISSUE TITLE
How to get latest today prices although stock market is closed?

### ISSUE THREAD

**Issue by Originn** [ranaroussi/yfinance#1073]
I want to exctract the latest stock price of current day although the stock market is closed, but my code extract the previous day prices instead.

My code is 

```
import pandas_datareader.data as web

new_row = web.get_data_yahoo(tickers=ticker, period='1m')
```

output

```
new_row
                   Open         High          Low        Close    Adj Close     Volume
Date
2022-10-03  138.2100067  143.0700073  137.6900024  142.4499969  142.4499969  114169700

```

**Comment by Originn** [comment]
Hey,

This will still give me 2022-10-03 as the last date. i'll need to get 2022-10-04 even if it's the same price as 2022-10-03 as US stock market is not yet open

**Comment by aaronteamAAR** [comment]
hi @aliencaocao  can do this when specifying the datetime for start and end  respectively ->" 2022-10-19 14:42:41 and  2022-10-19 14:52:41"

**Comment by aliencaocao** [comment]
So why did the suggestion above not work for him?

> def market_data (ticker:str):
> data = yf.download(tickers=ticker, start='2022-01-01', end='2022-10-05', interval='1d')
> return data
