### ISSUE TITLE
For daily quotes yf.download does not include the last day

### ISSUE THREAD

**Issue by cngmid** [ranaroussi/yfinance#1077]
Version 0.1.75 is addressing the issue #184. Thanks for that!

The fix is based on the a new function `utils._parse_user_dt(dt, exchange_tz)`. If the date doesn't include any time information, the function defaults it to `'00:00:00'`. 

In this case however, Yahoo does not provide any data during the day including the close. For example:
```
start = '2019-01-14'
end = '2019-01-16'
yf.download('SPY', start, end, interval='1d')
```
**is missing the close on `'2019-01-16'`**.

May I suggest to default the time to `'23:59:59'`? This would fix that issue.

As an additional suggestion, it would be great for `yf.download()` to support dates given in string format **with or without time and time zone information**. this would just require to modify the above function to something like:
```
def _parse_user_dt(dt, exchange_tz):
    if isinstance(dt, int):
        ## Should already be epoch, test with conversion:
        _datetime.datetime.fromtimestamp(dt)
    else:
        # Convert str/date -> datetime, set tzinfo=exchange, get timestamp:
        if isinstance(dt, str):
            # try a simple date
            try:
                # default the time to '23:59:59'
                dt = _datetime.datetime.strptime(dt, '%Y-%m-%d')
                dt = _datetime.datetime.combine(dt, _datetime.time(23, 59, 59))
            except ValueError:
                # try the ISO format '%Y-%m-%dT%H:%M:%S%Z'
                try:
                    dt = _datetime.datetime.fromisoformat(dt)
                except ValueError:
                    # try a common non ISO format
                    try:
                        dt = _datetime.datetime.strptime(dt, '%Y-%m-%d %H:%M:%S%Z')
                    except ValueError:
                        # try a common format with no timezone info
                        try:
                            dt = _datetime.datetime.strptime(dt, '%Y-%m-%d %H:%M:%S')
                        except ValueError as e:
                            # give up
                            raise ValueError(e)
        if isinstance(dt, _datetime.date) and not isinstance(dt, _datetime.datetime):
            # default the time to '23:59:59'
            dt = _datetime.datetime.combine(dt, _datetime.time(23, 59, 59))
        if isinstance(dt, _datetime.datetime) and dt.tzinfo is None:
            # Assume user is referring to exchange's timezone
            dt = _tz.timezone(exchange_tz).localize(dt)
        dt = int(dt.timestamp())
    return dt
```

**Comment by ValueRaider** [comment]
This is really about the meaning of `end` argument. There are two interpretations:
1. Stop as soon as clock hits the end date
2. Stop until clock no longer shows end date (so one more day)

You're assuming 2 but 1 makes more sense for [several good reasons](https://stackoverflow.com/a/9810359). Same reason that Python code `list[0:3]` doesn't include `list[3]`.

**Comment by cngmid** [comment]
You are right. This indeed makes sense.
