### ISSUE TITLE
EBIT wrongly returns Opreating Income for (quaterly) financials

### ISSUE THREAD

**Issue by aliencaocao** [ranaroussi/yfinance#1079]
```
import yfinance as yf
msft = yf.Ticker('msft')
msft.financials.iloc[:, 0]
```
Under 'Ebit', the value is wrong. In fact, it seems to be returning Opreating Income instead. Same issue for both quarterly and yearly.

Running latest 0.1.77, same issue exist in 0.1.75 which means is a long-term bug. Tested with INTC as well.

https://finance.yahoo.com/quote/MSFT/financials?p=MSFT

**Comment by ValueRaider** [comment]
Have you searched through existing issues? It likely already exists

**Comment by aliencaocao** [comment]
Yes, found 7 open issues, none had a proper solution, its all workarounds. I already have a workaround, but I would still like to report this because this is clearly a bug with the library.

**Comment by ValueRaider** [comment]
We haven't forgotten about those 7 issues, so please don't duplicate. Just comment on those threads.
