### ISSUE TITLE
Issues with Date field

### ISSUE THREAD

**Issue by nexbelgium** [ranaroussi/yfinance#1085]
This issue appeared in version 0.1.77. I did no other package or python version updates since then.

Following script used to work on the date field:
`df[df.Date > '2020-01-01']`

But I am now getting following error message: TypeError: '>' not supported between instances of 'Timestamp' and 'str'

When I solve that issue by converting the string to a date (pd.to_datetime), I am getting other issues like: ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True

Somewhat further in my script, there is a pd.merge function based on the Date field received from yfinance. It gives now following error: Cannot compare between dtype('<M8[ns]') and dtype('0')

So I guess something has changed with how the dates are passed through. If yes, do you know how I can strip the received date from all these tz related stuff and just use it as a datetime64? I tried things like .dt.normalize() or .dt.date, but it always seems to give errors.

**Comment by ValueRaider** [comment]
Use `df.index`

Btw I can't reproduce your error message exactly so you're doing more than described.

**Comment by nexbelgium** [comment]
Thanks

I have a jupyter notebook where I run my script, and there I have no issue. But when I run the same script in the CLI, I get these error messages.

I will try to find a solution with your idea

**Comment by nexbelgium** [comment]
Ok I should have read the changelog, my bad.

To understand it better, I now get multiple rows per date when using yf.download(), is that how it should work now?
How can I manage to only get one row per date?

**Comment by ValueRaider** [comment]
Please provide actual code we can run to reproduce error.

**Comment by ValueRaider** [comment]
It depends on your code. Hour/minute data obviously returns multiple rows per day.

You need to provide actual code we can run to reproduce error.

**Comment by nexbelgium** [comment]
For example 
`df = yf.download(['VWCE.F','SOLB.BR','AAPL'], period='1y', threads=False)  
print(df['Close'])`

Before 0.1.75, I got 1 row per date. Now I get multiple rows (I understand that's because of the timezones). 

What would be the method to get only 1 row per date?

**Comment by ValueRaider** [comment]
That would be a bug.

**Comment by nexbelgium** [comment]
After downloading, I create some extra columns to plot some graphs on the data. As I used to get one row per date, it was easy. I wonder how other people use it as nobody seem to raise that issue. 

If it's not seen as a bug, I'll write some extra code to group by date.

**Comment by ValueRaider** [comment]
I think adding a `ignore_tz` argument is best and easy.

**Comment by nexbelgium** [comment]
Yes indeed, thanks

**Comment by ValueRaider** [comment]
Try latest release. If solved close issue.

**Comment by nexbelgium** [comment]
Yes, it works perfectly. Thanks for the quick reaction!
