### ISSUE TITLE
Run am IF statement on ticker.history()  

### ISSUE THREAD

**Issue by aaronteamAAR** [ranaroussi/yfinance#1088]
**THIS IS NOT A BUG**
Please how do I run an IF statement on the return result in the picture below, i need it for work purposes. And also how do i remove the datetime
![Screenshot 2022-10-16 080209](https://user-images.githubusercontent.com/69767247/196022929-eb172015-62cd-4077-9804-df0a9a8ca8ba.png)

**Comment by ValueRaider** [comment]
This is a Pandas question, not yfinance.
