### ISSUE TITLE
Adjusted prices

### ISSUE THREAD

**Issue by nateGeorge** [ranaroussi/yfinance#109]
Just noticed the 'Adjusted Close' column is adjusted for dividends, but all columns are already adjusted for splits.  I think it would make more sense to name all the columns 'Adj Close', 'Adj Open', etc.  This is just an FYI mainly because this isn't obvious.

I'm also not sure the math works out properly when using the ratio of Adj Close to Close to also adjust the OHL columns.  I think to be more precise, the dividends should be subtracted from the OHL columns instead of using the ratio.

**Comment by rtaft** [comment]
That is how the data comes out of Yahoo.
