### ISSUE TITLE
Extended hours?

### ISSUE THREAD

**Issue by dayuyang1999** [ranaroussi/yfinance#1094]
Hi,

I am wondering if yfinance support downloading data from entended hours?

Best,

**Comment by aaronteamAAR** [comment]
Pretty sure it can do that, you need to specify the time but still confirm from the creators

**Comment by dayuyang1999** [comment]
> Pretty sure it can do that, you need to specify the time but still confirm from the creators

Thank you for the reply. Have you tried to grasp data from extended hours?

**Comment by aaronteamAAR** [comment]
Yes i have but at that time i was working with the robinhood API [API](https://robin-stocks.readthedocs.io/en/latest/robinhood.html#getting-market-information) and the yfinance at the same time, so not particularly solely with yfinance

**Comment by dayuyang1999** [comment]
> 

Interesting. I am using Alpaca API + yfinance. Found it not very easy to use. I will try it later.

**Comment by ValueRaider** [comment]
Try `prepost` argument
