### ISSUE TITLE
Getting stock data from a particular time of the day using start and end from Ticker.History

### ISSUE THREAD

**Issue by aaronteamAAR** [ranaroussi/yfinance#1095]
Please can I get data of stock for a particular time of the day like so` start='2022-10-19 14:42:41' end='2022-10-19 14:52:41'`

**Comment by ValueRaider** [comment]
Use `datetime.datetime(...)`. If you really need the string option then could you implement and submit a PR?

**Comment by aaronteamAAR** [comment]
Thanks @ValueRaider  I'll that out
