### ISSUE TITLE
Financials, Balance Sheets and Cashflows do not work anymore

### ISSUE THREAD

**Issue by JerBouma** [ranaroussi/yfinance#111]
I noticed that Yahoo Finance updated their layout of the financials, balance sheet and cashflow pages (with a new Premium function). This seems to have broken the functions. In some rare cases it does work.

![image](https://user-images.githubusercontent.com/46355364/65829451-fafee200-e2a5-11e9-9efe-77b959c5c880.png)

**Comment by kashaziz** [comment]
Still no update. Is there any hope?

**Comment by EJohnF** [comment]
Yea, really wanted to get it back

**Comment by ranaroussi** [comment]
Fixed in 0.1.46. Please reopen issue if the problem persists.

**Comment by vlaranjo** [comment]
> Fixed in 0.1.46. Please reopen issue if the problem persists.

Tried now for "MSFT" and "V" and it seems the problem persists.

**Comment by ranaroussi** [comment]
Just tested it using 0.1.48. and it worked great! Please upgrade to the latest version using:

```
$ pip install yfinance --upgrade --no-cache-dir
```

**Comment by vlaranjo** [comment]
That's right, now it works. Thank you.
