### ISSUE TITLE
Yfinance Intermittently working

### ISSUE THREAD

**Issue by locfinessemonster** [ranaroussi/yfinance#1111]
I have used yfinance for a while using a very old mac and haven't had any problems. I recently upgraded my computer to Windows 11 and am trying to run basic yfinance functions like yf.download in jupyter notebook on a chrome browser and I keep gettting the error message  "No data found for this date range, symbol may be delisted" as well as error 10060. I have tried downgrading to older library versions and using the "pip install yfinance --upgrade --no-cache-dir" recommended fix but I am still getting this problem. The workaround I came up with is to keep retrying the yf.download and sleeping for a couple seconds if it fails. It seems to eventually download after around 10 tries or so but this doesn't seem to be the most elegant solution. I have tried changing my firewall settings and it doesn't seem like my computer is blocking anything. I am pretty stumped, if you have any suggestions I would really appreciate it!

**Comment by locfinessemonster** [comment]
Code with errors that I am seeing:
![image](https://user-images.githubusercontent.com/74224128/197453374-9ee2d61b-85ba-4c37-9de0-90523456f041.png)
![image](https://user-images.githubusercontent.com/74224128/197453437-420b7490-ce1b-431d-80be-2648960429c6.png)

**Comment by locfinessemonster** [comment]
Work around code:
![image](https://user-images.githubusercontent.com/74224128/197453869-f2452de6-97e3-45bd-93e6-1d6485a0ffcd.png)

**Comment by locfinessemonster** [comment]
Longer sleep interval between requests seems to help me get it consistently on the second try, still a mystery as to why I consistently can't get it on the first try. 
![image](https://user-images.githubusercontent.com/74224128/197455377-df044570-0707-4b92-b000-339060b373f0.png)

**Comment by ValueRaider** [comment]
Did you try 0.1.74 or older?

**Comment by jordangrodecki** [comment]
Also had this bug after building a new venv - spent ages before dropping back to 0.1.74 which works fine.

**Comment by ValueRaider** [comment]
We think we know why and plan a release very soon.

**Comment by locfinessemonster** [comment]
> Also had this bug after building a new venv - spent ages before dropping back to 0.1.74 which works fine.

I tried pip install yfinance==0.1.7.4 and still got the same issue.
Tried yfinance==0.1.67 and got the same error

**Comment by locfinessemonster** [comment]
> We think we know why (related to #1076) and plan a release very soon.

Awesome, thank you for the update.

**Comment by ValueRaider** [comment]
> > Also had this bug after building a new venv - spent ages before dropping back to 0.1.74 which works fine.
> 
> I tried pip install yfinance==0.1.7.4 and still got the same issue. Tried yfinance==0.1.67 and got the same error

Oh, if you have same problem with 0.1.74 or older then no, that needs investigation. What version was on your Mac?

**Comment by locfinessemonster** [comment]
> > > Also had this bug after building a new venv - spent ages before dropping back to 0.1.74 which works fine.
> > 
> > 
> > I tried pip install yfinance==0.1.7.4 and still got the same issue. Tried yfinance==0.1.67 and got the same error
> 
> Oh, if you have same problem with 0.1.74 or older then no, that needs investigation. What version was on your Mac?

I was using version 0.1.74 on my Mac and never ran into many issues. 
I tried running a Beautiful Soup Scraper on my Windows 11 machine, and I got error #10060 from that as well and that code never had any problems either on my old Mac. I wonder if I somehow got blacklisted by yfinance? I don't think I really ever sent too many requests yfinance though which seems odd.
![image](https://user-images.githubusercontent.com/74224128/197934936-8c8b6e5b-ea28-4b91-ad2a-a0edf779e69b.png)

**Comment by ValueRaider** [comment]
Any blacklisting is very temporary, so rolling back to 0.1.74 should have eventually restored normal behaviour.

For 0.1.75 and later, a release went out yesterday that should resolve problem.

**Comment by locfinessemonster** [comment]
Built both the yf v0.1.83 and v0.1.84 from the tar.gz files released yesterday and still having same issues unfortunately.

**Comment by locfinessemonster** [comment]
**Did rolling back to 0.1.74 solve?**
No, still getting same errors with 0.1.74
**Does the for w in range loop with sleep removed always encounter your error? If yes. how many iterations?**
Yes, it pretty typically does, the standard range of iterations pretty typically seems to be between 2 and 10
![image](https://user-images.githubusercontent.com/74224128/198903785-5cd1fe23-0c0e-4032-9bc7-97900aec6ae0.png)
**What is the actual loop you are trying to run?**
The actual loop I am trying to run is trying to collect minutely price movement data for a list of stocks generally around 75 stocks long and export to csv.
![image](https://user-images.githubusercontent.com/74224128/198905237-a4e572f6-8740-4edd-b375-aa7222c48a08.png)
**What happens if you run in command line shell instead of Jupyter?**
Running from command line using a virtual environment with yfinance==0.1.74 installed still gives me the same errors I have been seeing
![image](https://user-images.githubusercontent.com/74224128/198902966-71694aad-7919-44c8-8bef-04e42ccd912d.png)

**Comment by ValueRaider** [comment]
It is curious that this only started with Windows, but the typical cause is you are triggering Yahoo rate limiting by running that loop many times each day/hour - are you? The solution is to stop spamming Yahoo for data you could cache locally.

If only running once per day, then unlikely to be Yahoo, which implies a Windows problem.

**Comment by locfinessemonster** [comment]
Since this code has not been working properly, I haven't been running it at all outside of trying to debug  yfinance. It's definitely a bit odd, I was thinking it was maybe my internet or firewall or something but  I have some similar code that requests data from the WeBull API and it has been running without any problems.

I gave requests_cache a shot and still no luck. 
![image](https://user-images.githubusercontent.com/74224128/199157755-cad43914-e257-40e5-9c77-153e9800fcfd.png)

I gave yfinance_cache a shot as well still getting an error
![image](https://user-images.githubusercontent.com/74224128/199159177-ab0933cf-6f75-48f4-881d-5a78ad5cee43.png)

**Comment by ValueRaider** [comment]
That last error looks like a Windows networking issue. Maybe start with Googling 10060 error code

**Comment by locfinessemonster** [comment]
I had some old tor code that I used to set a proxy on yf.download and now it seems as if everything is consistently working.
![image](https://user-images.githubusercontent.com/74224128/199390324-2bd8f9ea-3f92-471c-ae3f-4de71ee9aecb.png)

**Comment by locfinessemonster** [comment]
That sounds good, thanks for your help!
