### ISSUE TITLE
Found code that will always fail in silence

### ISSUE THREAD

**Issue by fredrik-corneliusson** [ranaroussi/yfinance#1114]
See:
[Complementary key-statistics code](https://github.com/ranaroussi/yfinance/blob/dev/yfinance/base.py#L860-L864)

This code references variable named `ticker` (should probably be `self.ticker`) that is not defined and will trigger exception:
But as the code is surrounded by a try/except that silences all exceptions it is probably never noticed more than the functionality not working as expected.

Note: Code exists in both main and dev branches but at different location.

```
        # Complementary key-statistics (currently fetching the important trailingPegRatio which is the value shown in the website)
        res = {}
        try:
            my_headers = {'user-agent': 'curl/7.55.1', 'accept': 'application/json', 'content-type': 'application/json',
                          'referer': 'https://finance.yahoo.com/', 'cache-control': 'no-cache', 'connection': 'close'}
            p = _re.compile(r'root\.App\.main = (.*);')
            r = _requests.session().get('https://finance.yahoo.com/quote/{}/key-statistics?p={}'.format(self.ticker,
                                                                                                        self.ticker), headers=my_headers)
            q_results = {}
            my_qs_keys = ['pegRatio']  # QuoteSummaryStore
            # , 'quarterlyPegRatio']  # QuoteTimeSeriesStore
            my_ts_keys = ['trailingPegRatio']

            # Complementary key-statistics
            data = _json.loads(p.findall(r.text)[0])
            key_stats = data['context']['dispatcher']['stores']['QuoteTimeSeriesStore']
            q_results.setdefault(self.ticker, [])
            for i in my_ts_keys:
                # j=0
                try:
                    # res = {i: key_stats['timeSeries'][i][1]['reportedValue']['raw']}
                    # We need to loop over multiple items, if they exist: 0,1,2,..
                    zzz = key_stats['timeSeries'][i]
                    for j in range(len(zzz)):
                        if key_stats['timeSeries'][i][j]:
                            res = {i: key_stats['timeSeries']
                                   [i][j]['reportedValue']['raw']}
                            q_results[self.ticker].append(res)

                # print(res)
                # q_results[ticker].append(res)
                except:
                    q_results[ticker].append({i: np.nan})

            res = {'Company': ticker}
            q_results[ticker].append(res)
        except Exception:
            pass
```

**Comment by fredrik-corneliusson** [comment]
Found another issue with the code, `np` is never imported so this will be need to be fixed as well.
```
q_results[ticker].append({i: np.nan})
```

**Comment by ValueRaider** [comment]
@asafravid This was introduced by your PR #911. There's a fundamental problem with that change - even if the above issues are fixed, it doesn't do anything because you overwrite the result.

**Comment by asafravid** [comment]
@ValueRaider the silenced exception is intentional

**Comment by ValueRaider** [comment]
@asafravid Sorry I deleted my last message, wanted to rephrase. The PR was #911

I have 2 questions:
- why retrieving 'pegRatio' when it's already in info[] via 'defaultKeyStatistics': https://github.com/ranaroussi/yfinance/blob/22131e9fc7062ad3a7b64a0cc36903eb819754af/yfinance/base.py#L434
- why is the logic to retrieve 'trailingPegRatio' so complicated? Why not just lookup with `key_stats["timeSeries"]["trailingPegRatio"][0]["reportedValue"]["raw"]`

**Comment by asafravid** [comment]
There was a whole investigation about the “why”
See the linked issue which this PR resolved

**Comment by asafravid** [comment]
@ValueRaider if the raw contains the same as the extended code then agree - but didn’t check this. The actual code fix was contributed by @eabase

**Comment by ValueRaider** [comment]
Thanks @asafravid.

@fredrik-corneliusson You're right about the silent error, but this triggered after the useful work was done (retrieving 'trailingPegRatio in loop') so no one noticed.

**Comment by eabase** [comment]
Nice catch @fredrik-corneliusson 💯 

*The dangers of nested try/catch...*
