### ISSUE TITLE
No data found for this date range, symbol may be delisted

### ISSUE THREAD

**Issue by aaronteamAAR** [ranaroussi/yfinance#1123]
Please how do I catch this error with maybe an if statement, basically i want to check the index of that particular stock is empty

**Comment by ValueRaider** [comment]
I believe you have already asked this question, and I answered that you need to do a Pandas tutorial: https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html

**Comment by aaronteamAAR** [comment]
No that’s not correct this is absolutely different, I’m trying to remove stocks that don’t return any data
