### ISSUE TITLE
TypeError: concat() got an unexpected keyword argument 'sort'

### ISSUE THREAD

**Issue by david22van** [ranaroussi/yfinance#113]
Hi Ran,
Just wondering if there is something need to be updated. I followed your example on your website. Just 2 simple step as:
import yfinance as yf

msft = yf.Ticker("MSFT")

msft.history(period="max")
Traceback (most recent call last):

  File "<ipython-input-3-596f23721d9f>", line 1, in <module>
    msft.history(period="max")

  File "C:\Anaconda3\lib\site-packages\yfinance-0.1.45-py3.6.egg\yfinance\__init__.py", line 402, in history
    df = _pd.concat([quotes, dividends, splits], axis=1, sort=True)

TypeError: concat() got an unexpected keyword argument 'sort'

**Comment by ranaroussi** [comment]
Please update your Pandas to 0.23+

**Comment by david22van** [comment]
Hi， Ran
Thanks for your reply. But I would like to say that my pandas is 0.24.2. So
the problem could be somewhere else.
David
