### ISSUE TITLE
Missing Quarterly SharesOutstanding

### ISSUE THREAD

**Issue by kkafkas** [ranaroussi/yfinance#1133]
Hello everyone,

I have noticed that yfinance doesn't support quarterly shares outstanding but only annual, is there a way to retrieve quarterly shares outstanding given that this is quite important in order to calculate various ratios such as market cap and FreeCashFlow

**Comment by kkafkas** [comment]
![image](https://user-images.githubusercontent.com/59070239/198891648-76f681bc-ed77-4909-867e-154c56d728ba.png)

stock.shares shows the annual shares outstanding, where I can find the quarterly?

**Comment by ValueRaider** [comment]
I have this in an experimental branch that needs someone to test for feedback: "feature/share-count" `yf.Ticker(...).shares_full(start=None, end=None)`

It isn't strictly quarterly, maybe it's recording each individual share issuance/buyback? E.g.

|  | count
| - | - |
| 2022-08-06 | 4105999872
| 2022-08-25 | 4116910080
| 2022-08-26 | 4105999872
| 2022-09-01 | 4105999872
| 2022-09-03 | 4177019904
| 2022-10-29 | 4127000064

**Comment by konstantinos-kafkas-cko** [comment]
@ValueRaider That's amazing and very useful, have you raised a PR?

**Comment by konstantinos-kafkas-cko** [comment]
Do you think we can merge this feature branch, to me this is quite important and should be supported by yFinance. Quarterly shares outstanding should be provided

**Comment by ValueRaider** [comment]
I'm still waiting for feedback - any bugs or improvements? Not gonna PR bad code.

You're the 3rd to see this, still no feedback.

**Comment by konstantinos-kafkas-cko** [comment]
@ValueRaider How many quarters it goes back? can you fetch shares-outstanding for more than > 3-4 months, or it has a limitation of a couple of months?

**Comment by ValueRaider** [comment]
Haven't got a clue, it's experimental. I only implemented because I stumbled upon API data point doing something else.

**Comment by ValueRaider** [comment]
This is now available in PIP release, via `Ticker.get_shares_full(start, end)`
