### ISSUE TITLE
Please mark RC as pre-release

### ISSUE THREAD

**Issue by iyanmv** [ranaroussi/yfinance#1136]
Hi,

Please consider tagging RCs and other similar releases as pre-releases on github. In my case I'm using [nvchecker](https://github.com/lilydjwg/nvchecker/) with `use_latest_release = True` to keep track of new stable releases of packages I maintain, and I was notified by the 0.2.0rc1 release.

Thanks

**Comment by ValueRaider** [comment]
Done. Try `nvchecker` again. I would do myself but can't see how to run command-line without creating a config file, shouldn't be this complex.

**Comment by iyanmv** [comment]
Yes, perfect, thanks!
