### ISSUE TITLE
Python 3.11 doesn't support yfinance

### ISSUE THREAD

**Issue by Mitun-at-work** [ranaroussi/yfinance#1139]
*** READ BEFORE POSTING ***

Before posting an issue - please upgrade to the latest version and confirm the issue/bug is still there.

Upgrade using:
`$ pip install yfinance --upgrade --no-cache-dir`

Bug still there? Delete this content and submit your bug report here and provide the following, as best you can:

- Simple code that reproduces your problem
- The error message

**Comment by ValueRaider** [comment]
*** READ BEFORE POSTING ***
