### ISSUE TITLE
Add GBX as a currency

### ISSUE THREAD

**Issue by DanielGoncalves47264** [ranaroussi/yfinance#1145]
I would appreciate that yFinance artificially introduced GBX as a currency (pence) such that:
```python3
import yfinance as yf
yf.download(['GBXUSD=X']  = yf.download(['GBPUSD=X'])/100
```
The reason behind it is to help converting to the same currency a portfolio with stocks from LSE as they are quoted in pence instead of pounds.
Best Regards,
Daniel

**Comment by ValueRaider** [comment]
yfinance is not associated in any way with Yahoo Finance. We cannot add tickers.
