### ISSUE TITLE
Unable to obtain daily stock prices using yfinance 

### ISSUE THREAD

**Issue by RSB-Balaji** [ranaroussi/yfinance#115]
`import pandas_datareader.data as pdr`
`import yfinance as yf`
`yf.pdr_override()`
`data = pdr.get_data_yahoo("AAPL",start ='2018-01-01',end='2018-12-31')`

The exception says:
Exception in thread Thread-1:
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

**Comment by ranaroussi** [comment]
This seems like a connection issue. Closing for now. Please reopen issue if the problem persists.
