### ISSUE TITLE
NameError: name 'yf' is not defined

### ISSUE THREAD

**Issue by grimlockdd** [ranaroussi/yfinance#1151]
Hi Everyone
I'm new to this and trying to use yfinance in python (anaconda/Spyder5). The code bellow gives me an error (bellow that). Could someone please help me out with this issue. It's probably an easy fix for you, but I'm getting hung up on it. 

Thanks

Lines of code

!pip install yfinance
!import pandas as pd
!import yfinance as yf
msft = yf.Ticker("MSFT")
print(msft)
msft.info

Error

  File "/Users/daviddowney/untitled4.py", line 5, in <module>
    msft = yf.Ticker("MSFT")

NameError: name 'yf' is not defined

**Comment by fredrik-corneliusson** [comment]
You should only have exclamation marks before shell commands not python code (and it only if you are working in a jupyter notebook like environment).

**Comment by grimlockdd** [comment]
Thank you for your response. I removed the ! and got a different error. I am using Spyder from the Anaconda python package.

The new code is 

pip install yfinance
import pandas as pd
import yfinance as yf
msft = yf.Ticker("MSFT")
print(msft)
msft.info

The new error is 

  File "/Users/daviddowney/untitled4.py", line 1
    pip install yfinance
        ^
SyntaxError: invalid syntax

I get this right away (it fails before I even get to the yf part issue.

Once again than you for your help.

**Comment by fredrik-corneliusson** [comment]
You did not use the code I added to my comment that works

**Comment by neha24647** [comment]
NameError                                 Traceback (most recent call last)
[/tmp/ipython-input-2-3966700808.py](https://localhost:8080/#) in <cell line: 0>()
----> 1 data = yf.download(tickers, start='2018-01-01', end='2023-01-01')['Adj Close']
      2 data.tail()

NameError: name 'yf' is not defined
how to fix it
