### ISSUE TITLE
Unused cleanup method

### ISSUE THREAD

**Issue by fredrik-corneliusson** [ranaroussi/yfinance#1152]
In the dev branch there is a nested function named cleanup that is no longer used.
Is it no longer needed or is this a bug?
https://github.com/ranaroussi/yfinance/blob/23e8423b8b5663c91c7f65fad80cc20f7897306b/yfinance/base.py#L737

**Comment by ValueRaider** [comment]
That can go. Was used by old financials code (cashflow etc), so now redundant.

**Comment by fredrik-corneliusson** [comment]
Ok I'll fix it in an upcoming PR

**Comment by fredrik-corneliusson** [comment]
Removed it as part of #1154
