### ISSUE TITLE
Getting historical quarterly finances

### ISSUE THREAD

**Issue by AjinkyaBankar** [ranaroussi/yfinance#1153]
I'm trying to get the historical quarterly finances for MSFT. I get those for the recent 4 quarters by using the following code:
`import yfinance as yf`
`msft = yf.Ticker("MSFT")`
`msft.quarterly_financials`

But I'm not able to get the same for a given period or for the entire quarters till date.
Is there a way to get this data from yfinance?

**Comment by ValueRaider** [comment]
yfinance returns what Yahoo website has. Where on Yahoo are you seeing more data?
