### ISSUE TITLE
pandas.read_csv error

### ISSUE THREAD

**Issue by Slepetys** [ranaroussi/yfinance#1158]
Dear yfinancers,

Two days ago, an intermittent error showed while using yfinance (v. 0.1.85 and also tested with v. 0.1.84 and 0.1.82). 

The last traceable error to finance was:
`pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields  saw 3`
which was caused by an unexpected return from Yahoo Finance, leading to more columns in the interim CSV file that is used to build the Pandas DataFrame. 

As the unpredictable error associated with such unexpected returns caused the yfinance to fail, I was able to track it to the **utils.py** submodule and fix it just by adding the option: `on_bad_lines='warn'` to the `pandas.read_csv` instruction in lines 339 and 358:

**util.py**
lines 338-340:
```
mutex.acquire()
df = _pd.read_csv(fp, index_col="Ticker",on_bad_lines='warn')
mutex.release()
```

line 358:
`df = _pd.read_csv(fp, index_col="Ticker",on_bad_lines='warn')`

Through this, the errors became warning messages which can be captured in the python script or redirecting the STDERR to STDOUT or a file enabling tracing to the original yahoo finance response to the yfinance request without interrupting the execution.

I recommend integrating such fix into the next versions.

All the best
Roberto Slepetys

**Comment by ValueRaider** [comment]
Roberto thanks for investigating this. Easy to fix (I'll silently "skip" instead) and I could just send out a patch, but I'm curious about how the csv file became corrupted. Were you a heavy user of `yf.download()` at the time ?

**Comment by Slepetys** [comment]
Hi Ran,

I do not consider myself a "heavy" user of yf.download(), most likely an
average user who is using the module in order to grab financial data in
order to experiment models for my own use.
Having knowledge of python, I try to contribute to any development team
when possible as a retribution everytime I find a potential opportunity.
Anyhow, yfinance is a very nice module, thank you for it!

Regarding the CSV file becoming corrupted, I was not able to reproduce it
easily, as was intermittent. I suspect that Yahoo had some records that
were crawler with extra commas, fields or missing fields - triggering the
error. Unfortunately I didn't have time to change the submodule to store
the CSV timely to debug it, but the "warn" fix, at least avoid yf to stop
during execution.

[]s

Roberto Slepetys
+49 1511 502.1927 (whatsapp)
