### ISSUE TITLE
get the industry of the stock

### ISSUE THREAD

**Issue by antonio-catalano** [ranaroussi/yfinance#116]
It is possible? I think it's an important metadata but i didn't find this info in the package.

**Comment by ranaroussi** [comment]
This information isn't returned from Yahoo!'s API. When it does, I'll add it to `yfinance`.

**Comment by vlaranjo** [comment]
This information is included in "info" function:

![image](https://user-images.githubusercontent.com/57137444/67769673-32071580-fa55-11e9-9a91-68161510c5dd.png)

**Comment by ranaroussi** [comment]
Only since version 0.1.46 as I'm using a different method for fetching this data 😄
