### ISSUE TITLE
dev: Cannot run tests from command-line

### ISSUE THREAD

**Issue by ValueRaider** [ranaroussi/yfinance#1160]
> python -m tests.ticker

This used to work with old test code containing just a simple `unittest.main()`, but fails with new suite. Am I being dumb?

> Traceback (most recent call last):
>   File "/usr/lib64/python3.10/unittest/case.py", line 366, in __init__
>     testMethod = getattr(self, methodName)
> AttributeError: 'TestTicker' object has no attribute 'Test ticker'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "yfinance-tz-cache/tests/ticker.py", line 288, in <module>
>     runner.run(suite())
>   File "yfinance-tz-cache/tests/ticker.py", line 279, in suite
>     suite.addTest(TestTicker('Test ticker'))
>   File "/usr/lib64/python3.10/unittest/case.py", line 371, in __init__
>     raise ValueError("no such test method in %s: %s" %
> ValueError: no such test method in <class '__main__.TestTicker'>: Test ticker

@fredrik-corneliusson

**Comment by fredrik-corneliusson** [comment]
That has never worked for me.
I've had to run it using "unittest" module.

Try running it like [this instead](https://docs.python.org/3/library/unittest.html#command-line-interface):
Whole suite:
`python -m unittest tests.ticker`

Specific test class:
`python -m unittest tests.ticker.TestTicker`

How to run the tests should probably be documented in a CONTRIBUTING.md file.

There is an issue with the cleanup code that should remove the CachedSession but it does not effect the tests, but annoying and should be looked in to.

**Comment by fredrik-corneliusson** [comment]
Regarding the issue with removing temp-folder I think the whole issue can be circumvented by not persisting on disk but instead initialize session on class object instead of instance setup and teardown
```
class TestTicker(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.session = requests_cache.CachedSession()

    @classmethod
    def tearDownClass(cls):
        cls.session.close()
```

**Comment by fredrik-corneliusson** [comment]
This is merged into dev, so should be fixed.
