### ISSUE TITLE
some errors are not `raise`d, but rather `print`ed

### ISSUE THREAD

**Issue by hamid-vakilzadeh** [ranaroussi/yfinance#1167]
- Simple code that reproduces your problem
when requesting a non-existing ticker symbol, the history method does not handle it as an error, but just a print output.
Therefore, since no error is raised, error handling using try and except is not possible.
For example:
```python
import yfinance as yf

# trying a ticker that does not exist
ticker = yf.Ticker('T1XN')
try:
    ticker.history(period='max')
except:
    print("not found")
```
- The error message
```
Got error from yahoo api for ticker T1XN, Error: {'code': 'Not Found', 'description': 'No data found, symbol may be delisted'}
- T1XN: No data found for this date range, symbol may be delisted
```
The error message is not actually an error message! 
right now the error is a `print` output rather than `raise`

**Comment by hamid-vakilzadeh** [comment]
@ValueRaider okay thank you for quick response!
I guess this issues can be closed now!

**Comment by misantroop** [comment]
For me, raise_errors has no effect here at all. Errors are just printed, not great when using tqdm to show progress.

**Comment by ValueRaider** [comment]
@misantroop What ticker prints an error? Any ticker so we can reproduce.
