### ISSUE TITLE
The latest date for DJI is 2022-03-02

### ISSUE THREAD

**Issue by iDataist** [ranaroussi/yfinance#1173]
I used the following code to retrieve the DJI historical price data. The latest date I got was 2022-03-02. What happens to the more recent data?

```
import yfinance as yf

df = yf.download(["DJI"], start="1970-01-02", end="2022-11-14", progress=False)
```

**Comment by ValueRaider** [comment]
What does Yahoo have? Make sure you spell ticker correctly.

**Comment by fredrik-corneliusson** [comment]
Index ticker symbols on yahoo usually starts with a "^".
Using "^DJI" gets the latest data (from 1992 and forward).:
```
df = yf.download(["^DJI"], start="1970-01-02", end="2022-11-14", progress=False)
```
