### ISSUE TITLE
Add a more restrictive issue template

### ISSUE THREAD

**Issue by eabase** [ranaroussi/yfinance#1175]
Please consider adding a more restrictive bug report template for the issues here.
Something that require people to provide some code to reproduce their issue. 

For ideas, see issue templates at `pypa`, `pip` and `setuptools` repos...

**Comment by ValueRaider** [comment]
For anyone who is keen to implement this, can be done like any other PR. Just modify [.github/ISSUE_TEMPLATE](https://github.com/ranaroussi/yfinance/tree/main/.github/ISSUE_TEMPLATE)

**Comment by ValueRaider** [comment]
I've recently added a new template for feature requests.
