### ISSUE TITLE
Intelligent caching of yfinance results not implemented

### ISSUE THREAD

**Issue by GregoryMorse** [ranaroussi/yfinance#118]
This would be a feature request.  But in reality it is not.  For the very future viability of this project, the amount of requests hammering yahoo which especially for parsing web data is not officially allowed, should be minimized.

The easiest thing is to add a new module e.g. TickerCache, which checks for a file `<TickerName>.data.csv` that contains all information about the stock (info, financials, balance sheet, cashflow, sustainability, history, options).  This way the whole history need not be refatched but only from the end of the history in the file to current time.  The time can be used to decide if 3 months has elapsed on the quarterly or a year for yearly financial data before re-retrieving those.  The details of market trading hours can also be used for even fetching day-to-day history.

I will submit a PR with a good amount of the propose code.

A major reason I requested timezone support was to deal with all the mechanics of this.  I already have it implemented in my projects.  It should be a de facto standard for this tool.  Anyone doing serious work with this likely requires it as well.

**Comment by ranaroussi** [comment]
I don't think the caching should be handled by the library as this will turn it from a library into an app. It should be a good idea to maybe create new wrapper library that handles the caching... Maybe call it `yfinance_cache` 😄

**Comment by GregoryMorse** [comment]
Indeed that is one solution - you are right it is more of an "app" but nonetheless I think if the library is causing excessive traffic to yahoo due to laziness such they might start changing or protecting things, it would be better if the app was just bundled as an extra class here since people might not find the cache plugin.

**Comment by marcusschiesser** [comment]
I added a caching layer to yfinance that you guys might want to check out: https://github.com/marcusschiesser/intraday - sorry, I didn't call it `yfinance_cache` though  - just saw the name proposal ;)

**Comment by jamespan** [comment]
```
import requests_cache
requests_cache.install_cache(cache_name=".cache", backend='sqlite')
```

can do the cache job

**Comment by binarymason** [comment]
perfect timing. thanks for the share, @jamespan :1st_place_medal:

**Comment by leeprevost** [comment]
I get Json decoder error when trying to use cache:

```
Invalid JSON body:
Traceback (most recent call last):
  File "C:\Users\lee\Anaconda3\lib\site-packages\requests_cache\cache_keys.py", line 165, in normalize_json_body
    body = json.loads(decode(original_body))
  File "C:\Users\lee\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\lee\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\lee\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

using this code:

```

tickers = yf.Tickers(" ".join(current_stocks))  #my list of stocks
analysis = pd.DataFrame()
requests_cache.install_cache(cache_name=".cache", backend='sqlite')

for key, to in tickers.tickers.items():
    print("Fetching analysis on {}".format(key))
    an = to.analysis
    if an is not None:
        an["symbol"]=key
        analysis = analysis.append(an)
```
