### ISSUE TITLE
Error on get_shares for some tickers

### ISSUE THREAD

**Issue by uzala92** [ranaroussi/yfinance#1187]
In 0.2.0rc2 version I get "object of type 'NoneType' has no len()" error for some tickers when trying to get yearly shares. I get the error with "BMW3.DE" ticker, for example. Code executed:

`stock = yf.Ticker("BMW3.DE")`
`shares = stock.get_shares()`

Thank you in advance for your efforts.

**Comment by fredrik-corneliusson** [comment]
This seems fixed in latest dev branch.
```
In [1]: import yfinance as yf; stock = yf.Ticker("BMW3.DE")

In [2]: stock.get_shares()
Out[2]: 
      BasicShares
Year
2018    657600576
2019    658118053
2020    658862376
2021    659681430
```
