### ISSUE TITLE
`pandas_datareader` override feature faulty

### ISSUE THREAD

**Issue by ValueRaider** [ranaroussi/yfinance#1192]
```
from pandas_datareader import data as pdr
import yfinance as yf
# yf.pdr_override()  # <- enable to break code
tkr = "INTC"
df = pdr.get_data_yahoo(tkr, start = '2022-10-31', interval="wk", get_actions=True)
print(df)
```

The README describe a `pandas_datareader` override feature that "uses yfinance while making sure the returned data is in the same format as pandas_datareader's get_data_yahoo()". This implies a seamless override inside `pandas_datareader` to use `yfinance` to fetch data and then `pandas_datareader` to post-process.

But actually all is happening is modifying the API:

> pandas_datareader.data.get_data_yahoo = yfinance.download

despite the two functions having different arguments, e.g. `get_actions` -> `actions`. And `yfinance` doesn't override `pandas_datareader.get_data_yahoo` so override not complete.

**Appears some users do use this feature, but should we force them onto `yfinance` API by removing the override?**

**Comment by ValueRaider** [comment]
@ranaroussi Can you comment on this?

**Comment by ranaroussi** [comment]
Back in the first version of yfinance it used to return data in the same structure as pandas_datareader. 

I think we can deprecate this functionality and remove it altogether v2. 

What do you think?

**Comment by ValueRaider** [comment]
It should go.

**Comment by ranaroussi** [comment]
Alrighty then :)

Let's keep the function though and have it print some sort of a message so it won't just fail.

Sounds like a plan?

**Comment by ValueRaider** [comment]
Message like "This is deprecated and will be removed in future version", like I've seen Pandas do ?

**Comment by ranaroussi** [comment]
Yep. Thank you!
