### ISSUE TITLE
Bug: Timestamp conversion fails on Windows platform

### ISSUE THREAD

**Issue by ymyke** [ranaroussi/yfinance#1199]
On Windows (my Windows at least), this:

```python
import yfinance as yf
data = yf.download("AAPL")
```

produces an `OSError` because the `start` parameter gets set to a default value that cannot be converted to a time via `utcfromtimestamp`.

Here's the line where it gets set:
https://github.com/ranaroussi/yfinance/blob/744e70ffff2c4cf0a384e88e855af60862e71397/yfinance/base.py#L167

Here's the line where it later breaks:
https://github.com/ranaroussi/yfinance/blob/744e70ffff2c4cf0a384e88e855af60862e71397/yfinance/base.py#L319

Windows spec:
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2022-‎10-‎15
OS build	22621.819
Serial number	PF39DFCV
Experience	Windows Feature Experience Pack 1000.22636.1000.0
```

System spec:
```
Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID	3C2CE2C1-3557-41D1-BD95-D0997E6A4CA4
Product ID	00330-53928-86026-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```

**Comment by ymyke** [comment]
This seems also to be the cause to https://github.com/ranaroussi/yfinance/issues/1171

**Comment by ymyke** [comment]
See PR for very straightforward fix. Feels rather crude but has the advantage that no other refactoring is necessary.

**Comment by fredrik-corneliusson** [comment]
Sorry #1171 should have been closed as this is fixed in dev branch.
The fix is to use the pandas version that does not have the issue.
Is this exception present in the stable releases?

**Comment by fredrik-corneliusson** [comment]
I think this is fixed in dev branch, @ymyke could you test and verify?

**Comment by ymyke** [comment]
Yes, @fredrik-corneliusson, verified that this is fixed on dev. Closing this. Thanks!
