### ISSUE TITLE
Premium Yahoo finance 

### ISSUE THREAD

**Issue by mbatzeris** [ranaroussi/yfinance#120]
Hi there,
Yahoo finance requires a premium access for financials and a few other sections . 
![screenshot-finance yahoo com-2019 10 29-13_29_37](https://user-images.githubusercontent.com/46544375/67763108-9fb04300-fa4f-11e9-9c3f-b2ba123acb47.png)
.financials .earnings .recommendations and .balance_sheet are returning an error
![screenshot-localhost_8888-2019 10 29-13_32_38](https://user-images.githubusercontent.com/46544375/67763573-b1461a80-fa50-11e9-917e-7afed28fa969.png)

Is there any chance that you might add a support for the premium section ?

**Comment by ranaroussi** [comment]
Please upgrade to version 0.1.47+ and try again. Upgrade using:

```
$ pip install yfinance --upgrade --no-cache-dir
```

**Comment by GregoryMorse** [comment]
I suspect premium information automatically work, however yfinance would need to have the right headers/cookies and such set when making the page request.  This would require another page request to login with a username and password.  Without a Yahoo Premium account its not testable either.  So someone should donate to the maintainer the funds for at least a year or two for this :).
