### ISSUE TITLE
Dev branch does not work on Python < 3.9

### ISSUE THREAD

**Issue by fredrik-corneliusson** [ranaroussi/yfinance#1207]
PR #1193 was merged without fixing the review comments and now does not work on Python versions older than 3.9.

**Comment by ValueRaider** [comment]
All review comments were addressed. The only outstanding question was default behaviour of `pretty` formatting, but we can figure that out later.

What exactly is the error with < 3.9?

**Comment by fredrik-corneliusson** [comment]
I cant see than any of the comments was implemented. Maybe they where missed.
The error keeping it from working on old Python is: TypeError: 'type' object is not subscriptable
![image](https://user-images.githubusercontent.com/2439232/204148968-09db7127-f35d-480d-8232-7ed51d7ad77f.png)

**Comment by fredrik-corneliusson** [comment]
@ranaroussi will you have any time to help out to keep an eye on the quality and direction of the development? 

I started to help out to scratch my own back after experiencing bugs and issues introduced in new releases.
However just reviewing PR:s (at the speed they are created) has eaten up to much of my time and I have to cut down my involvement. 

@ValueRaider What are your plans for new features and changes? 
Will the amount of changes decrease in the near future? If not I've been running the dev branch for some time and it fits my current need and has been stable so will probably stick with the current commit and not update it unless necessary. Just as a heads up.

**Comment by ValueRaider** [comment]
No new features planned from me, I think all price data issues have been identified and resolved in `dev`. I'll just keep an eye on Issues. I too want to move onto other projects.
