### ISSUE TITLE
Dev - downloading tickers will quickly get you blocked from yahoo

### ISSUE THREAD

**Issue by fredrik-corneliusson** [ranaroussi/yfinance#1213]
Running bulk ticker history with current dev branch will result in getting blocked from yahoo financials api.
This was not the issue before.

**Comment by ValueRaider** [comment]
How is the block manifesting? Because 'spam limiting' was always a problem.

**Comment by fredrik-corneliusson** [comment]
Seems like #1203 mitigates the issue.
