### ISSUE TITLE
Quick Start reports functionality that actually are not present

### ISSUE THREAD

**Issue by mhlg** [ranaroussi/yfinance#1224]
- Info about your system:
  - yfinance version 0.1.87
  - python version 3.8.2

Quick Start reports functionality that actually are not present .
- Simple code that reproduces your problem
`
import yfinance as yf
msft = yf.Ticker("MSFT")
# show analysts recommendations
msft.recommendations_summary 
# show analysts other work
msft.analyst_price_target
mfst.revenue_forecasts
mfst.earnings_forecasts
mfst.earnings_trend
`
- The error message

**Comment by ValueRaider** [comment]
Typos fixed in #1216
