### ISSUE TITLE
Historical data extremely slow, seems to stall, then the data eventually comes

### ISSUE THREAD

**Issue by llninja1** [ranaroussi/yfinance#1227]
Y FInance v. 0.1.87

Historical data which used to take split seconds to download now takes several minutes sitting idle before the data comes, as of 7:30am central time, Dec 6, 2022. 

import yfinance as yf
data = yf.download("aapl msft")

Not sure if this is a yfinance or Yahoo Finance issue.

**Comment by llninja1** [comment]
It seems to be getting worse, taking longer and longer. It's as if Yahoo has inserted some code to make yfinance unusable - similar to the way repeated failed passwords on a cellphone forces you to wait longer between attempts.

**Comment by llninja1** [comment]
Things are back to normal today. Maybe it's a temporary problem at Yahoo Finance.

**Comment by llninja1** [comment]
And the problem has returned today. Big long delays before data flows

**Comment by ValueRaider** [comment]
That code executed only a few times per day should not encounter delays, only when spamming do delays appear. What rate are you running?

**Comment by llninja1** [comment]
I ran my code once today for the first time at 5:14am Central time, and the delays appeared. So I can't say I am spamming at all. The last time I ran my full test set was Dec 1st, and maybe that is considered spamming. And I only need to run once per trade day for close data.

**Comment by ValueRaider** [comment]
You need to debug this more to narrow down where problem is. Try disabling `threads`,  or use `Ticker.history()`, do these behave better?

**Comment by ahnazary** [comment]
Apparently they have limits on requests sent to their API per IP (details of limitations are [here](https://developer.yahooinc.com/dsp/api/docs/traffic/info/rate-limits.html) in Yahoo's docs)

<br />

I had a smilier problem too that for a couple of hours could not retrieve anything from the API but I guess the limitation got lifted after some time and now I can query data again.

**Comment by ValueRaider** [comment]
@ahnazary Excellent find, first time I've seen actual numbers. Can you x-post to #1513, I don't want to take credit.

**Comment by t34hansen** [comment]
I'm having the same issue but I doubt it has anything to do with Yahoo rate limiting the number of requests. Here is why: I have a loop that downloads the last 3 months of quotes for tickers in the list I loop over, i.e. I only download data for one ticker at a time (not very efficient if you want to limit the number of requests... I know but that is not the point here). The first ticker takes forever. Any ticker after that runs in a blink of an eye. I ran this code piece in the REPL... now if I re-run that code piece w/o starting a new REPL session then it runs super quick for all tickers in my list. If I exit the REPL and re-enter then it takes forever again for the first ticker.
