### ISSUE TITLE
VWAP For Specific Date

### ISSUE THREAD

**Issue by nandonanders** [ranaroussi/yfinance#1229]
I've been looking for a way to automatically pull up the vwap for any given stock on any given date.

Is it possible to do this using yfinance? I'm not a coder and have been looking for a solution to this instead of manually looking volume for a date, then pulling up a chart and finding the vwap toward close, and multiplying volume*vwap = $vol for any given day.

Would be sick if you could make this happen!

**Comment by ValueRaider** [comment]
No chance. VWAP is an indicator, and TA is beyond scope of `yfinance`. Look into a TA library like `pandas-ta`.
