### ISSUE TITLE
Please version bump pandas in requirements file

### ISSUE THREAD

**Issue by mttpgn** [ranaroussi/yfinance#1230]
Hello,

Your requirements.txt file [allows](https://github.com/ranaroussi/yfinance/blob/main/requirements.txt#L1) any version of pandas above 0.24.0.

However, in your utils.py file, you [twice](https://github.com/ranaroussi/yfinance/blob/0.1.87/yfinance/utils.py#L358) [invoke](https://github.com/ranaroussi/yfinance/blob/0.1.87/yfinance/utils.py#L339) the pandas `read_csv` function with the `on_bad_lines` argument, an argument which was only introduced in [pandas 1.3.0](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.3.0.html). 

As a result, anyone running yfinance with a version of pandas greater than or equal to 0.24.0 but lower than 1.3.0 will experience a crash with the following error:
```
    df = _pd.read_csv(fp, index_col="Ticker", on_bad_lines="skip")
TypeError: parser_f() got an unexpected keyword argument 'on_bad_lines'
```

Please bump the version of pandas in your requirements.txt file to say
`pandas>=1.3.0`

**Comment by phnv** [comment]
It would be nice to update requirements to python 3.7+ too, since apparently pandas last version to support python 3.6 is v==1.3.0
