### ISSUE TITLE
Uses HTTPX instead of Requests.

### ISSUE THREAD

**Issue by bergginu** [ranaroussi/yfinance#1234]
**Describe the problem**
Requests and other libraries without HTTP 2 support are not performing well, causing problems due to protections in some cases.

**Describe the solution**
Replacing Requests with HTTPX (along with some request header settings) can improve the approach and perform better results.

**Additional context**

**Comment by ValueRaider** [comment]
How exactly would this benefit `yfinance`? Have you done benchmarking?
