### ISSUE TITLE
Can't get history for index fund

### ISSUE THREAD

**Issue by csm10495** [ranaroussi/yfinance#1239]
Example:

```
In [1]: import yfinance as yf

In [2]: yf.download(tickers='FXAIX', prepost=True, period='1d', interval='1m')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- FXAIX: No data found for this date range, symbol may be delisted
Out[2]:
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [3]: yf.__version__
Out[3]: '0.1.87'
```

Though yahoo finance has this listed: https://finance.yahoo.com/quote/FXAIX/

**Comment by csm10495** [comment]
It looks like on the browser it uses a request like: 

```
https://query1.finance.yahoo.com/v8/finance/chart/FXAIX?useYfid=true&range=1mo
```

Looks like both the range/interval has to follow a specific format AND it needs useYfid=true... no idea what that is intended to mean though.

**Comment by ValueRaider** [comment]
> Visit `finance.yahoo.com` and confirm they have your data

Did you confirm they have data for today? You only requested one day of trades, the most recent day.

**Comment by csm10495** [comment]
Ahh ok yeah. I tried '1m' and thought that was month but it was minute. All good. Closing this out.

**Comment by csm10495** [comment]
One other question @ValueRaider: is there a way to just get the 'last/most recent' price?  Like I don't need history beyond just that single price point.

**Comment by ValueRaider** [comment]
`Ticker.info` has 'currentPrice', but that fetch is much more expensive than just fetching a bunch of price history.

**Comment by csm10495** [comment]
the problem with history is that is there a combo of interval/period that work with everything? I was previously using interval=1m and period=1d but that didn't work here.

**Comment by ValueRaider** [comment]
Leave interval alone, the last row close price will always be most recent regardless. It might help to understand what it's fetching - https://finance.yahoo.com/quote/FXAIX/history?p=FXAIX
