### ISSUE TITLE
Ticker info missing fiftyTwoWeekHigh and fiftyTwoWeekLow stats

### ISSUE THREAD

**Issue by DattatrayHinge** [ranaroussi/yfinance#1247]
- Info about your system:
  - yfinance version - 0.1.87
  - operating system - Ubuntu 22.4
  
- Simple code that reproduces your problem
`
    import yfinance as yf

    msft_ticker = yf.Ticker("MSFT")
    print(msft_ticker.info)
`
- The error message
above code used to give **fiftyTwoWeekHigh** and **fiftyTwoWeekLow** in JSON format with some other stats data till Dec 16, 2022. But since Dec 17, 2022, it suddenly stopped giving this information

**Comment by galashour** [comment]
seems to be related to the same issue reported in #1246
