### ISSUE TITLE
ticker.info.get('floatShares') issue.

### ISSUE THREAD

**Issue by Korach250** [ranaroussi/yfinance#1248]
Thanks ranaroussi for this excellent service.

Current issue with ticker.info.get('floatShares').
Only a handful of tickers function, for example: TISI, PASG, SQL

I noticed that 'floatShares' usually returns commas as thousands separator.
However, (for me) the above FUNCTIONING tickers have NO SEPARATORS in float. 
I don't know how these particular symbols were presented before to survive this issue.
Is the issue a yahoo update on how they present the float data?

**Comment by jiangoz** [comment]
Might be related to https://github.com/ranaroussi/yfinance/issues/1246

**Comment by ValueRaider** [comment]
@Korach250 How are those tickers now? I left this issue open because your problem was slightly different.

**Comment by Korach250** [comment]
Excellent. Well done. Learnt a lot looking at your code, thanks.
