### ISSUE TITLE
As of today, the .info function does not provide any information for most tickers (e.g. AAPL). Only very few tickers are supported as of today (e.g. SRAD or HYRE).

### ISSUE THREAD

**Issue by onesoned** [ranaroussi/yfinance#1251]
As of today, the .info function does not provide any information for most tickers (e.g. AAPL). Only very few tickers are supported as of today (e.g. SRAD or HYRE).

**Example for AAPL:**
import yfinance as yf
tickerYF = yf.Ticker("aapl")
print("tickerYF.info:",tickerYF.info)
>>> tickerYF.info: {'regularMarketPrice': None, 'preMarketPrice': None, 'logo_url': ''}

**Example for SRAD:**
import yfinance as yf
tickerYF = yf.Ticker("srad")
print("tickerYF.info:",tickerYF.info) 
>>> tickerYF.info: {'zip': '9000', 'sector': 'Technology', 'fullTimeEmployees': 3700, 'longBusinessSummary': 'Sportradar Group AG, together with its subsidiaries, provides sports data services for the sports betting and media industries in the United Kingdom, the United States, Malta, Switzerland, and internationally. Its sports data services to the bookmaking under the Betradar brand name, and to the international media industry under the Sportradar Media Services brand name. The company offers mission-critical software, data, and content to sports leagues, betting operators, and media companies. In addition, the company provides sports entertainment, gaming solution, and sports solutions, as well as live streaming solution for online, mobile, and retail sports betting. Further, its software solutions address the entire sports betting value chain from traffic generation and advertising technology to the collection, processing, and extrapolation of data and odds, as well as to visualization solutions, risk management, and platform services. Sportradar Group AG was incorporated in 2001 and is headquartered in St. Gallen, Switzerland.', 'city': 'Sankt Gallen', 'phone': '41 71 517 72 00', 'country': 'Switzerland', 'companyOfficers': [], 'website': 'https://www.sportradar.com', 'maxAge': 1, 'address1': 'Feldlistrasse 2', 'fax': '41 71 517 72 99', 'industry': 'Software—Application', 'ebitdaMargins': 0.28054002, 'profitMargins': 0.07038, 'grossMargins': 0.44209, 'operatingCashflow': 154866000, 'revenueGrowth': 0.308, 'operatingMargins': 0.05451, 'ebitda': 189719008, 'targetLowPrice': 7.96, 'recommendationKey': 'buy', 'grossProfits': 269750000, 'freeCashflow': 14732000, 'targetMedianPrice': 17.15, 'currentPrice': 11.44, 'earningsGrowth': None, 'currentRatio': 2.061, 'returnOnAssets': 0.01358, 'numberOfAnalystOpinions': 10, 'targetMeanPrice': 16.87, 'debtToEquity': 29.762, 'returnOnEquity': 0.06584, 'targetHighPrice': 24.89, 'totalCash': 512492000, 'totalDebt': 236903008, 'totalRevenue': 676265024, 'totalCashPerShare': 1.725, 'financialCurrency': 'EUR', 'revenuePerShare': 2.276, 'quickRatio': 1.955, 'recommendationMean': 1.9, 'exchange': 'NMS', 'shortName': 'Sportradar Group AG', 'longName': 'Sportradar Group AG', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EST', 'isEsgPopulated': False, 'gmtOffSetMilliseconds': '-18000000', 'quoteType': 'EQUITY', 'symbol': 'SRAD', 'messageBoardId': 'finmb_1677875322', 'market': 'us_market', 'annualHoldingsTurnover': None, 'enterpriseToRevenue': 4.628, 'beta3Year': None, 'enterpriseToEbitda': 16.498, '52WeekChange': -0.42656642, 'morningStarRiskRating': None, 'forwardEps': 0.22, 'revenueQuarterlyGrowth': None, 'sharesOutstanding': 206572000, 'fundInceptionDate': None, 'annualReportExpenseRatio': None, 'totalAssets': None, 'bookValue': 2.657, 'sharesShort': 4278011, 'sharesPercentSharesOut': 0.014400001, 'fundFamily': None, 'lastFiscalYearEnd': 1640908800, 'heldPercentInstitutions': 0.82082003, 'netIncomeToCommon': 47598000, 'trailingEps': 0.09, 'lastDividendValue': None, 'SandP52WeekChange': -0.15323704, 'priceToBook': 4.305608, 'heldPercentInsiders': 0.03002, 'nextFiscalYearEnd': 1703980800, 'yield': None, 'mostRecentQuarter': 1664496000, 'shortRatio': 15.14, 'sharesShortPreviousMonthDate': 1664496000, 'floatShares': 162756709, 'beta': None, 'enterpriseValue': 3129931520, 'priceHint': 2, 'threeYearAverageReturn': None, 'lastSplitDate': None, 'lastSplitFactor': None, 'legalType': None, 'lastDividendDate': None, 'morningStarOverallRating': None, 'earningsQuarterlyGrowth': None, 'priceToSalesTrailing12Months': 5.023152, 'dateShortInterest': 1667174400, 'pegRatio': 0.59, 'ytdReturn': None, 'forwardPE': 52, 'lastCapGain': None, 'shortPercentOfFloat': 0.0623, 'sharesShortPriorMonth': 5074764, 'impliedSharesOutstanding': 0, 'category': None, 'fiveYearAverageReturn': None, 'previousClose': 12, 'regularMarketOpen': 12.25, 'twoHundredDayAverage': 10.927, 'trailingAnnualDividendYield': 0, 'payoutRatio': 0, 'volume24Hr': None, 'regularMarketDayHigh': 12.34, 'navPrice': None, 'averageDailyVolume10Day': 325580, 'regularMarketPreviousClose': 12, 'fiftyDayAverage': 9.4078, 'trailingAnnualDividendRate': 0, 'open': 12.25, 'toCurrency': None, 'averageVolume10days': 325580, 'expireDate': None, 'algorithm': None, 'dividendRate': None, 'exDividendDate': None, 'circulatingSupply': None, 'startDate': None, 'regularMarketDayLow': 11.21, 'currency': 'USD', 'trailingPE': 127.1111, 'regularMarketVolume': 378144, 'lastMarket': None, 'maxSupply': None, 'openInterest': None, 'marketCap': 3396982016, 'volumeAllCurrencies': None, 'strikePrice': None, 'averageVolume': 277040, 'dayLow': 11.21, 'ask': 11.7, 'askSize': 1200, 'volume': 378144, 'fiftyTwoWeekHigh': 21.98, 'fromCurrency': None, 'fiveYearAvgDividendYield': None, 'fiftyTwoWeekLow': 7.1, 'bid': 11.21, 'tradeable': False, 'dividendYield': None, 'bidSize': 1100, 'dayHigh': 12.34, 'coinMarketCapLink': None, 'regularMarketPrice': 11.44, 'preMarketPrice': None, 'logo_url': 'https://logo.clearbit.com/sportradar.com'}

Were there any changes in yfinance or in Yahoo Finance in the night from December 16th to 17th, 2022?

Best regards
onesoned

_Originally posted by @onesoned in https://github.com/ranaroussi/yfinance/discussions/1250_

**Comment by ValueRaider** [comment]
Check existing issues first before duplicating.

**Comment by onesoned** [comment]
Please name me an existing duplicate, before closing my issue.
