### ISSUE TITLE
yf.Ticker('AAPL').info

### ISSUE THREAD

**Issue by gunnu22** [ranaroussi/yfinance#1254]
Running this module
![2022-12-18_12-26-54](https://user-images.githubusercontent.com/90532373/208311184-a9ab2a16-469d-478e-b198-0567a4076d7d.jpg)
 information extracted is only as attached. It is incomplete. 
Is this a bug or data issue on Yahoo's end ? 

Generally on the weekends, Yahoo data is somewhat erratic. 

Please clarify.

**Comment by ValueRaider** [comment]
Look through recent issues first before posting, particularly the PINNED issue.
