### ISSUE TITLE
How do you get data for NYSE and NASDAQ indexes? (NYA and .IXIC)

### ISSUE THREAD

**Issue by so87** [ranaroussi/yfinance#1269]
## What are you trying to do?
1. Get data for this index: https://www.google.com/finance/quote/.IXIC:INDEXNASDAQ
2. Get data for this index: https://www.google.com/finance/quote/NYA:INDEXNYSEGIS 

## what did you already try:
* yf.Ticker("NASDAQ")
* yf.Ticker("NYSE")
* yf.Ticker(".IXIC")
* yf.Ticker("IXIC")
* yf.Ticker("NYA")

## What did I expect to happen?
I don't want data on the symbols inside those exchanges. I want the index data. I expected this to work like any other ticker(see google links above). I searched through questions and documentation but i couldn't find anything on trying to get just the big composite indexes.

**Comment by galashour** [comment]
nq = yf.Ticker('^IXIC')
nq_data = nq.history(period='3mo')

**Comment by so87** [comment]
@galashour thank you! Is the NYSE index the same? I thought it was odd this wasn't documented because i would assume people would want to get the nasdaq/sp500/dow/etc

**Comment by galashour** [comment]
didn't check the below with yahoo finance, but should work similar to the one above for nasdaq:

NYSE yahoo ticker seems to be '^NYA' or maybe '^XAX'
SP500 yahoo ticker seems to be '^SPX'
DOW index yahoo ticker seems to be '^DJI'

by the way, if you just want to track the trends, you can use the ETFs (e.g, SPY, DIA, etc.).
