### ISSUE TITLE
Ticket data from different timezone are not aligned (bug introduced with #1085)

### ISSUE THREAD

**Issue by DE0CH** [ranaroussi/yfinance#1275]
I am trying to find correlations between tickets in differnet timezone (one in the New York Stock exchange and the other in the London Stock Exchange). Due to changes to the timezone logic, the data in each row of `yfinance.download` are no longer the data of the Tickets at the same time. Using `ignore_tz=False` fixes this problem. This problem didn't exist with version `0.1.77` and previous. So I think by default `ignore_tz` should be set to `False` as that behaviour is consistent with the previous minor versions.

**Comment by ValueRaider** [comment]
But `ignore_tz=True` is default behaviour. Sounds like you copy-pasted from README without reading - post your code please.

**Comment by DE0CH** [comment]
I wrote my code with version `0.1.75`. I upgraded my packages the other day and found out my data analysis was completely off. Using `ignore_tz=False` brought back the old behaviour. See below for a minimal example
```
import yfinance as yf

tickets = yf.download(tickers=f"^FTSE ^DJI", period='7d', interval='1m', ignore_tz=True)
for index, row in tickets.iterrows():
    a = row['Close']['^FTSE']
    b = row['Close']['^DJI']
    # a and b are not data at the same time 

tickets = yf.download(tickers=f"^FTSE ^DJI", period='7d', interval='1m', ignore_tz=False)
for index, row in tickets.iterrows():
    a = row['Close']['^FTSE']
    b = row['Close']['^DJI']
    # a and b ar data at the same time
```

**Comment by ValueRaider** [comment]
I understand now, behaviour has changed since old version. Do you mind submitting a PR?

**Comment by DE0CH** [comment]
Sure. Is the PR just changing the default value to `ignore_tz=False`?

**Comment by ValueRaider** [comment]
Yes. I know it's trivial but I want community to be more involved in code.

**Comment by DE0CH** [comment]
I didn't see doc, so I just updated README.
