### ISSUE TITLE
Holdings data not yet added

### ISSUE THREAD

**Issue by GregoryMorse** [ranaroussi/yfinance#128]
Yahoo! is finally giving holder data which can be pretty valuable to measure what I call the "manipulability" of a stock.  See for example: https://finance.yahoo.com/quote/MSFT/holders?p=MSFT

This is a feature request, any chance we will see it in the next release, as I saw many nice new data was added in 0.1.50?

**Comment by ranaroussi** [comment]
Added in 0.1.51

```
stock.major_holders
stock.institutional_holders
```
