### ISSUE TITLE
Historical data on some stocks have many zeroes in beginning of the 'Open' column

### ISSUE THREAD

**Issue by williamioniana** [ranaroussi/yfinance#1281]
HI,

I am not sure if there is already a fix, but some stocks' historical data seems to have 0 for the first few rows of the column 'Open', for example, the JNJ stock seems to have this issue, and about 1 in 5 stocks have this issue too.

`import yfinance as yf`
`stock = yf.Ticker('JNJ')`
`df = stock.history(period = 'max')`
`pd.set_option('display.max_rows', None)`
`pd.set_option('display.max_columns', None)`
`df = df.drop(columns=['High','Low','Volume','Dividends','Stock Splits'])`
`print(df)`

when I print this out, the column 'Open' seems to have a few zeroes in them
![bug](https://user-images.githubusercontent.com/108611088/211142672-58fd4461-aa87-4133-a892-7a7c708a913e.PNG)

**Comment by ValueRaider** [comment]
Read the issue template carefully

> ### Does Yahoo actually have the data?
> 
> Visit `finance.yahoo.com` and confim they have your data.

If you want `yfinance` to somehow repair bad Yahoo data, that's a whole other discussion.

**Comment by williamioniana** [comment]
Ok turns out I checked the historical prices on charts and it was there, but the actual values from historical data are sometimes 0
