### ISSUE TITLE
Failed to download indices.

### ISSUE THREAD

**Issue by ChunxiaoYang** [ranaroussi/yfinance#1285]
Hi!
I got into trouble when I tried to download S&P500 Index history. The code for S&P500 in Yahoo Finance is ^GSPC, am I right? However I could download stocks like Apple, Amazon successfully. I don't know what is going on. Could you tell me how to fix it? Thanks a lot!
![aapl](https://user-images.githubusercontent.com/121948670/211181767-da0768df-2ead-4182-a521-dc9b9c5735ed.png)
![spx](https://user-images.githubusercontent.com/121948670/211181770-08c6039c-740f-4af5-8be5-dc5f110d27f4.png)

**Comment by ValueRaider** [comment]
Run this, what happens?
```
tz1 = yf.Ticker("^GSPC")._fetch_ticker_tz(debug_mode=True, proxy=proxy, timeout=10)
print("tz1 =", tz1)

from yfinance import utils as yfu
tz2 = yfu.get_tz_cache().lookup("^GSPC")
print("tz2 =", tz2)
```

**Comment by chrisvil** [comment]
I made an update to newest version today and I have the same issue. All ticker data can be loaded but ^GSPC and ^NDX return an empty data frame. Everything worked fine until yesterday (until I made the update today).

**Comment by chrisvil** [comment]
I tried the code above (set proxy to any). tz1 returns none, tz2 returns 'America/New_York'
<img width="288" alt="image" src="https://user-images.githubusercontent.com/59801557/211197807-7bca6538-d342-46ec-8f07-4575959cea89.png">

**Comment by ValueRaider** [comment]
I added a third print, run that too.

**Comment by ChunxiaoYang** [comment]
@ValueRaider Thanks for your help! Though it seems that it doesn't work for me, LOL. I couldn't download any stock data using your code "tz1" and "tz3"(Apple also failed, but I could download Apple using yf.download() so I think it's not the proxy's fault). Due to the internet policy, I couldn't connect to Yahoo without using proxy, so I don't know whether the code "tz2" works or not.  : )
![image](https://user-images.githubusercontent.com/121948670/211198478-8e045aea-86c8-4997-8304-638ea938d218.png)

**Comment by ChunxiaoYang** [comment]
@ValueRaider And if I change the stock code into Apple(AAPL), code "tz3" returns "America/New_York".   : )
![image](https://user-images.githubusercontent.com/121948670/211198733-a8cd7cd8-e76b-4596-8fcb-2a384c7556b0.png)

**Comment by ValueRaider** [comment]
@chrisvil Interesting, `_fetch_ticker_tz()` should always return timezone if ticker valid.

1. I edited my code, can you run 3rd print?
2. Can you debug `_fetch_ticker_tz()` and see what Yahoo returns, specifically this line: `data["chart"]["result"][0]["meta"]["exchangeTimezoneName"]`

**Comment by chrisvil** [comment]
Mhh, now I get error messages

<img width="879" alt="image" src="https://user-images.githubusercontent.com/59801557/211199430-f197d1b3-bcf9-4781-b000-b5849a275a62.png">

**Comment by chrisvil** [comment]
ValueRaider, can you receive valid data when you run simple code to download ^GSPC data? I'm doing a very simple call index_df = pdr.get_data_yahoo(index_name, start_date, end_date) and that worked until yesterday. All other ticker, except ^GSPC and ^NDA works.

**Comment by ValueRaider** [comment]
Yes works fine for me. Which makes debugging this tricky, because you need to help investigate.

**Comment by ChunxiaoYang** [comment]
@chrisvil Can you download other indices like "^DJI" or "^HSI" successfully? I couldn't download these two indices either.  : (

**Comment by chrisvil** [comment]
Just tried, now nothing works (= no data) since I tried your debug code (I was able to download every S&P500 ticker an hour ago). I will restart my Mac completely and try again.

**Comment by ChunxiaoYang** [comment]
@ValueRaider Maybe the version of your yfinance package is an older one? Since @chrisvil said that yesterday an older version worked. My version of yfinance is 0.2.3.

**Comment by chrisvil** [comment]
Machine is back. Version 0.2.3
All S&P500 ticker can be downloaded. ^DJI and ^HSI cannot be downloaded (same issue as ^GSPC and ^NDX). I use the same function call for all.

**Comment by chrisvil** [comment]
I also changed my IP address to different country via VPN ... no difference.

**Comment by chrisvil** [comment]
I found a workaround ... I'm calling the function again when the data frame is empty and that seems to work.
        index_df = pdr.get_data_yahoo(index_name, start_date, end_date)
        if len(index_df) < 20:
            index_df = pdr.get_data_yahoo(index_name, start_date, end_date)

**Comment by ChunxiaoYang** [comment]
@chrisvil Wow! It really works!!! Many thanks for your warm help! Also many thanks to @ValueRaider ! You saved my final project! :)👍 
So maybe pandas_datareader is necessary? I just installed the package pandas_datareader. It seems that I couldn't download indices without it. Anyway, I got the data. 

The following is my code that works: 

import yfinance as yf
from pandas_datareader import data as pdr
yf.pdr_override()
index_df = pdr.get_data_yahoo('^GSPC', start="2021-12-31", end="2022-12-31")
if len(index_df) < 20:
    index_df = pdr.get_data_yahoo("GSPC", start="2021-12-31", end="2022-12-31")
print(index_df)

**Comment by ValueRaider** [comment]
`get_data_yahoo` doesn't do anything except call `yfinance.download` directly. Proof: `pdr.get_data_yahoo == yf.download` = True

So try with `yf.download()`

**Comment by ChunxiaoYang** [comment]
@ValueRaider You are right! pdr.get_data_yahoo equals yf.download. Now my code yf.download() works too! So it's my fault, I didn't installed pandas_datareader at the beginning. After I installed pdr, everything works!

However a new issue appears: 
There is missing data when downloading index "^HSCI". I set the date range(start="2021-12-31", end="2022-12-31"), but the dataframe only includes data from 20130430 to 20210930, and 20210903-20210930 also disappears. I tried several times the results are the same.  :(
![image](https://user-images.githubusercontent.com/121948670/211203978-221b16f3-8eaa-4681-8790-068ed340b7c2.png)

**Comment by ValueRaider** [comment]
```
df6 = pdr.get_data_yahoo(...
```

`pandas-datareader` is an entirely different project

**Comment by pygary** [comment]
python tpo_chart.py ^HSI 2025-11-18
Downloading HSI 1h from 2025-10-27 to 2025-11-19 ...
tpo_chart.py:48: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start=start, end=end, interval=interval, progress=False)

1 Failed download:
['HSI']: YFPricesMissingError('possibly delisted; no price data found  (1h 2025-10-27 -> 2025-11-19)')
No data fetched.
