### ISSUE TITLE
Make a wiki of yfinance

### ISSUE THREAD

**Issue by CollieIsCute** [ranaroussi/yfinance#1287]
With [this reply](https://github.com/ranaroussi/yfinance/pull/1178#issuecomment-1375477108) and #886, I think it's a good time to work on a wiki of yfinance. I think this documentation contains

- Classes
  - Describe "when to use" simply.
  - introduce member functions and data.
- Functions
  - Definition and meaning of each parameters within yfinance.
  - Type of return objects
  - FAQs (solve problems like   #266, #336 )

With the docs, newbies like me could spend less time tracing source code. I spent much time reading source code to find out something like "what's difference between `download()` and  `history()`" and "Which is more efficient when iterating? `List` of `Ticker` objs or `Tickers` obj?"

Last but not least, this is [my first version of wiki](https://github.com/CollieIsCute/yfinance/wiki/Home/2d5a87a0dba525ccbd41591aa31b2de649c37aa7). Is the template looks ok?

**Comment by CollieIsCute** [comment]
I think it might be great if we have a sketch first, then others could improve contents gradually. I will also contribute it. (slowly and steadily😀)

**Comment by ValueRaider** [comment]
Wiki is a great idea, I wasn't aware of it. I would start at a higher level:
- User guides. E.g. guide to financials data?
- API doc (which you've started)

**Comment by CollieIsCute** [comment]
@ValueRaider As far as I see, nope.
You might check this [wiki permission tutorial](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis) for further details. :)

**Comment by ValueRaider** [comment]
Try now

**Comment by CollieIsCute** [comment]
It works 💯
