### ISSUE TITLE
Debian - yfinance - ERROR: Could not build wheels for cryptography, which are required to inatall pyproject.toml-based projects

### ISSUE THREAD

**Issue by SymbReprUnlim** [ranaroussi/yfinance#1288]
### Still think it's a bug? YES, definitely.

- Info about your system:
  - yfinance version - UNABLE TO INSTALL **ANY** yfinance version using    pip3 install yfinance
Python: 3.7.3
platform: Linux-4.19.0-22-686-i686-with-debian-10.13
pip: n/a
setuptools: 65.6.3
setuptools_rust: 1.5.2
rustc: 1.66.0 (69f9c33d7 2022-12-12)

Summary of errors at bottom of terminal console:
 error: command '/usr/bin/i686-linux-gnu-gcc' failed with exit code 1
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

Selected relevant info from attempt to install yfinance
$ pip3 install yfinance
 Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting yfinance
  Using cached https://www.piwheels.org/simple/yfinance/yfinance-0.2.3-py2.py3-none-any.whl (50 kB)
...
...
Collecting cryptography>=3.3.2
  Using cached cryptography-39.0.0.tar.gz (603 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
...
...
Building wheels for collected packages: cryptography
  Building wheel for cryptography (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  Building wheel for cryptography (pyproject.toml) did not run successfully.
  exit code: 1
  
  [300 lines of output]
...

Perhaps install an older version of yfinance (before cryptography became a requirement)?  How to fix problem???

Please help.

**Comment by ValueRaider** [comment]
[This suggests it is an issue with PIP or requirements.txt](https://stackoverflow.com/questions/59441794/error-could-not-build-wheels-for-cryptography-which-use-pep-517-and-cannot-be-i). Why is it trying to compile `cryptography` instead of just downloading it?

**Comment by SymbReprUnlim** [comment]
Debian/Linux is not everywhere uniform or identical. In this Linux case Debian is unable to find a local compiled version of cryptography on the designated machine/OS, so it attempts to compile it.  It is not uncommon to have to compile programs in order to then use them. The machine was using a previous version of yfinance, mostly correctly, until certain yfinance functions stopped returning data in them. On or about 12/20 yfinance was updated and that version WITH CRYPTOGRAPHY is failing.

Per the abbreviated console above, pip is seemingly not the problem.
ref: This error originates from a subprocess, and is likely NOT a problem with PIP.

**Comment by SymbReprUnlim** [comment]
Also, in order to use the "new" version of yfinance, the prior version of yfinance had to be removed prior to pip3 install yfinance.  Again, the machine currently has no yfinance on it, nor apparently any way to install an older, possibly partially working version of yfinance, an earlier version. Obviously the latest version of yfinance would be better.  Other people are apparently having similar problems with cryptography.
Ref. [How to get rid of cryptography build error?](https://stackoverflow.com/questions/66118337/how-to-get-rid-of-cryptography-build-error) 
https://stackoverflow.com/questions/66118337/how-to-get-rid-of-cryptography-build-error

**Comment by ValueRaider** [comment]
Yahoo began encrypting the embedded data stores in December, except price data. We didn't add it for fun, nor is `yfinance` encrypting data so I don't see relevance of chart.

Reason I suggest PIP is problem `cryptography` say:
> [If you are using Linux, then **you should upgrade pip** (in a virtual environment!) and attempt to install cryptography again before trying to install the Rust toolchain. On most Linux distributions, the latest version of pip will be able to install a binary wheel](https://cryptography.io/en/latest/installation/#rust)

Another option: can you install `pycryptodome` instead?

**Comment by SymbReprUnlim** [comment]
"don't see relevance of chart.": Cryptography==Encryption+Decryption. Chart shows exponentially increasing exponential function. Since cryptography now underpins yfinance, yfinance's maintenance coding is likely therefore exponentially more complicated than before cryptography was necessary, ref. "cryptography, which is required to install pyproject.toml-based projects".  Therefore this is a learning moment or not regarding cryptgraphy.

Again, pip is the less likely source of the problem. Pip was upgraded before attempting to install yfinance. Clearly, cryptography is not compiling and that is causing installation failure.

**Comment by ValueRaider** [comment]
> yfinance's maintenance coding is likely therefore exponentially more complicated than before

Nonsense. Chart shows runtime of encryption + decryption. Nothing to do with code maintenance/complexity.

> Clearly, cryptography is not compiling

I never denied the compilation is failing. I only questioned why PIP was compiling instead of just downloading a binary wheel, and whether anything can be done to get PIP to download binary.

You need to meet us halfway here, constructively and precisely, because your issue is unusual - the first crypto issue since release 3 weeks ago.

**Comment by SymbReprUnlim** [comment]
You fail to acknowledge that cryptography significantly increases code complexity, calling it nonsense.
You fail to offer users, including at least this user, a way to install yfinance using a prior, non-cryptographic required version of yfinance.

I will consider possibly installing pycryptodome,, after further researching it.

Meet you halfway? How exactly and precisely have you listened to and understood the perspectives of this user?

In the meantime, attempting to reinstall the current version of yfinance FAILED, yet again, with the exact same errors as was pointed out in the original message. Other software on the Linux/Debian machine is running fine, Scipy, MatPlotLib, Numpy, pandas, json, urllib, requests, tkinter, PySimpleGui, ...

Lastly, yfinance used to be a very useful tool, before the addition of cryptography as a requirement. It had a lot of very useful features, NOT ALL OF WHICH were being blocked by Yahoo, nor cryptography.

I'm not closing this topic because the problem has not been solved for this Debian/Linux user. Thank you very, very much for your time. Personally, I'm saddened you have found zero additional learning in all of this software exercise. Best Regards.

**Comment by ajgringo619** [comment]
Could this be a 32-bit Linux problem? All of **cryptography's** supported versions of Linux are 64-bit.

**Comment by ValueRaider** [comment]
Your attitude is most unhelpful.

> You fail to acknowledge that cryptography significantly increases code complexity, calling it nonsense.

- Wrong. I called your description of the chart nonsense, because it does not show what you claim. Nor is `yfinance` "exponentially" more complicated, that is a mathematical rate-of-change concept e.g. runtime vs key-length.

> You fail to offer users, including at least this user, a way to install yfinance using a prior, non-cryptographic required version of yfinance

- It's likely just you so preferred option is to get PIP installing `cryptography`. instead of maintaining a second non-crypto price-only module just for you.

> Meet you halfway?

- Yes because we are not paid support and your situation is rare.

> How exactly and precisely have you listened to and understood the perspectives of this user?

- Summary: Compilation is failing. You don't know why PIP is choosing to compile, nor do you care. You want us to provide a custom non-crypto `yfinance` just for you, instead of helping fix your compilation issue.

> In the meantime, attempting to reinstall the current version of yfinance FAILED

- Of course it failed, nothing changed, and I never requested you reinstall.

**Comment by ValueRaider** [comment]
@ajgringo619 Good point, I see now their platform is 32-bit.

**Comment by SymbReprUnlim** [comment]
Q: Could this be a 32-bit Linux problem?
A: (from user) Very possibly, but difficult to perform any specific tests since cryptography just will not compile.

Some partial good news for me and by me (self-congratulary pat-on-the-back): I was able to restore yfinance version 0.1.87 (which is a pre-cryptography version) using the Terminal command:
$ pip3 install yfinance==0.1.87

Keeping older versions of software around can be very very helpful, particularly when some new requirement becomes an edict and integrated into a production version of new or revised software.  Not everybody is immediately familiar with determining older versions of software available and how to install those, prior, earlier, partially or fully-functional, still-working versions.

This at least restores partial functionality of yfinance until all the Debian/Linux/32 vs. 64-bit kinks can be worked out regarding cryptography. This is not a viable long-term solution, but it sure helps keep the basic hammer and screwdriver (basic Yahoo data retrieval) tools busy in the meantime, instead of zero yfinance tools available.  Again, not all the Yahoo information available under yfinance is cryptographically protected or unavailable.

Thanks for thinking about the problem.

**Comment by ajgringo619** [comment]
OK, I think I've made some progress. Running **Debian 11 i386** - it was the ISO I had downloaded awhile back - I was able to get **cryptography** to build. The key was to install **libssl-dev**. Another option that I found is to install the **python3-crytography** package (yes, it exists for **Debian 10**). The version is older - 2.6.1-3+deb10u2 - but it should still work.

**Comment by SymbReprUnlim** [comment]
A Major Congratulations to ajgringo619! You successfully decoded the "Debian Buster 10" install of yfinance!
The 2-3 needed commands were:
$ sudo apt install libssl-dev
followed by a
$ pip3 install yfinance                    [after first doing a pip3 uninstall yfinance   to delete the previous version (0.1.87 or whatever) of yfinance]

The above installed yfinance without any errors!  I have yet to try out yfinance for several of its previously non-working tools, but the install went without incident.  Again, thank you - that missing "libssl-dev" was THE missing correctly-create-library link.

The "Building wheel for cryptography (pyproject.toml) ... done" and "Created wheel for cryptography" steps completed without erroring out, seamlessly.  I still have reservations with cryptography and the original intent of the Internet which was to open up communications around the world, but Putin and unrestrained hackers around the world make open communications impossible.  There is a sometimes hidden overhead CPU processing cost/speed/throughput reduction due to encryption/decryption, especially for large amounts of data.

Thanks again for decoding the process!  Happy Friday! Cheerio!

**Comment by ajgringo619** [comment]
You're most welcome; glad it ended up being something simple.
