### ISSUE TITLE
cash_flow and cash_flow attributes are missing for some yfinance.Ticker objects

### ISSUE THREAD

**Issue by tjrix** [ranaroussi/yfinance#1292]
For example, if you try TSX tickers "CP.TO" or "CNR.TO", the income statements (quarterly and annually) and balance sheet statements (quarterly and annually) DataFrames are populated in the class, but the cashflow statement attributes (quarterly and annually" both are blank; They are instantiated as string objects and are not DataFrames yet. Thanks!

**Comment by ValueRaider** [comment]
This is related to #1291. Only price data will work.

**Comment by ValueRaider** [comment]
This is related to #1291. Only price data is working.

**Comment by tjrix** [comment]
Sure, no problem. Here is the chunk that should do it. In my code it was spread over some other code bits but I think this extract covers it...

It fails on the last line as it can't seem to generate the cashflow statement for CP.TO (an others)

tick_str = 'CP.TO'
session = requests_cache.CachedSession('yfinance.cache')
yf_results = yf.Tickers(tick_str, session=session)
annual_cashflow_statement_df = yf_results.tickers['CP.TO'].cashflow

**Comment by tjrix** [comment]
This morning I found a similar case, but different, for ticker = 'CCL-B.TO'.  Income statement and Cashflow statement worked for that one, but now it is the balance sheet that fails to populate within the ticker object.

**Comment by ValueRaider** [comment]
Not seeing this error anywhere?

> TypeError: string indices must be integers

Can you try with the fork/branch in #1297

**Comment by chongwuyang** [comment]
i have the same problem , some tickers return empty dataframe

>>> t=yf.Ticker('GPN')
>>> t.cashflow
Empty DataFrame
Columns: []
Index: []
>>> t.quarterly_cashflow
Empty DataFrame
Columns: []
Index: []

**Comment by ValueRaider** [comment]
Can't reproduce bug with latest yfinance
