### ISSUE TITLE
yf.Ticker(ticker).info Error

### ISSUE THREAD

**Issue by robertluisw** [ranaroussi/yfinance#1293]
# yf.Ticker(ticker).info TypeError

**- Info about your system:**

  - yfinance version
    0.2.3

  - operating system
  Windows 10

**- Simple code that reproduces your problem**
import yfinance as yf
ticker = 'AAPL'
stock_info = yf.Ticker(ticker).info

**- The error message**
TypeError: string indices must be integers, not 'str'

**Comment by ValueRaider** [comment]
Duplicate of #1291

**Comment by robertluisw** [comment]
I didn't see the duplicate issue.  Thanks for all your help @ValueRaider.
