### ISSUE TITLE
KeyError: 'regularMarketPrice' not working in version 1.50

### ISSUE THREAD

**Issue by ricardomerces** [ranaroussi/yfinance#130]
Ran, 

'regularMarketPrice' working on version 1.45

This key is very relevant (to me ...)

**Comment by kennguyen01** [comment]
I had the same issue so I used regularMarketOpen to keep my app working.

**Comment by ranaroussi** [comment]
Fixed in 0.1.51 :)

**Comment by ricardomerces** [comment]
Thank you!
