### ISSUE TITLE
Extremely minor changes, but would be really useful for me

### ISSUE THREAD

**Issue by james-stevens** [ranaroussi/yfinance#1304]
1. Would be nice to have the following properties included in (say) `info`
    - `regularMarketTime` - market's time stamp of the price given
    - `marketState` - shows the trading status of the market, e.g. open, closed etc
    
     I use both of these in my s/w

2. Would be nice if it supported getting quotes on currency prices. I have shares in foreign currencies & crypto assets, so I have them included in my portfolio tracker, e.g. `GBPUSD=X` or `BTC-USD`

So far I've got round both of these issues by simply adding an `all` property to the `Quote` class to make the original JSON available externally (which might be a nice feature to include anyway), but in my experience custom mods to open source are always unsatisfactory.

If anybody is interested in my portfolio tracker its - https://github.com/james-stevens/diamond-hands - its hard coded to price everything in GBP, but that should be easy to change. 

It requires a MySQL backend & comes with a WebUI with a few graphs. Right now, it just tracks the portfolio value & provides some graphs. Right now, adding trades & closing trades needs to be done manually in SQL!

Warning: its *very* insecure cos the rest/api gives direct access to the SQL database, so use with caution, like don't make it publicly accessible.

**Comment by ValueRaider** [comment]
`regularMarketTime` - is this covered by `Ticker.get_history_metadata()["regularMarketTime"]` ?

`marketState` - can derive this from `Ticker.get_history_metadata()["currentTradingPeriod"]`

Feel free to submit pull requests, sometimes code is easier to review.

**Comment by ValueRaider** [comment]
@james-stevens Close this issue if you don't want changes to `yfinance`.
