### ISSUE TITLE
yfinance 0.1.96: Unable to load ticker information or financial data

### ISSUE THREAD

**Issue by uzala92** [ranaroussi/yfinance#1309]
It seems that yfinance version 0.1.96 since a few days ago does not return neither the ticker information nor the financial data. 

Example:
stock = yf.Ticker("AAPL")
print(stock.info)

Output:
{'regularMarketPrice': None, 'preMarketPrice': None, 'logo_url': '', 'trailingPegRatio': 2.6006}

**Comment by robertluisw** [comment]
This issue is addressed in #1291. It should be fixed with the most recent update.  pip install the newest version to fix.

**Comment by uzala92** [comment]
Thanks for your response. I thought a version 0.1.97 would be released as it was previously stated that version 0.1.* was going to continue to have support. I am still using it and that is why I have opened the issue because it seems that it has not yet been fixed for this version.

**Comment by ValueRaider** [comment]
> version 0.1.* was going to continue to have support

Fair point. This was intended to allow time for (i) 0.2 to be stress-tested and (ii) users to adjust. Any reason you can't switch?

**Comment by uzala92** [comment]
I have a database where the nomenclature is adjusted to the indexes with space of the fundamental of version 0.1.*. In version 0.2.* the indices with "legacy=True" are mismatched with the data that I already have stored since the indices are without spaces and it involves big changes to make the jump to the new version. Anyway, knowing that it is as you say, I will work to see how to make compatible the new indexes with the database that I have now. Thank you very much.

**Comment by ValueRaider** [comment]
> the indices are without spaces

Read the function arguments. You can restore spaces.
