### ISSUE TITLE
Ticker info gives error

### ISSUE THREAD

**Issue by raaheim** [ranaroussi/yfinance#131]
Hi, thanks for the great package.

In version 1.50, when I run the following code.

aapl = yf.Ticker("AAPL")
aapl.info

I get the attatched error

Currently on 0.25.3 of pandas.

[error.txt](https://github.com/ranaroussi/yfinance/files/3840366/error.txt)

**Comment by khannema** [comment]
I have got the same error after trying to get either yf.Ticker.info/ balance_sheet/ financials/ cashflow.
Seems to be related to a call to pandas in _get_fundamentals().
I already tried to downgrade pandas but received the same error.
[yfinance_error.txt](https://github.com/ranaroussi/yfinance/files/3870134/yfinance_error.txt)

**Comment by peruzzoa** [comment]
You can fix this by changing the file ~/anaconda3/lib/python3.6/site-packages/yfinance/base.py

line 269 from:
                      s = _pd.DataFrame(index=[0], data=d)[-1:].T
to: 
                     s = _pd.DataFrame(index=[0], data=[d])[-1:].T

**Comment by khannema** [comment]
Thanks a lot! This did the trick. It is working again.

**Comment by nga-27** [comment]
This is a wonderful fix.  

Another note:
Running 2 different tickers, specifically `MSFT` and `MMM`, one of these worked and the other showed the error above.  By wrapping "d" in a list as shown above (`... data=[d])...`), both cases work now. Thank you for your help!

**Comment by amartin211** [comment]
Hi, this fix (data=[d]) doesn't seem to be working anymore as I'm facing the same issue. (i.e. tried with ticker "MMM"). Error is still on line 269 of base.py but not sure what to do. Anyone has any idea please ? thanks

**Comment by ranaroussi** [comment]
Fixed in 0.1.51 :)

**Comment by amartin211** [comment]
Thanks, have upgraded to 0.1.51. 
There seems to be a tiny fix to be done as I'm now getting this error => 
"ValueError: unit='s' not valid with non-numerical val='{'raw': 1546214400, 'fmt': '2018-12-31'}" when I'm calling yf.Ticker("MMM").info
That's line 255 of base.py in the function cleanup(data). Have tried to fix it myself but without success thus far..

**Comment by ranaroussi** [comment]
Can you update to version 0.1.52 and see if the problem was solved?

```
$ pip install yfinance -U
```

Thanks!

**Comment by amartin211** [comment]
Looks good! many thanks for looking into it so quickly.

**Comment by ranaroussi** [comment]
👍
