### ISSUE TITLE
0.2.3 yf.download() was working up to Jan 13, 2023, but now the df is empty except for crypto tickers.

### ISSUE THREAD

**Issue by Bill-Fujimoto** [ranaroussi/yfinance#1310]
- Info about your system:
  - 0.2.4
  - Windows 10
- Simple code that reproduces your problem
```
def get_data(tickers: List[str]):
    startdate = date. Today()
    ydata = yf.download(tickers, startdate) # DataFrame with all tickers
    ydata.reset_index(inplace=True) # Date index is Datetime from yahoo
    print(ydata)
```
- Print statement result
![image](https://user-images.githubusercontent.com/40809714/212731612-591df375-f1ce-4bb8-90c9-46e93dec7900.png)

yf version 0.2.3 was working fine up thru Jan 13 but suddenly stopped from Jan 14 onward. 0.2.4 does the same thing. I'm wondering if yahoo finance is doing something weird as crypto tickers are working but regular stock tickers are not working as shown in the screen capture.  I can see the stock ticker data on finance.yahoo.com but the ticker data is NaN in the dataframe.

**Comment by Bill-Fujimoto** [comment]
Just realized the US market is closed for MLK holiday.  I think that explains the empty data except for crypto.
It would be nice if the data returned would be for the most recent trading day, just as it is shown on the yahoo finance page.

**Comment by 31deerfield2** [comment]
Right. It looks like only US market data is not available. I tried with different markets (TSX) and it is working fine.

**Comment by Bill-Fujimoto** [comment]
No real issue, just a matter of not expecting valid quotes on non-trading days

**Comment by ValueRaider** [comment]
`history()` returns what the chart shows. No trades = no data.
