### ISSUE TITLE
data_stores is a string instead of a dictionary

### ISSUE THREAD

**Issue by DanielKirshner** [ranaroussi/yfinance#1312]
I'm getting this error:
`TypeError: string indices must be integers`

The error is caused by the following line:
`keys = _finditem1("key", data_stores['FinancialTemplateStore'])`

It seems that data_stores is a string instead of a dictionary, and it's causing the TypeError when trying to access the key 'FinancialTemplateStore' on it.

I have tried to update my yfinance library to the latest version, but it doesn't help.
I have also tried to change the version of python that running the script on.

**Comment by DanielKirshner** [comment]
I've tried with python 3.8.10 , 3.10.0 and 3.11.0

**Comment by DanielKirshner** [comment]
I've tried with those python versions - 3.8.10 , 3.10.0 , 3.11.0. 
yfinance version - 0.2.4

**Comment by rickturner2001** [comment]
can you give us some more context? what are you trying to do here? in the meantime, you should check the type of all variables with type. It seems like data_stores might be a list and not a dictionary.

**Comment by DanielKirshner** [comment]
This is part of my project - https://github.com/DanielKirshner/Dividend-Stocks-Analyzer
I'm using yfinance and get the error mentioned above...
The line I mentioned is not part of my code. It's probably a wrong implementation inside yfinance source code.

**Comment by DanielKirshner** [comment]
> can you give us some more context? what are you trying to do here? in the meantime, you should check the type of all variables with type. It seems like data_stores might be a list and not a dictionary.

This is part of my project - https://github.com/DanielKirshner/Dividend-Stocks-Analyzer
I'm using yfinance and get the error mentioned above...
The line I mentioned is not part of my code. It's probably a wrong implementation inside yfinance source code.

**Comment by DanielKirshner** [comment]
> can you give us some more context? what are you trying to do here? in the meantime, you should check the type of all variables with type. It seems like data_stores might be a list and not a dictionary.

@rickturner2001 
This is part of my project - https://github.com/DanielKirshner/Dividend-Stocks-Analyzer
I'm using yfinance and get the error mentioned above...
The line I mentioned is not part of my code. It's probably a wrong implementation inside yfinance source code.

**Comment by scottangle** [comment]
I was getting this issue a little bit ago on 0.2.3, but after upgrading to 0.2.4 it went away. I did a `pip uninstall` and then a `pip install` if that makes a difference. Very likely could be an intermittent issue as @jjbiggins said. Instead of returning a json the store object was an encoded string that looked similar to a base64 string.

**Comment by ValueRaider** [comment]
`data_stores` code has been removed
