### ISSUE TITLE
There are too many columns.

### ISSUE THREAD

**Issue by WonSeokChoi-Unicorn** [ranaroussi/yfinance#1313]
# READ BEFORE POSTING

### Are you up-to-date?

Upgrade to the latest version and confirm the issue/bug is still there.

`$ pip install yfinance --upgrade --no-cache-dir`

Confirm by running:

`import yfinance as yf ; print(yf.__version__)`

and comparing against [PIP](https://pypi.org/project/yfinance/#history).

### Does Yahoo actually have the data?

Visit `finance.yahoo.com` and confim they have your data. Maybe your ticker was delisted.

Then check that you are spelling ticker *exactly* same as Yahoo.

### Are you spamming Yahoo?

Yahoo Finance free service has limit on query rate (roughly 100/s). Them delaying or blocking your spam is not a bug.

### Still think it's a bug?

Delete this default message and submit your bug report here, providing the following as best you can:

- Info about your system:
  - yfinance version : 0.2.3
  - operating system : Windows 10 64 bit 21H2
- Simple code that reproduces your problem
import yfinance as yf
timeinterval = '60m'
dateperiod = '5d'
stockcode = "NI PR B"
df = yf.download(stockcode, interval = timeinterval, period = dateperiod, progress = False) 

Open, High, Low, Close, Adj Close, Volume Only 6 items should appear, but there is a problem with 18 items appearing.

**Comment by rickturner2001** [comment]
Hey @WonSeokChoi-Unicorn, this is not actually a bug, you're passing the wrong ticker!

Take a look at the first two lines in the definition for the download function:

```python3
  # create ticker list
    tickers = tickers if isinstance(
        tickers, (list, set, tuple)) else tickers.replace(',', ' ').split()
```

This means that if you pass a string of tickers separated by a whitespace, split will transpose your string

```python3
 "NI PR B"
```
onto a list of 3 tickers: 

```
["NI", "PR", B"]
```

This also explains why you get 18 columns. Each ticker produces six columns on its own: Open, High, Low, Close, Adj Close, and Volume.

**Comment by WonSeokChoi-Unicorn** [comment]
> Hey @WonSeokChoi-Unicorn, this is not actually a bug, you're passing the wrong ticker!
> 
> Take a look at the first two lines in the definition for the download function:
> 
> ```python
>   # create ticker list
>     tickers = tickers if isinstance(
>         tickers, (list, set, tuple)) else tickers.replace(',', ' ').split()
> ```
> 
> This means that if you pass a string of tickers separated by a whitespace, split will transpose your string
> 
> ```python
>  "NI PR B"
> ```
> 
> onto a list of 3 tickers:
> 
> ```
> ["NI", "PR", B"]
> ```
> 
> This also explains why you get 18 columns. Each ticker produces six columns on its own: Open, High, Low, Close, Adj Close, and Volume.

Thanks for your explanation.

I wil not use symbol contain blank.

**Comment by rickturner2001** [comment]
@WonSeokChoi-Unicorn Very good! please close the discussion.
