### ISSUE TITLE
Parsing FinancialTemplateStore failed

### ISSUE THREAD

**Issue by uzala92** [ranaroussi/yfinance#1314]
I have noticed that I am not able to obtain some specific stock fundamentals even though they exist in yahoo finance. This has been tested with version 0.2.4, repeated multiple times just in case. Example:

stock = yf.Ticker("4HP.BE")
cashflow_quart = stock.get_cashflow(proxy=proxy, freq="quarterly", legacy=False)
print(cashflow_quart)

Result:
**- 4HP.BE: Failed to create cash-flow financials table for reason: YFinanceDataException("Parsing FinancialTemplateStore failed, reason: KeyError('FinancialTemplateStore')")**
Empty DataFrame
Columns: []
Index: []

This error "_4HP.BE: Failed to create cash-flow financials table for reason: YFinanceDataException("Parsing FinancialTemplateStore failed, reason: KeyError('FinancialTemplateStore')")"_ appears just sometimes.

Here yo can find that the cashflow table I am requesting actually exists: https://es.finance.yahoo.com/quote/4HP.BE/cash-flow?p=4HP.BE (see quarts)

It seems that being the spanish domain (es.finance.yahoo.com) the table exists but not in the general domain (finance.yahoo.com)...

**Comment by ValueRaider** [comment]
1. I only see one row of actual data in quarterly cash flow, so does it really exist?
2. "Isetan Mitsukoshi Holdings" is a Japanese company on Tokyo exchange, why are you using an obscure German ticker?

**Comment by uzala92** [comment]
I am currently processing a large group of stock... This appears to be a Japanese stock that is also listed in Germany. Do you think it is a bug that it has not returned the table or is it part of the normal scraping behavior of yfinance?

Thanks for your work and best regards.

**Comment by ValueRaider** [comment]
Yahoo hasn't got the data 🤷 . See 1

**Comment by uzala92** [comment]
I think it is because in the "non-Spanish" web there is no table as you point out. Thanks!
