### ISSUE TITLE
No summary info found, symbol may be delisted

### ISSUE THREAD

**Issue by ganynmednet** [ranaroussi/yfinance#1315]
Just started receiving the following error for the most of SP500 & Nasdaq stocks: **_No summary info found, symbol may be delisted_**

```
import yfinance as yf

test = yf.Ticker("AMZD") # KARO, CSTL, FALN, etc
print(test.info)
```

**Comment by ajgringo619** [comment]
Working here (yfinance 0.2.4); tried the 1st couple in your list. Maybe a temporary glitch on Yahoo?

**Comment by ganynmednet** [comment]
yeah, also it's probably yahoo's rate limiter. I've been querying stocks in 20 threads, after 1-2k queries it starts returning this error
