### ISSUE TITLE
.history() function broken 

### ISSUE THREAD

**Issue by lysmm203** [ranaroussi/yfinance#1318]
I'm currently running the latest yfinance version (0.2.4.), and the update seems to have broken the history function. 

`msft = yf.Ticker("MSFT"
msft.history(period="max")`

The two lines of code above are enough to replicate the error. The error message that pops up is sqlite3.IntegrityError: NOT NULL constraint failed: kv.key

**Comment by ValueRaider** [comment]
Post the traceback

**Comment by ajgringo619** [comment]
Are you sure that code is accurate? If I run:
```
msft = yf.Ticker("MSFT")
msft.history(period="max")
```
I get data back to 1986.

**Comment by ValueRaider** [comment]
#1321 is same problem but documented better, so fixing efforts are there.

**Comment by lysmm203** [comment]
Noted, thanks!

**Comment by pumpk1nco** [comment]
Just got the same problem as it was installed by pip install yfinance inside VS Code, conda install yfinance again problem solved.
