### ISSUE TITLE
NameError ... not defined

### ISSUE THREAD

**Issue by mariachi9999** [ranaroussi/yfinance#132]
Hello! Thank you so much for this tool!

I am really new at programming!

When I use your tool, I receive this error:

_>>> AA.info
Traceback (most recent call last):
  File "<pyshell#100>", line 1, in <module>
    AA.info
NameError: name 'AA' is not defined_

Please, what am I missing?

Thx!!!

**Comment by kennguyen01** [comment]
If you want to access the data of AA ticker, assign a variable to that Ticker module. something like `aa = yf.Ticker('AA')`. Then you can call `aa.info`. Refer to the [README](https://github.com/ranaroussi/yfinance).
