### ISSUE TITLE
yfinance 0.2.4: Unable to load ticker information 

### ISSUE THREAD

**Issue by VG2000** [ranaroussi/yfinance#1320]
** Same issue as #1246 last month **

- Info about your system:
  - yfinance version - 0.2.4
  - operating system - MacOS Ventura 13.0.1
  
- Simple code that reproduces your problem
`yf.Ticker('TSLA')
 tsla.info`

- The error message
Function returns : {'regularMarketPrice': None,
 'preMarketPrice': None,
 'logo_url': '',
 'trailingPegRatio': 1.22}

**Comment by ajgringo619** [comment]
Working here on **Linux**. Does another symbol work?

**Comment by VG2000** [comment]
Unfortunately not. For AAPL I get : `{'regularMarketPrice': None,
 'preMarketPrice': None,
 'logo_url': '',
 'trailingPegRatio': 2.627}`

**Comment by Tarsopilami** [comment]
Same problem here, with Linux.

**Comment by boscomanilow128** [comment]
my same code didnt work on Linux (Ubuntu) but as I do that on Google Colab, it worked. not sure why.

**Comment by 31deerfield2** [comment]
Same is happening with me. Info is returning as None for any symbol.

**Comment by boscomanilow128** [comment]
> my same code didnt work on Linux (Ubuntu) but as I do that on Google Colab, it worked. not sure why.

just note that my pandas on Google Colab was 1.3 but on my Ubuntu Linux was 1.5. Maybe the older 1.3 version somehow matches with the yfinance API. just my two cents.

**Comment by Jeanfabra** [comment]
I Tried updating yfinance module and now I get this output:
Exception: Yahoo has again changed data format, yfinance now unsure which key(s) is for decryption

**Comment by ValueRaider** [comment]
@Jeanfabra Search through existing issues before posting.

**Comment by kang-im** [comment]
same issue, I tried many times was fail

**Comment by iFalkon** [comment]
Same issue, tried across a wide variety of tickers. Returning nothing. Other functions seem to work, though. I just need to get float information.

**Comment by Tarsopilami** [comment]
Update to latest version - it works !

**Comment by VG2000** [comment]
The 0.2.9 update has fixed my issue. Thanks.

**Comment by meekey463** [comment]
installing the latest version of 0.2.33 resolved the issue
