### ISSUE TITLE
Routing console info to logging file

### ISSUE THREAD

**Issue by Ruin2121** [ranaroussi/yfinance#1322]
**Describe the problem**
I'd like to be able to route the info that yfinance sends to the console into a log file.
Example:
AAC: No earnings dates found, symbol may be delisted
AACI: No earnings dates found, symbol may be delisted
AACIU: Yahoo did not return share count in date range 2021-07-21 00:00:00-04:00 -> 2023-01-21 00:00:00-05:00
AACIU: No earnings dates found, symbol may be delisted
AACIW: 1d data not available for startTime=-2208994789 and endTime=1674224959. Only 100 years worth of day granularity data are allowed to be fetched per request.
AACIW: 1d data not available for startTime=-2208994789 and endTime=1674224959. Only 100 years worth of day granularity data are allowed to be fetched per request.
AACIW: 1d data not available for startTime=-2208994789 and endTime=1674224959. Only 100 years worth of day granularity data are allowed to be fetched per request.
AACIW: 1d data not available for startTime=-2208994789 and endTime=1674224959. Only 100 years worth of day granularity data are allowed to be fetched per request.
AACIW: 1d data not available for startTime=-2208994789 and endTime=1674224959. Only 100 years worth of day granularity data are allowed to be fetched per request.
AACIW: Yahoo did not return share count in date range 2021-07-21 00:00:00-04:00 -> 2023-01-21 00:00:00-05:00
AACIW: No earnings dates found, symbol may be delisted

Truthfully, this may already be possible, but I've seen no documentation regarding how to do this.

**Describe the solution**
My best guess to implement this could be to set the api up to optionally accept a logger "variable", perhaps in the main ticker class/function so that it populates to the individual information grabbers.

**Comment by ValueRaider** [comment]
Checkout the `dev` branch, this uses the Python `logging` module which can easily be configured to write to file. Feel free to request more changes.
