### ISSUE TITLE
Pandas

### ISSUE THREAD

**Issue by anglosachs** [ranaroussi/yfinance#1323]
Issues with the date time object since Jan 12 2023. When calling a ticker/fx pair the data frame is now showing a time stamp; Ben working with yfinance for a year now and never encountered this - also, finding more problems when trying to call to fx pairs together in the same data frame.

**Comment by irezumi** [comment]
Try:

dataframe = dataframe.tz_localize(None)

to remove time zone localisation in DataFrame index.

My error was: FutureWarning: Indexing a timezone-aware DatetimeIndex with a timezone-naive datetime is deprecated and will raise KeyError in a future version. Use a timezone-aware object instead.

I compared pd.DatetimeIndex with datetime.now().

**Comment by ValueRaider** [comment]
Or do what it says, use timezone-aware datetime e.g. `pandas.Timestamp.utcnow()`
