### ISSUE TITLE
version 0.2.4 incompatibility?

### ISSUE THREAD

**Issue by tab-co** [ranaroussi/yfinance#1325]
Version 0.2.4 appears not to play nicely with pandas.  Pandas issues a runtime error of "ValueError: Excel does not support datetimes with timezones. Please ensure that datetimes are timezone unaware before writing to Excel.".  Rolling back to version 0.2.3 clears up the problem

**Comment by nexbelgium** [comment]
Indeed, it doesn't work for me neither since 0.2.4

**Comment by irezumi** [comment]
Try:

dataframe = dataframe.tz_localize(None)

to remove time zone localisation in DataFrame index.

My error was: FutureWarning: Indexing a timezone-aware DatetimeIndex with a timezone-naive datetime is deprecated and will raise KeyError in a future version. Use a timezone-aware object instead.

I compared pd.DatetimeIndex with datetime.now().

**Comment by tab-co** [comment]
Yfinance version 0.2.9 still fails without using the fix from irezumi.  If I use yfinance 0.2.3, all is well.  I was messaged with what versions of pytz and pandas I was using - here's the complete list of versions I'm using for yfinance dependencies but with sensitive file location information redacted:

Collecting yfinance
  Downloading yfinance-0.2.9-py2.py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 kB 971.5 kB/s eta 0:00:00
Requirement already satisfied: pandas>=1.3.0 in .....\lib\site-packages (from yfinance) (1.5.3)
Requirement already satisfied: numpy>=1.16.5 in .....\lib\site-packages (from yfinance) (1.24.1)
Requirement already satisfied: requests>=2.26 in .....\lib\site-packages (from yfinance) (2.28.2)
Requirement already satisfied: multitasking>=0.0.7 in .....\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in .....\lib\site-packages (from yfinance) (4.9.2)
Requirement already satisfied: appdirs>=1.4.4 in .....\lib\site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in .....\lib\site-packages (from yfinance) (2022.7.1)
Requirement already satisfied: frozendict>=2.3.4 in .....\lib\site-packages (from yfinance) (2.3.4)
Requirement already satisfied: cryptography>=3.3.2 in .....\lib\site-packages (from yfinance) (39.0.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in .....\lib\site-packages (from yfinance) (4.11.1)
Requirement already satisfied: html5lib>=1.1 in .....\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in .....\.lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.2.post1)
Requirement already satisfied: cffi>=1.12 in .....\lib\site-packages (from cryptography>=3.3.2->yfinance) (1.15.1)
Requirement already satisfied: six>=1.9 in .....\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in .....\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in .....\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in .....\lib\site-packages (from requests>=2.26->yfinance) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in .....\lib\site-packages (from requests>=2.26->yfinance) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in .....\lib\site-packages (from requests>=2.26->yfinance) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in .....\lib\site-packages (from requests>=2.26->yfinance) (2022.12.7)
Requirement already satisfied: pycparser in .....\lib\site-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)
Installing collected packages: yfinance
  Attempting uninstall: yfinance
    Found existing installation: yfinance 0.2.3
    Uninstalling yfinance-0.2.3:
      Successfully uninstalled yfinance-0.2.3
Successfully installed yfinance-0.2.9

**Comment by ValueRaider** [comment]
Or just do what Excel requests:
> ensure that datetimes are timezone unaware before writing to Excel
```
df = df.tz_convert(None)
```

Excel is the problem for not handling timezone-aware datetimes, a perfectly reasonable requirement.
