### ISSUE TITLE
NSE Data Mismatch

### ISSUE THREAD

**Issue by goki75** [ranaroussi/yfinance#1326]
While using yfinance==0.2.4, i am finding the ticker data returned
is not tallying with that at yahoo finance site ... i seem to be getting 
some kind of interpolated data unrelated to actual ticker data

For 24/Jan/2022  the OHLCV Ticker Values returned by Yfinance "AEGISCHEM.NS"

**205.43  209.177  193.611  195.119   876049**

![from Yfinance](https://user-images.githubusercontent.com/399954/213885161-2add1ce5-5ab7-4e88-b5d2-c88f530f6e01.jpg)

But From Finance.Yahoo.com the actual values are

**211.15    215.00    199.00   200.55       876050**

![Picture2](https://user-images.githubusercontent.com/399954/213885180-acb26efe-080b-4d86-a561-c25a7ad32789.png)

The error exists for almost all historical values

Even checked manually  from yahoo finance

https://query1.finance.yahoo.com/v8/finance/chart/AEGISCHEM.NS?symbol=AEGISCHEM.NS&period1=1642968752&period2=1674331826&useYfid=true&interval=1d

![Screenshot 2023-01-22 014611](https://user-images.githubusercontent.com/399954/213885707-8dad3087-9ae6-449c-87c2-9dc0b85d8ee7.png)

the Yfinance is seemingly scraping data from some place else

**Comment by ValueRaider** [comment]
`history` is adjusting for dividends. README didn't say so not your fault.

We're working on improving docs via the Wiki, can you review and feedback if helpful?
