### ISSUE TITLE
Hi guys,

### ISSUE THREAD

**Issue by BobCeulemans** [ranaroussi/yfinance#1331]
Hi guys,

I love yfinance (thanks RanAroussi)! Now I am very sad!
I have developed a Python program based on yf 0.1.x that extracts fin data from YF and performs a very thorough financial analysis on practically any number, values the company and gives its own score and advice. I was testing the program practically every day before I making it public.

But suddenly, two or three weeks ago, my program (called tickertwister) stopped working! I have not updated yf 0.1.74. Then updated to 0.1.94 and disabled quantstats (which was the only program used in tickertwister that also had an update) and the program worked again. After a few days I updated to yf 0.2.3 and it stopped working so downgraded back to 0.1.94. Now, a week ago, everything stopped working again.

I am a novice developer (started learning Python 6 months ago and worked very hard to be able to develop tickertwister. I have written more than 8500 lines of code.) Now I have not programmed for a few months and I have forgotten many things (I learn very quickly, but forget very quickly if I don't repeat it weekly).

My question: Why did my program stop working while yf was not yet updated? Thanks for any advice!

_Originally posted by @BobCeulemans in https://github.com/ranaroussi/yfinance/discussions/1324_

**Comment by mexicantexan** [comment]
It is not a yfinance issue but the underlying API to Yahoo Finance. Yahoo changed it recently, so you'll have to upgrade to the latest (as of writing -> 0.2.4) to get your stuff working again. 

From a development standpoint, this is unfortunately common when dealing with external APIs. This is also why companies and developers that provide wrappers for APIs get paid a decent amount. The end user paying for these wrappers is looking for stability without having to adjust their codebase as much. This wrapper is provided free of charge on the backs of a lot of developers, as such there will be moments like this where things break and the open-source community scrambles to patch the issue. If you need absolute stability and LTS then you should look to paid API wrappers, that will buffer you from this issue you are having now.

**Comment by BobCeulemans** [comment]
Thank you for your reply mexicantexan!
In the meantime I was looking at Alpha Vantage to figure out if I could use this (premium / paid) API in stead of yfinance. Now reading your reply I think I will try to reprogram my app to use yfinance ver. 0.2.4 and hopefully be able to reanimate tickertwister!
Friendly regards,
Bob
