### ISSUE TITLE
in .history(period = 'max') funtion I got this error: AttributeError: 'Index' object has no attribute 'tz_localize'

### ISSUE THREAD

**Issue by 1uislopez** [ranaroussi/yfinance#1332]
Hi,

how can I fix the below error? 

### **Code:**

google = yf.Ticker("GOOG")
google_data = google.history(period="max")

### **Error:** 

--> 279 df.index = df.index.tz_localize("UTC").tz_convert(
    280     data["chart"]["result"][0]["meta"]["exchangeTimezoneName"])
    282 if params["interval"][-1] == "m":
    283     df.index.name = "Datetime"

AttributeError: 'Index' object has no attribute 'tz_localize'

**Comment by PatrickDionne** [comment]
Hi, you need to add a line of code to remove the timezone-sensitive DataFrame index

google = yf.Ticker("GOOG")
google_data = google.history(period="max")
google_data.index = google_data.index.tz_localize(None) # Remove timezone

**Comment by ValueRaider** [comment]
@PatrickDionne That won't fix errors originating inside `yfinance`

@1uislopez What version are you using? I can't find that code anywhere.

**Comment by cotZhong** [comment]
> @PatrickDionne That won't fix errors originating inside `yfinance`
> 
> @1uislopez What version are you using? I can't find that code. But I've seen error before and potential fix is in branch `fix/prices-index-not-datetime` for you to test (instructions #1080)

Sorry I can not find the branch fix/prices-index-not-datetime

**Comment by ValueRaider** [comment]
I closed this and deleted branch because I considered issue fixed. Create a new issue.

**Comment by cotZhong** [comment]
> I closed this and deleted branch because I considered issue fixed. Create a new issue.

Oh thx! But I fix it with install pandas at version 1.3.5 (instead of 2.2.2)
