### ISSUE TITLE
Historical information is getting timestamps besides the datestamps

### ISSUE THREAD

**Issue by RudyNL** [ranaroussi/yfinance#1344]
Retrieving historical stock exchange data is giving problems (version 0.2.6):
```
>>> import yfinance as yf
>>> yf.Ticker("MSFT").history()
```
Gives as result
```
                                              Open        High         Low       Close    Volume  Dividends  Stock Splits
Date                                                                                                        
2022-12-27 00:00:00-05:00  238.699997  238.929993  235.830002  236.960007  16688600        0.0           0.0
2022-12-28 00:00:00-05:00  236.889999  239.720001  234.169998  234.529999  17457100        0.0           0.0
2022-12-29 00:00:00-05:00  235.649994  241.919998  235.649994  241.009995  19770700        0.0           0.0

```
What is new is the timestamp following the date. This timestamp is irrelevant in case of the open, high, low and close data of one day.
If you are merging data of different stock exchanges around the world its giving indexing problems of the rows. Every stock exchange has a different timestamp.

I had to introduce a work around to merge data from different stock exchanges
```
>>> import yfinance as yf
>>> yf.Ticker("MSFT").history().tz_localize(None)
```
Now the result is
 ```
                 Open        High         Low       Close    Volume  Dividends  Stock Splits
Date                                                                                         
2022-12-27  238.699997  238.929993  235.830002  236.960007  16688600        0.0           0.0
2022-12-28  236.889999  239.720001  234.169998  234.529999  17457100        0.0           0.0
2022-12-29  235.649994  241.919998  235.649994  241.009995  19770700        0.0           0.0
```
I think its a problem caused by Yahoo because it is a problem in case of the functions "history" from "yfinance" and "get_data_yahoo" from "pandas_datareader"

**Comment by msroth** [comment]
I'm getting a strange error that says:  pytz.exception.UnknownTimeZoneError: 'America/New_York'.  I removed the time zone as noted above and don't see America/New_York any where in the data.  Using Python 3.9.

**Comment by ValueRaider** [comment]
This because yfinance adds timezone information to all timestamps. Being forced to remove it to merge different exchanges is a good thing, gets you thinking how best to merge USA with Australia/Japan.
