### ISSUE TITLE
Nothing works "Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers"

### ISSUE THREAD

**Issue by semiexperienced** [ranaroussi/yfinance#1347]
Hello:
I am working with scripts I had working last night. Now, whatever I run returns "Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers"

Even something as simple as:
`import yfinance as yf

msft = yf.Ticker("MSFT")
print(msft.info)`

I have tried uninstalling and reinstalling multiple times, but no luck. I am at a complete loss

**Comment by ValueRaider** [comment]
See #1329
