### ISSUE TITLE
How can I get advanced info data in v0.2.6

### ISSUE THREAD

**Issue by 0zd3m1r** [ranaroussi/yfinance#1349]
I was using it until the update.

i've get this error

`Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers`

How can i get this datas?

Sector
Ebitdamargins
Profitmargins
Grossmargins
Operatingcashflow
Revenuegrowth
Operatingmargins
Ebitda
Earningsgrowth
Returnonassets
Targetmeanprice
Debttoequity
Returnonequity
Totalcash
Totaldebt
Totalrevenue
Recommendationmean
Pricetobook
Shortratio
Beta
Enterprisevalue
Pegratio
Forwardpe
Dividendyield

etc.

Thanks!

**Comment by ValueRaider** [comment]
Right now, `yahooquery` module.

**Comment by 0zd3m1r** [comment]
Bad situation for yfinance. So why am I getting this error on all requests?

```
stock = yf.Ticker(symbol)
print(stock)
```

`Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers`

print(stock.balance_sheet
`Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers`

print(stock.income_stmt)
`Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers`

print(stock.quarterly_income_stmt)
`Exception: yfinance failed to decrypt Yahoo data response with hardcoded keys, contact developers`

...

**Comment by ValueRaider** [comment]
You should know why - read #1300 carefully.

**Comment by ValueRaider** [comment]
Most data is scraped from embedded data stores that are now encrypted. Exceptions are price data and share count, and also these are faster (hence #1300).

**Comment by 0zd3m1r** [comment]
https://dpguthrie-yahooquery-streamlit-app-eydpjo.streamlit.app/
