### ISSUE TITLE
Ticker.info not pulling yield data for mutual funds

### ISSUE THREAD

**Issue by jsultan2323** [ranaroussi/yfinance#135]
It looks like Ticker.info is working for everything except mutual funds (at least for yield data). I see yield data on Yahoo Finance for example:

`fssnx= yf.Ticker('fssnx')`
`fssnx.info`

Yield key-value pair results in None: 
![dictionary_results](https://user-images.githubusercontent.com/47575677/69368470-d13bb900-0c5f-11ea-8c80-04b233a07de1.PNG)

Value exists on Yahoo's side:
![yahoo_results](https://user-images.githubusercontent.com/47575677/69368550-fb8d7680-0c5f-11ea-969c-5d5c0583e466.PNG)

Not entirely sure what the problem is here. Seems to be pulling the yield metrics for other security types.

**Comment by ranaroussi** [comment]
Fixed in 0.1.51 :)
