### ISSUE TITLE
Failure to get fast_info['last_price'] on some symbols

### ISSUE THREAD

**Issue by sdeibel** [ranaroussi/yfinance#1360]
With yfinance 0.2.7 on macOS with Python 3.10 I'm getting failure to obtain last_price via fast_info on some symbols.  For example:

import yfinance as yf
ticker = yf.Ticker('QCSTIX')
print(ticker.fast_info['last_price'])

The result is:

QCSTIX: Period '380d' is invalid, must be one of ['1mo', '3mo', '6mo', 'ytd', '1y', '2y', '5y', '10y', 'max']
nan

Stack trace is:

demobug.py,  line 3
  print(ticker.fast_info['last_price'])
base.py,  line 103, in __getitem__
  return getattr(self, k)
base.py,  line 224, in last_price
  prices = self._get_1y_prices()
base.py,  line 116, in _get_1y_prices
  self._prices_1y = self._tkr.history(period="380d", auto_adjust=False)
base.py,  line 559, in history
  err_msg = "Period '{}' is invalid, must be one of {}".format(period, self._history_metadata[

It looks like _get_1y_prices might be making an incorrect assumption about period but I'm not sure.

**Comment by ValueRaider** [comment]
That symbol doesn't have any trading history, which I hadn't anticipated. But can be solved ...

**Comment by sdeibel** [comment]
Just a note in case it helps in testing, etc later:  Oddly this seems to come and go.  I haven't updated yfinance, the problem went away, then came back, and is gone again.  So the data obtained seems to vary and this symbol in particular seems to do weird things.

**Comment by ValueRaider** [comment]
Fixed in `dev` and PIP pre-release
