### ISSUE TITLE
fast_info failing for 2.7 on timezone

### ISSUE THREAD

**Issue by geoffmcnamara** [ranaroussi/yfinance#1361]
basic_info still worked for me while fast_info fails on timezone
For what it is worth, I wrote code to bring all the values backtogther into a single dictionary ie: like the old Ticker info
There is a penalty of course in time but I put my data into redis to reduce calls to yfinance
'''
sym  = sym  # from above
      sinfo_d = {}
      removed_d = {"regularMarketPrice": "last_price", "dayHigh": "day_high", "dayLow": "day_low", 'fiftyTwoWeekHigh': 'year_high',
                   'fiftyTwoWeekLow': "year_low", 'volume': 'last_volume', 'averageVolume': 'three_month_average_volume',
                   'regularMarketVolume': 'ten_day_average_volume', 'marketCap': 'market_cap', 'currency': 'currency',
                   'regularMarketDayHigh': "day_high", 'regularMarketDayLow': 'day_low', 'averageVolume10days': "ten_day_average_volume",
                   'open': "open", "toCurrency": "currency", 'fiftyDayAverage': "fifty_day_average",
                   'twoHundredDayAverage': "two_hundred_day_average", 'averageDailyVolume10Day': "ten_day_average_volume",
                   'regularMarketPreviousClose': 'previous_close', 'previousClose': "previous_close", 'regularMarketOpen': 'open', 'regularMarketClose': 'close',
                   'exchangeTimezoneName': 'timezone', 'exchangeTimezoneShortName': 'timezone', 'exchange': 'exchange', 'symbol': 'symbol', 'currentPrice': 'last_price'
>>                }
      for k in sinfo:
          # dbug(f"chkg k: {k}")
          if k in removed_d:
              dbug(f"Grabbing basic_info for k: {k}")
              if k == 'symbol':
                  sinfo_d[k] = sym
              else:
                  sinfo_d[k] = sbinfo_d[removed_d[k]]
              dbug(sinfo_d[k])
              continue
          # dbug(f"k: {k} {sinfo[k]}")
          sinfo_d[k] = sinfo[k]
      gtable(sinfo_d, 'hdr', 'prnt', title="debugging", footer=dbug('here'), rnd=2, human=True)  # displays table of info dictionary
''''

**Comment by ValueRaider** [comment]
> - Simple code that reproduces your problem

Because error may only occur with your specific symbol.

**Comment by geoffmcnamara** [comment]
It was SCHW - but I understand. For me it is no big deal except that is bombs out with an exception which means I would have to do a try/exception on every key pair as a work around.

**Comment by ValueRaider** [comment]
Working for me. Posting the actual error message + traceback might help.
