### ISSUE TITLE
Symbol in info

### ISSUE THREAD

**Issue by ben-eastwest** [ranaroussi/yfinance#1369]
Why has the ticker code of a stock dropped out of the info dictionary?

yf.ticker('appl').info no longer has an entry 'Symbol : AAPL'

Can this be re-added? It's handy when organising the data into a DF

**Comment by ben-eastwest** [comment]
yf.Ticker('goog').info
goog = yf.Ticker('goog').info
df = pd.DataFrame([goog])
df = df.set_index('symbol')

KeyError: "None of ['symbol'] are in the columns"

**Comment by ValueRaider** [comment]
Because you know it already:
```
yf.ticker('aapl')
```

"AAPL"

Part of effort to stop unnecessary use of `info`

**Comment by ben-eastwest** [comment]
Thankyou, I shall work around it!
