### ISSUE TITLE
Thomas Brown

### ISSUE THREAD

**Issue by tombrownservices** [ranaroussi/yfinance#1373]
# IMPORTANT

If you want help, you got to read this first. All of it.

### Are you up-to-date?

Upgrade to the latest version and confirm the issue/bug is still there.

`$ pip install yfinance --upgrade --no-cache-dir`

Confirm by running:

`import yfinance as yf ; print(yf.__version__)`

and comparing against [PIP](https://pypi.org/project/yfinance/#history).

### Does Yahoo actually have the data?

Are spelling ticker *exactly* same as Yahoo?

Visit `finance.yahoo.com` and confim they have the data you want. Maybe your ticker was delisted, or your expectations of `yfinance` are wrong.

### Are you spamming Yahoo?

Yahoo Finance free service has rate-limiting depending on request type - roughly 60/minute for prices, 10/minute for info. Once limit hit, Yahoo can delay, block, or return bad data. Not a `yfinance` bug.

### Still think it's a bug?

Delete this default message (all of it) and submit your bug report here, providing the following as best you can:

- Simple code that reproduces your problem, that we can copy-paste-run
- Exception message with full traceback
- `yfinance` version and Python version
- Operating system type

**Comment by ValueRaider** [comment]
what?
