### ISSUE TITLE
discrepancies between yfinance historical price and yahoo finance historical price

### ISSUE THREAD

**Issue by williamioniana** [ranaroussi/yfinance#1374]
There seems to be some discrepancies between the historical data returned by yfinance and the the historical data on yahoo finance itself. This discrepancy appears to happen with a few stocks, for example: ABBV

```python
import yfinance as yf
import pandas as pd

stock = yf.Ticker('ABBV')
df = stock.history(start='2015-01-02',end='2015-01-09')

print(df)

```

![image](https://user-images.githubusercontent.com/108611088/215326149-055c1f11-3fae-4862-ba0e-62bd84a9037e.png)
![image](https://user-images.githubusercontent.com/108611088/215326163-fafe10c5-07c5-4f98-b5a6-51dde438c337.png)

**Comment by ValueRaider** [comment]
`history()` default dividend-adjusts the prices.

**Comment by williamioniana** [comment]
Oh I see, so how would I get the opening price without dividend-adjusts?

**Comment by ValueRaider** [comment]
Ideally documentation answers that, but it might need improvement: https://github.com/ranaroussi/yfinance/wiki

**Comment by RudyNL** [comment]
See also https://github.com/ranaroussi/yfinance/issues/1333

**Comment by asafravid** [comment]
Can close? indeed the dividend adjustments are the issue here CloseAdj
