### ISSUE TITLE
Negative value in open, high, low, close data.

### ISSUE THREAD

**Issue by slapslash** [ranaroussi/yfinance#138]
Due to the adjustment of OHLC with one of:

            auto_adjust: bool
                Adjust all OHLC automatically? Default is True
            back_adjust: bool
                Back-adjusted data to mimic true historical prices

it may happen, that ohlc values get negative.
One example is the ticker FPE3.DE.

**Comment by tombohub** [comment]
ticker HCHC also starts with negative value when pulling from 2019-1-1

**Comment by silvavn** [comment]
Can you provide a code example where this happens?

**Comment by tombohub** [comment]
```python
import yfinance as yf

hchc = yf.Ticker('hchc)
df = hchc.history(start='2019-1-1')
df


  | Open | High | Low | Close | Volume | Dividends | Stock Splits
-- | -- | -- | -- | -- | -- | -- | --

-0.749007 | -0.797980 | -0.731722 | -0.769172 | 288100 | 0.0 | 0


```

**Comment by pat42w** [comment]
Another example is ITRN 

```
import yfinance as yf
yf.download(['MSFT','ITRN'],'2006-1-1')['Adj Close']
```
![image](https://user-images.githubusercontent.com/43762957/112752161-8ce5c900-8fc9-11eb-846f-fd17cdc87dbc.png)

**Comment by silvavn** [comment]
Problem seems that `Close` prices are adjusted for splits by default, but `Adj Close` are adjusted for dividends and splits.

It happens that if so many dividends were given, the price of `Adj Close` can be negative. 
This is not an issue with yfinance but with how Yahoo adjusts their prices. 
See this for reference: https://blog.quandl.com/guide-to-stock-price-calculation?utm_source=google&utm_medium=organic&utm_campaign=&utm_content=guide-to-stock-price-calculation#section3
