### ISSUE TITLE
download and history methods fail with proxy

### ISSUE THREAD

**Issue by vidalmarco** [ranaroussi/yfinance#1386]
Description
yFinance.dowload() and Ticker.history() methods do not work with proxy and return no data with a message like:
1 Failed download:
- AMZN: No data found for this range, symbol may be delisted

yFinance: 0.2.9 + hotfix/proxy (base.py and fundamentals.py)
python: 3.9.12
OS: Windows 10 20H2

Analysis
Bug is in base.py module in function history() at line 571:
```
data = get_fn(
url=url,
params=params,
timeout=timeout
)
```

Fix
To fix it simply add 
`proxy=proxy` 
as a fourth parameter.

Enjoy!!
MV

**Comment by ValueRaider** [comment]
We have a fix but waiting for someone to test, can you? It's `hotfix/proxy`, instructions in #1080

**Comment by ValueRaider** [comment]
Just use it normally and confirm/deny issue fixed.

**Comment by Vidal4SigurRos** [comment]
Hotfix works for history() and download() methods. 👍 
Unfortunately it does not work for fundamentals. It gives an Https error. 

The following worked but I'll let you the complete design. Thanks:
1) proxy should be passed also to Ticker object at init time as an optional param and stored in self after a preprocessing into a proxy string (not a dict):
if proxy is not None:
  if isinstance(proxy, dict) and "https" in proxy:
      proxy = proxy["https"]
self.proxy = proxy
2) modify all property functions of Ticker class like: get_shares(proxy=self.proxy)

From my tests above code worked for every fundamentals property with the exception of: market_cap (yet to be implemented as of hotfix time??) isin (which is experimental).

HTH

Best,
Marco
