### ISSUE TITLE
The requested range must be within the last 60 days.

### ISSUE THREAD

**Issue by tootooot** [ranaroussi/yfinance#1389]
Hello Guys.
yf.download("btc-usd",interval="5m",start='2022-12-01', end='2023-02-01')
THE Error:
5m data not available for startTime=1669852800 and endTime=1675209600. The requested range must be within the last 60 days.

Why 60 days.

**Comment by asafravid** [comment]
Did you try a 60 day range? Does it work?

**Comment by ValueRaider** [comment]
The correct answer is: because Yahoo says so.

**Comment by ivan23kor** [comment]
@tootooot, While some intervals (e.g., `1d`, `1m`) will work for any periods, your period (14 months) is too large for the `5m` interval.
Please close this issue if setting `period <= 60d` works.

**Comment by KyoungWan** [comment]
it is also not working
@ivan23kor 
`https://query2.finance.yahoo.com/v8/finance/chart/KRW=X?interval=5m&period1=1699549200&period2=1699549400`
