### ISSUE TITLE
Ticker.get_isin method does not work with proxy 

### ISSUE THREAD

**Issue by vidalmarco** [ranaroussi/yfinance#1399]
I spent some time on debugging the get_isin method after having applied `hotfix/proxy` (see also #1387)

After some failures (always getting HTTPS Tunnel 407 failure) I've tried to test it via curl.

**First** (as generated by get_isin)
`curl -x 10.xx.xxx.xx:pppp https://markets.businessinsider.com/ajax/SearchController_Suggest?query=IBM`
curl: (56) Received HTTP code 407 from proxy after CONNECT

**Second** (specify a user)
`curl -x 10.xx.xxx.xx:pppp https://markets.businessinsider.com/ajax/SearchController_Suggest?query=IBM -U <my_username>`
Enter proxy password for user '<my_username>':
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

**Third** (specify a user and a ssl cert verification check = False)
`curl -x 10.xx.xxx.xx:pppp https://markets.businessinsider.com/ajax/SearchController_Suggest?query=IBM -U <my_username> --ssl-no-revoke`

Enter proxy password for user '<my_username>':
mmSuggestDeliver(0, new Array("Name", "Category", "Keywords", "Bias", "Extension", "IDs"), new Array(new Array("IBM Corp. (International Business Machines)", "Stocks", "IBM|US4592001014|IBM||IBM", "75", "", "ibm|IBM|1|389"),new Array("The Options Clearing Corp OCC OPRA - Package Basket for ETD Developed from IBM", "Stocks", "IBM1|XD0114686534|IBM1||", "75", "", "ibm1|IBM1|1|369657383"),new Array("IBJ Inc", "Stocks", "|JP3104960004|||", "75", "", "ibj||1|1349241"),new Array("IBIDEN CO LTDShs", "Stocks", "IBIDF|JP3148800000|IBIDF||", "75", "", "ibidf|IBIDF|1|12090"),new Array("Masmovil Ibercom SA Bearer Shs", "Stocks", "MMBMF|ES0184696104|MMBMF||", "75", "", "mmbmf|MMBMF|1|21595152"),new Array("IMMOFINANZ", "Stocks", "|AT0000A21KS2|||", "75", "", "immofinanz||1|19145188"),new Array("ImmuCell", "Stocks", "ICCC|US4525253062|ICCC||", "75", "", "iccc|ICCC|1|2819"),new Array("Al Hassan Ghazi Ibrahim Shaker Co. Bearer Shs", "Stocks", "|SA12I0OGIV12|||", "75", "", "al_hassan_ghazi_ibrahim_shaker||1|27215953"),new Array("Immuron Ltd", "Stocks", "|AU000000IMC7|||", "75", "", "immuron||1|25442"),new Array("ImmunoGen Inc.", "Stocks", "IMGN|US45253H1014|IMGN||IMGN", "75", "", "imgn|IMGN|1|613")), 10, 0); 👍

**Fourth** (w/o a user and a ssl cert verification check = False)
`curl -x 10.xx.xxx.xx:pppp https://markets.businessinsider.com/ajax/SearchController_Suggest?query=IBM --ssl-no-revoke`
curl: (56) Received HTTP code 407 from proxy after CONNECT

Any ideas on how to overcome the usage of username? 
Could it be due to the lack of an API ticket for markets.businessinsider?
Also I don't think it's advisable to use the `verify=False` (equivalent of `--ssl-no-revoke` curl option) in `session.get` call

**Comment by vidalmarco** [comment]
Shouldn't the lib provide an API key for accessing markets.businessinsider.com REST API calls?

**Comment by ValueRaider** [comment]
:shrug: it works without proxy

**Comment by ValueRaider** [comment]
Can you clarify, does this never work with proxy?

**Comment by vidalmarco** [comment]
with mine, yes. It does never work.

**Comment by vidalmarco** [comment]
I've found a workaround but I'm not sure whether it is appropriate to be implemented inside the library or just left as a how-to.
Here are the steps,
1. define the proxy with **'https'** key and with **http** protocol as the value
`proxy = {'https': 'http://<username>:<password>@<ip address>:<port>'}`
2. (optional) to suppress warning message specify: `requests.packages.urllib3.disable_warnings()` before the call.
3. `requests.get()` inside `Ticker.get_isin()` must be called with parameter: `verify=False`

I guess 1. and 3. steps above can be implemented by relying on the session object.

**Comment by ValueRaider** [comment]
You think much easier to implement 3 inside `yfinance`? I don't see why need MITM protection.

**Comment by ValueRaider** [comment]
Is original SSL error fixed by installing `python-certifi-win32` ? https://github.com/ranaroussi/yfinance/issues/963#issuecomment-1062510178
