### ISSUE TITLE
Several parameters missing in stock.get_info() with and without proxy

### ISSUE THREAD

**Issue by uzala92** [ranaroussi/yfinance#1402]
Using yfinance 0.2.9 in Python 3.8.10.

I test stock.get_info() for common tickers such as AAPL and MSFT and some important information is now missing.  Some of the missing parameters are:
- symbol
- marketCap
- currentPrice
- currency
- exchange

These are widely used parameters. Does anyone know why they no longer appear?

Thanks in advance.

**Comment by ValueRaider** [comment]
Read the message `yfinance` prints, this isn't complicated.

**Comment by uzala92** [comment]
Thanks, but I am running it in google colab and I don't see any message neither in the package loading nor in the function execution.

**Comment by ValueRaider** [comment]
Hmm, interesting. The solution is easy but I don't want you to then disappear. First, any advice for getting message to show?

**Comment by uzala92** [comment]
Ok, I didn't understand the way to get this message as I was just printing the info.

Anyway, I just looked at the shares in fast_info and it seems to give them in thousands. I don't know if this is true for all assets.
MSFT:
'shares': 7443800064,
'market_cap': 1898094619209.375,
'last_price': 254.99000549316406,
1898094619209.375 / 7443800064 = 254990

**Comment by ValueRaider** [comment]
Are you serious? I copy-and-paste that division into a calculator and get correct price.

**Comment by uzala92** [comment]
ups, really sorry, con paste dot dissapeared.
