### ISSUE TITLE
Example - yf.Ticker("MSFT").info missing data

### ISSUE THREAD

**Issue by gunnu22** [ranaroussi/yfinance#1404]
### Still think it's a bug?

I am using Yfinance 0.2.9 with Python 3.10.. 

On running yf.Ticker(stock).info there are many data fields coming back with null value in the response.  1. mktcap, 2.high52, 3.low52, 4.currpr, 5.vol, 6.voltendayavg, 7.dayhigh, 8.daylow.

Are these data fields no longer available from this this function or is there any bug in retrieval ? 

- Simple code that reproduces your problem, that we can copy-paste-run
-  yf.Ticker('MSFT).info

**Comment by ajgringo619** [comment]
I don't see any of those keys when testing this. Are you certain of those key names? Some of the null values you see are for cryptocurrency values, so that's expected.

**Comment by gunnu22** [comment]
You are right. We used to have these keys earlier, but for the past week or so the data fields are missing.  Trying to find the reason for missing. Attached is the dump from latest query.
[yf.ticker.info.txt](https://github.com/ranaroussi/yfinance/files/10678538/yf.ticker.info.txt)

**Comment by ajgringo619** [comment]
Yeah, that's similar to the MSFT dump. Yahoo seems to be spending an inordinate amount of time changing their data services.

**Comment by ValueRaider** [comment]
Is this fixed in latest release?

**Comment by checkmarkets** [comment]
With me, none of the fundamental data queries from msft.info to get_balance_sheet and all do not work at all.

If I download yf.Ticker["MSFT].info the following answer appears:
**{'regularMarketPrice': None, 'preMarketPrice': None, 'logo_url': ''}**

**Comment by vismoh2010** [comment]
@gunnu22 Latest version of yfinance should fix it.

**Comment by checkmarkets** [comment]
You're right. Works out again. Thanks guys for making it work again 🙏🏻
