### ISSUE TITLE
Several tickers return Exception when getting historical data with `period="max"` and `interval="1mo"`

### ISSUE THREAD

**Issue by pfischer1687** [ranaroussi/yfinance#1405]
# Several tickers return Exception when getting historical data with `period="max"` and `interval="1mo"`

I had code that used yfinance to get monthly max period close price data for a small number of tickers. The code worked fine for yfinance version 0.1, but I ran it again using yfinance version 0.2.9 and for several of the tickers it was returning the exception below. It worked just fine for several of the tickers, but then returned the exception below for others. I checked the yahoo! finance website and the data is all there for those tickers that are returning the exception. Oddly enough, it seemed to work fine when I changed either the period or interval - it just didn't seem to like having both `period="max"` and `interval="1mo"` for some reason.

# Examples
## Works fine

`yf.Ticker("ABBV").history(period="10y", interval="1mo")["Close"]`
`yf.Ticker("ABBV").history(period="max", interval="1wk")["Close"]`

## Returns Exception

`yf.Ticker("ABBV").history(period="max", interval="1mo")["Close"]`

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13864/234900509.py in <module>
----> 1 yf.Ticker('ABBV').history(period="max", interval="1mo")["Close"]

~\Anaconda3\lib\site-packages\yfinance\base.py in history(self, period, interval, start, end, prepost, actions, auto_adjust, back_adjust, repair, keepna, proxy, rounding, timeout, debug, raise_errors)
    709         df = quotes.sort_index()
    710         if dividends.shape[0] > 0:
--> 711             df = utils.safe_merge_dfs(df, dividends, interval)
    712         if "Dividends" in df.columns:
    713             df.loc[df["Dividends"].isna(), "Dividends"] = 0

~\Anaconda3\lib\site-packages\yfinance\utils.py in safe_merge_dfs(df_main, df_sub, interval)
    631             df = _pd.concat([df, df_sub_missing], sort=True)[col_ordering]
    632         else:
--> 633             raise Exception("Lost data during merge despite all attempts to align data (see above)")
    634 
    635     return df

Exception: Lost data during merge despite all attempts to align data (see above)

**Comment by ValueRaider** [comment]
Thanks for detail. Simple problem, simple fix. Can you try branch `hotfix/prices-merge-events`?

**Comment by ValueRaider** [comment]
@ivan23kor FYI. Can you create the PR?
