### ISSUE TITLE
yf.Ticker(ticker) ==> yfinance failed to decrypt Yahoo data response

### ISSUE THREAD

**Issue by onesoned** [ranaroussi/yfinance#1408]
1)    cmd --> pip install yfinance --upgrade

2)
ticker = "aapl"
import yfinance as yf
tickerYF = yf.Ticker(ticker)
print(tickerYF.info)

3)    result:
> Traceback (most recent call last):
> File "C:\Users###\source\repos\2021_12_15 Google API Python\2022_03_09 API\tester.py\00 yahooFinance tester.py", line 49, in
> print(tickerYF.info)
> File "C:\Program Files\Python37\lib\site-packages\yfinance\ticker.py", line 142, in info
> return self.get_info()
> File "C:\Program Files\Python37\lib\site-packages\yfinance\base.py", line 1268, in get_info
> data = self._quote.info
> File "C:\Program Files\Python37\lib\site-packages\yfinance\scrapers\quote.py", line 95, in info
> self._scrape(self.proxy)
> File "C:\Program Files\Python37\lib\site-packages\yfinance\scrapers\quote.py", line 124, in _scrape
> json_data = self._data.get_json_data_stores(proxy=proxy)
> File "C:\Program Files\Python37\lib\site-packages\yfinance\data.py", line 41, in wrapped
> return func(*args, **kwargs)
> File "C:\Program Files\Python37\lib\site-packages\yfinance\data.py", line 307, in get_json_data_stores
> stores = decrypt_cryptojs_aes_stores(data, keys)
> File "C:\Program Files\Python37\lib\site-packages\yfinance\data.py", line 162, in decrypt_cryptojs_aes_stores
> raise Exception("yfinance failed to decrypt Yahoo data response")
> Exception: yfinance failed to decrypt Yahoo data response

**Comment by ValueRaider** [comment]
duplicate
