### ISSUE TITLE
dji ticker is not working

### ISSUE THREAD

**Issue by ZiyiXia** [ranaroussi/yfinance#1410]
Hello, currently I got an error when running:
`yf.download(tickers = "dji", interval = "1d", period = "1d")`
Output:
```
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- DJI: AttributeError("'NoneType' object has no attribute 'tz_convert'")
```
And this returns an empty dataframe.

yfinance version: 0.2.10
Python version: 3.8 on Google Colab

**Comment by ZiyiXia** [comment]
I switched the version back to 0.2.9 and didn't run into this error, is that caused by some changes in yesterday's update of 0.2.10?

**Comment by sdeibel** [comment]
If the same problem I'm running into with symbol QCSTIX while accessing fast_info['last_price'] on the ticker then the solution is to change the code in utils.py's format_history_metadata that reads:

    for k in ["firstTradeDate", "regularMarketTime"]:
        if k in md:
            md[k] = _pd.to_datetime(md[k], unit='s', utc=True).tz_convert(tz)

To instead read:

    for k in ["firstTradeDate", "regularMarketTime"]:
        if k in md:
            if md[k] is not None:
                md[k] = _pd.to_datetime(md[k], unit='s', utc=True).tz_convert(tz)

**Comment by ValueRaider** [comment]
@sdeibel Spot on. Would you mind submitting a pull request? I know it's simple, but it'll introduce you to process in case you want to submit other changes. Read #1084 first.

**Comment by wingware-dev** [comment]
Will do, although not until later today (EST) since I'm traveling.

**Comment by sdeibel** [comment]
Sure.  I'm traveling so a bit slow t get to this, but will try to do it soon.

**Comment by sdeibel** [comment]
OK just submitted https://github.com/ranaroussi/yfinance/pull/1411
