### ISSUE TITLE
Prevent Warning info / decryption keys?

### ISSUE THREAD

**Issue by Rapid1898-code** [ranaroussi/yfinance#1418]
Hello - is there any way to prevent these output with the newest yfinance version 0.2.11.:
WARNING: No decryption keys could be extracted from JS file. Falling back to backup decrypt methods.

**Comment by ValueRaider** [comment]
Huh, the backup decryption working today, wasn't expecting that.

Not currently possible to disable, but I can change that. How annoying is it?

**Comment by Rapid1898-code** [comment]
No real problem at all - only my customers are asking what this is all about.

**Comment by pat704** [comment]
You could comment out the print statement in line 297 of data.py. Might be difficult for your customers to figure out how to do that though...

**Comment by ValueRaider** [comment]
Someone could submit a pull request to disable message, only developers need it really.

**Comment by EpsilonTal** [comment]
@ValueRaider, I receive this message on any request I make.

> isable message, only developers need it really.

Can I skip it (from your latest comment here)?

**Comment by ValueRaider** [comment]
@EpsilonTal Code is open-source, do what you want.

**Comment by ValueRaider** [comment]
Decryption code gone.
