### ISSUE TITLE
Error in version 0.1.51 using .info/ .quarterly_financials

### ISSUE THREAD

**Issue by TimBstn** [ranaroussi/yfinance#142]
Hey, I just updatet to the latest version and just tried 
```
import yfinance as yf

msft = yf.Ticker('MSFT')

print(msft.info)
print(msft.quarterly_financials)
```

It got me the following error:

> Traceback (most recent call last):

>   File "C:\Users\Tim_B\Documents\Python Download\lib\site-packages\yfinance\base.py", line 253, in cleanup
>     df.index = _pd.to_datetime(df.index, unit='s')
>   File "C:\Users\Tim_B\Documents\Python Download\lib\site-packages\pandas\util\_decorators.py", line 208, in wrapper
>     return func(*args, **kwargs)
>   File "C:\Users\Tim_B\Documents\Python Download\lib\site-packages\pandas\core\tools\datetimes.py", line 788, in to_datetime
>     result = convert_listlike(arg, box, format)
>   File "C:\Users\Tim_B\Documents\Python Download\lib\site-packages\pandas\core\tools\datetimes.py", line 347, in _convert_listlike_datetimes
>     result, tz_parsed = tslib.array_with_unit_to_datetime(arg, unit, errors=errors)
>   File "pandas/_libs/tslib.pyx", line 421, in pandas._libs.tslib.array_with_unit_to_datetime
> ValueError: unit='s' not valid with non-numerical val='{'raw': 1561852800, 'fmt': '2019-06-30'}

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):

 

>  File "C:/Users/Tim_B/Documents/Projekt/test.py", line 5, in <module>

   

> print(msft.info)
>   File "C:\Users\Tim_B\Documents\Python Download\lib\site-packages\yfinance\ticker.py", line 134, in info
>     return self.get_info()
>   File "C:\Users\Tim_B\Documents\Python Download\lib\site-packages\yfinance\base.py", line 406, in get_info
>     self._get_fundamentals(proxy)
>   File "C:\Users\Tim_B\Documents\Python Download\lib\site-packages\yfinance\base.py", line 356, in _get_fundamentals
>     key[0]['yearly'] = cleanup(data[item][key[2]])
>   File "C:\Users\Tim_B\Documents\Python Download\lib\site-packages\yfinance\base.py", line 255, in cleanup
>     df.index = _pd.to_datetime(df.index)
>   File "C:\Users\Tim_B\Documents\Python Download\lib\site-packages\pandas\util\_decorators.py", line 208, in wrapper
>     return func(*args, **kwargs)
>   File "C:\Users\Tim_B\Documents\Python Download\lib\site-packages\pandas\core\tools\datetimes.py", line 788, in to_datetime
>     result = convert_listlike(arg, box, format)
>   File "C:\Users\Tim_B\Documents\Python Download\lib\site-packages\pandas\core\tools\datetimes.py", line 456, in _convert_listlike_datetimes
>     result, tz_parsed = objects_to_datetime64ns(
>   File "C:\Users\Tim_B\Documents\Python Download\lib\site-packages\pandas\core\arrays\datetimes.py", line 1969, in objects_to_datetime64ns
>     result, tz_parsed = tslib.array_to_datetime(
>   File "pandas/_libs/tslib.pyx", line 465, in pandas._libs.tslib.array_to_datetime
>   File "pandas/_libs/tslib.pyx", line 688, in pandas._libs.tslib.array_to_datetime
>   File "pandas/_libs/tslib.pyx", line 826, in pandas._libs.tslib.array_to_datetime_object
>   File "pandas/_libs/tslib.pyx", line 660, in pandas._libs.tslib.array_to_datetime
> TypeError: <class 'dict'> is not convertible to datetime

How can I handle this error?
btw: great feature, love it!

BR 
Tim

**Comment by ranaroussi** [comment]
I can't replicate this. Just in case... Can you update to version 0.1.52 and see if the problem was solved?

```
$ pip install yfinance -U
```

Thanks!

**Comment by TimBstn** [comment]
With 0.1.52 everything works as it should.
Thanks for the great work!
