### ISSUE TITLE
Exception: yfinance failed to decrypt Yahoo data response

### ISSUE THREAD

**Issue by Rapid1898-code** [ranaroussi/yfinance#1426]
Hello - when i run the folklowing code:

```
import yfinance as yf
import time

if __name__ == '__main__':
  ticker = ["AAPL", "XYZ", "MSFT"]
  while True:
    for t in ticker:
      data = yf.Ticker(t)
      if data.info == None:
        print(f"Nothing found for ticker")
      else:
        print(f"Date read for {t}")
      time.sleep(1)
```

I get (earlier or later) the following error message -

```
$ python test.py
Traceback (most recent call last):
  File "G:\DEV\Python-Diverses\YFinance\test.py", line 9, in <module>
    if data.info == None:
  File "G:\DEV\.venv\selAll\lib\site-packages\yfinance\ticker.py", line 138, in info
    return self.get_info()
  File "G:\DEV\.venv\selAll\lib\site-packages\yfinance\base.py", line 1475, in get_info
    data = self._quote.info
  File "G:\DEV\.venv\selAll\lib\site-packages\yfinance\scrapers\quote.py", line 95, in info
    self._scrape(self.proxy)
  File "G:\DEV\.venv\selAll\lib\site-packages\yfinance\scrapers\quote.py", line 124, in _scrape
    json_data = self._data.get_json_data_stores(proxy=proxy)
  File "G:\DEV\.venv\selAll\lib\site-packages\yfinance\data.py", line 41, in wrapped
    return func(*args, **kwargs)
  File "G:\DEV\.venv\selAll\lib\site-packages\yfinance\data.py", line 311, in get_json_data_stores
    stores = decrypt_cryptojs_aes_stores(data, keys)
  File "G:\DEV\.venv\selAll\lib\site-packages\yfinance\data.py", line 162, in decrypt_cryptojs_aes_stores
    raise Exception("yfinance failed to decrypt Yahoo data response")
Exception: yfinance failed to decrypt Yahoo data response
```

Why is that - and why is it happening in the line with this statement:
`if data.info == None:`

Is there anything i can do for preventing such errors?

**Comment by Korach250** [comment]
**More : Exception: yfinance failed to decrypt Yahoo data response**
LIBRARIES DOWNLOADED : 0.2.12
2023-02-18 W07 Saturday
New York       02:39:59

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
[<ipython-input-28-e187ddce5e6c>](https://localhost:8080/#) in <module>
----> 1 MKV(df)
      2 
      3 pd.set_option('display.max_columns', None)
      4 pd.set_option('display.max_rows', None)
      5 

7 frames
[/usr/local/lib/python3.8/dist-packages/yfinance/data.py](https://localhost:8080/#) in decrypt_cryptojs_aes_stores(data, keys)
    160                 pass
    161         if not success:
--> 162             raise Exception("yfinance failed to decrypt Yahoo data response")
    163 
    164     decoded_stores = json.loads(plaintext)

Exception: yfinance failed to decrypt Yahoo data response

**Comment by pydazhang** [comment]
Same issues here. Really wanted to know how to get a yahoo key :)

**Comment by ValueRaider** [comment]
@Rapid1898-code If you maintain this software for clients, you should really know how to read Python. `yf.Ticker.info` triggers a fetch that ultimately fails to decrypt.

**Comment by Rapid1898-code** [comment]
Hello - i don´t understand what is wrong with checking if there is some result with:
`if data.info == None:`
Is this in any way wrong handling?
And why is it outputting an error with "yfinance failed to decrypt Yahoo data response"?

**Comment by ValueRaider** [comment]
`info` isn't a variable. It's a property function, see the source code.

**Comment by Rapid1898-code** [comment]
So to correct way is to allways use a try and except logic when accessing data from info.
Do i understand this correct?

**Comment by ValueRaider** [comment]
No. If decryption is failing, go outside for a walk because there's nothing you can do.

**Comment by Rapid1898-code** [comment]
Hello - i still not get it -
I have the situation that i read several tickers - ticker by ticker (eg. 100 tickers)
And sometimes as described i get this error after 10 tickers or so.

But with a workaround it seems to work -
So i make a try and except and when i get this exception i wait for eg. 5 seconds and then try it again.
Most of the time after this 5 seconds access to info works fine.

So it seems for me that there is something i can do.
(or it would be a very short walk...)

**Comment by ValueRaider** [comment]
Interesting, I thought decryption had 100% broken for everyone. Certainly has for me. But it's ultimately your decision what to do when `yfinance` can't decrypt Yahoo's data.

**Comment by Rapid1898-code** [comment]
so you mean generally there is sometimes no way to get data from yfinance you think?

**Comment by ValueRaider** [comment]
No

Read #1407

**Comment by ValueRaider** [comment]
Read #1407
