### ISSUE TITLE
Float Issue : AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Korach250** [ranaroussi/yfinance#1429]
yf LIBRARY DOWNLOADED : 0.2.12
2023-02-18 W07 Saturday
New York       07:02:30
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-6-e187ddce5e6c>](https://localhost:8080/#) in <module>
----> 1 MKV(df)
      2 
      3 pd.set_option('display.max_columns', None)
      4 pd.set_option('display.max_rows', None)
      5 

[<ipython-input-5-bf06b4026122>](https://localhost:8080/#) in MKV(df)
      3     #Float size
      4     flt_shares = {}
----> 5     flt_shares[f'{symbol}'] = ticker.info.get('floatShares')
      6     df['Float'] = (flt_shares[f'{symbol}'])
      7 

AttributeError: 'NoneType' object has no attribute 'get'
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**UPDATE : Error message changed.**

yf LIBRARY DOWNLOADED : 0.2.12
2023-02-18 W07 Saturday
New York       08:25:39

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
[<ipython-input-14-e187ddce5e6c>](https://localhost:8080/#) in <module>
----> 1 MKV(df)
      2 
      3 pd.set_option('display.max_columns', None)
      4 pd.set_option('display.max_rows', None)
      5 

7 frames
[/usr/local/lib/python3.8/dist-packages/yfinance/data.py](https://localhost:8080/#) in decrypt_cryptojs_aes_stores(data, keys)
    160                 pass
    161         if not success:
--> 162             raise Exception("yfinance failed to decrypt Yahoo data response")
    163 
    164     decoded_stores = json.loads(plaintext)

Exception: yfinance failed to decrypt Yahoo data response

**Comment by pat704** [comment]
@Korach250 This is caused by issue #1407. The line info.get('floatshares') returns None because yfinance is unable to decrypt data response so floatShares key doesn't exist. The backup decrypt method had been working until yesterday but is not working at the moment unfortunately
