### ISSUE TITLE
get_news: raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by williamc1998** [ranaroussi/yfinance#1440]
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
specifically after using get_news, I pass info over to frontend. this was working before so is this a new issue relating to the new encryption?
edit: this was working about 6 hours ago and is a new issue. additionally, performance seems to have taken a massive hit
I've been forced to switch to alpha vantage

**Comment by williamc1998** [comment]
site-packages/yfinance/base.py", line 1606, in get_news
    data = data.json()

**Comment by ivan23kor** [comment]
@williamc1998 the following code works:
```python
import yfinance as yf
ticker = yf.Ticker('SPY')
print(ticker.news)
```

Please upload a reproducer code.
