### ISSUE TITLE
Unable to download data using yfinance

### ISSUE THREAD

**Issue by rishabhgupta93** [ranaroussi/yfinance#1442]
Hi Experts,

I have been unable to download data using yfinance, for the last two days. Getting the following error:

Downloading data for ^NSEI from 2020-05-01 to 2023-03-04 11:09:56.546582
Traceback (most recent call last):
  File "F:\PyCharmProjects\bullish-pullback\Backtest\dma-pullback\Strategy1.py", line 78, in <module>
    index_df = TickersData(start_date=start,
  File "F:\PyCharmProjects\bullish-pullback\DownloadData\TickersData.py", line 36, in getTickerData
    return self.tickersData[ticker]
KeyError: '^NSEI'
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- ^NSEI: No data found for this date range, symbol may be delisted

The same code was working a few days back.

Thanks

**Comment by williamc1998** [comment]
Is it just for this specific ticker?

**Comment by rishabhgupta93** [comment]
It is happening for '^NSEI'. But behavior is very intermittent. When I try multiple times, it works for the same ticker.

**Comment by rishabhgupta93** [comment]
It is happening intermittently for any index.

**Comment by ivan23kor** [comment]
@rishabhgupta93 could you provide a reproducer code?

**Comment by rishabhgupta93** [comment]
Closing this as issue is duplicated and reported in https://github.com/ranaroussi/yfinance/issues/1443
