### ISSUE TITLE
Unable to download data

### ISSUE THREAD

**Issue by rishabhgupta93** [ranaroussi/yfinance#1443]
Hi Experts,

I am unable to download data using yfinance. 

Running following code:

import yfinance as yf

yf.download(tickers="^CRSLDX",
                                                           start="2021-09-01",
                                                           end="2023-03-05",
                                                           rounding=True,
                                                           interval="1d",
                                                           auto_adjust=False,
                                                           ignore_tz=True,
                                                           progress=False)

But I am getting this error.

1 Failed download:
- ^CRSLDX: No data found for this date range, symbol may be delisted

**Comment by ivan23kor** [comment]
Hi @rishabhgupta93,
I couldn't replicate the issue, here is my output:
```python
                Open      High       Low     Close  Adj Close    Volume
Date                                                                   
2021-09-01  14611.65  14640.60  14527.05  14551.35   14551.33  18422700
2021-09-02  14571.30  14692.00  14548.50  14684.35   14684.33  22044800
2021-09-03  14724.70  14770.85  14682.20  14759.30   14759.28  24543700
2021-09-06  14827.05  14843.40  14783.45  14805.85   14805.83  16059600
2021-09-07  14834.95  14852.25  14713.55  14784.25   14784.23  23696100
...              ...       ...       ...       ...        ...       ...
2023-02-27  14600.90  14609.40  14465.70  14548.70   14548.70  13597900
2023-02-28  14550.00  14584.45  14476.00  14518.75   14518.75  20385500
2023-03-01  14557.00  14675.05  14550.10  14664.85   14664.85  16097000
2023-03-02  14654.80  14668.40  14575.95  14587.25   14587.25  15599200
2023-03-03  14686.25  14813.05  14676.05  14774.75   14774.75  18314000

[375 rows x 6 columns]
```

Are you still facing this issue?

**Comment by rishabhgupta93** [comment]
does yahoo have any limit on the number of requests per minute?

**Comment by ivan23kor** [comment]
@rishabhgupta93, yes. It's not a fixed RPS limit but something that adapts to how often you use.

You can run yfinance for 10 times in a row with no delay and don't get blocked. If you keep doing it for like 10 minutes, your cookie will get blocked by Yahoo and you'll have to wait for about a day until the value is refreshed (from personal experience).

**Comment by ivan23kor** [comment]
@rishabhgupta93 The last commit on `main` is about rate limiting from @ValueRaider, he might clarify better.

**Comment by rishabhgupta93** [comment]
I have recently started facing this issue. A Few days ago it was working flawlessly for 500 tickers.

**Comment by ChemicalShard** [comment]
I'm sad to see Yahoo obfuscate their data in this way. I'm a hobby investor who has just started getting into coding and this API is brilliant. I am looking forward to seeing it work. I am unable to offer a solution but I will think of ways to harness the API when the time comes.

**Comment by shql-tgr** [comment]
> 

Hi, i am facing the same issue. Worked smoothly for over a week for downloading Dow Jones constituents, now i can't download a single stock's data. Were you able to fix the problem?

**Comment by ValueRaider** [comment]
Try this: https://github.com/ranaroussi/yfinance/issues/1268#issuecomment-1464906732
