### ISSUE TITLE
End point data not included in output

### ISSUE THREAD

**Issue by mpopescu1** [ranaroussi/yfinance#1445]
start = dt.datetime(2019,12,1)
end = dt.datetime(2019,12,31)
aapl = yf.download('AAPL',start,end)['Adj Close']
aapl.tail(1)

The output DataFrame's last observation is 12/30, although the market was open on 12/31 and there is an Adjusted Close for that day. 

- yfinance  0.2.12
- MacOS Catalina

**Comment by ivan23kor** [comment]
Hello @mpopescu1,

Looks like yfinance's period is `[start, end)`, i.e. the date is not included in the period.

**Comment by mpopescu1** [comment]
That's what I thought as well. I wish it were mentioned in the documentation, or perhaps a future version could close the interval with the end date.

**Comment by ValueRaider** [comment]
I cannot say if `[start, end)` was originally intended behaviour, but AFAIK it has always been that way, and isn't necessarily wrong because it mimics Python/Numpy array access `a[i:j]`. Problem with changing now is the big userbase, some codes may rely on this behaviour and break if changed.

**Comment by mpopescu1** [comment]
I understand the problem with changing it. I mostly raised the issue because I wanted to double check it wasn't my mistake. I used pandas-datareader to get yahoo data until last December but it no longer works. Thank you all for the comments!

**Comment by ivan23kor** [comment]
@mpopescu1  Opened #1448 for this (better dosctrings).

**Comment by ivan23kor** [comment]
@mpopescu1 Do you mind closing this?
