### ISSUE TITLE
Is the debug parameter in the download method deprecated?

### ISSUE THREAD

**Issue by spacecadet27** [ranaroussi/yfinance#1450]
The Wiki says the debug parameter can be set in the download method, but including debug as a parameter throws an exception. Does the wiki need to be updated?

**Simple code that reproduces your problem, that we can copy-paste-run**

ticker = yf.download(tickers=TICKER, period='2y', interval='1d', repair=True, rounding=True, progress=False, debug=True)

**Exception message with full traceback, or proof `yfinance` returning bad data**

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\layer02\Merlin-prod\app2.py", line 9, in <module>
    _ticker = yf.download(tickers=TICKER, period='2y', interval='1d', repair=True, rounding=True, progress=False, debug=True)
TypeError: download() got an unexpected keyword argument 'debug'

**`yfinance` version and Python version**

yfinance==0.2.12

Python version
3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

**Operating system type**

Pycharm 2021.2.4 (Community Edition)

Build #PC-212.5712.39
Runtime Version: 11.0.13+8-b1504.49 amd64
VM: OpenJDK 64-bit Server VM by JetBrains s.r.o.

Windows 10 Home
Version: 10.0.19044 Build 19044

**Comment by spacecadet27** [comment]
This is my first time doing this, please let me know if I did something incorrectly or how I can improve.

**Comment by ValueRaider** [comment]
No you're right the Wiki is wrong. This is my fault, looks like I mixed up with `Ticker.history()`. Correct API is in `yfinance/multi.py`. Wiki is open-edit if you want to fix.

**Comment by spacecadet27** [comment]
Yeah! I do want to fix it. Let me try.

**Comment by ValueRaider** [comment]
Can you fix rest of `download` API too? Like I said I mixed up with `Ticker.history`, and `download` has some more arguments.

**Comment by spacecadet27** [comment]
Oh, do you mean look through the Ticker.history and download methods to make sure the wiki reflects the available parameters?

**Comment by ValueRaider** [comment]
Yes but just for `download` Wiki

**Comment by spacecadet27** [comment]
Done. The raise_errors parameter did not exist in the download method, so I took it out of the wiki and saved it.
