### ISSUE TITLE
Unable to aggregate "Capital Gains" 

### ISSUE THREAD

**Issue by mppics** [ranaroussi/yfinance#1453]
Some tickers return a Capital Gains column (mutual funds?).  When requesting 1mo or 3mo interval I get the following error:
`File "xxx/mwe.py", line 3, in <module>
    yf.Ticker('fxaix').history(period='10y',interval='3mo')
  File "xxx\site-packages\yfinance\base.py", line 814, in history
    df = utils.safe_merge_dfs(df, capital_gains, interval)
  File "xxx\site-packages\yfinance\utils.py", line 592, in safe_merge_dfs
    df_sub = _reindex_events(df_sub, new_index, data_col)
  File "xxx\site-packages\yfinance\utils.py", line 568, in _reindex_events
    raise Exception("New index contains duplicates but unsure how to aggregate for '{}'".format(data_col_name))
Exception: New index contains duplicates but unsure how to aggregate for 'Capital Gains'`

5d and 1wk didn't give error, I'm guessing because there were no duplicates within the interval.

MRE:
`import yfinance as yf

yf.Ticker('fxaix').history(period='10y',interval='3mo')`

Potential fix to utils.py, safe_merge_dfs, above line 559 at time of writing:
`elif data_col_name == "Capital Gains":
            # Add
            df = df.groupby("_NewIndex").sum()
            df.index.name = None`

https://github.com/ranaroussi/yfinance/blob/1edeaf07dc8ea9129e37f08dc770c1e3a16f431f/yfinance/utils.py#L559

**Comment by ValueRaider** [comment]
That's the right idea but can be simpler with: `if data_col_name in ["Dividends", "Capital Gains"]:`

Can you submit a PR with a simple unit test in `tests/prices.py`?

**Comment by mppics** [comment]
Indeed, that's a better way to do it.  Thanks!

Fix and test in this PR: #1455
