### ISSUE TITLE
Downloading multi using ticker full name access

### ISSUE THREAD

**Issue by gr3ybr0w** [ranaroussi/yfinance#146]
I am trying to get the information using yf.Tickers

`tester = yf.Tickers('1COV.DE 3IN.L')`

However I now can't access the ticker info by using

`tester.1COV.DE`

**Comment by jeppeskajaa** [comment]
Was you able to figure out a solution for this issue? I might have a similar problem with Danish, where I cannot use XXXXXX.CO or YYYYYYYY.CO. Maybe it can only query US stocks?

**Comment by silvavn** [comment]
I believe there are several misconceptions here:
1. Tickers does not have those properties, if you were trying to get the prices, you would need to do `tester = yf.Tickers('1COV.DE 3IN.L').history()`
2. The DataFrame object is divided by feature, not stock, so you would do `tester.Close` for example
