### ISSUE TITLE
Exception: yfinance failed to decrypt Yahoo data response (WARNING: No decryption keys could be extracted from JS file. Falling back to backup decrypt methods)

### ISSUE THREAD

**Issue by datatrexx** [ranaroussi/yfinance#1462]
Hi There,

[issue - Exception: yfinance failed to decrypt Yahoo data response].

You folks are stars! Please may I request help on the issue below, 

Steps take 
1. Followed advise from request #1080  but am getting the failed decrpt error. 

Things I have done:

1. Installed GIT, 
2. Ran the command for the hot fix patch "git clone -b hotfix/decryption https://github.com/ranaroussi/yfinance.gi "(also ran the sys.path.insert(0, "C:\yfinance\yfinance") to complie yfinance to the session in jupyter notebook)
3. I did completely uninstall pyton and reinstall it after which did the same with yfinance ,  still no luck.

please may I request your help (I have some time off so wanted to have some fun working on this).

**Comment by datatrexx** [comment]
Thank you very much for your reply, any timeline on by when this will be fixed?

**Comment by ValueRaider** [comment]
volunteer-maintained software doesn't have a timeline
