### ISSUE TITLE
Add retry in yf.download to avoid random data not found

### ISSUE THREAD

**Issue by XJTLUmedia** [ranaroussi/yfinance#1463]
**Describe the problem**
we typically save all tickers in a list and then download in yf
`python

tickers=pd.read_excel('tickers.xlsx').to_list()
stock_data_close = pd.DataFrame(yf.download(tickers, start=start_date, end=end_date)['Adj Close'])
stock_data_open = pd.DataFrame(yf.download(tickers, start=start_date, end=end_date)['Open'])
stock_data_high = pd.DataFrame(yf.download(tickers, start=start_date, end=end_date)['High'])
stock_data_low = pd.DataFrame(yf.download(tickers, start=start_date, end=end_date)['Low'])

`
but sometimes the ticker not getting results are randomly like this, does not always the same
[*********************100%***********************]  1630 of 1630 completed

27 Failed downloads:
- OXY: No data found for this date range, symbol may be delisted
- HD: No data found for this date range, symbol may be delisted
- GATX: No data found for this date range, symbol may be delisted
- RACE: No data found for this date range, symbol may be delisted
- FIS: No data found for this date range, symbol may be delisted
- BTU: No data found for this date range, symbol may be delisted
- ALV: No data found for this date range, symbol may be delisted
- TW: No data found for this date range, symbol may be delisted
- VSH: No data found for this date range, symbol may be delisted
- WPP: No data found for this date range, symbol may be delisted
**Describe the solution**
Add multiple retry for a specific ticker if it is not able to download
stock_data_low = pd.DataFrame(yf.download(tickers, start=start_date, end=end_date,**retry=5**)['Low'])
Means for any failed download in a specific ticker, retry for 5 times.
**Additional context**

**Comment by ValueRaider** [comment]
Some considerations:
- may need to delay retries e.g. 2 seconds
- consider that Yahoo returning nothing because that symbol didn't trade / doesn't exist
- I hope obvious: only retry symbols that failed

**Comment by XJTLUmedia** [comment]
> Some considerations:
> 
> * may need to delay retries e.g. 2 seconds
> * consider that Yahoo returning nothing because that symbol didn't trade / doesn't exist
> * I hope obvious: only retry symbols that failed

I tried to download single chart in a for loop, comparing to download from a list.
It seems most failed download are finished after retry only one more time, and delay is not necessary.

5 tries would be the best if no delay applied and skipped almost instantly

The code I wrote is using if condition on the dataframe
like 
for i in range(5):
    if df.empty==True:
              continue
    else:
              break

**Comment by ValueRaider** [comment]
Is this fixed in latest release 0.2.17?

**Comment by XJTLUmedia** [comment]
> Is this fixed in latest release 0.2.17?

not yet, I have tried myself, but my coding skills isn't good enough and failed. Let's see if other people can work on

**Comment by XJTLUmedia** [comment]
> @XJTLUmedia ... you use PIP upgrade. Don't overthink it.

Ok, then no, it didn't fix
