### ISSUE TITLE
Display the greeks when returning options data

### ISSUE THREAD

**Issue by thezenvan** [ranaroussi/yfinance#1465]
**Describe the problem**
When displaying the options chain for a symbol it is missing the greeks (delta, theta, gamma, vega)

**Describe the solution**
Display the greeks when showing the options chain for a symbol

**Additional context**
Displaying the options chain using this code
```
wmt = yf.Ticker('WMT')
opt = wmt.option_chain(date='2023-04-14')
print(opt.calls)
```

**Comment by ValueRaider** [comment]
Does Yahoo display greeks on website?

**Comment by thezenvan** [comment]
No, doesn't look like it
