### ISSUE TITLE
feature request : add 'silent' option

### ISSUE THREAD

**Issue by ksjk1998** [ranaroussi/yfinance#147]
Lets say I download 'AAAA'. this would output:

1 Failed download:
- AAAA: No data found, symbol may be delisted

Is it possible to ensure this print statement doesn't output anything?

**Comment by ksjk1998** [comment]
yeah, instead of being the guy to suggest the change i decided to BE the change lol, here's my repo link if you want a free feature added.

https://github.com/ksjk1998/yfinance.git

**Comment by pranjal-joshi** [comment]
> Lets say I download 'AAAA'. this would output:
> 
> 1 Failed download:
> 
> * AAAA: No data found, symbol may be delisted
> 
> Is it possible to ensure this print statement doesn't output anything?

If this has been successfully implemented, Can you make a Pull Request to this repo so we all can get the same feature that we want.

**Comment by imLightSpeed** [comment]
You can already do this when passing `debug=False` to methods ie history.

>import yfinance as yf
> #Delisted ACR-C
> t = yf.Ticker("ACR-C")
> print(t.history(debug=False))

This will not print that the ticker is delisted

**Comment by pranjal-joshi** [comment]
> You can already do this when passing `debug=False` to methods ie history.
> 
> >import yfinance as yf
> > #Delisted ACR-C
> > t = yf.Ticker("ACR-C")
> > print(t.history(debug=False))
> 
> This will not print that the ticker is delisted
> 

`download` method internally prints error.
Provided `Ticker` method example isn't helpful in this case

**Comment by pranjal-joshi** [comment]
This can be closed as the feature implemented in #717
