### ISSUE TITLE
0.2.14 `yf.Ticker("<ticker").info` No Longer has Sector, Industry, Description Data as in 0.2.12

### ISSUE THREAD

**Issue by kennykos** [ranaroussi/yfinance#1471]
In version 0.2.12, running the code 

```
import yfinance as yf

msft = yf.Ticker("MSFT")

# get all stock info (slow)
msft.info
```

yielded sector, industry, and description, taken from the profile page, as seen below. However, this is not the case on 0.2.14. If this is intentional and the information is moved somewhere else, it is not well documented. Else, this is a bug.

![image](https://user-images.githubusercontent.com/73120774/228978253-b6ab32d9-1084-4de5-8eb8-baf1442009dd.png)

**Comment by ValueRaider** [comment]
@qianyun210603 replaced web scraping (broken) with an API fetch #1461. Is is possible to get these missing keys?

**Comment by kennykos** [comment]
I've been getting the same data from
```
from yahooquery import Ticker

symbols = 'fb aapl amzn nflx goog'

tickers = Ticker(symbols)

# Retrieve each company's profile information
data = tickers.asset_profile
```

**Comment by qianyun210603** [comment]
@ValueRaider My usage is satisfied with current version and I don't have much time on open source thing recently. Maybe will check later. 
If someone needs that urgently, they can create pr. should not be hard since the api can be found in yahooquery.

**Comment by tylerjiang1127** [comment]
> In version 0.2.12, running the code
> 
> ```
> import yfinance as yf
> 
> msft = yf.Ticker("MSFT")
> 
> # get all stock info (slow)
> msft.info
> ```
> 
> yielded sector, industry, and description, taken from the profile page, as seen below. However, this is not the case on 0.2.14. If this is intentional and the information is moved somewhere else, it is not well documented. Else, this is a bug.
> 
> ![image](https://user-images.githubusercontent.com/73120774/228978253-b6ab32d9-1084-4de5-8eb8-baf1442009dd.png)

Hey, I got the same issue here… kind of annoying with those section/industry/summary info missing. Can I downgrade the package to temporarily solve this issue?

**Comment by sanyearng** [comment]
Noted here, for inclusiveness (alongside appreciation for the fixes to yf.Ticker that have been provided so far)...  

The other data that appears missing now from yf.Ticker includes (as well as: 
'sector', 
'industry', and 
description - i.e. 'longBusinessSummary), includes the following:

1. 'website'
2. 'longName'
3. 'exchange'
4. 'targetLowPrice'
5. 'targetHighPrice'
6. 'targetMeanPrice'
7. 'targetMedianPrice'
8. 'lastDividendValue'

And simply renamed from prior versions:

1. 'forwardEps' ... is now 'epsForward'

Missing names for data items referenced above align with those that existed from yf.Ticker, pre-decryption issue, version 2.09.

**Comment by cybernkotb** [comment]
I keep getting this error : AttributeError: 'NoneType' object has no attribute 'group' when trying to access .info or any other method.
