### ISSUE TITLE
Leverage dict & list comprehensions

### ISSUE THREAD

**Issue by garrettladley** [ranaroussi/yfinance#1473]
https://github.com/ranaroussi/yfinance/blob/5367f62bd7f3b2769bf0af87fd089742af5bc7cb/yfinance/tickers.py#L89

**Comment by ValueRaider** [comment]
I don't understand what the bug is.

**Comment by garrettladley** [comment]
Not necessarily an issue, but more a stylistic thing. The PR updates the function to do the same thing with dict & list comps instead

**Comment by ValueRaider** [comment]
Oh, just submit the PR alone next time.
