### ISSUE TITLE
ImportError: lxml not found, please install it

### ISSUE THREAD

**Issue by smartyram** [ranaroussi/yfinance#148]
Code to reproduce.
```
import yfinance as yf

msft = yf.Ticker("MSFT")

msft.info
```

Ran on Python 3.6.1

**Comment by smartyram** [comment]
Once you install lxml we get this error
```ImportError: html5lib not found, please install it```

Once you install html5lib we get this error
```ImportError: BeautifulSoup4 (bs4) not found, please install it```

After you install BeautifulSoup4 we get this error
```urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>```

**Comment by arlucio** [comment]
Got this error and just did " pip3 install lxml" and it worked. I'm using python 3.7.5

Check your Python installation

**Comment by smartyram** [comment]
Thank you for your reply. I have moved on to a paid service for better reliability. Yahoo will keep changing its website and keep breaking this API. I need more stability than that.
