### ISSUE TITLE
ticker_object.income_stmt not working for days

### ISSUE THREAD

**Issue by LoreBell96** [ranaroussi/yfinance#1481]
Hi All,

I'm trying to use ticker_object.income_stmt for several days now, but I've got the following error message

   CE = ticker_object.income_stmt
         ^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: yfinance failed to decrypt Yahoo data response

how can I fix it? 

thank you in advance

**Comment by homerokzam** [comment]
What version of pandas are you using?

**Comment by ValueRaider** [comment]
@homerokzam Pandas nothing to do with this issue.

Duplicate of #1407
