### ISSUE TITLE
Get bid & ask volume?

### ISSUE THREAD

**Issue by ninetynin** [ranaroussi/yfinance#1486]
**Describe the problem**
I can't find a way to check whether the volume is in green or red for the day but only the total volume for the day
**Describe the solution**
I'm not exactly sure and idk how to do it because there's just volume quantity but not green or red as per other trading platforms
**Additional context**
If the green or red is indicated based on comparing it to previous day then feel free to close this feautre request as i thought it is idicated based on the buy / sell orders on that day but not by comparision

**Comment by ValueRaider** [comment]
Volume is just a number, it doesn't have colour.

**Comment by ValueRaider** [comment]
You mean bid & ask volume. I've never seen it on Yahoo.
