### ISSUE TITLE
No module named yfinance

### ISSUE THREAD

**Issue by luckyvictor** [ranaroussi/yfinance#149]
I am using a mac machine. I have used pip install yfinance, but when I use it in a script, it complains that there is  No module named yfinance

![Screenshot 2019-12-13 at 22 03 36](https://user-images.githubusercontent.com/16015693/70835345-b4287f00-1df4-11ea-83a0-64582f3a4223.png)

**Comment by darrenlimweiyang** [comment]
@luckyvictor you can try 

`python -m pip install yfinance --user`

**Comment by darrenlimweiyang** [comment]
I don't think that's an issue with the module. Possible that you installed it in one place while the script is running in a different environment? (For example.)

**Comment by zenmark29** [comment]
I didn't see a message that looks like this? 
Successfully installed multitasking-0.0.9 yfinance-0.1.54
Did it not complete successfully?

**Comment by shubscode** [comment]
I am having the same issue and also on Mac (if that helps)

**Comment by silvavn** [comment]
Closed as this is not a problem with the module itself.
