### ISSUE TITLE
[Potential bug] make symbol uppercase 

### ISSUE THREAD

**Issue by xareelee** [ranaroussi/yfinance#1491]
**EDIT: after I review my code again, I found I downloaded those tickers synchrously in a for-loop, so I alter my description.**

----

yfinance version: 0.2.17

I got a `KeyError` when downloading a ticker `FPLpB` (note that there is a lowercase in the symbol). I got this symbol from [polygon.io](https://polygon.io/) API, and I tried to download the history data by `yfinance`.

```py
df = yf.download("FPLpB")
```

```
File {path_to_project}/yfinance/multi.py:163 in download(...)
    161 if len(tickers) == 1:
    162     ticker = tickers[0]
--> 163     return shared._DFS[shared._ISINS.get(ticker, ticker)]
    165 try:
    166     data = _pd.concat(shared._DFS.values(), axis=1, sort=True,
    167                       keys=shared._DFS.keys())

KeyError: 'FPLPB'
```

Obviously, `shared._ISINS.get(ticker, ticker)` in line 163 is `FPLPB` and my ticker is `FPLpB`.

I tried to download the ticker `FPLpB` alone again, and the error did not show up. I don't know why.

In [multi.py#L142](https://github.com/ranaroussi/yfinance/blob/0.2.17/yfinance/multi.py#L142):

```py
# This changes the symbol as the key.
shared._DFS[ticker.upper()] = data
```

I'm not sure whether the symbol should always be capitalized or just be the original one.

**Comment by ValueRaider** [comment]
FPLpB doesn't exist on Yahoo
