### ISSUE TITLE
Note of missing yf.Ticker fields

### ISSUE THREAD

**Issue by sanyearng** [ranaroussi/yfinance#1500]
The following is a list of missing keys from yf.Ticker that had existed in the version prior to the encryption rework, and which are now missing from 0.2.18 (description in square brackets):

- currentRatio [Current Ratio (Mrq)]
- debtToEquity [Total Debt/Equity (Mrq)]
- ebitda [Ebitda (M)]
- enterpriseToEbitda [Enterprise Value/Ebitda]
- freeCashflow [Levered Free Cash Flow (Ttm) (M)]
- shortPercentOfFloat [Short % Of Float (%)]

Really appreciate all the work in this... it would be great if these could be additionally added.

**Comment by rickturner2001** [comment]
@sanyearng All these keys still exist. When you use yf.Ticker, you get back an instance of yf.Ticker. Within that instance, you can then access the `.info` property

```python
import yfinance as yf
aapl = yf.Ticker("AAPL")

info = aapl.info

print("Current Ratio:        ", info['currentRatio'])
print("Debt to Equity:       ", info['debtToEquity'])
print("EBITDA:               ",info['ebitda'])
print("Enterprise to EBITDA: ", info["enterpriseToEbitda"])
print("Free Cashflow:        ", info["freeCashflow"])
print("Short % of Float:     ", info["shortPercentOfFloat"])
```

output

```shell
Current Ratio:         0.938
Debt to Equity:        195.868
EBITDA:                125287997440
Enterprise to EBITDA:  21.522
Free Cashflow:         84729126912
Short % of Float:      0.0070999996
```

**Comment by sanyearng** [comment]
Appreciate the feedback.  I’ll double check my code, but assume it was just rejecting null values (and will assume, per your comment, that the key exists).
