### ISSUE TITLE
`period` attribute broken

### ISSUE THREAD

**Issue by parthareja** [ranaroussi/yfinance#1501]
The period='' attribute for yf.download has been broken (very recently—within this week).

period='20d' gives data for 19 days only.

yf.download(ticker, period='1d') AND yf.download(ticker, period='2d'), both giving data for ONLY current day. 

This bug has been introduced very recently. It is breaking all of my codes.

**Comment by rickturner2001** [comment]
@parthareja  it's hard to understand what the problem is if we don't know what you are trying to do and what your code looks like.  

It seems like the error might be on your end. You should investigate and understand when this event is occurring

```python
import yfinance as yf

df = yf.download("AAPL", period='2d')

assert len(df) == 2


df = yf.download("AAPL", period='1d')
assert len(df) == 1


df = yf.download("AAPL", period='20d')
assert len(df) == 20

print("Everything works!")
```

Output
```shell
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
Everything works!
```

**Comment by ValueRaider** [comment]
I'm working on improving the logging so you interrogate what `yfinance` is doing and confirm/deny it is the problem. Can you use and give feedback? Follow instructions at #1080 to install Git branch `feature/error-reporting`, then run like this:
```
import logging
logger = logging.getLogger('yfinance')
logger.setLevel(logging.DEBUG)
df = yf.Ticker('AAPL').history(period="2d")
```
and you will see this:

> DEBUG AAPL: Yahoo GET parameters: {'range': '2d', 'interval': '1d', 'includePrePost': False, 'events': 'div,splits,capitalGains'}
> DEBUG AAPL: yfinance received OHLC data: 2023-04-20 13:30:00 -> 2023-04-21 13:30:00
> DEBUG AAPL: OHLC after cleaning: 2023-04-20 09:30:00-04:00 -> 2023-04-21 09:30:00-04:00
> DEBUG AAPL: OHLC after combining events: 2023-04-20 00:00:00-04:00 -> 2023-04-21 00:00:00-04:00
> DEBUG AAPL: yfinance returning OHLC: 2023-04-20 00:00:00-04:00 -> 2023-04-21 00:00:00-04:00
