### ISSUE TITLE
is there a way to download the tickers list that yfinance provided?

### ISSUE THREAD

**Issue by peterpkoap** [ranaroussi/yfinance#1503]
Hi there,

yfinance is great for download the stock data, but you need to know the ticker first. 

I am wondering if there is a function that can show you all the tickers that yfinance has data for? for example, I want to know all the German stock market symbol that yfinance supports, is there a way to do that? Thanks!

**Comment by rickturner2001** [comment]
Hey @peterpkoap. Unfortunately, there is no direct way to list all the tickers supported by Yahoo Finance. You might want to go to their website and see for yourself.

Alternatively, you could download a list of all the stocks in the Frankfurt Stock Exchange and download them

```python
import yfinance as yf
import pandas as pd

fse_collection = pd.read_html("https://topforeignstocks.com/stock-lists/the-list-of-listed-companies-in-germany/")

if fse_collection is None:
    raise Exception("Could not find a table...")

# You can also save this locally
# for index, table in enumerate(fse_collection):
#     table.to_csv(f"collection_{index}.csv")

fse_prime_standard = fse_collection[0]
fse_general_standard = fse_collection[1]
fse_companies_on_scale = fse_collection[2]

# Download any collection
df = yf.download(list(fse_prime_standard['Ticker'].values), period="1y", interval="1d")

# Swap axis if you prefer df['Ticker']['Value'] over df['Value']['Ticker']
df = df.swaplevel(axis=1)
```

**Comment by peterpkoap** [comment]
Thank you very much!
