### ISSUE TITLE
The data seems wrong.

### ISSUE THREAD

**Issue by ChenQX1** [ranaroussi/yfinance#1505]
I fetch AAPL from 2000-01-01 by two ways, but they give different data. After checking on the yahoo finance web, i find that yfinance returns the wrong data.

```python
import pandas_datareader.data as pdr
import yfinance as yf
yf.pdr_override()

aapl_yf = yf.Ticker('AAPL')
df1 = aapl_yf.history(
    period='1y',
    start='2000-01-01',
)
df2 = pdr.get_data_yahoo(
   'AAPL',
    start='2000-01-01',
    end='2000-12-31'
)
```
Let's check the df.head() for both:
<img width="825" alt="Screenshot 2023-04-23 at 11 37 15" src="https://user-images.githubusercontent.com/61534062/233818461-8768335a-92c9-4bf8-963a-dc0defc58bcc.png">

And you can verify the real data from web https://finance.yahoo.com/quote/AAPL/history?period1=946684800&period2=949276800&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true

Anyone knows the reason?

**Comment by paulmcq** [comment]
Notice that `df1.Close` values match `df2.Adj Close`. This might be a clue.
And the Volume numbers do match.

**Comment by ChenQX1** [comment]
> Notice that `df1.Close` values match `df2.Adj Close`. This might be a clue.
> And the Volume numbers do match.

Yes. I notice that. So i am wondering whether all values are adjusted.
