### ISSUE TITLE
Data stops before end date

### ISSUE THREAD

**Issue by MaraMarsu** [ranaroussi/yfinance#1506]
For some reason the data I get is stopping at 22 April at seven a clock

  `yf.pdr_override()
  
  stock = "ETH-USD"
  start = datetime.now() - timedelta(days=50)
  now = dt.datetime.now()
  
  print(now)
  df_daily = pdr.get_data_yahoo(stock,start,now, interval = "1d")
  df_hourly = pdr.get_data_yahoo(stock,start,now, interval = "1h")`

And I get this as the last line index is this:
2023-04-22 07:00:00+00:00
![image](https://user-images.githubusercontent.com/96589467/233936267-905bd3c5-61fc-441c-949f-cb3ac5abcd92.png)

**Comment by ValueRaider** [comment]
I'm working on improving the logging so you interrogate what `yfinance` is doing and confirm/deny it is the problem. Can you use and give feedback? Follow instructions at #1080 to install Git branch `feature/error-reporting`, then run like this:
```
import logging
logging.getLogger('yfinance').setLevel(logging.DEBUG)
df_hourly = ...
```
and you will see this:

> DEBUG ETH-USD: Yahoo GET parameters: {'period1': '2023-03-05 12:22:32+00:00', 'period2': '2023-04-24 12:22:32+00:00', 'interval': '1h', 'includePrePost': False, 'events': 'div,splits,capitalGains'}
> DEBUG ETH-USD: yfinance received OHLC data: 2023-03-05 12:00:00 -> 2023-04-22 07:26:00
> DEBUG ETH-USD: OHLC after cleaning: 2023-03-05 12:00:00+00:00 -> 2023-04-22 07:00:00+00:00
> DEBUG ETH-USD: OHLC after combining events: 2023-03-05 12:00:00+00:00 -> 2023-04-22 07:00:00+00:00
> DEBUG ETH-USD: yfinance returning OHLC: 2023-03-05 12:00:00+00:00 -> 2023-04-22 07:00:00+00:00

**Comment by scott-n58** [comment]
this 5' snippet was successful returning a full day's 5' price action bars, but for some reason now stops all price action requests after 10:55.  is this a problem with Yahoo finance portal or some other unknown?
using pendulum to support datetime requests between TZs.
start = pendulum.parse(today+ " " + st_time).add(hours= -1) # local CST
end  = pendulum.parse(today+ " " + nd_time).add(hours= -1) # same
print(yf.download(tickers= symbol, interval= '5m', start= start, end= end))

ie - at the time of this submittal 11:53am CST & i am able to see 5' PA records
from 09:30:00-04:00 to 10:55:00-04:00 

thoughts or suggestions?

**Comment by ValueRaider** [comment]
@scott-n58 see my above reply
