### ISSUE TITLE
Errors in yfinance prices for dates before May 9th 2019

### ISSUE THREAD

**Issue by kannesito** [ranaroussi/yfinance#151]
Hello @ranaroussi

Do you know, what is happening on May 9th, May 10th? Seems like there is some break in the prices (plotted for two cases, Adidas ["ADS.DE"] and Allianz ["ALV.DE"]) (sorry for the different axis limits!)
On https://finance.yahoo.com/ itself the prices in the chart seem to be OK!

![allianz_yfinance_vs_AlphaVantage](https://user-images.githubusercontent.com/37479009/70868615-9d179780-1f82-11ea-8ae3-52ce5ddf3b45.png)

![adidas_yfinance_vs_AlphaVantage](https://user-images.githubusercontent.com/37479009/70868598-84a77d00-1f82-11ea-9b35-cf12ed31adf3.png)

Best regards,
Hannes

**Comment by kannesito** [comment]
I used 
```
msft = yfinance.Ticker("ADS.DE")
stock = msft.history(period="1y", interval="1d")["Close"]
```
to request the data.
I saw another YahooFinance API, where the data appear to be sane: https://github.com/maggyboy/yahoo_finance_api

Best regards,
Hannes

**Comment by ryanzlu** [comment]
AlphaVantage/yahoo shows close price instead of adjusted close price. So you would need to set `history(period="1y", interval="1d", auto_adjust=False)`

**Comment by silvavn** [comment]
Closing since answer above solves issue
