### ISSUE TITLE
Intraday data cannot extend last 60 days

### ISSUE THREAD

**Issue by shihkung** [ranaroussi/yfinance#1510]
**Describe the problem**
For Intraday data with only last 60 days, EMA can not capture the lowest price of SPX on 2023/4/26 
because it includes the holidays and the actual data length is less then that
**Describe the solution**
modify the Intraday data cannot extend last 90 days

**Additional context**

**Comment by rickturner2001** [comment]
Hey @shihkung, can you try to better articulate what the problem is?
