### ISSUE TITLE
Falure when using single ISIN as a ticker (fix included)

### ISSUE THREAD

**Issue by sevimo123** [ranaroussi/yfinance#1525]
Multiple tickers with ISINs mixed in do work, but a single ISIN fails. Here is the culprit (multi.py):

>     if len(tickers) == 1:
>        ticker = tickers[0]
>        return shared._DFS[shared._ISINS.get(ticker, ticker)]

The last line should be just

> return shared._DFS[ticker]

as at that point in time both _DFS and tickers refer to Yahoo ID instead of ISIN, and lookup by original ISIN in _DFS is failing. 

Testcase:

>import yfinance as yf
>yf.download("SE0000594111", period="7d", repair=True, progress=False, threads=False, timeout=30)

(corresponding Yahoo ID is '0P00000FYR.ST'.

**Comment by ValueRaider** [comment]
Anyone can contribute code, just read #1084
