### ISSUE TITLE
Q: has anyone noticed, yahoo finance minute data changed format?

### ISSUE THREAD

**Issue by mw66** [ranaroussi/yfinance#1527]
**Describe the problem**
Previously, the CSV doesn't have "Adj close" column, now it has and is before the "Volume" column.

Also, in the new header there is "Datetime", previously this column name is empty.

**Describe the solution**

Provide convert option to convert old data format to the new format?

**Additional context**

I didn't know when the new change started, maybe someone who has continuously downloaded data for some time knows.

**Comment by mw66** [comment]
i.e. for intraday (e.g. 5-min bar), the old format:
```
,Open,High,Low,Close,Volume
```

the new format:
```
Datetime,Open,High,Low,Close,Adj Close,Volume                                                                                                                                
```

**Comment by ValueRaider** [comment]
You followed the wrong bug template, try "Bug report"

**Comment by ValueRaider** [comment]
You followed the wrong Issue template. A bug report requires more info: https://github.com/ranaroussi/yfinance/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by mw66** [comment]
I'm not sure if this should be reported as a bug or feature request, since it's a data issue from the server side, of the historical data.

**Comment by PeterSchober005** [comment]
since you are able to download minute data, I guess you will also be able to download daily data... on my side, I am having issues with downloading data (https://github.com/ranaroussi/yfinance/issues/1526). Which pandas version and operating system are you using?

**Comment by ValueRaider** [comment]
A bug is a bug, not a new feature request. We need more info than you have provided.
