### ISSUE TITLE
Add method for insider roster

### ISSUE THREAD

**Issue by eshgovil** [ranaroussi/yfinance#1529]
**Describe the problem**
There currently exists no method to access the insider roster available on the site, next to the holders, e.g. https://finance.yahoo.com/quote/MSFT/insider-roster?p=MSFT

**Describe the solution**
Like the Holders class, implement one for InsiderRoster. 

**Additional context**

Here is how I am hacking it for now:

```python
def get_insider_roster(ticker: yf.Ticker, proxy = None) -> pd.DataFrame:
    url = f'https://finance.yahoo.com/quote/{ticker._data.ticker}/insider-roster'
    resp = ticker._data.cache_get(url, proxy)
    insiders = pd.read_html(resp.text)
    insiders = insiders[0].iloc[:-1]
    return insiders
```

**Comment by ValueRaider** [comment]
You could just submit a pull request, that's basically the code just convert columns to sensible types. Read #1084

**Comment by sshcli** [comment]
@eshgovil I agree this feature is needed. 
I also would like to suggest adding `Insider Transactions` as well.  
@ValueRaider Please let us know if this already exists.

**Comment by ValueRaider** [comment]
@sshcli Code and pull requests are public record, have a look.

**Comment by sshcli** [comment]
@ValueRaider Got it. Thanks.
