### ISSUE TITLE
Yahoo sometimes fails to apply stock split to past prices, YF could repair

### ISSUE THREAD

**Issue by ValueRaider** [ranaroussi/yfinance#1531]
Symbol CNE.L had a stock split recently, but clearly most prices before split have not been updated (except May 9):

![image](https://github.com/ValueRaider/yfinance-cache/assets/96923577/c81ccc9f-5393-497b-9fd2-357a6991d0fd)

Because the problem is obvious, implies a technical solution is possible.

~Will need to recalculate `Adj Close` - dividend is split-adjusted but Yahoo using pre-split price to calculate. May only be necessary when dividend on same day as split. Adjustment = 1 - dividend / (close day before).~ <- Not possible because impossible to know if dividend is split-adjusted or not.

Implement under the `repair` flag so default is disabled. Search in `base.py`, should be obvious.

Watch out for multiple stock splits, e.g. last week and 2 years ago. Probably the older split is properly processed, only the recent one is bad.

**Comment by ValueRaider** [comment]
I've drafted a fix but I want more examples for testing.

**Comment by lcrmorin** [comment]
Noticed the same problem during the M6 competition. I was mainly identifying problems from mostly symetrical log returns if that helps. I will report if I see another problem and will be able to help to check the solution.

**Comment by ValueRaider** [comment]
I've since found more examples for testing, and I feel confident in the algorithm, so really all it needs now is people to use and check.
