### ISSUE TITLE
Is the package able to extract top gainers via Yahoo API?

### ISSUE THREAD

**Issue by boyac** [ranaroussi/yfinance#154]
Is the package able to extract top gainers via Yahoo API? Thanks!

**Comment by CacheMoneyPlaya** [comment]
just use beautiful soup:

```
        url = "https://finance.yahoo.com/gainers"
        soup = BeautifulSoup(requests.get(url).text, 'html.parser')
        assets = soup.find_all('a', attrs={"class":"Fw(600)"})
```

This gets top 5 performers of the day

**Comment by boyac** [comment]
@CacheMoneyPlaya  Thanks a million!!

**Comment by legout** [comment]
You can also use pandas therefore.

```
import pandas as pd
gainers = pd.read_html('https://finance.yahoo.com/gainers')
```

**Comment by drizham** [comment]
is there away of getting top gainers for a specific index? Like DAX or FTSE100 or Nikkei?

**Comment by IoIxD** [comment]
This is an awful solution. The page will give you a 404 if you don't have a user agent set, and even if you do, the resulting page is ginormous because yahoo craps their site to the brim with useless shit.

    curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" https://finance.yahoo.com/gainers -o lol
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 1909k    0 1909k    0     0  1517k      0 --:--:--  0:00:01 --:--:-- 1517k
    ➜  ~ du lol -h
    1.9M    lol
    ➜  ~

**Comment by ValueRaider** [comment]
`yahooquery` code has references to "gainers", maybe look into that (`yahooquery` uses API instead of scraping = faster). If you're interested in porting to yfinance, post in #1546

**Comment by MikePendo** [comment]
```
screener = yf.Screener()
 screener.set_predefined_body(predefined_key='day_gainers')
 dict = screener.response
```

**Comment by MikePendo** [comment]
The OP didnt mention what gainers he wants. I dont see an api of how to get 52 week gainers.
@ValueRaider any idea? (sorry I am very new to it)

**Comment by ValueRaider** [comment]
Is 52 weeks gainers on website?

**Comment by R5dan** [comment]
> Is 52 weeks gainers on website?

Yes: https://finance.yahoo.com/markets/stocks/52-week-gainers/

**Comment by ValueRaider** [comment]
Firefox -> F12 network tab -> refresh -> manually inspect urls

**Comment by R5dan** [comment]
Already done, thats how I have got other urls. There is no summary url, the data is in the HTML on request.

**Comment by MikePendo** [comment]
I see, thanks. Any suggestion besides BeautifulSoup or scraping?

**Comment by ValueRaider** [comment]
> There is no summary url

I assure you all, there is a screener url for 52-week gainers.

**Comment by ValueRaider** [comment]
This isn't it?

https://query1.finance.yahoo.com/v1/finance/screener/predefined/saved?count=25&formatted=true&scrIds=FIFTY_TWO_WK_GAINERS&sortField=&sortType=&start=0&useRecordsResponse=false&fields=ticker%2Csymbol%2ClongName%2Csparkline%2CshortName%2CregularMarketPrice%2CregularMarketChange%2CregularMarketChangePercent%2CregularMarketVolume%2CaverageDailyVolume3Month%2CmarketCap%2CtrailingPE%2CfiftyTwoWeekChangePercent%2CfiftyTwoWeekRange%2CregularMarketOpen&lang=en-US&region=US

**Comment by R5dan** [comment]
Yes, that is it. I can't find that anywhere in the requests (even when looking for it). I will open a PR to add this and change some screener functionality as all the other predefined screeners can be put into that url.

**Comment by MikePendo** [comment]
@ValueRaider 
I also didnt see it in the requests so I used scraping, how did find that query (out of curiosity )?
