### ISSUE TITLE
Feature Request - No data found, symbol may be delisted

### ISSUE THREAD

**Issue by slacker247** [ranaroussi/yfinance#1548]
When I call yf.Ticker or ticker.history and the symbol is not found
Your code spits out the error directly to console
No timezone found, symbol may be delisted
Got error from yahoo api for ticker RFP, Error: {'code': 'Not Found', 'description': 'No data found, symbol may be delisted'}        

stepping out side the code execution gives error messages that are outside of my control

Yes I have the latest.  pip show yfinance 0.2.18

        try:
            histData = yf.Ticker(asset)
            data = histData.history(period="max", interval=t.OneMonth)
            print(f"data: {data}")
        except Exception as ex:
            print(f"Error: {ex}")

Which could be that yahoo is complaining that max is the problem and wants a smaller time frame.  or it could be that the symbol does not exist.
Just returning an empty dataframe and spitting an error out to the console isn't helpful
perhaps return a tuple with [dataframe, error]
error being the error you output to the console
Error: {'code': 'Not Found', 'description': 'No data found, symbol may be delisted'}

**Comment by ValueRaider** [comment]
`history` already has an argument for raising an exception, so problem is really documentation. How can it be improved?

**Comment by ValueRaider** [comment]
I answered those questions the first time you asked. I know this exact functionality exists because I implemented it.

**Comment by ValueRaider** [comment]
> enabling the "raise_error" option does not suppress the library error message

It's not meant to. It's meant to *raise* the error as an exception. I thought you wanted that.

> The default example code would be the best place to show this as an option to be set.

I want to keep the example compact, only showing popular options. Underneath is a link to Wiki covering full API, did you know?

**Comment by lcrmorin** [comment]
Hi. I faced the same problem. I'd prefer a warning and an empty dataframe personnaly. I usually handle the missing values myself down the pipeline. I prefer that than have to hurry because an error broke everything. 

The real question for me is: from a delisted ticker, could we get data history before delisting (then na after the delisting) instead of an error ? It seems very very important from a theoretical perspective to deal with survival bias.

**Comment by ValueRaider** [comment]
> I'd prefer a warning and an empty dataframe personnaly.

This is default behaviour ...

> The real question for me is: from a delisted ticker, could we get data history before delisting

Doesn't `yfinance` do this already? As long as date range covers delist date.

**Comment by lcrmorin** [comment]
Ok my bad. I had some other problem. 

Regarding the second point it doesn't seems to be the case. My exemple is the ticker 'DRE' (that was part of the M6 competition) I don't find it anymore on yahoo. I am investigating what happened, if this is a standard delisting that should not prevent getting data or another thing.

**Comment by ValueRaider** [comment]
Ok, only recent delistings are available. But once Yahoo removes data I don't see what `yfinance` can do, not affiliated with Yahoo.
