### ISSUE TITLE
Earnings per share & Weighted average shares outstanding

### ISSUE THREAD

**Issue by steven2K19** [ranaroussi/yfinance#155]
Is there ways I can find Earnings per share & Weighted average shares outstanding in fundamental sections?  Everything is provided except shares and EPS info. 
Please address.
Thanks!

**Comment by mapogu** [comment]
I think that at least EPS is available, look for forwardEps or trailingEPS under defaultKeyStatistics. For shares there is sharesOutstanding as well as floatShares. Accodring to Yahoo Finance, sharesOutstanding corresponds to 

"Shares outstanding is taken from the most recently filed quarterly or annual report and Market Cap is calculated using shares outstanding."¨

And floatShares correspnds to:
"Data provided by Morningstar, Inc."

Both of these are available at defaultKeyStatistics. 

Hope that helps!

**Comment by steven2K19** [comment]
Thanks for the answer.
The goal is to calculate YOY P/E, P/S, P/B  Growth and growth relative to industry average. 
Without the Basic share provided,  I am unable to create the important features.

**Comment by legout** [comment]
Basic and diluted EPS as well as basic average and diluted average shares is available in the income statement.

**Comment by samuelgneff** [comment]
There isn't a method to grab the income statement specifically. How can we access the income statement?

**Comment by Ankur1Ahuja** [comment]
Hi, is anyone working on this? Yahoo Finance does provide the Basic and Diluted EPS in the income statement section under financials. Is there any way for the financials function to capture that value?
