### ISSUE TITLE
Getting an exception for some tickers when fetching historical data for interval="1mo" and period="50mo"

### ISSUE THREAD

**Issue by adityanparikh** [ranaroussi/yfinance#1550]
I'm trying to build a screener and everything works fine for most tickers. But for certain few tickers I get the below exception.  I checked the Yahoo finance website and the data is all there for those tickers that are returning the exception. It seems to work fine when I change either the period or interval.

### Working Examples
`print(yf.Ticker("F").history(period="49mo",interval="1mo"))`
`print(yf.Ticker("F").history(period="51mo",interval="1mo"))`
`print(yf.Ticker("F").history(period="50mo",interval="3mo"))`

### Returning Exception
`print(yf.Ticker("F").history(period="50mo",interval="1mo"))`

### Exception
> DEBUG F: Yahoo GET parameters: {'range': '50mo', 'interval': '1mo', 'includePrePost': True, 'events': 'div,splits,capitalGains'}
DEBUG F: yfinance received OHLC data: 2019-05-01 04:00:00 -> 2023-06-07 20:03:08
DEBUG F: OHLC after cleaning: 2019-05-01 00:00:00-04:00 -> 2023-06-01 00:00:00-04:00
Traceback (most recent call last):
  File "c:\Users\Documents\stock-screener\test.py", line 7, in <module>
    print(yf.Ticker("F").history(period="50mo",interval="1mo",prepost=True))
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\base.py", line 388, in history
    df = utils.safe_merge_dfs(df, dividends, interval)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\utils.py", line 704, in safe_merge_dfs
    raise Exception("Lost data during merge despite all attempts to align data (see above)")
Exception: Lost data during merge despite all attempts to align data (see above)

**Comment by ValueRaider** [comment]
I'll handle this.

**Comment by ValueRaider** [comment]
Can you try Git branch `fix/events-merging` ? Instructions in #1080

**Comment by adityanparikh** [comment]
Thank for the quick turnaround, I was able to get the proper response using this branch.

**Comment by adityanparikh** [comment]
Just FYI, could be unrelated but started seeing a different exception with a different line of code from this `fix/events-merging` branch. I went back and checked into the main branch and this exception is not thrown with the same line of code.

`print(yf.Ticker("BAOS").history(period="50wk",interval="1wk"))`

> Traceback (most recent call last):
  File "c:\Users\Documents\stock-screener\test.py", line 3, in <module>
    print(yf.Ticker("BAOS").history(period="50wk",interval="1wk"))
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\base.py", line 394, in history
    df = utils.safe_merge_dfs(df, splits, interval)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\utils.py", line 587, in safe_merge_dfs
    td = _interval_to_timedelta(interval)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\utils.py", line 356, in _interval_to_timedelta
    return _pd.Timedelta(days=7, unit='d')
  File "pandas\_libs\tslibs\timedeltas.pyx", line 1350, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
TypeError: Invalid datetime unit in metadata string "[d]"

**Comment by ValueRaider** [comment]
It is unrelated, and odd only you get that error. What is `pandas` version?

You might be able to fix by deleting part `, unit='d'`, it's not necessary.

**Comment by adityanparikh** [comment]
That's odd. But as per your suggestion deleting `, unit='d'` from \site-packages\yfinance\utils.py seems to have fixed it for me. Thanks again.

**Comment by ValueRaider** [comment]
Leave issue open until fixed by an official PIP release.

Also feel free to patch that `timedelta` bug with a pull request.
