### ISSUE TITLE
Missing ETF weights 

### ISSUE THREAD

**Issue by lcrmorin** [ranaroussi/yfinance#1554]
First of all let me take this opportunity to thank you for greatly improving the time it takes to get ticker info. Some of my code that took 15+ mins to run now run in a minute. 

However something else changed in the code. More specifically I was able to get sector weights for ETF. This data seems to still be available on yahoo (see: https://finance.yahoo.com/quote/IVV/holdings?p=IVV, sector weighing). But this info doesn't seems to be available in the info. 

Is this an expected change ? Am i missing something ?

**Comment by ValueRaider** [comment]
`info` fetch was completely redone in PRs #1461 and #1480 - converting webpage scraping to API requests.

I had a quick look and fix super-easy, so can I get you to submit a patch to `dev` branch #1084? It's simply adding `'topHoldings'` to `modules` in `quote.py` - look at code and should be obvious.

**Comment by ValueRaider** [comment]
Also add `'price'`, this will restore more data. I think there's another issue about this, let me find it ...

**Comment by AKwoKWH** [comment]
> `info` fetch was completely redone in PRs #1461 and #1480 - converting webpage scraping to API requests.
> 
> I had a quick look and fix super-easy, so can I get you to submit a patch to `dev` branch #1084? It's simply adding `'topHoldings'` to `modules` in `quote.py` - look at code and should be obvious.

Not sure if I added the patch correctly.
Can we also have sector/asset class and country allocation of mutual funds?
eg: https://finance.yahoo.com/quote/HGIYX/holdings?p=HGIYX

**Comment by AKwoKWH** [comment]
I further check the codes, 
It seems it is getting the page "Holders" instead of "Holdings"
