### ISSUE TITLE
code from quickstart is not working properly

### ISSUE THREAD

**Issue by lcrmorin** [ranaroussi/yfinance#1557]
I am referring to the code that is displayed under the Quick Start section of the module. It doesn't seems to work with version 0.2.20 with the following error

yfinance failed to decrypt Yahoo data response

for the following attribute:

#msft.shares
#msft.income_stmt
#msft.quarterly_income_stmt
#msft.balance_sheet
#msft.quarterly_balance_sheet
#msft.cashflow
#msft.quarterly_cashflow
#msft.earnings
#msft.quarterly_earnings
#msft.sustainability
#msft.recommendations
#msft.recommendations_summary
#msft.analyst_price_target
#msft.revenue_forecasts
#msft.earnings_forecasts
#msft.earnings_trend
#msft.calendar

I get that there was a significant API change. I was wondering how to improve the quickstart guide. I was thinking about removal of the code that is not working for a start. But maybe there is a better way to proceed (Is there a way to get these informations from an alternative way in the API and document that ?)

**Comment by ValueRaider** [comment]
> Is there a way to get these informations from an alternative way in the API and document that ?

See #1546

**Comment by ValueRaider** [comment]
@ranaroussi Can you make a call on this? Because probably means **officially** recommending `yahooquery` until fixed, something I tried to avoid doing to now. Little has happened on switch to API - just 2 contributions to fix `Ticker.info` - so could be a long time until financials are ported (if ever).

**Comment by ValueRaider** [comment]
I've fixed financials tables, then removed the still-broken attributes from README.
