### ISSUE TITLE
Provide ticker lists ? 

### ISSUE THREAD

**Issue by lcrmorin** [ranaroussi/yfinance#1558]
I think it could be usefull to have ready to go ticker lists, corresponding to major indexes. Currently I am mainly working 'on the fly' by scrapping wikipedia (see code below).

```
import pandas as pd
import numpy as np

sp500 = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
sp500_list = np.array(sp500[0]['Symbol'])
```
I have found myself doing this for different indices / geographical zones. I was thinking that the module could provide some of the major indexes ticker lists. Would this be a good idea to try to include that in the module ? would you have an idea for a more reliable data source ?

Edit: I have seen multiple code / sources for ticker list (see answers here: https://quant.stackexchange.com/questions/26162/where-can-i-get-a-list-of-all-yahoo-finance-stocks-symbols). But nothing seems practically reliable for me.

**Comment by ValueRaider** [comment]
I think this is best kept to online discussions e.g. #1512
