### ISSUE TITLE
Help: Don't work with Python 3 X86 :-( only with Python x64

### ISSUE THREAD

**Issue by pbenaim** [ranaroussi/yfinance#1564]
With python x86 ( not 64 ) I haven't any error with install with : 

`pip install yfinance --upgrade --no-cache-dir` 👍 

But when I call : 

`import yfinance as yf`

Python exit, just after, without any error message 👎 

Any idea why ? With in X86? Because I use one old Win Tablet as a server ;-)

yfinance working only in 64 ? 

Thanks a lot for your help

**Comment by ValueRaider** [comment]
Any other Python modules have same problem?

**Comment by pbenaim** [comment]
Which module?

**Comment by ValueRaider** [comment]
You can name them if you want.
