### ISSUE TITLE
Last Low equal to 0 in brazilian tickers (sometimes)

### ISSUE THREAD

**Issue by sandrex** [ranaroussi/yfinance#1566]
Frequently, the last Low of data is equal to 0 when downloading Brazilian stocks. As it happened again today,  I tested on Nasdaq and it was fine.

![PLPL3 SA](https://github.com/ranaroussi/yfinance/assets/5465557/7771d533-4b89-42f3-b88d-8c5fe1b997e8)

# partial code

period = '60wk'
interval = '1wk'

ticker_data = {}

for ticker in tickers:
    try:
        data = yf.download(ticker, period=period, interval=interval, progress=False, auto_adjust=True, timeout=60)
        #data = yf.download(ticker, start='2022-01-02', end='2023-05-01', interval=interval, progress=False, show_errors=False)
        ticker_data[ticker] = data
    except Exception as e:
        print(f"An error occurred while processing {ticker}: {e}")

**Comment by ValueRaider** [comment]
Try setting `repair=True` in `download()`

**Comment by sandrex** [comment]
It works! Thank you very much!
