### ISSUE TITLE
 Have not implemented fetching 'recommendations' from Yahoo API

### ISSUE THREAD

**Issue by pythonsus** [ranaroussi/yfinance#1577]
CODE:
`import yfinance as yf)`

`tsla = yf.Ticker('TSLA'))`

`recommendations = tsla.get_recommendations())`

`print(recommendations)`

ERROR:
yfinance.exceptions.YFNotImplementedError: Have not implemented fetching 'recommendations' from Yahoo API

**Comment by sammy3755** [comment]
It seems that the 'recommendations' feature is not currently implemented in the yfinance library for fetching data from the Yahoo API. The error you encountered indicates that this specific functionality is not available.

To work around this issue, you can try using other libraries or APIs that provide recommendations data for stocks. Some popular alternatives include Alpha Vantage, Finnhub, or using a financial data provider such as Bloomberg Terminal or Refinitiv Eikon.

Here's an example of using the Alpha Vantage API to fetch stock recommendations for Tesla (TSLA):

import requests

API_KEY = 'YOUR_ALPHA_VANTAGE_API_KEY'
symbol = 'TSLA'

url = f'https://www.alphavantage.co/query?function=OVERVIEW&symbol={symbol}&apikey={API_KEY}'

response = requests.get(url)
data = response.json()

if 'RecommendationKey' in data:
    recommendation = data['RecommendationKey']
    print(f"Recommendation for {symbol}: {recommendation}")
else:
    print("Recommendation data not available.")

**Comment by paulmcq** [comment]
Thanks for the code, but this url does return recommendations for me. According to https://www.alphavantage.co/documentation/#company-overview, function=OVERVIEW response does not include analyst recommendations. My API KEY appears to work okay. Do you maybe have a higher-level service/subscription??

**Comment by sammy3755** [comment]
Yes sir I do, what do you want to achieve so I scale, and see my availability for your project

**Comment by paulmcq** [comment]
Ooops! I omitted a *NOT* from my comment above, rendering it incoherent. I apologize. Edited it to now say:
    '...this url does NOT return recommendations for me.'
My question about your possible subscription to AlfaVantage was just to determine whether that could be the reason that you get more information than I do from that url.
Thanks for your patience.

**Comment by hydrastarmaster** [comment]
AlphaVantage has changed its web services availability at some point in the last week of 2023-06. "Sustainability" is currently no longer available. Please check on https://www.alphavantage.co/ the current documentation.

**Comment by bspallholtz** [comment]
Any movement on this? 
yfinance version = 1.3.5

Still getting 
```
yfinance.exceptions.YFNotImplementedError: Have not implemented fetching 'recommendations' from Yahoo API
```

**Comment by diasssavio** [comment]
Yeah, that would be really nice. I'm using version 0.2.28 from Anaconda repository and still getting not implemented exception.

**Comment by AustinBrownLaw** [comment]
With a little bit of research, it seems that Yahoo Finance has cut off the API for sustainability and recommendations. I think we're going to have to find another way to scrape it.

**Comment by ValueRaider** [comment]
@AustinBrownLaw That's hard to believe. Normally the Yahoo webpage fetches data from API. A quick browser inspection shows me the API for ESG scores.

**Comment by AustinBrownLaw** [comment]
> @AustinBrownLaw That's hard to believe. Normally the Yahoo webpage fetches data from API. A quick browser inspection shows me the API for ESG scores.

I have to admit that I'm pretty new at this--I'm coming from doing more straightforward stats on my own data--but I'm not finding sustainability. When I inspect the site, I'm seeing nothing but formatting around the score written as a float.

**Comment by ValueRaider** [comment]
Firefox -> F12 -> Network -> F5. It isn't hard, just takes time.
