### ISSUE TITLE
No financial data ver 0.1.54

### ISSUE THREAD

**Issue by yihjian** [ranaroussi/yfinance#158]
Hi,

For all the financial related functions, including financials, balance_sheet, cashflows, I'm getting an empty dataframe.

Here's the code I used:
```
aapl = yf.Ticker('AAPL')
print(aapl.financials)
````
And I got this:
```
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []
```

Thank you for your attentions.

**Comment by palmbook** [comment]
URL seems to have been changed. I have created a pull request. For now, you can use my fork temporarily.

https://github.com/palmbook/yfinance

**Comment by palmbook** [comment]
By the way, I could not confirm the correctness of "Major Holders" and "Institutional Holders" data. Someone else please check them.

**Comment by palmbook** [comment]
I made a temporary fix. Created a pull request.

If you want, you can temporarily edit base.py with my code. Look in my repo.

**Comment by getamu** [comment]
I am having a similar issue. May I know what was the fix?
