### ISSUE TITLE
yfinance is not found with Python 3.11 Visual Studio Code on Windows 11

### ISSUE THREAD

**Issue by wzhengnz** [ranaroussi/yfinance#1580]
version = "0.2.22"
Python 3.11, Windows 11.
Error: ModuleNotFoundError: No module named 'yfinance' 
Though its installed at ...\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance

**Comment by ValueRaider** [comment]
Given you have [same issue with other modules](https://github.com/dpguthrie/yahooquery/issues/199), this isn't a problem with `yfinance`.

**Comment by wzhengnz** [comment]
Well, it starts to work after I downgrade to Python 3.9, which says the module does not support Python 3.11 well.

**Comment by ValueRaider** [comment]
Wrong. It says it isn't installed.

**Comment by ValueRaider** [comment]
I just tried installing to 3.11, works fine

```
[...]$ python3.11
Python 3.11.2 ...
>>> import yfinance as yf
>>> print(yf)
```
> <module 'yfinance' from '.../.local/lib/python3.11/site-packages/yfinance/__init__.py'>
