### ISSUE TITLE
Getting IntCastingNaNError on yf.download with repair=True

### ISSUE THREAD

**Issue by justinsl** [ranaroussi/yfinance#1587]
I am running the following code on yfinance 0.2.22:

```
df= yf.download(
    ['NISP.JK', 'IMPC.JK', 'TOWR.JK', 'ELTY.JK', 'BBRM.JK', 'MDKI.JK', 'IBFN.JK', 'MAPI.JK', 'IKAI.JK', 'BLTZ.JK'],
    interval='1d',
    start='2017-01-01',
    keepna=True,
    repair=True,
    actions=True,
    ignore_tz=True,
)
```

and it returns the following error:
`['NISP.JK', 'IMPC.JK', 'TOWR.JK', 'ELTY.JK', 'BBRM.JK', 'MDKI.JK', 'IBFN.JK', 'MAPI.JK', 'IKAI.JK', 'BLTZ.JK']: IntCastingNaNError('Cannot convert non-finite values (NA or inf) to integer')
`

Seems to work perfectly with `repair = False` though. Any idea whats going on?

**Comment by justinsl** [comment]
Thanks in advance!

**Comment by ValueRaider** [comment]
You skipped an important step in the `### Still think it's a bug?` section that answers your question. When you find it, can you recommend how to make it more obvious?
