### ISSUE TITLE
Printing '1m data not available for startTime=<epoch time> and endTime=<epoch time>' when using 2m request with repair=True

### ISSUE THREAD

**Issue by melgazar9** [ranaroussi/yfinance#1589]
Hey I'm on version 0.2.22 (newest at time of writing) and I'm experiencing the "Only 7 days worth of 1m granularity data are allowed to be fetched per request" message when requesting 2m data for forex. Here's a reproducible example.

No warning error message:
```
ticker = 'EURUSD=X'
start = (max((datetime.today() - timedelta(days=58)), pd.to_datetime('1950-01-01'))).strftime('%Y-%m-%d')
t = yf.Ticker(ticker)
df = t.history(start=start, interval='2m', prepost=True)
```

Now when you set `repair=True` you get the error message `EURUSD=X: 1m data not available for startTime=1687042800 and endTime=1687734000. Only 7 days worth of 1m granularity data are allowed to be fetched per request.`

```
df = t.history(start=start, interval='2m', prepost=True, repair=True)
```

I tried this even with a 30 day window and it also appears even though we can go up to 60 days with a 2m interval set. Is this expected because `repair=True` tries to go back beyond the start date set?

```
df = \
    t.history(start=(datetime.today() - timedelta(days=30)).strftime('%Y-%m-%d'),
              interval='2m',
              prepost=True,
              repair=True)
```

**Comment by ValueRaider** [comment]
It's expected because repairing 2m data requires fetching 1m that is hopefully correct. Run with `yf.enable_debug_mode()`

**Comment by melgazar99** [comment]
Why does 2m data need 1m intervals?

**Comment by ValueRaider** [comment]
https://github.com/ranaroussi/yfinance/wiki/Price-repair

**Comment by ValueRaider** [comment]
No worries, only wrote it yesterday.
