### ISSUE TITLE
info IndexError for some Tickers

### ISSUE THREAD

**Issue by fadyatala** [ranaroussi/yfinance#159]
Hello,

In version 0.1.54, some symbols/tickers error out when their info is downloaded as seen below (one of these tickers is TWER).

![F34AA2C1-E7C9-4FEB-953F-D7F1C613D2F3](https://user-images.githubusercontent.com/33677035/71745688-a8dad900-2e1f-11ea-840d-de27b3a1654c.png)

**Comment by mapogu** [comment]
Seems like the code is by defualt downloading holders data however some tickers might not have it. I tried with for instance "KINV-B.ST". The URL as such seems to work.

**Comment by ymyke** [comment]
Another example is ticker NESN.SW. It sometimes produces "index out of range":

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
z:\fignal\sandbox\yahoo_sandbox.py in 
----> 1 yf.Ticker("NESN.SW").info

~\Anaconda3\envs\fignal\lib\site-packages\yfinance\ticker.py in info(self)
    136     @property
    137     def info(self):
--> 138         return self.get_info()
    139 
    140     @property

~\Anaconda3\envs\fignal\lib\site-packages\yfinance\base.py in get_info(self, proxy, as_dict, *args, **kwargs)
    413 
    414     def get_info(self, proxy=None, as_dict=False, *args, **kwargs):
--> 415         self._get_fundamentals(proxy)
    416         data = self._info
    417         if as_dict:

~\Anaconda3\envs\fignal\lib\site-packages\yfinance\base.py in _get_fundamentals(self, kind, proxy)
    284         holders = _pd.read_html(url)
    285         self._major_holders = holders[0]
--> 286         self._institutional_holders = holders[1]
    287         if 'Date Reported' in self._institutional_holders:
    288             self._institutional_holders['Date Reported'] = _pd.to_datetime(

IndexError: list index out of range
```

And sometimes "No tables found":

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
z:\fignal\sandbox\yahoo_sandbox.py in 
----> 1 yf.Ticker("NESN.SW").info

~\Anaconda3\envs\fignal\lib\site-packages\yfinance\ticker.py in info(self)
    136     @property
    137     def info(self):
--> 138         return self.get_info()
    139 
    140     @property

~\Anaconda3\envs\fignal\lib\site-packages\yfinance\base.py in get_info(self, proxy, as_dict, *args, **kwargs)
    413 
    414     def get_info(self, proxy=None, as_dict=False, *args, **kwargs):
--> 415         self._get_fundamentals(proxy)
    416         data = self._info
    417         if as_dict:

~\Anaconda3\envs\fignal\lib\site-packages\yfinance\base.py in _get_fundamentals(self, kind, proxy)
    282         # holders
    283         url = "{}/{}/holders".format(self._scrape_url, self.ticker)
--> 284         holders = _pd.read_html(url)
    285         self._major_holders = holders[0]
    286         self._institutional_holders = holders[1]

~\Anaconda3\envs\fignal\lib\site-packages\pandas\io\html.py in read_html(io, match, flavor, header, index_col, skiprows, attrs, parse_dates, thousands, encoding, decimal, converters, na_values, keep_default_na, displayed_only)
   1103         na_values=na_values,
   1104         keep_default_na=keep_default_na,
-> 1105         displayed_only=displayed_only,
   1106     )

~\Anaconda3\envs\fignal\lib\site-packages\pandas\io\html.py in _parse(flavor, io, match, attrs, encoding, displayed_only, **kwargs)
    910             break
    911     else:
--> 912         raise_with_traceback(retained)
    913 
    914     ret = []

~\Anaconda3\envs\fignal\lib\site-packages\pandas\compat\__init__.py in raise_with_traceback(exc, traceback)
     45     if traceback == Ellipsis:
     46         _, _, traceback = sys.exc_info()
---> 47     raise exc.with_traceback(traceback)
     48 
     49 

ValueError: No tables found
```

**Comment by PeterChea** [comment]
This appears to occur when there is no "Top institutional holders" section under the "holders" and "major holders" page of a given ticker.

It's a very big issue causing around a third of my tickers to error.

**Comment by bparkin1283** [comment]
Yeah, love the project but this one is annoying. Someone mentioned in another thread that it probably affects other .info instantiation (_get_fundamentals?) variables as well if they do not apply. There should be some generic assignment and continue statements if the index is out of error (likely thevalues don't apply) . 

I got around this one by modifying base.py, adding a try/except around the self._institutional_holders assignment.

**Comment by otaviogaiao** [comment]
I getting the same error with ITSA4 and KLBN11, just to name a few.

**Comment by jabarny** [comment]
> Yeah, love the project but this one is annoying. Someone mentioned in another thread that it probably affects other .info instantiation (_get_fundamentals?) variables as well if they do not apply. There should be some generic assignment and continue statements if the index is out of error (likely the case that those values don't apply or are not available to the particular ticker) .
> 
> I got around this one by modifying base.py, adding a try/except around the self._institutional_holders assignment.

Hey, could you explain to a newb what is the workaround? I'm in pycharm and see the base.py script, but my try/except workaround is still returning same error. thank you. I am experiencing this issue for 'CCL'. Thank you.

**Comment by bparkin1283** [comment]
> > Yeah, love the project but this one is annoying. Someone mentioned in another thread that it probably affects other .info instantiation (_get_fundamentals?) variables as well if they do not apply. There should be some generic assignment and continue statements if the index is out of error (likely the case that those values don't apply or are not available to the particular ticker) .
> > I got around this one by modifying base.py, adding a try/except around the self._institutional_holders assignment.
> 
> Hey, could you explain to a newb what is the workaround? I'm in pycharm and see the base.py script, but my try/except workaround is still returning same error. thank you. I am experiencing this issue for 'CCL'. Thank you.

Here's what I did for self._institutional_holders. Make sure you traceback your error and that it is self._institutional_holders, otherwise you'll have to do something similar elsewhere. 

`        try:
            self._institutional_holders = holders[1]
        except Exception:
            self._institutional_holders = [None]`

**Comment by jabarny** [comment]
Awesome! Thank you.

had to delete the base.py file from the folder itself and duplicate it manually as the changes weren't saving.

**Comment by bparkin1283** [comment]
Good to hear. The cache can be annoying, I usually google it for an hour and realize restarting the terminal works, but you lose all your imports obviously.

**Comment by milkywade** [comment]
same issue here
