### ISSUE TITLE
Exception when running yf.download for some tickers

### ISSUE THREAD

**Issue by tomnewg** [ranaroussi/yfinance#1590]
Hi there,

updated to the latest version 0.2.22 and now getting this error for quite a few tickers. These tickers worked before and now I am getting N/A for the entire time series.

['MDGSW']: Exception('%ticker%: 1d data not available for startTime=-2208994789 and endTime=1689079312. Only 100 years worth of day granularity data are allowed to be fetched per request.')

Many thanks for your help

Tom

**Comment by arks-public** [comment]
I have noticed this behaviour with some other tickers. It seems that certain Yahoo tickers only have price data for 1-day and 5-day periods.

For example, notice how https://finance.yahoo.com/quote/MDGSW is blank for all views besides 1D and 5D. I think this could be related to your error.

**Comment by ValueRaider** [comment]
> Only 100 years worth of day granularity data are allowed to be fetched per request

This specific issue is fixed in pre-release 0.2.25b1.
