### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by jschelter** [ranaroussi/yfinance#1592]
I'm on yfinance version 0.2.22 (Python 3.9.10 on macOS 12.6.3), and since today, I keep getting the following error (e.g. on calling `yf.Ticker('AAPL').info`):

`HTTPError: 401 Client Error: Unauthorized for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true`

Is this a known/global issue at the moment?

#### @ValueRaider hijacking top post
Please only post if you have something useful

**Comment by eevilgeniuss** [comment]
same issue here just now... python 10, latest yfinance version, windows...

**Comment by lapis42** [comment]
It seems "v10 quoteSummary" also needs cookie and crumb.

**Comment by jyerramshetty** [comment]
Same here, from yesterday (12th July, 2023)...

**Comment by ictheblackc** [comment]
I have the same problem...

**Comment by vkrishnam** [comment]
Yes, witnessing the same problem.

**Comment by NinoNinov** [comment]
I have the same issue, it came on Thusday, on Wednesday morning my script was working and now again. Hope that can be fixed.

**Comment by mhtorregrosa** [comment]
I also have the same problem since this morning. It would be great if we could find a solution. Thanks!

**Comment by pbenaim** [comment]
history work 👍  but not Info 👎

**Comment by ValueRaider** [comment]
Well obviously this is a problem. Let's keep thread tidy and constructive now.

@lapis42 You know that because you have it working with cookie and crumb?

**Comment by decadecity** [comment]
If I use the [URL in the original message](https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true)

Using `curl` I get:

```{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Cookie"}}}```

If I do the same in a browser that has a logged in session to Yahoo! finance it returns:

```{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}```

**Comment by ValueRaider** [comment]
I have code that can extract crumb, might help. I've never used it in requests.

``` Python
import requests, re, json
def get_crumb():
    response = requests.get("https://finance.yahoo.com")
    pat = re.compile(r'window\.YAHOO\.context = ({.*?});', re.DOTALL)
    match = re.search(pat, response.text)
    if match:
        js_dict = json.loads(match.group(1))
        return js_dict.get('crumb')
    return None
```

**Comment by decadecity** [comment]
Done a bit of digging around with `curl` and browser requests and as a minimum it seems like it needs the `A1` cookie and the `crumb` URL parameter.

**Comment by pbenaim** [comment]
I had already noticed these errors on the infos, when asking for example, for crypto currencies, like BTC-USD

**Comment by lapis42** [comment]
@ValueRaider Yes, I was able to retrieve the data after providing crumb with cookie.

**Comment by vismoh2010** [comment]
I cannot understand what solution has to be done. Is this solved as I am having the same problem? It says invalid crumb.

**Comment by ValueRaider** [comment]
@lapis42 @decadecity Could you 2 elaborate on how you obtained and provided cookie & crumb?

**Comment by decadecity** [comment]
I got the cookie by visiting `finances.yahoo.com` in a browser and clicked through the consent dialogue which sends a POST to `consent.yahoo.com` which returns a 302 with the `Set-Cookie` for the `A1`.  I got the crumb from `window.YAHOO.context.crumb` (which I found from your comment).

With those two I could then put them into a command line `curl` and it returned the data:

`curl 'https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true&crumb={{ crumb }}'  -H 'cookie: A1={{ A1 cookie }}'`

I've not looked into how to do this in Python.

**Comment by ValueRaider** [comment]
@decadecity With a basic free Yahoo account?

**Comment by decadecity** [comment]
@ValueRaider Initially yes but once I'd used that to figure out the minimum information required I was able to do it anonymously in a private browsing window with a completely clean session.

**Comment by decadecity** [comment]
@ValueRaider @signifer-geo v0.2.23 is working for me 👍🏻

**Comment by pbenaim** [comment]
Not for me :-(

**Comment by ValueRaider** [comment]
@pbenaim You're right, `info` is missing data. We should have tested more. Can you try Git branch `hotfix/info-missing-values` - looks good to me, but worth checking

**Comment by lapis42** [comment]
@ValueRaider I used curl to check, and I was able to retrieve the data.

To get the crumb:
`curl --header "Cookie: cookie_that_i_extracted_from_the_browser https://query1.finance.yahoo.com/v1/test/getcrumb
`

To get the data:
`curl --header "Cookie: cookie_that_i_extracted_from_the_browser" https://query1.finance.yahoo.com/v10/finance/quoteSummary?modules=price,summaryDetail&crumb=crumb_that_i_just_got`

**Comment by farbodbahari** [comment]
I have the same issue with 0.2.22. Upgraded to 0.2.23 and can run the get_info(), but some columns are missing like total revenue, totaldebt, margin etc.

import yfinance as yf
msft = yf.Ticker("MSFT")

# get all stock info
msft.get_info()

**Comment by pedrochassin** [comment]
I was able to fix it by upgrading yfinance: `pip install --upgrade yfinance`
hope it works for someone

**Comment by vkrishnam** [comment]
Yes, upgrading to 0.2.23 works !!!

**Comment by farbodbahari** [comment]
Is anyone able to pull the same number of fields with .23 version as they did with .22 version? I need the other fundamentals fields such as revenue and margins whcih the .23 veraion does not provide anymore.

**Comment by jyerramshetty** [comment]
It worked after upgradation, but some fields are missing, like "currentPrice" as well... Any idea on how to get that information?...

**Comment by Coachcflan** [comment]
same thing happened to me I need description field... Anybody know how to get all the fields back?

**Comment by ValueRaider** [comment]
Does no one read anymore? https://github.com/ranaroussi/yfinance/issues/1592#issuecomment-1634938667

**Comment by OktayBogazkaya** [comment]
Upgrading to 0.2.23 works, but I can't get the ticker symbol from ticker.info anymore ???

ticker = yf.Ticker(isin)
ticker.info["symbol"]

**Comment by ColaOfficial** [comment]
Hey,
 with me the retrieval of "info" also works after the update of yfinance. But now I can't retrieve information like "sector" or "longName" anymore. The problem is that with "info" this information is not displayed anymore (output: {'maxAge': 86400, 'priceHint': 2, 'previousClose': 189.77, 'open': 190.5, 'dayLow': 189.78, 'dayHigh': 191.19, 'regularMarketPreviousClose': 189.77, 'regularMarketOpen': 190. 5, 'regularMarketDayLow': 189.78, 'regularMarketDayHigh': 191.19, 'dividendRate': 0.96, 'dividendYield': 0.0050999997, 'exDividendDate': 1683849600, 'payoutRatio': 0.1559, 'fiveYearAvgDividendYield': 0.89, 'beta': 1.292349, 'trailingPE': 32.131535, 'forwardPE': 28. 957447, 'volume': 38321242, 'regularMarketVolume': 38321242, 'averageVolume': 56677663, 'averageVolume10days': 51027070, 'averageDailyVolume10Day': 51027070, 'bid': 0. 0, 'ask': 0.0, 'bidSize': 1000, 'askSize': 1300, 'marketCap': 2996946599936, 'fiftyTwoWeekLow': 124. 17, 'fiftyTwoWeekHigh': 194.48, 'priceToSalesTrailing12Months': 7.7823563, 'fiftyDayAverage': 180.4268, 'twoHundredDayAverage': 156. 0571, 'trailingAnnualDividendRate': 0.92, 'trailingAnnualDividendYield': 0.004847974, 'currency': 'USD', 'trailingPegRatio': 2.618}). Does anyone have the same problem or know how I can solve it?
 
 `import yfinance as yf
tickersymbol = "AAPL"
ticker = yf.Ticker(tickersymbol)
info = ticker.info

print(info)`

**Comment by decadecity** [comment]
How's this:

```
import urllib.parse

modules = ['summaryProfile', 'financialData', 'quoteType',
                     'defaultKeyStatistics', 'assetProfile', 'summaryDetail']
urllib.parse.urlencode([('ssl', 'true')] + [('module', m) for m in modules])
```

Results in:

`'ssl=true&module=summaryProfile&module=financialData&module=quoteType&module=defaultKeyStatistics&module=assetProfile&module=summaryDetail'`

**Comment by emmaai** [comment]
I've fixed it. Can I have permission to push to the repo? thanks.

**Comment by ValueRaider** [comment]
Why are people fixing this instead of reading the thread? I've already fixed it, just waiting for someone to verify.

**Comment by ColaOfficial** [comment]
Is this Code correct for this Problem?

`import requests

# Extract and replace the cookie and crumb from the browser
cookie = "your_cookie"
crumb = "your_crumb"

# Function to retrieve the crumb
def get_crumb():
    url = "https://query1.finance.yahoo.com/v1/test/getcrumb"
    headers = {"Cookie": cookie}
    response = requests.get(url, headers=headers)
    crumb = response.content.decode("utf-8")
    return crumb

# Function to retrieve the data
def get_data():
    url = f"https://query1.finance.yahoo.com/v10/finance/quoteSummary?modules=price,summaryDetail&crumb={crumb}"
    headers = {"Cookie": cookie}
    response = requests.get(url, headers=headers)
    data = response.json()
    return data

# Retrieve the crumb
crumb = get_crumb()

# Retrieve the data
data = get_data()

# Example processing of the obtained data
if "quoteSummary" in data:
    quote_summary = data["quoteSummary"]
    if "result" in quote_summary:
        result = quote_summary["result"]
        if result:
            # Example access to price information
            price_info = result[0].get("price")
            if price_info:
                regular_market_price = price_info.get("regularMarketPrice")
                if regular_market_price:
                    print("Regular Market Price:", regular_market_price)
            # Example access to detail information
            summary_detail = result[0].get("summaryDetail")
            if summary_detail:
                market_cap = summary_detail.get("marketCap")
                if market_cap:
                    print("Market Cap:", market_cap)
else:
    print("Error retrieving data.")
`

**Comment by emmaai** [comment]
> Why are people fixing this instead of reading the thread? I've already fixed it, just waiting for someone to verify.
> 
> Am I muted?

coz the code doesn't work on the branch, at least for me...

**Comment by ValueRaider** [comment]
@emmaai My branch does that, see: https://github.com/ranaroussi/yfinance/compare/main...hotfix/info-missing-values

**Comment by arturmeneghel** [comment]
Hello all,
I do not seem to understand how to implement the fix suggested in https://github.com/ranaroussi/yfinance/compare/main...hotfix/info-missing-values, could someone explain?

**Comment by eromualdez** [comment]
As of 0.2.23, accessing .info is still not providing the usual info provided.

`{'maxAge': 86400, 'priceHint': 2, 'previousClose': 449.56, 'open': 450.475, 'dayLow': 450.1204, 'dayHigh': 451.36, 'regularMarketPreviousClose': 449.56, 'regularMarketOpen': 450.475, 'regularMarketDayLow': 450.1204, 'regularMarketDayHigh': 451.36, 'trailingPE': 22.682621, 'volume': 14989271, 'regularMarketVolume': 14989271, 'averageVolume': 79326621, 'averageVolume10days': 72189580, 'averageDailyVolume10Day': 72189580, 'bid': 451.13, 'ask': 451.15, 'bidSize': 800, 'askSize': 1200, 'yield': 0.0147, 'totalAssets': 422720372736, 'fiftyTwoWeekLow': 348.11, 'fiftyTwoWeekHigh': 451.36, 'fiftyDayAverage': 426.8016, 'twoHundredDayAverage': 401.6613, 'trailingAnnualDividendRate': 5.662, 'trailingAnnualDividendYield': 0.012594538, 'navPrice': 449.6167, 'currency': 'USD', 'trailingPegRatio': None}`

**Comment by ValueRaider** [comment]
@decadecity Your experience is interesting, because it *should* only be returning "summaryDetail" module = ~37 values instead of ~130

Anyway I've created a PR #1603

**Comment by decadecity** [comment]
@ValueRaider on `main` (0.2.23) it returns 37, it returned 129 on the fix branch so, purely based on number of keys, seems like it's working.

**Comment by farbodbahari** [comment]
The 23 versionn does not work anymore. I now get error with 24 version - which was uploasded an hour ago- as well.

**Comment by NinoNinov** [comment]
What error I extracted sucessfully data that needed for my report with version 24

**Comment by tusharrusia** [comment]
> What error I extracted sucessfully data that needed for my report with version 24

Working fine for me also, tested just now.

**Comment by meekey463** [comment]
> I was able to fix it by upgrading yfinance: `pip install --upgrade yfinance` hope it works for someone

updating yfinance worked.thanks

**Comment by hzahiri1985** [comment]
it works for me by upgrading the finance to 0.2.24. thanks everyone!

**Comment by VaglioF** [comment]
> I was able to fix it by upgrading yfinance: `pip install --upgrade yfinance` hope it works for someone

It works, thank you!

**Comment by ictheblackc** [comment]
version 0.2.24 works fine!
