### ISSUE TITLE
Getting number of shares at the time of request (now)

### ISSUE THREAD

**Issue by mahmoodn** [ranaroussi/yfinance#1593]
I was reading yfinance documentation to see if it is possible to the the number of shares of a given company at the time of sending the request, but didn't find that explicitly. There is an example like
````
# show share count
msft.get_shares_full(start="2022-01-01", end=None)
````
But that needs a date. I was thinking about a code like this:
```
while true:
    n = msft.get_shares_full(NOW)
    print("Number of shares =", n)
    sleep(60)
````
Using `get_shares_full()` shows a list of shares based on some dates, e.g:
```
2022-01-27    7496869888
2022-02-04    7800719872
2022-02-05    7496869888
2022-02-11    7496869888
2022-03-04    7605040128
...
````
Is there a way to achieve that?

**Comment by ValueRaider** [comment]
Share count isn't trading volume.
