### ISSUE TITLE
Ticker.info data bug

### ISSUE THREAD

**Issue by WellyngtonF** [ranaroussi/yfinance#1598]
After the latest update to fix the 401 error, the function Ticker.Info dont return the same data as before, in my app i use this to get the LongName of the ticker, but now this value doesnt exist anymore.

Print of return data for the ticker ^BVSP:
![image](https://github.com/ranaroussi/yfinance/assets/59291417/c9f90171-021d-4fa4-80ea-92a78abd5a14)

**Comment by ValueRaider** [comment]
We know, see https://github.com/ranaroussi/yfinance/issues/1592#issuecomment-1634938667

**Comment by WellyngtonF** [comment]
> We know, see [#1592 (comment)](https://github.com/ranaroussi/yfinance/issues/1592#issuecomment-1634938667)

Thanks, so i'll wait for the update, thanks for your time solving the problem.

**Comment by ValueRaider** [comment]
@ColaOfficial The explanation has already been provided. Twice. https://github.com/ranaroussi/yfinance/issues/1592#issuecomment-1635652075
