### ISSUE TITLE
Get News Articles

### ISSUE THREAD

**Issue by RainmakerP** [ranaroussi/yfinance#1602]
Hi, 

Is there a way to get news articles, with their content, through yfinance?

It seems like currently we're only getting metadata for the articles but not the actual content of the article.

Any help or pointers are greatly appreciated!

Thanks!

**Comment by GerritVanMol** [comment]
Any updates on this? This would be very useful for me as well...

**Comment by wj210** [comment]
is there any way to get historical news as well? like over a time frame?

**Comment by rickturner2001** [comment]
Beautifulsoup is in the requirements.txt, we could use that to write a scraper and get the news for whatever ticker. any thoughts on this @ValueRaider ?

**Comment by ValueRaider** [comment]
`Ticker.news` already returns URLs so why scraping needed?

**Comment by rickturner2001** [comment]
Well in the same request we could screape the headline, description, publisher and when the news was published. So it might be a good idea to provide a dataframe with this data

**Comment by ValueRaider** [comment]
You've enumerated everything already returned by `Ticker.news`
