### ISSUE TITLE
KeyError: shortName

### ISSUE THREAD

**Issue by vismoh2010** [ranaroussi/yfinance#1609]
My program needs to get the name for a stock. This is done in finance by getting the shortName value in the dictionary. This worked until version 0.2.22. However, after updating to 0.2.24 due to missing values, I am getting a KeyError for the shortName. I am guessing that after the update, shortName is not included in the info.

Is this a global issue?
How do I fix this?

Python version is 3.10.6

**Comment by vismoh2010** [comment]
Thanks in advance.

**Comment by vismoh2010** [comment]
@ValueRaider waiting on a response.

**Comment by ValueRaider** [comment]
You skipped an important step in the `### Still think it's a bug?`. When you find it, can you recommend how to make it more obvious?

**Comment by ValueRaider** [comment]
It's a constructive way of asking why you ignored instructions. They're there for a reason.
