### ISSUE TITLE
When using `apple.info`, an HTTPError occurs."

### ISSUE THREAD

**Issue by elcsong** [ranaroussi/yfinance#1618]
### Suddenly, a feature that used to work doesn't work anymore.

`import yfinance as yf

apple = yf.Ticker("AAPL")
apple.info`

### The Error (below)
----
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Input In [39], in <cell line: 6>()
      3 apple = yf.Ticker("AAPL")
      5 # get all stock info
----> 6 apple.info

File ~\anaconda3\lib\site-packages\yfinance\ticker.py:138, in Ticker.info(self)
    136 @property
    137 def info(self) -> dict:
--> 138     return self.get_info()

File ~\anaconda3\lib\site-packages\yfinance\base.py:1020, in TickerBase.get_info(self, proxy)
   1018 def get_info(self, proxy=None) -> dict:
   1019     self._quote.proxy = proxy
-> 1020     data = self._quote.info
   1021     return data

File ~\anaconda3\lib\site-packages\yfinance\scrapers\quote.py:555, in Quote.info(self)
    551 @property
    552 def info(self) -> dict:
    553     if self._info is None:
    554         # self._scrape(self.proxy)  # decrypt broken
--> 555         self._fetch(self.proxy)
    557         self._fetch_complementary(self.proxy)
    559     return self._info

File ~\anaconda3\lib\site-packages\yfinance\scrapers\quote.py:706, in Quote._fetch(self, proxy)
    703 self._already_fetched = True
    704 modules = ['summaryProfile', 'financialData', 'quoteType',
    705              'defaultKeyStatistics', 'assetProfile', 'summaryDetail']
--> 706 result = self._data.get_raw_json(
    707     _BASIC_URL_ + f"/{self._data.ticker}", params={"modules": ",".join(modules), "ssl": "true"}, proxy=proxy
    708 )
    709 result["quoteSummary"]["result"][0]["symbol"] = self._data.ticker
    710 query1_info = next(
    711     (info for info in result.get("quoteSummary", {}).get("result", []) if info["symbol"] == self._data.ticker),
    712     None,
    713 )

File ~\anaconda3\lib\site-packages\yfinance\data.py:209, in TickerData.get_raw_json(self, url, user_agent_headers, params, proxy, timeout)
    207 def get_raw_json(self, url, user_agent_headers=None, params=None, proxy=None, timeout=30):
    208     response = self.get(url, user_agent_headers=user_agent_headers, params=params, proxy=proxy, timeout=timeout)
--> 209     response.raise_for_status()
    210     return response.json()

File ~\anaconda3\lib\site-packages\requests\models.py:960, in Response.raise_for_status(self)
    957     http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
    959 if http_error_msg:
--> 960     raise HTTPError(http_error_msg, response=self)

HTTPError: 401 Client Error: Unauthorized for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true
----
### my environment
Jupyter notebook 6.4.8
yf version : 0.2.18
pip version: 23.2
conda 22.11.0

**Comment by PhuongHoang1182** [comment]
Me too  
![image](https://github.com/ranaroussi/yfinance/assets/30220537/75ef4a2d-d727-4191-9d7b-b27262915387)
