### ISSUE TITLE
PEP 8 Coding Style Adjustments

### ISSUE THREAD

**Issue by ricardoprins** [ranaroussi/yfinance#1624]
I know this is not exactly an urgent matter...however, cleaner code is usually easier to maintain (and often easy to understand). 

There are a total of 633 PEP 8 coding style violations. I can submit a huge PR fix that adjusts the entire code or separate PRs for each code. Here's my current list (considering the main branch)

- [x] base.py (102 PEP 8 coding style violations)
- [ ] const.py (363 PEP 8 coding style violations)
- [ ] context.py (10 PEP 8 coding style violations)
- [ ] data.py (1 PEP 8 coding style violations)
- [ ] fundamentals.py (3 PEP 8 coding style violations)
- [ ] holders.py (1 PEP 8 coding style violations)
- [ ] multi.py (5 PEP 8 coding style violations)
- [x] prices.py (64 PEP 8 coding style violations)
- [ ] quote.py (29 PEP 8 coding style violations)
- [ ] setup.py (1 PEP 8 coding style violations)
- [ ] ticker.py (5 PEP 8 coding style violations)
- [ ] tickers.py (1 PEP 8 coding style violations)
- [ ] fundamentals.py (47 PEP 8 coding style violations)

After that, another suggestion would be to add a linter action that automatically scans the submitted code with each PR.

**Comment by ValueRaider** [comment]
Generally this is a good idea, but just remember these are guidelines not strict rules, so be thoughtful. My personal preference is to exempt `E702: multiple statements on one line` - this is done rarely but for good reason. May also need to exempt some `E501 line too long`, or adjust the max length.

**Comment by ricardoprins** [comment]
Yeah, we can filter some of those. However there are some more serious things such as imports in the middle of the code, bare excepts, and things like that. 

I can send a sample PR for one of the files, just to have an idea of the kind of modifications I'm talking about.

**Comment by ValueRaider** [comment]
Sure go ahead
