### ISSUE TITLE
[QUESTION] Get currency pair live data

### ISSUE THREAD

**Issue by cobap** [ranaroussi/yfinance#1637]
Hello. I searched over the issues and documentation but was not able to find if this library support live FX data like image below

![image](https://github.com/ranaroussi/yfinance/assets/6344807/b111fbb8-bead-4661-adf8-41cecae00355)

I need to know multiple currency pair FX in real-time (not historical info). Is that possible?

**Comment by rickturner2001** [comment]
You can just pass the name you see between parens to yfinance

```python
import yfinance as yf

df = yf.download("USDCOP=X", period="1y", interval="1d")
print(df)
```

**Comment by rickturner2001** [comment]
Ah I understand. As you can see in the image, the time is specified down to the minutes, so what you're gonna wanna do is download minute data and get the last entry

```python
import yfinance as yf

df = yf.download("USDCOP=X", period="1d", interval="1m")

last_entry = df.iloc[-1]
last_price = last_entry['Close']

print(last_price)

```

**Comment by cobap** [comment]
Makes a lot of sense! Appreciate it @rickturner2001 !!

**Comment by specialteam** [comment]
thanks a lot for this snippet code
