### ISSUE TITLE
[DEV] import error

### ISSUE THREAD

**Issue by ValueRaider** [ranaroussi/yfinance#1642]
Error in `dev` branch:

```
import yfinance
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "yfinance/__init__.py", line 23, in <module>
    from .ticker import Ticker
  File "yfinance/ticker.py", line 29, in <module>
    from .base import TickerBase
  File "yfinance/base.py", line 38, in <module>
    from . import utils
  File "yfinance/utils.py", line 46, in <module>
    from .base import _BASE_URL_
ImportError: cannot import name '_BASE_URL_' from partially initialized module 'yfinance.base' (most likely due to a circular import) (yfinance/base.py)
```

@ricardoprins Probably related to the PEP 8 changes.

**Comment by ricardoprins** [comment]
I will check, but just by reading this, I can tell you that this is not due to PEP 8 changes but to a bad structure of the module; there is a circular import right there.

**Comment by ValueRaider** [comment]
You introduced the circular import: https://github.com/ranaroussi/yfinance/pull/1638/files#diff-e0f80384481d23961abddb2e1b613fe5558c1a825b665f7762c2305b5b9a9f76
