### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by suntech123** [ranaroussi/yfinance#1644]
While using below function for multiple stocks (ticks) in below i am getting this error. Please suggest resolution

yf.download(ticks, period="1d", interval="1m", rounding=False, prepost=True, ignore_tz=False, progress=False)

  File "/home/user/doc/lib/python3.11/site-packages/yfinance/utils.py", line 105, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/doc/lib/python3.11/site-packages/yfinance/multi.py", line 193, in download
    for ticker in shared._TRACEBACKS:
RuntimeError: dictionary changed size during iteration

**Comment by ValueRaider** [comment]
Why you didn't use the "Bug report" issue template?

**Comment by suntech123** [comment]
Thanks for noticing this. where can i refer this template if available?

**Comment by ValueRaider** [comment]
It's the default option with bright green button ...

**Comment by VishnuAkundi** [comment]
Hey, I tried to reproduce this bug and did not get the same error you got. It returned the correct dataframe for me. Here is the code I used:
`import yfinance`

`yfinance.download(["AAPL", "META"], period="1d", interval="1m", rounding=False, prepost=True, ignore_tz=False, progress=False)`

Anything specific about the symbols you used?
