### ISSUE TITLE
why interval couldn't be '1m'

### ISSUE THREAD

**Issue by JaneLiu0617** [ranaroussi/yfinance#165]
Hi Ran, 
Thank you very much for the APT, while when I try to get the data, for example:

msft = yf.Ticker("MSFT")
# get historical market data, here max is 5 years.
msft.history(start = '2015-01-01', end = '2017-12-31', interval = '1m')

I couldn't get it and I got the message:

- MSFT: 1m data not available for startTime=1420099200 and endTime=1514707200. Only 7 days worth of 1m granularity data is allowed to be fetched per request.

I would like to get the monthly price from 2015-01-01 to 2018-12-31, could you be so kind as to give me some advice?

**Comment by dpguthrie** [comment]
The interval you used is for 1 minute. Use ‘1mo’ for one month.

**Comment by JaneLiu0617** [comment]
Thanks Doug!

**Comment by silvavn** [comment]
Closed as problem is solved
