### ISSUE TITLE
KeyError: 'currentPrice' on certain symbols

### ISSUE THREAD

**Issue by vismoh2010** [ranaroussi/yfinance#1651]
### Simple code that reproduces your problem

import yfinance as yf

data = yf.Ticker("FEDERALBNK.BO")
info = data.info
price = info["currentPrice"]
print(info)

### Debug log

Traceback (most recent call last):
  File "C:\Users\mohan\Downloads\test.py", line 6, in <module>
    price = info["currentPrice"]
            ~~~~^^^^^^^^^^^^^^^^
KeyError: 'currentPrice'

### Bad data proof

Remember that missing-info-values bug that happened recently? Well, it didn't fix all the stocks. Some of them which are known to me are:

IDFCFIRSTB.BO
BANDHANBNK.BO
BPCL.BO
FEDERALBNK.BO



### `yfinance` version

0.2.27

### Python version

3.10.6

### Operating system

_No response_

**Comment by vismoh2010** [comment]
@ValueRaider I don't know why it is occurring only for certain stocks. Help please?

**Comment by ValueRaider** [comment]
I'm not your personal assistant, also see #1649.
