### ISSUE TITLE
yfinance with python 3.11 works on windows 11 but not on windows 10

### ISSUE THREAD

**Issue by Biber76** [ranaroussi/yfinance#1658]
### Simple code that reproduces your problem

import pandas as pd
import yfinance as yf

print('start')
ticker = "AAPL"
print('ticker is AAPL')
df = yf.download(ticker, period="max")  # <- Python silently quits in here somewhere
print(df.head())
print('middle')
df.to_csv(f"./Data/{ticker}.csv")
print('end')

### Debug log

It doesn't crash but it doesn't download in vscode. It does download in vscode interactive window
Please find more information on: https://github.com/microsoft/vscode-python/issues/21774

### `yfinance` version

0.2.27

### Python version

3.11.2

### Operating system

windows 10

**Comment by Biber76** [comment]
If you say that I don't give you much, you probably missed the link to the vscode discussion...
The script starts and prints "start" and then "ticker is AAPL" after that it takes a few seconds and then the command line is back in the terminal. but the last three print statements are not executed. But there is also no error showing up. The file gets automatically deleted in vscode. This issue happens when it is run in vscode "run python file" or in the terminal. When I use the interactive window in vscode, it works fine. If I can add anything that would help you solve the issue, please let me know.

**Comment by ValueRaider** [comment]
I like brevity. I've added a comment to your code.

Try tracing, see where exactly Python stops. https://stackoverflow.com/a/49914639

**Comment by Biber76** [comment]
Unfortunately, this produces an endless loop. I had to interrupt it after about a minute.
![image](https://github.com/ranaroussi/yfinance/assets/83268686/d3fc5088-2234-4c7f-8741-06108ba8abb9)
![image](https://github.com/ranaroussi/yfinance/assets/83268686/f5588863-e268-4c63-9047-ddc520f4c562)

**Comment by Biber76** [comment]
This is what I still have in the terminal. There was much more. But it moved so fast that I couldn't see what it is. I can make a video if that helps...

**Comment by Biber76** [comment]
I tried to interrupt it right after it starts. this is what I've got. I hope it helps.
![image](https://github.com/ranaroussi/yfinance/assets/83268686/557c9d6d-f4ee-415d-9e71-33043cc1565f)

**Comment by ValueRaider** [comment]
Why would you interrupt it? You want to see where (in yfinance) it stops.

**Comment by Biber76** [comment]
ok I let it run again.

**Comment by Biber76** [comment]
![image](https://github.com/ranaroussi/yfinance/assets/83268686/bf3df04e-d1f4-4ef7-93c3-eff0ccf0ed87)

![image](https://github.com/ranaroussi/yfinance/assets/83268686/e4676fdb-3e07-4816-95bd-8fc6c9affb13)

**Comment by Biber76** [comment]
that's all I've got. Is there anything else I can do to help you?

**Comment by ValueRaider** [comment]
You can help me by analysing that trace output yourself. At least look at the last line ...

**Comment by Biber76** [comment]
Sorry, but this is totally new to me and I have no idea what this should tell me

**Comment by ValueRaider** [comment]
Sure, but you can read. What does the title of the StackOverflow post say?

**Comment by Biber76** [comment]
that every line gets printed... I can read that it prints "end"... does that explain the behaviour I experience. No. So I don't get it.

**Comment by Biber76** [comment]
Now it runs... This time my anti virus popped up and when I said it is ok, it ran without a problem. I hope this is the reason for the abortion and the automatic deletion of the file. Thank you for your help!

**Comment by ValueRaider** [comment]
I can't think of any other way to know where, in yfinance, vscode is terminating. 

If you are posting here because only yfinance is affected, then the only thing that sets yfinance apart from other Python modules is it's persistent cache. See the readme.

**Comment by Biber76** [comment]
I posted here because it only happened with that script. All other python files ran without causing problems. So I thought it must be the module that I'm not using in the other scripts.

**Comment by ValueRaider** [comment]
Possibly your AV thinks yfinance's caching is "malicious". First such issue in almost a year, so up to you to find a fix.

**Comment by Biber76** [comment]
I just got a fix from the AV support. I just have to whitelist this folder. It works now, thanks.
