### ISSUE TITLE
Missing information for PETR4.SA

### ISSUE THREAD

**Issue by macimottin** [ranaroussi/yfinance#1659]
### Simple code that reproduces your problem

I queried

# Get petr4 data
petr4 = yf.Ticker("PETR4.SA")
petr4_data = petr4.history(period="1mo") 

 and it did not bring data for yesterday (Aug 7th, 2023) and also brought missing information about today's date (Aug 8th, 2023).

### Debug log

no debug log to show. No failure was detected while running the program, despite the data that the API brought is incorrect.

### Bad data proof

these are the last 4 records that the the query brought:

2023-08-02,30.510000228881836,30.579999923706055,29.799999237060547,30.530000686645508,62068400,0.0,0.0
2023-08-03,30.93000030517578,31.1299991607666,30.6200008392334,30.920000076293945,57304400,0.0,0.0
2023-08-04,30.700000762939453,31.139999389648438,29.739999771118164,30.0,120685800,0.0,0.0
2023-08-08,0.0,0.0,0.0,30.219999313354492,0,0.0,0.0

It should have brought data for 2023-08-07 and proper information about the day 08-08-2023.
I can see that the data is also incorrect in yfinance website, when checking for daily data.

### `yfinance` version

0.2.27

### Python version

3.11

### Operating system

Windows 10

**Comment by ValueRaider** [comment]
If Yahoo is missing data, what you want yfinance to do?

**Comment by macimottin** [comment]
@ValueRaider 

Maybe have a more reliable data source, i guess! 
yfinance package is useless with incorrect data ;)

**Comment by ValueRaider** [comment]
yfinance exists to fetch from Yahoo, clue is in the name. Other sources have other packages.

**Comment by macimottin** [comment]
Yeah, I know that. I will be moving my application to another data source! Thanks

**Comment by ValueRaider** [comment]
Or read the documentation? https://github.com/ranaroussi/yfinance/wiki/Price-repair
