### ISSUE TITLE
Tickers without "info" and "historical data"

### ISSUE THREAD

**Issue by alessandroralc** [ranaroussi/yfinance#166]
Hey,

Congrats for the great job. I'm creating this issue, more as a suggestion.
For some tickers, i have a problem, that the historical data isn't filled. E.G.: IVVB11

To calculate the current day variation, the other option, it would be using the "Previous Close" information. But this is not possible, because this ticker, also has no info filled.

Is it possible to separate the previous close information, from the info array? Do you think is it a good idea?

Thank you.
Regards!

**Comment by silvavn** [comment]
Previous close is simply the information from the previous date.
