### ISSUE TITLE
Absence of Balltic Dry Index Data

### ISSUE THREAD

**Issue by devfinwiz** [ranaroussi/yfinance#1667]
The BDI (Baltic Dry Index) is a leading indicator for the bulk shipping industry. It's a measure of the cost of shipping major bulk commodities on a number of shipping routes. It's calculated daily by the Baltic Exchange. It's based on current freight rates.

It is a very great indicator that I feel should be a part of this library... Consider adding support for this new feature.

**Comment by rickturner2001** [comment]
@devfinwiz yfinance is a library that interacts with Yahoo finance's web API to provided real-time prices and historical data. The library is not supposed to provide indices and/or analysis tools for traders

**Comment by devfinwiz** [comment]
@rickturner2001 Makes sense. I was simply wondering if prices/historical data for BDI could also be made available using this API.

**Comment by devfinwiz** [comment]
Oh, my bad. There's just an etf related to it on Yahoo and the actual price history and data is available on investing.com. Closing the issue.
