### ISSUE TITLE
1d data not available for startTime=-2208994789 and endTime=1693575325

### ISSUE THREAD

**Issue by kuatroka** [ranaroussi/yfinance#1671]
### Simple code that reproduces your problem

When running the code below I'm getting an error that was supposed to be solved in an older issue [570](https://github.com/ranaroussi/yfinance/issues/570)

```
ticker = yf.Ticker("ARKOW")
ticker.get_splits()
```
There is no way to pass parameters directly to `yf.Ticker `or `get_splits() `to limit the dates from and to

Error:
```
ARKOW: 1d data not available for startTime=-2208994789 and endTime=1693575325. Only 100 years worth of day granularity data are allowed to be fetched per request.
[]
```

### Debug log

```
DEBUG    Entering history()
DEBUG     ARKOW: Yahoo GET parameters: {'period1': '1924-09-24 20:00:00-04:00', 'period2': '2023-09-01 09:41:57-04:00', 'interval': '1d', 'includePrePost': False, 'events': 'div,splits,capitalGains'}
DEBUG     ARKOW: yfinance received OHLC data: 2023-08-31 19:59:24 -> 2023-08-31 19:59:24
DEBUG     ARKOW: OHLC after cleaning: 2023-08-31 15:59:24-04:00 -> 2023-08-31 15:59:24-04:00
DEBUG     ARKOW: OHLC after combining events: 2023-08-31 00:00:00-04:00 -> 2023-08-31 00:00:00-04:00
DEBUG     ARKOW: yfinance returning OHLC: 2023-08-31 00:00:00-04:00 -> 2023-08-31 00:00:00-04:00
DEBUG    Exiting history()
```

### Bad data proof

Error message:

ARKOW: 1d data not available for startTime=-2208994789 and endTime=1693575325. Only 100 years worth of day granularity data are allowed to be fetched per request.
[]

### `yfinance` version

0.2.28

**Comment by ValueRaider** [comment]
> startTime=-2208994789

That's 125 years ago not 100, something going wrong here on your system because works fine for me:
https://github.com/ranaroussi/yfinance/blob/0713d9386769b168926d3959efd8310b56a33096/yfinance/base.py#L169
What version of Pandas?

**Comment by kuatroka** [comment]
Thanks. I was on 2.0.0. After update to 2.1.0 it works fine now.

**Comment by kuatroka** [comment]
I just tried a different ticker and keep getting errors connected with the date range. Below is the similar error

```
import yfinance as yf
yf.enable_debug_mode()
ticker = yf.Ticker("SFB")
ticker.splits
```

Error:
```
DEBUG    Entering history()
DEBUG     SFB: Yahoo GET parameters: {'period1': '1924-09-25 20:00:00-04:00', 'period2': '2023-09-01 21:51:53-04:00', 'interval': '1d', 'includePrePost': False, 'events': 'div,splits,capitalGains'}
ERROR     SFB: Period 'max' is invalid, must be one of ['1d', '5d']
DEBUG    Exiting history()
[]
```

I'm using pandas 2.1.0

**Comment by ValueRaider** [comment]
Yahoo not accepting `period='max'` _specifically for SFB_ - ook at its website. Maybe you know how yfinance can handle better.

**Comment by kuatroka** [comment]
Looking at yahoo, there are no splits for SFB at all, so I'd say yfinance should just skip it as empty because with the current message it's not clear if there is no data for this ticker or there indeed is data but something went wrong downloading it or with parameters. Maybe. splits, dividends, actions could get some optional parameters too that could be changed if needed. Like adding optional period, interval. Whatever the errors out. Thanks

**Comment by ValueRaider** [comment]
#1084

**Comment by ValueRaider** [comment]
Because the original issue was resolved, I'm closing this. Continue discussion of the subsequent `period='max'` issue in #1677
