### ISSUE TITLE
DatabaseError('database disk image is malformed') when importing multiple tickers

### ISSUE THREAD

**Issue by Byunk** [ranaroussi/yfinance#1674]
I believe this is the same bug as #1573, and it sporadically occurs but is observed quite frequently.

### Simple code that reproduces your problem

`data = yf.download(["JPM", "BAC", "WFC", "C"], period="10y")`

### Debug log

```
[*********************100%%**********************]  4 of 4 completed

3 Failed downloads:
['BAC', 'JPM', 'WFC']: DatabaseError('database disk image is malformed')
The Column Header : [('Date', ''), ('Close', 'BAC'), ('Close', 'C'), ('Close', 'JPM'), ('Close', 'WFC')]
           Date Close                   
                  BAC          C JPM WFC
0    2013-09-03   NaN  49.369999 NaN NaN
1    2013-09-04   NaN  49.599998 NaN NaN
2    2013-09-05   NaN  49.860001 NaN NaN
3    2013-09-06   NaN  49.220001 NaN NaN
4    2013-09-09   NaN  50.090000 NaN NaN
...         ...   ...        ...  ..  ..
2513 2023-08-28   NaN  41.320000 NaN NaN
2514 2023-08-29   NaN  41.720001 NaN NaN
2515 2023-08-30   NaN  41.369999 NaN NaN
2516 2023-08-31   NaN  41.290001 NaN NaN
2517 2023-09-01   NaN  41.590000 NaN NaN

[2518 rows x 5 columns]
```

### `yfinance` version

0.2.28

### Python version

3.9.15

### Operating system

macOS 13.4.1

**Comment by ValueRaider** [comment]
That's not debug log. Run with `yf.enable_debug_mode()`

**Comment by Byunk** [comment]
@ValueRaider Unfortunately, it cannot be reproduce with `yf.enable_debug_mode()`, still be occasionally observed though. Is it related to how frequently call API so that it affected by logging?

**Comment by ValueRaider** [comment]
No, this is an internal bug. Anything unusual about your environment? E.g. cloud or multiple process instances?

**Comment by Byunk** [comment]
Probably nothing unusual. I ran with my local macOS environment, and it occurs either while it runs with few other processes are running or no process is running at the same time.

**Comment by ValueRaider** [comment]
Can you try Git branch `hotfix/database-error`? #1080

**Comment by Byunk** [comment]
@ValueRaider It seems to work properly now. Thank you 👍
