### ISSUE TITLE
Feature Request: Add an option to have column and index names as lower case in history/download

### ISSUE THREAD

**Issue by furechan** [ranaroussi/yfinance#1680]
Ticker.history and download both return a dataframe with column names properly cased (first letter is upper).

Some technical analysis/charting libraries expect column names as lower case!

Currently I have to sprinkle over some calls to rename and rename_axis to convert column and index names :

`prices = prices.rename(columns=str.lower).rename_axis(index=str.lower)`

It would be nice to have an option in the api to do the same builtin.

Thanks for the great library!

**Comment by ValueRaider** [comment]
If those libraries expect lower-case, then it's their responsibility to convert to lower-case.

**Comment by furechan** [comment]
OK. Thank You

**Comment by pinkfrog9** [comment]
I would say "lower-case" is not something not used.
