### ISSUE TITLE
Performance Degradation in Python 3.11 when Fetching Ticker Information

### ISSUE THREAD

**Issue by KiringYJ** [ranaroussi/yfinance#1686]
### Describe bug

Performance degradation observed when fetching ticker information using the yfinance library in Python 3.11 as compared to Python 3.10. The execution time is approximately 5 times slower in Python 3.11.

### Simple code that reproduces your problem

```
import cProfile
import yfinance as yf

cProfile.run("yf.Ticker('QQQ').info['previousClose']")
```

### Debug log

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query2.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query2.finance.yahoo.com:443 "GET /v6/finance/quoteSummary/QQQ?modules=financialData&modules=quoteType&modules=defaultKeyStatistics&modules=assetProfile&modules=summaryDetail&ssl=true HTTP/1.1" 200 1640
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query1.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query1.finance.yahoo.com:443 "GET /ws/fundamentals-timeseries/v1/finance/timeseries/QQQ?symbol=QQQ&type=trailingPegRatio&period1=1679270400&period2=1695081600 HTTP/1.1" 200 96
         14057 function calls (13936 primitive calls) in 1.056 seconds

### `yfinance` version

0.2.28

### Python version

3.11.5 64-bit and 3.10.9 64-bit

### Operating system

Windows 10 22H2 64-bit

**Comment by ValueRaider** [comment]
Clean up that cProfile output, it's mostly zero, no one is reading that.
