### ISSUE TITLE
Operation Error : Database is Locked.

### ISSUE THREAD

**Issue by talk2jaydip** [ranaroussi/yfinance#1689]
### Describe bug

While using yfinance from docker container, throwing Error saying Operation Error: Database is locked
ticke size is 100 symobls at time
```
# Define a function that takes a list of tickers and returns a DataFrame
def download_data(ticker=None):
    try:
        time.sleep(2)
        data = yf.download (tickers=ticker,group_by="Ticker", period="60d", interval="1h",proxy=None)
        
        return data
```

### Simple code that reproduces your problem

give above

### Debug log

AS shown above

### `yfinance` version

latest

### Python version

3.7

### Operating system

ANY

**Comment by ValueRaider** [comment]
Try `main` branch, it has relevant changes that should fix.

**Comment by talk2jaydip** [comment]
@ValueRaider :

Tried out this inside docker:
 pip install git+https://github.com/ranaroussi/yfinance.git@main


![image](https://github.com/ranaroussi/yfinance/assets/16099789/0b53650b-0bc6-49e9-adf6-cd939b78ed32)

**Comment by talk2jaydip** [comment]
FYI:

```
    # Create a pool of processes with the number of CPU cores available
    with concurrent.futures.ProcessPoolExecutor(max_workers=mp.cpu_count()) as executor:
        for c in itertools.islice(tasks,mp.cpu_count()-1):
            c = [stock for stock in c if stock not in failed_list_yf]
            futures.update({executor.submit(  download_data,list(c)  ): c[0]})

```

**Comment by ValueRaider** [comment]
So you're running multiple processes, not just threads?

**Comment by talk2jaydip** [comment]
YES... to make process other signal based on latest value. otherwise would take long time.
Issue is while running with  Thread/Process PollExecutors

**Comment by ValueRaider** [comment]
`yf.download` in a loop = ‼️ Maybe rethink why do this. Maybe you need https://pypi.org/project/yfinance-cache/

**Comment by talk2jaydip** [comment]
Not in a loop, in simple terms sending 100 symbols at a time, so with  multiprocessing sending  8 req at time so that can be downloaded parallelly. 

Thanks for sharing yf-cache, i will look into it.

**Comment by ValueRaider** [comment]
> multiprocessing sending 8 req at time

‼️

`download` is already parallel.
