### ISSUE TITLE
Search by ISIN

### ISSUE THREAD

**Issue by AlexAdamenko** [ranaroussi/yfinance#170]
Thanks for the amazing library!

Is it possible to get data for instruments by ISIN and not by a symbol?

Thank you.
Regards!

**Comment by kushagrajain11** [comment]
Were you able to find a solution for this? I have the same requirement of stock search using ISIN.

**Comment by Medenor** [comment]
Same here

**Comment by pykcel** [comment]
Unfortunately it's not possible as the ISIN code can be the same for multiple ticker symbols. The ticker symbol is at exchange level and it is different depending on the market: IBM ticker is not the same in NYSE and in Buenos Aires yet ISIN is same

**Comment by Medenor** [comment]
Hello,

Seems legit. Thanks for the reply :)

**Comment by silvavn** [comment]
Not Possible.
