### ISSUE TITLE
yfinance python package creating problem in deployment

### ISSUE THREAD

**Issue by tusharrusia** [ranaroussi/yfinance#1710]
![IMG_20231001_225221](https://github.com/ranaroussi/yfinance/assets/76607467/6783679d-b8a5-4dee-a952-8e3f90c0e05c)

I am trying to host a Django Application with yfinance as one of the package using pythonanywhere.com which gives 500 MB free space.There are only three packages Django, plotly and yfinance but the size of built is crossing more than 500mb. 

I have noticed that there are many packages installed simultaneously when yfinance is installed. Are they all necessary or is there any way to avoid them ?

**Comment by rickturner2001** [comment]
Can you please provide the full  Error log message?

**Comment by suyash-9** [comment]
> Can you please provide the full Error log message?

There is no particular error , the error is just that you have overshoot the allowed disc space while installing yfinance

**Comment by tusharrusia** [comment]
> Can you please provide the full Error log message?

There is no particular error , the error is just that you have overshoot the allowed disc space while installing yfinance

**Comment by rickturner2001** [comment]
starting from scratch a venv is around **26Mb** after `pip install yfinance` the venv is going to be something like **214Mb**

after installing yfinance you should have plenty of room for whatever you need.

**Comment by tusharrusia** [comment]
I successfully solved the issue. The problem was that the linux remote server was collecting some cache files of around 100 Mb. I first installed yfinance, then django and then deleted the cache manually and then installed plotly. Yfinance needed some necessary cache files which I installed with the command :
dpkg -S /var/cache and apt-get --reinstall install yfinance

The point is that cache contains mostly temporary files which could be deleted !

**Comment by tusharrusia** [comment]
Indeed yfinance is a large package due to its dependencies crossing around 200 Mb after installation. To optimize the Disc space in case of constraints, cache files can be safely deleted. Cache files contains mostly temporary files which could be easily deleted and if any python package is giving any error due to missing necessary cache files it can be restored using the command:
dpkg -S /var/cache and apt-get --reinstall install PACKAGE_NAME
