### ISSUE TITLE
Close vs. Adj. Close

### ISSUE THREAD

**Issue by TZimm55** [ranaroussi/yfinance#1749]
**I am looking for Close price data that matches Yahoo Finance's Historical Data.**

Yahoo Finance's website under Historical Data, at the bottom, says that '*Close price adjusted for splits.' and '**Adjusted close price adjusted for splits and dividend and/or capital gain distributions.'

When I pull data from Yahoo via yfinance I don't see an 'Adj. Close' price column.
```
ticker_data = yf.Ticker('ceg')
hist = ticker_data.history(start = '1900-01-01')
print(hist.columns)
```
The only columns I see are:
```
Index(['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits'], dtype='object')
```

When I compare data from yfinance to Yahoo's Historical Data it looks like yfinance's 'Close' column matches Yahoo Finance's Historical Data 'Adj. Close' price.

Assuming yfinance's 'Close' column is Yahoo Finance's Historical Data 'Adj. Close' price, then that data should be '**...adjusted for splits and dividend and/or capital gain distributions.', but I am looking for the close price that is only '*...adjusted for splits'.

I tried looking through the code but I am not savvy enough yet to back track this. I think it, depending on how easy it is to get the 'Adj. Close' price column from Yahoo, then adding that to the output and swapping the labels would be the solution.

Information: 
yfinance, 0.2.32
IDE, Thonny
OS, Windows 11

**Comment by TZimm55** [comment]
Boom! Perfect! Exactly what I wanted. Thank you very much @bot-unit! Case closed.

**Comment by TZimm55** [comment]
I guess also, did I miss this anywhere in the any documentation?

**Comment by ValueRaider** [comment]
Wiki

**Comment by ValueRaider** [comment]
Read the README, there's a link to documentation. If not obvious then propose a change.

**Comment by quant12345** [comment]
@bot-unit do I understand correctly that if I need the old functionality, then I just pass: `auto_adjust=False`?

**Comment by ValueRaider** [comment]
https://ranaroussi.github.io/yfinance/index.html
