### ISSUE TITLE
CAC 4O equities (ex: Total FP.PA, Danone BN.PA, Orange ORA.PA...) doesn't work

### ISSUE THREAD

**Issue by baterija** [ranaroussi/yfinance#175]
Hello, i noticed that it is impossible to get any of the request except the data points for the french market in general. I tried some of the most famous equities, requesting info, cash... I get the following.
Thank you for help

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-84-454bd26d650c> in <module>
----> 1 stock.info

~/anaconda3/lib/python3.6/site-packages/yfinance/ticker.py in info(self)
    120     @property
    121     def info(self):
--> 122         return self.get_info()
    123 
    124     @property

~/anaconda3/lib/python3.6/site-packages/yfinance/base.py in get_info(self, proxy, as_dict, *args, **kwargs)
    358 
    359     def get_info(self, proxy=None, as_dict=False, *args, **kwargs):
--> 360         self._get_fundamentals(proxy)
    361         data = self._info
    362         if as_dict:

~/anaconda3/lib/python3.6/site-packages/yfinance/base.py in _get_fundamentals(self, kind, proxy)
    267                     d[item] = data['esgScores'][item]
    268 
--> 269             s = _pd.DataFrame(index=[0], data=d)[-1:].T
    270             s.columns = ['Value']
    271             s.index.name = '%.f-%.f' % (

~/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    409             )
    410         elif isinstance(data, dict):
--> 411             mgr = init_dict(data, index, columns, dtype=dtype)
    412         elif isinstance(data, ma.MaskedArray):
    413             import numpy.ma.mrecords as mrecords

~/anaconda3/lib/python3.6/site-packages/pandas/core/internals/construction.py in init_dict(data, index, columns, dtype)
    255             arr if not is_datetime64tz_dtype(arr) else arr.copy() for arr in arrays
    256         ]
--> 257     return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    258 
    259 

~/anaconda3/lib/python3.6/site-packages/pandas/core/internals/construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype)
     85     axes = [ensure_index(columns), index]
     86 
---> 87     return create_block_manager_from_arrays(arrays, arr_names, axes)
     88 
     89 

~/anaconda3/lib/python3.6/site-packages/pandas/core/internals/managers.py in create_block_manager_from_arrays(arrays, names, axes)
   1697         return mgr
   1698     except ValueError as e:
-> 1699         construction_error(len(arrays), arrays[0].shape, axes, e)
   1700 
   1701 

~/anaconda3/lib/python3.6/site-packages/pandas/core/internals/managers.py in construction_error(tot_items, block_shape, axes, e)
   1713 
   1714     if passed == implied and e is not None:
-> 1715         raise e
   1716     if block_shape[0] == 0:
   1717         raise ValueError("Empty data passed with indices specified.")

~/anaconda3/lib/python3.6/site-packages/pandas/core/internals/managers.py in create_block_manager_from_arrays(arrays, names, axes)
   1693     try:
   1694         blocks = form_blocks(arrays, names, axes)
-> 1695         mgr = BlockManager(blocks, axes)
   1696         mgr._consolidate_inplace()
   1697         return mgr

~/anaconda3/lib/python3.6/site-packages/pandas/core/internals/managers.py in __init__(self, blocks, axes, do_integrity_check)
    141 
    142         if do_integrity_check:
--> 143             self._verify_integrity()
    144 
    145         self._consolidate_check()

~/anaconda3/lib/python3.6/site-packages/pandas/core/internals/managers.py in _verify_integrity(self)
    343         for block in self.blocks:
    344             if block._verify_integrity and block.shape[1:] != mgr_shape[1:]:
--> 345                 construction_error(tot_items, block.shape[1:], self.axes)
    346         if len(self.items) != tot_items:
    347             raise AssertionError(

~/anaconda3/lib/python3.6/site-packages/pandas/core/internals/managers.py in construction_error(tot_items, block_shape, axes, e)
   1717         raise ValueError("Empty data passed with indices specified.")
   1718     raise ValueError(
-> 1719         "Shape of passed values is {0}, indices imply {1}".format(passed, implied)
   1720     )
   1721 

ValueError: Shape of passed values is (2, 31), indices imply (1, 31)

​
`

**Comment by Medenor** [comment]
Same here, it would be nice to be able to analyze european stocks on Euronext :)

**Comment by ValueRaider** [comment]
I'm going through old issues. Is this still a problem? BN.PA works for me

**Comment by duranbe** [comment]
Indeed need to use add .PA in ticker to get the Paris Quotation 

ex for Total Energies (TTE)

NYSE : `tte = yf.Ticker("TTE")`
Euronext Paris : `tte = yf.Ticker("TTE.PA")`
