### ISSUE TITLE
 ticker "HSTECH.HK"  ,  history data not showing ,but only current day data listed

### ISSUE THREAD

**Issue by OliverYangKe** [ranaroussi/yfinance#1763]
### Describe bug

for ticker "HSTECH.HK", it is a index in HONGKONG market, should be ^HTI , and there is an error to get history data while only today data is showing.
https://hk.finance.yahoo.com/quote/HSTECH.HK/history?p=HSTECH.HK

### Simple code that reproduces your problem

1 Failed download:
['HSTECH.HK']: Exception("%ticker%: Period 'max' is invalid, must be one of ['1d', '5d']")

### Debug log

is bad data

### Bad data proof

![Screenshot 2023-12-07 at 14 07 44](https://github.com/ranaroussi/yfinance/assets/13498344/e1359128-d20c-4fe4-b7f1-c4ef3b4af0cf)

### `yfinance` version

0.2.32

**Comment by ValueRaider** [comment]
For proof you need to show that Yahoo has the data.
