### ISSUE TITLE
No way to get a list of tickers for exchanges;

### ISSUE THREAD

**Issue by wail-shudar** [ranaroussi/yfinance#1780]
### Describe bug

I'm not able to get a list of tickers from an exchange of choice.

Not exactly a bug but an important feature that is missing. 

Is there a reason this hasn't been included? I wouldn't mind contributing this feature otherwise.

### Simple code that reproduces your problem

n/a

### Debug log

n/a

### `yfinance` version

2023.11.17

### Python version

3.9

### Operating system

Win11

**Comment by ValueRaider** [comment]
https://github.com/ranaroussi/yfinance/discussions?discussions_q=tickers
