### ISSUE TITLE
Start/end arguments error

### ISSUE THREAD

**Issue by Onerafaz** [ranaroussi/yfinance#1786]
When using ```
start='2023-12-01', end='2023-12-13'
``` `symbol may be delisted` error comes up but using ```period='1mo'``` no problems found. Is it just me or anyone else with this type of error?

**Comment by ValueRaider** [comment]
You need to fill the form.

**Comment by Onerafaz** [comment]
In mobile, apologies. Meanwhile check if it's a valid error or just me.
