### ISSUE TITLE
Turkish BIST stockmarket index data and some stocks data after divident is incorrect

### ISSUE THREAD

**Issue by TA2WK** [ranaroussi/yfinance#1788]
Hi there,

As you can see in screenshot Turkish BIST stock exchange market index data is incorrect. Because 2 zeros were deleted from the index in 2020 (ie, from 120.000 to 1200) however your index graph is showing the data without correction of previous periods. Thats strange. 

![GBUrvO9W4AA47z8](https://github.com/ranaroussi/yfinance/assets/68240/0efb56d1-eacd-401d-9838-7686738e0119)

Similarly stock prices are not showing the correction on previous price data after divident.

**Comment by yimmas-yimmas** [comment]
This library is extremely useful for prediction. This fix is critical for Turkish market Your help on this is really appreciated
