### ISSUE TITLE
yfinance.download and yfinance.Ticker issue

### ISSUE THREAD

**Issue by devjq** [ranaroussi/yfinance#1791]
### Describe bug

Hi all, I have difficulties getting this API to work for some reason.
I ran into `AttributeError` when running `yf.Ticker("SPY")`. Am I missing anything?

### Simple code that reproduces your problem

```
import yfinance as yf
spy = yf.Ticker("SPY")
print(spy)
```

### Debug log

`AttributeError: partially initialized module 'yfinance' has no attribute 'Ticker' (most likely due to a circular import)`

### `yfinance` version

0.2.33

**Comment by paintdog** [comment]
I couldn't reprocude your problem, it works well for me. Have you tried to reinstall yfinance?
```python
import yfinance as yf
spy = yf.Ticker("SPY")
print(spy.get_isin())```

**Comment by ValueRaider** [comment]
Probably they named the file "yfinance.py"

**Comment by devjq** [comment]
> Probably they named the file "yfinance.py"

yes, I did. it works now. thanks for the response!
