### ISSUE TITLE
yf.Ticker(symbol).info hits 404 client error

### ISSUE THREAD

**Issue by kechan** [ranaroussi/yfinance#1794]
I am calling yf.Ticker(symbol).info to try to get company profile of a symbol. For past few days, [https://query2.finance.yahoo.com/v6/finance/quoteSummary](https://query2.finance.yahoo.com/v6/finance/quoteSummary/... seemed to be down and showing 
<img width="465" alt="Screenshot 2023-12-19 at 9 36 42 PM" src="https://github.com/ranaroussi/yfinance/assets/122762/2d119812-7a01-4a2a-96a2-960de66f5091">

just wonder if anyone else have seen this, and if there's a status page somewhere to check

**Comment by jianjye** [comment]
I had the same issue. upgrading yfinance to the latest version (0.2.33) seems to work for me.
