### ISSUE TITLE
Earnings and other financial information now being populated

### ISSUE THREAD

**Issue by gautama** [ranaroussi/yfinance#181]
Hello, thank you for this package. I had an issue with earnings and other related data not being populated. Is this known?

```
aapl = yf.Ticker('AAPL')
aapl.earnings

	Open	High	Low	Close	Adj Close	Volume
Date						


aapl.get_cashflow()

	Open	High	Low	Close	Adj Close	Volume
Date				
```

**Comment by jramiromolina** [comment]
I had exactly the same issue, 2 weeks ago it still worked. But now is not possible to get that information. I hope is temporary, I really like this package.

**Comment by motraor3** [comment]
https://github.com/ranaroussi/yfinance/pull/187#issue-368083903
https://github.com/ranaroussi/yfinance/pull/174#issue-363186514
Add the changes from those two pull-requests in order to fix the issue

**Comment by TimBstn** [comment]
I don't quite know what I have to do there?
