### ISSUE TITLE
Yesterdays stock data is unavailable

### ISSUE THREAD

**Issue by CacheMoneyPlaya** [ranaroussi/yfinance#182]
I am using the following to retrieve data:

```yf.download(tickers = t,period = '1d',interval = '1m')```

Expecting to give me the previous days stock data in 1 minute intervals however it only returns data from 2020/01/17 and not 2020/01/20

I thought this may be poor understanding but when I then specify a start and end date with the history method and dates 2020/01/20 and 2020/01/21  I get no data available?

Is this an issue with the package or Yahoo?

**Comment by dpguthrie** [comment]
Markets were closed yesterday for MLK day.

**Comment by CacheMoneyPlaya** [comment]
Ahhh, hate being European :(
