### ISSUE TITLE
Save errors as list when performing bulk ticker downloads

### ISSUE THREAD

**Issue by AndrewJCB** [ranaroussi/yfinance#183]
I'd like to be able to save the tickers that fail to download as a list so that I can update my list of tickers for stocks daily rather than having to copy the console output of the data function and clean the data - is there a way to include this functionality in yfinance? Attempting to download all ASX listed stocks produces this list but fails to remove them from 'data'. Is there a way to automatically remove the failed downloads from data or to have it as a variable say data.errors()?

[*********************100%***********************]  2189 of 2189 completed

178 Failed downloads:
- EMD.AX: No data found, symbol may be delisted
- CST.AX: No data found for this date range, symbol may be delisted
- PPZ.AX: No data found, symbol may be delisted
- XPD.AX: No data found, symbol may be delisted
- LI1.AX: No data found, symbol may be delisted
- RT2.AX: No data found, symbol may be delisted
- TT9.AX: No data found, symbol may be delisted
- IMG.AX: No data found, symbol may be delisted
- MBL.AX: No data found for this date range, symbol may be delisted
- MEQ.AX: No data found for this date range, symbol may be delisted
- SUM.AX: No data found, symbol may be delisted
- MBJ.AX: No data found, symbol may be delisted
- AO2.AX: No data found, symbol may be delisted
- TT7.AX: No data found, symbol may be delisted
- FM2.AX: No data found, symbol may be delisted
- SCA.AX: No data found, symbol may be delisted
- SS7.AX: No data found, symbol may be delisted
- INH.AX: No data found, symbol may be delisted
- WEJ.AX: No data found, symbol may be delisted
- VPC.AX: No data found, symbol may be delisted
- SAC.AX: No data found, symbol may be delisted
- CU2.AX: No data found, symbol may be delisted
- RTD.AX: No data found for this date range, symbol may be delisted
- PUK.AX: No data found, symbol may be delisted
- LLP.AX: No data found, symbol may be delisted
- MPZ.AX: No data found, symbol may be delisted
- SBK.AX: No data found, symbol may be delisted
- NRO.AX: No data found, symbol may be delisted
- RFE.AX: No data found for this date range, symbol may be delisted
- TIH.AX: No data found, symbol may be delisted
- AR1.AX: No data found for this date range, symbol may be delisted
- TDY.AX: No data found, symbol may be delisted
- MZ2.AX: No data found, symbol may be delisted
- AYU.AX: No data found, symbol may be delisted
- DXA.AX: No data found, symbol may be delisted
- TNF.AX: No data found, symbol may be delisted
- PUS.AX: No data found, symbol may be delisted
- VPG.AX: No data found for this date range, symbol may be delisted
- HVM.AX: No data found, symbol may be delisted
- DAE.AX: No data found, symbol may be delisted
- TOZ.AX: No data found, symbol may be delisted
- NFN.AX: No data found, symbol may be delisted
- NRM.AX: No data found for this date range, symbol may be delisted
- INN.AX: No data found, symbol may be delisted
- DMG.AX: No data found, symbol may be delisted
- ANV.AX: No data found, symbol may be delisted
- LTF.AX: No data found, symbol may be delisted
- NAO.AX: No data found, symbol may be delisted
- XCL.AX: No data found, symbol may be delisted
- EMI.AX: No data found for this date range, symbol may be delisted
- DAZ.AX: No data found, symbol may be delisted
- AOR.AX: No data found for this date range, symbol may be delisted
- DAM.AX: No data found, symbol may be delisted
- SIX.AX: No data found, symbol may be delisted
- WSO.AX: No data found, symbol may be delisted
- PEU.AX: No data found, symbol may be delisted
- PUB.AX: No data found, symbol may be delisted
- SFV.AX: No data found, symbol may be delisted
- RE1.AX: No data found, symbol may be delisted
- MZT.AX: No data found, symbol may be delisted
- KIG.AX: No data found, symbol may be delisted
- SGL.AX: No data found for this date range, symbol may be delisted
- LT1.AX: No data found, symbol may be delisted
- WE1.AX: No data found, symbol may be delisted
- LO1.AX: No data found, symbol may be delisted
- MVT.AX: No data found, symbol may be delisted
- WSN.AX: No data found, symbol may be delisted
- SSF.AX: No data found, symbol may be delisted
- AOJ.AX: No data found, symbol may be delisted
- QNB.AX: No data found, symbol may be delisted
- IDJ.AX: No data found, symbol may be delisted
- WEF.AX: No data found, symbol may be delisted
- IMQ.AX: No data found, symbol may be delisted
- NFI.AX: No data found, symbol may be delisted
- WSZ.AX: No data found, symbol may be delisted
- WSQ.AX: No data found, symbol may be delisted
- TNJ.AX: No data found, symbol may be delisted
- DA1.AX: No data found, symbol may be delisted
- WSH.AX: No data found, symbol may be delisted
- PUJ.AX: No data found, symbol may be delisted
- WEH.AX: No data found, symbol may be delisted
- SM9.AX: No data found, symbol may be delisted
- NIB.AX: No data found, symbol may be delisted
- REK.AX: No data found, symbol may be delisted
- SCD.AX: No data found for this date range, symbol may be delisted
- SAZ.AX: No data found, symbol may be delisted
- PUV.AX: No data found, symbol may be delisted
- AO3.AX: No data found, symbol may be delisted
- ATB.AX: No data found, symbol may be delisted
- POV.AX: No data found, symbol may be delisted
- LCN.AX: No data found, symbol may be delisted
- RFC.AX: No data found, symbol may be delisted
- WSD.AX: No data found, symbol may be delisted
- IMO.AX: No data found, symbol may be delisted
- KFW.AX: No data found, symbol may be delisted
- EMT.AX: No data found, symbol may be delisted
- POX.AX: No data found, symbol may be delisted
- PUQ.AX: No data found, symbol may be delisted
- MDZ.AX: No data found, symbol may be delisted
- AVQ.AX: No data found, symbol may be delisted
- PER.AX: No data found, symbol may be delisted
- CBE.AX: No data found, symbol may be delisted
- KEB.AX: No data found, symbol may be delisted
- NAF.AX: No data found, symbol may be delisted
- LT3.AX: No data found, symbol may be delisted
- MZF.AX: No data found, symbol may be delisted
- LI6.AX: No data found, symbol may be delisted
- PU1.AX: No data found, symbol may be delisted
- KOP.AX: No data found, symbol may be delisted
- COS.AX: No data found for this date range, symbol may be delisted
- NXR.AX: No data found for this date range, symbol may be delisted
- CHJ.AX: No data found, symbol may be delisted
- RDA.AX: No data found, symbol may be delisted
- NAJ.AX: No data found, symbol may be delisted
- MZC.AX: No data found, symbol may be delisted
- XQL.AX: No data found, symbol may be delisted
- HTB.AX: No data found, symbol may be delisted
- MED.AX: No data found, symbol may be delisted
- WLC.AX: No data found, symbol may be delisted
- LI4.AX: No data found, symbol may be delisted
- CU1.AX: No data found, symbol may be delisted
- ICB.AX: No data found, symbol may be delisted
- CM1.AX: No data found, symbol may be delisted
- CCB.AX: No data found, symbol may be delisted
- SHZ.AX: No data found, symbol may be delisted
- PES.AX: No data found, symbol may be delisted
- TTZ.AX: No data found, symbol may be delisted
- MZ1.AX: No data found, symbol may be delisted
- KI1.AX: No data found, symbol may be delisted
- LGP.AX: No data found, symbol may be delisted
- AOL.AX: No data found, symbol may be delisted
- PUZ.AX: No data found, symbol may be delisted
- IMK.AX: No data found, symbol may be delisted
- INB.AX: No data found, symbol may be delisted
- IFX.AX: No data found, symbol may be delisted
- WEK.AX: No data found, symbol may be delisted
- WSJ.AX: No data found, symbol may be delisted
- MZA.AX: No data found, symbol may be delisted
- TES.AX: No data found for this date range, symbol may be delisted
- ELE.AX: No data found, symbol may be delisted
- PUO.AX: No data found, symbol may be delisted
- PSL.AX: No data found, symbol may be delisted
- LI5.AX: No data found, symbol may be delisted
- RFB.AX: No data found, symbol may be delisted
- SCW.AX: No data found, symbol may be delisted
- TNA.AX: No data found, symbol may be delisted
- SPW.AX: No data found, symbol may be delisted
- DGF.AX: No data found, symbol may be delisted
- QBC.AX: No data found, symbol may be delisted
- WEN.AX: No data found, symbol may be delisted
- VCD.AX: No data found, symbol may be delisted
- CHU.AX: No data found, symbol may be delisted
- HCS.AX: No data found, symbol may be delisted
- MHK.AX: No data found, symbol may be delisted
- CSK.AX: No data found, symbol may be delisted
- RTC.AX: No data found, symbol may be delisted
- RT1.AX: No data found, symbol may be delisted
- RT9.AX: No data found, symbol may be delisted
- ZOR.AX: No data found, symbol may be delisted
- TT1.AX: No data found, symbol may be delisted
- IMN.AX: No data found, symbol may be delisted
- NAH.AX: No data found, symbol may be delisted
- PUU.AX: No data found, symbol may be delisted
- TNB.AX: No data found, symbol may be delisted
- LC1.AX: No data found, symbol may be delisted
- WPG.AX: No data found, symbol may be delisted
- XVG.AX: No data found, symbol may be delisted
- TNH.AX: No data found, symbol may be delisted
- KAU.AX: No data found, symbol may be delisted
- PEP.AX: No data found for this date range, symbol may be delisted
- SS6.AX: No data found, symbol may be delisted
- IMX.AX: No data found, symbol may be delisted
- IDH.AX: No data found, symbol may be delisted
- POT.AX: No data found, symbol may be delisted
- LT4.AX: No data found, symbol may be delisted
- LI2.AX: No data found, symbol may be delisted
- SXB.AX: No data found, symbol may be delisted
- DAS.AX: No data found, symbol may be delisted

**Comment by HartBlanc** [comment]
I'm accessing the failed tickers as in the example below.
Not sure if this resolves your issue?

```python3
import yfinance as yf
data = yf.download(tickers, start_date)
missing = list(yf.shared._ERRORS.keys())
```

**Comment by VictoryPIG1952** [comment]
I also have such a issues.

`data = yf.download(
            tickers = tickerlist,
            period = '1d',
            interval = '1d',
            group_by = 'ticker',
            auto_adjust = False,
            prepost = False,
            threads = True,
            proxy = None
        )

    data = data.T
    values = []
    for company in companylist:
        
        tickdata = data.loc[(company['tick'].upper(),),].T
        result = tickdata.reset_index().to_json(None, orient='records', date_format='iso')
        resultjson = json.loads(result)
        
        if len(resultjson) == 0:
            continue
        
        if (resultjson[0]['Open']) is None:
            continue`

**Comment by VictoryPIG1952** [comment]
I also have like that issues.

data = yf.download(
            tickers = tickerlist,
            period = '1d',
            interval = '1d',
            group_by = 'ticker',
            auto_adjust = False,
            prepost = False,
            threads = True,
            proxy = None
        )

    data = data.T
    values = []
    for company in companylist:
        
        tickdata = data.loc[(company['tick'].upper(),),].T
        result = tickdata.reset_index().to_json(None, orient='records', date_format='iso')
        resultjson = json.loads(result)
        
        if len(resultjson) == 0:
            continue
        
        if (resultjson[0]['Open']) is None:
            continue

Help me
