### ISSUE TITLE
FutureWarning: from base.py :     _empty_series = pd.Series()

### ISSUE THREAD

**Issue by gene-git** [ranaroussi/yfinance#1836]
FYI - today I started getting this warning from latest git ::

```
.../yfinance/base.py:48: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  _empty_series = pd.Series()
```

**Comment by ValueRaider** [comment]
@mreiche #1724

**Comment by mreiche** [comment]
This warning doesn't show up in dependency `pandas>=1.3.0`. Should we upgrade Pandas or be forward-compatible to `pandas>=2.0.0`?

**Comment by mreiche** [comment]
@gene-git Which Pandas version are you using?

**Comment by gene-git** [comment]
Yeh thank you @mreiche  - Arch is very out of date for some reason - 1.5.3

**Comment by gene-git** [comment]
here are lots of version restrictions on building pandas (2.2.0 or git head) so be bit of a pain for me to do - think I'll wait for arch to update.

So, should we close this ?

**Comment by mreiche** [comment]
You could try something like suppressing `FutureWarnings`: https://stackoverflow.com/questions/15777951/how-to-suppress-pandas-future-warning

**Comment by gene-git** [comment]
I put this in my application - added these lines (import warnings and import pandas ::

```
import warnings
import pandas
import yfinance as yf
```
and then at the top of main I put:

```
warnings.simplefilter(action='ignore', category=FutureWarning)
_unused_dummy = pd.Series()
```

then run my program - still emits same warning in yf but not from my dummy
```
/usr/lib/python3.11/site-packages/yfinance/base.py:48: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  _empty_series = pd.Series()
```

**Comment by gene-git** [comment]
Is there a reason not to follow the suggestion and  simply add dtype to the pd.Series() line?

**Comment by mreiche** [comment]
> then run my program - still emits same warning in yf but not from my dummy
> 
> ```
> /usr/lib/python3.11/site-packages/yfinance/base.py:48: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
>   _empty_series = pd.Series()
> ```

The reason here is, that `_empty_series` gets instanced at the very beginning of the whole `yfinance` module, before you disabled warnings.

Try
```
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)

import yfinance as yf
```
Unfortunately, `_empty_series` still exists due merge conflicts beforehand. This can easily be fixed with another PR. Let me get back here soon.

**Comment by mreiche** [comment]
> Is there a reason not to follow the suggestion and simply add dtype to the pd.Series() line?

IMHO, it's outdated and fixed in current versions. Why beeing upwards-compatible for these edge cases? It's not my decision to support `pandas<2` and not beeing fully compatible. No body else complaint about this, so I guess it's not a popular thing.

**Comment by gene-git** [comment]
Okidok - moving the warning above import as you suggest works fine too.

thanks

Yeh I am fine with ignoring outdated stuff too. It's rare for arch to be this far behind on package.
