### ISSUE TITLE
download daily US quotes are off by one day if run on a computer with European locale

### ISSUE THREAD

**Issue by cngmid** [ranaroussi/yfinance#184]
On a computer localised in Europe:
```
>>> from tzlocal import get_localzone
>>> get_localzone()
<DstTzInfo 'Europe/Berlin' LMT+0:53:00 STD>
```
if one tries to get the SPY quotes between Jan 14th and Jan 16th with the naive command:
```
>>> import datetime
>>> start = datetime.datetime(2020, 1, 14)    # or '2020-01-14
>>> end = datetime.datetime(2020, 1, 16)    # or '2020-01-16
>>> yf.download('SPY', start, end, interval='1d')
[*********************100%***********************]  1 of 1 completed
                  Open        High         Low       Close   Adj Close    Volume
Date
2020-01-13  326.390015  327.959991  325.920013  327.950012  327.950012  47086800
2020-01-14  327.470001  328.619995  326.839996  327.450012  327.450012  62832800
2020-01-15  327.350006  329.019989  327.260010  328.190002  328.190002  72056600
```
one gets an extra quote for Jan 13th and misses the quote for Jan 16th.

Here is the reason why. In the function `yfinance.base.TickerBase.history`, the code uses the function `time.mktime` to convert a `time.struct_time` into a timestamp (seconds from epoch, which is UTC based). However this [function](https://docs.python.org/3/library/time.html#time.mktime) assumes the argument to be in local time. In our case, the start date '2020-01-14 00:00' is interpreted as a 'Europe/Berlin' time corresponding to the UTC time '2020-1-13 23:00' and returns the time stamp 1578956400:
```
>>> import time
>>> time.mktime(datetime.datetime(2020,1,14).timetuple())
1578956400.0
```
(a quick way to check this is to remark that 1578956400 has a remainder of 23 hours when dividing by `60*60*24`).

Moreover Yahoo returns the SPY quote for '2020-01-13' if and only if the timestamp interval includes any time between '2020-01-13 00:00 EST' and '2020-01-13 23:59 EST', i.e. '2020-01-13 05:00 UTC' and '2020-01-14 04:59 UTC'. 
This is the case for our start date and explains the extra quote that we got. Similarly, the end date '2020-01-16' is interpreted as '2020-01-15 23:00 UTC', which falls outside the range '2020-01-16 00:00 EST' to '2020-01-16 23:59 EST', i.e. '2020-01-16 05:00 UTC' to '2020-01-17 04:59 UTC'. And this explains the missing quote.

To make it work, one should rather input
```
>>> import pytz
>>> start = pytz.timezone('EST').localize(datetime.datetime(2020, 1, 14)).astimezone(pytz.timezone('CET'))
>>> end = pytz.timezone('EST').localize(datetime.datetime(2020, 1, 16)).astimezone(pytz.timezone('CET'))
>>> yf.download('SPY', start, end, interval='1d')
[*********************100%***********************]  1 of 1 completed
                  Open        High         Low       Close   Adj Close    Volume
Date
2020-01-14  327.470001  328.619995  326.839996  327.450012  327.450012  62832800
2020-01-15  327.350006  329.019989  327.260010  328.190002  328.190002  72056600
2020-01-16  329.700012  330.920013  329.450012  330.920013  330.920013  54050300
```
This is a bit cumbersome and in any case prevents the usage of strings as input for the start and end dates. Also it makes the simultaneous download of quotes across time zones quite tricky.

I'm not sure what's the best answer. For daily quotes, I ended up passing to the yahoo api the timestamp at noon UTC (which is in the middle of both the US/Eastern day and the Asia/Tokyo day). To do this with `yfinance`, I wrote a wrapper around `yfinance.download` that converts any date to the datetime at noon UTC and in the timezone of my LOCALE (see `get_localzone()`). Something like
```
>>> start = datetime.datetime(2020, 1, 14)
>>> end = datetime.datetime(2020, 1, 16)
>>> local_tz = get_localzone()
>>> start_ = pytz.UTC.localize(start.replace(hour=12)).astimezone(local_tz)
>>> end_ = pytz.UTC.localize(end.replace(hour=12)).astimezone(local_tz)
>>> yf.download('SPY', start_, end_, interval='1d')
[*********************100%***********************]  1 of 1 completed
                  Open        High         Low       Close   Adj Close    Volume
Date
2020-01-14  327.470001  328.619995  326.839996  327.450012  327.450012  62832800
2020-01-15  327.350006  329.019989  327.260010  328.190002  328.190002  72056600
2020-01-16  329.700012  330.920013  329.450012  330.920013  330.920013  54050300
```

Note that for intraday data this becomes
```
>>> start = pytz.timezone('Asia/Tokyo').localize(datetime.datetime(2020, 1, 16, 9)).astimezone(pytz.timezone('CET'))
>>> end = pytz.timezone('Asia/Tokyo').localize(datetime.datetime(2020, 1, 16, 10)).astimezone(pytz.timezone('CET'))
>>> yf.download('7203.T', start, end, interval='15m')
[*********************100%***********************]  1 of 1 completed
                             Open    High     Low   Close  Adj Close  Volume
Datetime
2020-01-16 09:00:00+09:00  7672.0  7691.0  7661.0  7674.0     7674.0  166100
2020-01-16 09:15:00+09:00  7675.0  7689.0  7673.0  7678.0     7678.0  171200
2020-01-16 09:30:00+09:00  7679.0  7685.0  7675.0  7677.0     7677.0  117500
2020-01-16 09:45:00+09:00  7677.0  7681.0  7673.0  7678.0     7678.0   93800
```

Any better idea?

**Comment by bt-maclearn** [comment]
I think you can use tomorrow's date for today's last data point.

**Comment by remiromi** [comment]
I had the same issue on European Central Time, I followed by putting the TZ environment variable at UTC before importing the date module

``` 
import os
os.environ['TZ'] = "UTC"
```
Putting this code as first instructions I was asking to the history method the queries with the appropriate dates. Before that I got an automatic conversion of my unaware datetime into UTC time, so for example 2020-06-09 00:00:00 was automatically converted into 2020-06-08 22:00:00 before the query.

But this way no further instruction was needed to have every date in UTC

**Comment by cngmid** [comment]
> I had the same issue on European Central Time, I followed by putting the TZ environment variable at UTC before importing the date module
> 
> ```
> import os
> os.environ['TZ'] = "UTC"
> ```
> 
> Putting this code as first instructions I was asking to the history method the queries with the appropriate dates. Before that I got an automatic conversion of my unaware datetime into UTC time, so for example 2020-06-09 00:00:00 was automatically converted into 2020-06-08 22:00:00 before the query.
> 
> But this way no further instruction was needed to have every date in UTC

Good point. This makes things much easier. However I do need to keep my environment time zone to Europe. But maybe one can wrap this in a `with ...:` paragraph.

**Comment by nono-london** [comment]
> import os
> os.environ['TZ'] = "UTC"

This doesn't seem to work on Windows. and i couldn't make use of the "tz" variable in the download function, probably not wondows compatible either

**Comment by remiromi** [comment]
> > import os
> > os.environ['TZ'] = "UTC"
> 
> This doesn't seem to work on Windows. and i couldn't make use of the "tz" variable in the download function, probably not wondows compatible either

I was on Windows, make sure to not import other modules who take the timezone as input before. This has to be the first import and the first instruction.

**Comment by akhtariali** [comment]
@ranaroussi Should I make a pull request and add `timezone` param to `history()` and manage timezone stuff internally using `pytz`?

**Comment by ymyke** [comment]
Did anybody in this thread have any further insights here? Is it enough to do:

```python
import os
os.environ['TZ'] = "UTC"
```

**Comment by ValueRaider** [comment]
Can you try using the main branch instead of PIP? I recently merged a PR that should fix this timezone stuff.
Instructions: https://github.com/yfinance-fork-team/yfinance-x/discussions/14#discussion-4392039

Once I know it's working and stable I'll ask Ran to push to PIP
