### ISSUE TITLE
Options stopped working

### ISSUE THREAD

**Issue by bruerFSol** [ranaroussi/yfinance#1840]
### Describe bug

The Ticker module has stopped working.

tk = yf.Ticker("TSLA")
exps = tk.options
print(exps)

This returns an empty bracket ()
This code worked just 2 days ago.

I have tried to upgrade to version 0.2.4, but that didn't help. I'm running python 3.10.8 on macbook pro.

### Simple code that reproduces your problem

import yfinance as yf

tk = yf.Ticker("TSLA")
exps = tk.options
print(exps)

### Debug log

urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): query2.finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://query2.finance.yahoo.com:443 "GET /v8/finance/chart/AN?period1=-2208994789&period2=1706220332&interval=1d&includePrePost=False&events=div%2Csplits%2CcapitalGains HTTP/1.1" 200 None
[*********************100%***********************]  1 of 1 completed
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): query2.finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://query2.finance.yahoo.com:443 "GET /v8/finance/chart/AN?period1=-2208994789&period2=1706220335&interval=1d&includePrePost=False&events=div%2Csplits%2CcapitalGains HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/analysis HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/balance-sheet HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/balance-sheet HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/cash-flow HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/cash-flow HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /calendar/earnings?symbol=AN&offset=0&size=12 HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/holders HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): query2.finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://query2.finance.yahoo.com:443 "GET /v1/finance/search?q=AN HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): query2.finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://query2.finance.yahoo.com:443 "GET /v7/finance/options/AN HTTP/1.1" 401 90
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/balance-sheet HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/balance-sheet HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/cash-flow HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/cash-flow HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): query2.finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://query2.finance.yahoo.com:443 "GET /v7/finance/options/AN HTTP/1.1" 401 90
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/balance-sheet HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/balance-sheet HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/cash-flow HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/cash-flow HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): query2.finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://query2.finance.yahoo.com:443 "GET /v7/finance/options/AN HTTP/1.1" 401 90
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/balance-sheet HTTP/1.1" 404 None
- AN: Failed to create balance-sheet financials table for reason: YFinanceDataException("Parsing FinancialTemplateStore failed, reason: KeyError('FinancialTemplateStore')")
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/cash-flow HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/cash-flow HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://finance.yahoo.com:443 "GET /quote/AN/financials HTTP/1.1" 200 None
urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): query2.finance.yahoo.com:443
urllib3.connectionpool - DEBUG - https://query2.finance.yahoo.com:443 "GET /v7/finance/options/AN HTTP/1.1" 401 90

### `yfinance` version

0.2.4

### Python version

3.10.8

### Operating system

MacOS Ventura 13.4.1

**Comment by Coding4Sec** [comment]
Same here, again!

Like the issue reported on Nov 8, 2023. After two days it was working again, then. Not this time.... 

My scripts return empty brackets as well.

**Comment by Shmuma** [comment]
It might be some issue on finance.yahoo.com. 

For example, forex quotes also stopped working two days ago. On yahoo website there is no daily rates (https://finance.yahoo.com/quote/EURUSD%3DX/history?p=EURUSD%3DX) and CSV export returns 403 error

**Comment by bruerFSol** [comment]
New update. I downloaded a VPN client and tried again from my Mac, with the US set for the VPN. That did NOT fix the problem, still getting an empty bracket.

**Comment by ValueRaider** [comment]
> I have tried to upgrade to version 0.2.4

🤔 Is that really the latest?

**Comment by aredare** [comment]
I've been experiencing the same issue yesterday. 
My script has been returning empty brackets as well.

**Comment by nxkryptor** [comment]
I have been having the same issue the last three days (from 24/1/24).

**Comment by bruerFSol** [comment]
Updating to python 3.12 solved the problem!

**Comment by Coding4Sec** [comment]
> Updating to python 3.12 solved the problem!

Interesting. I am now running my notebook in an venv on python 3.12.1 but issue remains....

**Comment by Coding4Sec** [comment]
> Updating to python 3.12 solved the problem!

Ok, sorry you are right. Switching to python 3.12 solves the issue.

I m using  python 3.12 in Venv but simply copied my old version notebooks into new venv. These nb's reference on old python... Setting up every nb from within venv with python 3.12 solved the issue.

Thanks and regards, Rick

**Comment by zmcx16** [comment]
I tried using Python 3.12, and both ticker and ticker.options work fine. However, ticker.option_chain is not functioning properly...

**Comment by ValueRaider** [comment]
```
yfinance version

0.2.4
```

Solution is to update.
