### ISSUE TITLE
Have not implemented fetching 'earnings' from Yahoo API

### ISSUE THREAD

**Issue by HWilson65** [ranaroussi/yfinance#1843]
### Describe bug

Hello,
I am trying to get the earning data from a single company ticker, but this does not seem to be implemented?

I have seen some code examples making use of the function, so I presume it was removed at some point after a Yahoo API change or something similar. 

I could not find another issue regarding this. Does any know when this would be implemented, or if there is a possible workaround or alternative to it?

### Simple code that reproduces your problem

import yfinance as yf

ticker = yf.Ticker("MSFT")

ticker.get_earnings(freq="quarterly")

### Debug log

Have not implemented fetching 'earnings' from Yahoo API
Stack trace:
 >  File "...\FiancialNN.py", line 7, in <module> (Current frame)
 >    ticker.get_earnings(freq="quarterly")
 >yfinance.exceptions.YFNotImplementedError: Have not implemented fetching 'earnings' from Yahoo API
Loaded 'yfinance.scrapers.fundamentals'
Loaded 'yfinance.base'
Loaded '__main__'
Loaded 'runpy'

### `yfinance` version

0.2.36

### Python version

3.11.7

**Comment by ValueRaider** [comment]
Duplicate #1737
