### ISSUE TITLE
Options date returning blank ()

### ISSUE THREAD

**Issue by rhnagpal** [ranaroussi/yfinance#1845]
### Describe bug

Hi - I'm a big fan of yfinance and have built some personal tools around it. Unfortunately, starting this week I see the the options command (eg: msft.options and msft.options_chain('yyyy-mm-dd') returns blank (no value or null). Any help would be a big deal for me here. Thanks in advance!

### Simple code that reproduces your problem

msft.options

opt = msft.option_chain("2024-02-02")
opt.calls

### Debug log

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 1
----> 1 opt = msft.option_chain("2024-02-02")
      2 opt.calls

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\ticker.py:86, in Ticker.option_chain(self, date, proxy, tz)
     84     self._download_options()
     85 if date not in self._expirations:
---> 86     raise ValueError(
     87         "Expiration `%s` cannot be found. "
     88         "Available expiration are: [%s]" % (
     89             date, ', '.join(self._expirations)))
     90 date = self._expirations[date]
     91 options = self._download_options(date, proxy=proxy)

ValueError: Expiration `2024-02-02` cannot be found. Available expiration are: []

### Bad data proof

It's just a blank or null return

### `yfinance` version

latest

### Python version

3.1

### Operating system

Windows

**Comment by ValueRaider** [comment]
What version? Also that's not the debug log.

**Comment by rhnagpal** [comment]
yfinance==0.2.18

**Comment by rhnagpal** [comment]
Is this the right debug: 

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query2.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:[https://query2.finance.yahoo.com:443](https://query2.finance.yahoo.com/) "GET /v7/finance/options/MSFT HTTP/1.1" 401 90

**Comment by ValueRaider** [comment]
Not latest version.
