### ISSUE TITLE
No timezone found, symbol may be delisted

### ISSUE THREAD

**Issue by byteatwork** [ranaroussi/yfinance#1848]
### Describe bug

history function fails to return the price data even they are available from the yahoo website for some of the tickers (not all of them)

### Simple code that reproduces your problem

See debug log

### Debug log

Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import yfinance as yf
E:\venv\py\lib\site-packages\yfinance\base.py:48: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  _empty_series = pd.Series()
>>> stock = yf.Ticker('AGIL').history(period='max',interval='1d')
AGIL: No timezone found, symbol may be delisted
>>>

### Bad data proof

![image_2024-02-03_135831372](https://github.com/ranaroussi/yfinance/assets/8535500/df1ab3ee-cf3d-4329-b40c-6a1920f2ff3f)

### `yfinance` version

0.2.36

### Python version

3.9.2

### Operating system

Windows 10

**Comment by ghyzx** [comment]
hi @byteatwork , may i know have you solved this issue?
