### ISSUE TITLE
yf.Tickets is broken

### ISSUE THREAD

**Issue by WolVesz** [ranaroussi/yfinance#185]
When testing out your code sample, it seems downloading multiple tickers at the same time via the Tickers function does not let you select the individual tickers. In the below case (which is akin to the version on pip/front page, you would need, test.tickers.msft.info.

`Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import yfinance as yf
>>>
>>> test = yf.Tickers('msft aapl goog')
>>> # ^ returns a named tuple of Ticker objects
>>> test.msft.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Tickers' object has no attribute 'msft'
>>>`

**Comment by particledecay** [comment]
I think the documentation is just outdated. The ticker should be available at `test.tickers.MSFT`.
