### ISSUE TITLE
Pre-Market data

### ISSUE THREAD

**Issue by simonislee** [ranaroussi/yfinance#1851]
Hi,

is there any way to get pre-market data in Ticker.info?

i have seen it in the old version. (#390)

**Comment by cultivater** [comment]
> Hi,
> 
> is there any way to get pre-market data in Ticker.info?
> 
> i have seen it in the old version. (#390)

Hi,
I have the same question, any progress?

**Comment by ValueRaider** [comment]
Duplicate #1393
