### ISSUE TITLE
No options data. again !

### ISSUE THREAD

**Issue by mmx5** [ranaroussi/yfinance#1861]
### Describe bug

can't recive options data of the stock.  it returns empty list.

### Simple code that reproduces your problem

import yfinance as yf
import sys
yf.enable_debug_mode()

print('run')
print(sys.version)

s_ticker = '^XSP'
ticker = yf.Ticker(s_ticker)
# data = ticker.get_fast_info()
# data = ticker.info
data = ticker.options
print('************ OPTIONS DATES ^XSP ***********')
print(data)
print('************ END OPTIONS DATES ^XSP ***********')
print(' ')

### Debug log

run
3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
************ OPTIONS DATES ^XSP ***********
()
************ END OPTIONS DATES ^XSP ***********

### `yfinance` version

0.2.25

### Python version

3.10.0

### Operating system

win 10 22H2

**Comment by mmx5** [comment]
After 2 days it strangely works back just after couple of mins i opened this issue. so i'm closing the issue.

**Comment by ValueRaider** [comment]
Why did you skip the first instruction? I'm genuinely asking, this is the real problem.

# Are you up-to-date?

**Comment by mmx5** [comment]
### **Yes, i am.**

**Comment by ValueRaider** [comment]
0.2.25 is not latest
