### ISSUE TITLE
how to download CVOL-USD data

### ISSUE THREAD

**Issue by aixuedegege** [ranaroussi/yfinance#1902]
Can I download CVOL data from this link? [https://finance.yahoo.com/quote/CVOL-USD/](https://finance.yahoo.com/quote/CVOL-USD/%EF%BC%8Cusing) 
I hava tried this code:
```python
df = yf.download('CVOL-USD', start=start, end=end, progress=False, interval = f'1d')
```
but i got Exception('%ticker%: No price data found, symbol may be delisted ?

**Comment by ValueRaider** [comment]
Your code doesn't work:
> NameError: name 'start' is not defined

**Comment by JennyCon** [comment]
It does look like the code is being blocked.  You can get a Yahoo finance API and run that   
import requests

url = "https://yahoo-finance15.p.rapidapi.com/api/v1/markets/options"

querystring = {"ticker":"CVX"}

headers = {
	"X-RapidAPI-Key": "afe626d890msh86f6ff2bf3517c0p10b6e8jsn3f04f4fa18a6",
	"X-RapidAPI-Host": "yahoo-finance15.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

**Comment by aixuedegege** [comment]
> Your code doesn't work:
> 
> > NameError: name 'start' is not defined

sorry, i forgot it, you can define it by:
```python
start='2023-12-11', end='2023-12-12'
```

**Comment by aixuedegege** [comment]
> It does look like the code is being blocked. You can get a Yahoo finance API and run that import requests
> 
> url = "https://yahoo-finance15.p.rapidapi.com/api/v1/markets/options"
> 
> querystring = {"ticker":"CVX"}
> 
> headers = { "X-RapidAPI-Key": "afe626d890msh86f6ff2bf3517c0p10b6e8jsn3f04f4fa18a6", "X-RapidAPI-Host": "yahoo-finance15.p.rapidapi.com" }
> 
> response = requests.get(url, headers=headers, params=querystring)
> 
> print(response.json())

thank you ! but where should i get the information about "CVX"?

**Comment by JennyCon** [comment]
The information about the stock is returned in the json file, and you have to extract it...  You can log onto rapidapi and get your own api for free.
https://rapidapi.com/sparior/api/yahoo-finance15/pricing

**Comment by aixuedegege** [comment]
ok thks a lot

**Comment by paulmcq** [comment]
@JennyCon You should remove or **mask** the API key when you post that.

**Comment by ValueRaider** [comment]
> @JennyCon You should remove or **mask** the API key when you post that.

I've removed it.

**Comment by JennyCon** [comment]
Thanks!!!


Dr. Jennifer I Considine

221A Casale Place

Canmore, AB

 Canada

403 807 6894

[University of Dundee shield logo]<http://uod.ac.uk/sig-home>

Jennifer Considine
Senior Research Fellow
School of Social Sciences, University of Dundee
***@***.*** | +44(0)1382 384300<mailto:+44(0)1382%20384300>

[University of Dundee Facebook]<http://uod.ac.uk/sig-fb> [University of Dundee Twitter] <http://uod.ac.uk/sig-tw>  [University of Dundee LinkedIn] <http://uod.ac.uk/sig-li>  [University of Dundee YouTube] <http://uod.ac.uk/sig-yt>  [University of Dundee Instagram] <http://uod.ac.uk/sig-ig>  [University of Dundee Snapchat] <http://uod.ac.uk/sig-sc>
We're Scottish University of the Year again!<http://uod.ac.uk/sig-strapline>
The Times / Sunday Times Good University Guide 2016 and 2017

________________________________
