### ISSUE TITLE
[Bug] 404 response in get_major_holders()

### ISSUE THREAD

**Issue by sshcli** [ranaroussi/yfinance#1907]
### Describe bug

 `get_major_holders()` is generating the following 404 error after recent changes made in Yahoo Finance website:

```
404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/?modules=institutionOwnership%2CfundOwnership%2Cm
ajorDirectHolders%2CmajorHoldersBreakdown%2CinsiderTransactions%2CinsiderHolders%2CnetSharePurchaseActivity&corsDomain=finance.yahoo.com&symbol=
ZTS&formatted=false&crumb=zlfwefYLrg6
```

### Simple code that reproduces your problem

`get_major_holders()`

### Debug log

I can't do this right now, I'm not in my office

### `yfinance` version

 0.2.37

### Python version

3.9

### Operating system

Centos 7.9

**Comment by ValueRaider** [comment]
Dup #1904

**Comment by sshcli** [comment]
@ValueRaider Sorry, didn't notice due to hurry.
I'm closing this one.
Thanks.
