### ISSUE TITLE
Empty Data Frame/ Missing library?

### ISSUE THREAD

**Issue by TimBstn** [ranaroussi/yfinance#193]
Hey together, I got an issue calling this stuff:

`import yfinance as yf

ticker = yf.Ticker('MSFT')

print(ticker.financials)`

I just get an empty Data-Frame. Two hours ago it worked, but then I uninstalled a couple of libraries and since then it stopped working. The .info an .history are still working fine, its just the .financials and .bilancesheet etc.
I did not uninstall numpy, pandas and the other libraries given in the explanation of Ran.
Has anyone of you an idea what is the problem?

Thanks a lot,
Tim

**Comment by jramiromolina** [comment]
Somebody posted a potential solution,  I didn't tested yet.
[https://github.com/ranaroussi/yfinance/issues/181#issuecomment-581093593](url)

**Comment by TimBstn** [comment]
I don't quite know what to do there?

**Comment by TimBstn** [comment]
For all with the same problem: Posted a solution here #191
