### ISSUE TITLE
Error: Failed to parse holders json data.

### ISSUE THREAD

**Issue by bserg1966** [ranaroussi/yfinance#1940]
### Describe bug

Code generate exception for 15-17% fom about 5500 tickers - Error: Failed to parse holders json data.
[major_holders not found_0-1.txt](https://github.com/ranaroussi/yfinance/files/15368718/major_holders.not.found_0-1.txt)
[major_holders not found_1-2.txt](https://github.com/ranaroussi/yfinance/files/15368719/major_holders.not.found_1-2.txt)
[major_holders not found_2-3.txt](https://github.com/ranaroussi/yfinance/files/15368720/major_holders.not.found_2-3.txt)
[major_holders not found_3-4.txt](https://github.com/ranaroussi/yfinance/files/15368721/major_holders.not.found_3-4.txt)
[major_holders not found_4-5.txt](https://github.com/ranaroussi/yfinance/files/15368723/major_holders.not.found_4-5.txt)
[major_holders not found_5-6.txt](https://github.com/ranaroussi/yfinance/files/15368724/major_holders.not.found_5-6.txt)
In files wrong tickers.Digits in files names mean number of thousands (from 5500 extracted tickers).

### Simple code that reproduces your problem

stock = yf.Ticker(ticker)
NewDf = stock.major_holders

### Debug log

 Error: Failed to parse holders json data.

### Bad data proof

If this problem need to connect with those who create json files. 
Give me please their contacts or write to them yourself.
Thanks.

### `yfinance` version

0.2.38

### Python version

3.12

### Operating system

Win11

**Comment by mRcSchwering** [comment]
Same with version `0.2.40`:

```
Python 3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yfinance
>>> ticker = yfinance.Ticker("1COV.DE").major_holders
Traceback (most recent call last):
  File "/home/marc/anaconda3/envs/findata_data/lib/python3.11/site-packages/yfinance/scrapers/holders.py", line 103, in _fetch_and_parse
    self._parse_insider_transactions(data["insiderTransactions"])
                                     ~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'insiderTransactions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marc/anaconda3/envs/findata_data/lib/python3.11/site-packages/yfinance/ticker.py", line 109, in major_holders
    return self.get_major_holders()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marc/anaconda3/envs/findata_data/lib/python3.11/site-packages/yfinance/base.py", line 176, in get_major_holders
    data = self._holders.major
           ^^^^^^^^^^^^^^^^^^^
  File "/home/marc/anaconda3/envs/findata_data/lib/python3.11/site-packages/yfinance/scrapers/holders.py", line 35, in major
    self._fetch_and_parse()
  File "/home/marc/anaconda3/envs/findata_data/lib/python3.11/site-packages/yfinance/scrapers/holders.py", line 107, in _fetch_and_parse
    raise YFDataException("Failed to parse holders json data.")
yfinance.exceptions.YFDataException: Failed to parse holders json data.
```
