### ISSUE TITLE
Period '2d' is invalid error when fetching 2-day data with yfinance

### ISSUE THREAD

**Issue by bruce1095** [ranaroussi/yfinance#1950]
### Describe bug

I am encountering an issue with the yfinance library when trying to fetch 2-day historical data with 1-minute intervals for the ticker symbol ES=F. The code returns an error stating that the period ‘2d’ is invalid.

### Simple code that reproduces your problem

import yfinance as yf

symbol = input("Enter the symbol: ")

equity = yf.Ticker(symbol)

try:
    df = equity.history(period="2d", interval="1m")

    if df.empty:
        raise ValueError("No data available for the specified period and interval.")

except Exception as e:
    print(f"An error occurred: {e}")
    print("Attempting to fetch alternative data...")

### Debug log

ERROR:yfinance:ES=F: Period '2d' is invalid, must be one of ['1d', '5d', '1mo', '3mo', '6mo', '1y', '2y', '5y', '10y', 'ytd', 'max']
An error occurred: No data available for the specified period and interval.
Attempting to fetch alternative data...

### `yfinance` version

Latest

**Comment by ItzXyers** [comment]
Well, that error sums it upp pretty good: "Period '2d' is **invalid**, *must* be one of ['1d', '5d', '1mo', '3mo', '6mo', '1y', '2y', '5y', '10y', 'ytd', 'max']"

A possible fix could be to get the data for five days and then truncate the data down to the last two. The following result appears to work. It should be noted that your code worked for me when I used 'symbol = "aapl"'...

```python
import pandas as pd
import yfinance as yf

symbol = input("Enter the symbol: ")

equity = yf.Ticker(symbol)

try:
    df = equity.history(period="5d", interval="1m")

    if df.empty:
        raise ValueError("No data available for the specified period and interval.")

except Exception as e:
    print(f"An error occurred: {e}")
    print("Attempting to fetch alternative data...")

# Current date (timezone aware)
now = pd.Timestamp.now(tz=df.index.tz)

# Calculate the date for yesterday
two_days_ago = now - pd.Timedelta(days=1)

# Truncate the DataFrame to include only data from the last two days
# Only include results that are from today, or yesterday
df_last_two_days = df[df.index >= two_days_ago]

df_last_two_days

```
