### ISSUE TITLE
"Loss Adjustment Expense" not pulled as part of Income Statement

### ISSUE THREAD

**Issue by rhwvu** [ranaroussi/yfinance#1961]
With some insurance companies, their biggest expenses are listed as "Loss Adjustment Expense" which is not pulled at all by `income_stmt`. Using ELV as an example, you can see above that it's not pulled at all, and neither is "Net Policyholder Benefits And Claims" which is a subexpense of it on Yahoo Finance and would work the same.

I'm trying to pull the expenses from Yahoo Finance, but pulling the Total Expenses is not helpful for me because ELV includes Depreciation & Amortization under that and I specifically don't want that included.

Here's a link to the Yahoo Finance page:
https://finance.yahoo.com/quote/ELV/financials/

```python import yfinance as yf
ticker_object = yf.Ticker('ELV')
inc = ticker_object.income_stmt
print(bal)
input("...")

**Comment by ValueRaider** [comment]
Is the data you want anywhere on website? yfinance can only fetch what's there.

**Comment by rhwvu** [comment]
Yes. At the link I put in the first post, under "Total Expenses", here's the exact thing I'd want to pull:
![image](https://github.com/ranaroussi/yfinance/assets/123055089/58f3ed68-3bbb-4728-81fc-d5ba60769ba4)

**Comment by ValueRaider** [comment]
Solution will involve https://github.com/ranaroussi/yfinance/blob/main/yfinance/const.py

**Comment by rhwvu** [comment]
The merged issue fixes this. I manually edited my pip package to add this fix since it's not in the release yet. Thanks.
