### ISSUE TITLE
fullTimeEmployees function not found 

### ISSUE THREAD

**Issue by tilakpatel22** [ranaroussi/yfinance#1973]
### Describe bug

i can't find the function from which i used to get data before can someone please assist me from where can i solve this info.get('fullTimeEmployees')

### Simple code that reproduces your problem

import yfinance as yf
data=yf.Ticker('RITES.NS')info.get('fullTimeEmployees')
print(data)

### Debug log

NA

### `yfinance` version

yfinance 0.2.40

**Comment by ericpien** [comment]
I suspect the data just isn't available from the source: https://finance.yahoo.com/quote/IRCTC.NS/profile/

I can confirm I can retrieve the data if available: https://finance.yahoo.com/quote/TCS.NS/profile/
`tcs = yf.Ticker("TCS.NS")`
`print(tcs.info.get("fullTimeEmployees")`
-> `601546`
