### ISSUE TITLE
Currency data for statements

### ISSUE THREAD

**Issue by mking007** [ranaroussi/yfinance#1976]
### Describe bug

Currency data for financial statements

For some stocks, like BP.L, the share price data is GBp whereas the financial statements are in USD.

The currency of GBp is available in fast_info but the currency (USD) for the financial statements does not appear to be available. 

Am I missing something?

### Simple code that reproduces your problem

import yfinance as yf
ticker = yf.Ticker("BP.L")
ticker.info['currency']

### Debug log

not a bug

### Bad data proof

ticker.info['currency']
'GBp'

### `yfinance` version

0.2.40

**Comment by ValueRaider** [comment]
I had a quick poke around:
> info['financialCurrency']

No idea how reliable that is.

**Comment by ValueRaider** [comment]
It's reliable.

**Comment by mking007** [comment]
This works. Closed issue. Thanks :)
