### ISSUE TITLE
prepost not working

### ISSUE THREAD

**Issue by ItayFedler** [ranaroussi/yfinance#200]
```
import yfinance as yf
stock_name='AMZN'
data = yf.download(stock_name,start='2012-01-01',end='2020-2-16', prepost=True)
print(data.shape)
```
result:
(2043, 6)
```
import yfinance as yf
stock_name='AMZN'
data = yf.download(stock_name,start='2012-01-01',end='2020-2-16', prepost=False)
print(data.shape)
```
result:
(2043, 6)

**Comment by mobone** [comment]
Another example.

`>>> yfinance.download(['AAPL'],prepost=False).tail(1)
[*********************100%***********************]  1 of 1 completed
                  Open    High         Low  Close  Adj Close    Volume
Date
2020-02-18  315.359985  319.75  314.609985  319.0      319.0  38132800
>>> yfinance.download(['AAPL'],prepost=True).tail(1)
[*********************100%***********************]  1 of 1 completed
                  Open    High         Low  Close  Adj Close    Volume
Date
2020-02-18  315.359985  319.75  314.609985  319.0      319.0  38132800`

**Comment by martimfj** [comment]
I looked at the code, and this option is not even implemented. I"m interested in doing that, but I need to know exactly what the pre-post option should add to the output.

**Comment by mobone** [comment]
Yeah I checked it out too. The data is there it just needs to be broken up into the premarket and post market hours groups. I can probably take a stab at it if I’m free and bored someday.
