### ISSUE TITLE
Missing data for every month's third week first monday

### ISSUE THREAD

**Issue by beyhangl** [ranaroussi/yfinance#202]
There's a minor bug in stock_p.history(period="max"). when you call all stock price data of any stock's every month's third week's first monday is missing

For example 17 February 2020 , 20 January 2020,etc. are missing.

**Comment by MichaelYuMH** [comment]
Hi @beyhangl, I think it should be a coincidence that both 2020/02/17 and 2020/01/20 are holidays (President's Day and Martin Luther King Jr. Day) where the stock market is closed. I checked the third week's Monday in December (2019/12/16) and the data is presented.

**Comment by rweipi** [comment]
I just noticed this too. @MichaelYuMH  is correct the empty days are market holidays. This should be fixed so that market holidays are treated like weekends.
