### ISSUE TITLE
Dividend Events Provide Ex-Dividend Date Instead of Payment Date

### ISSUE THREAD

**Issue by Ludevsoftware** [ranaroussi/yfinance#2056]
## Description
When querying for dividend events using the `"events": "div"` parameter, the returned data provides the Ex-dividend date instead of the payment date. This can be misleading as users may expect to receive the actual payment date for the dividends. 

Is there any way to obtain the dividend history along with the payment date?

## Example
Here is an example of the response for the Apple ticker where the last payment date was 2024-08-14, but the date in payload is 2024-08-12:

```json
"events": {
  "dividends": {
    "1699453800": {
      "amount": 0.24,
      "date": 1699626600
    },
    "1707229800": {
      "amount": 0.24,
      "date": 1707489000
    },
    "1715002200": {
      "amount": 0.25,
      "date": 1715347800
    },
    "1723210200": {
      "amount": 0.25,
      "date": 1723469400
    }
  }
}

**Comment by ValueRaider** [comment]
Read #568
