### ISSUE TITLE
Can't pull prices anymore

### ISSUE THREAD

**Issue by farbodbahari** [ranaroussi/yfinance#2138]
### Describe bug

Can't pull prices anymore
![Screenshot 2024-11-19 2 11 32 PM](https://github.com/user-attachments/assets/d7018bcd-1bfa-488f-9653-acd48a6b36b9)

### Simple code that reproduces your problem

import yfinance as yf
print(yf.__version__)
import yfinance as yf

msft = yf.Ticker("MSFT")

### The 2 method below don't work anymore
# get all stock info

msft.info
msft.history(period="1mo")

### Debug log

DEBUG    get_raw_json(): https://query2.finance.yahoo.com/v10/finance/quoteSummary/MSFT
DEBUG    Entering get()
DEBUG     Entering _make_request()
DEBUG      url=https://query2.finance.yahoo.com/v10/finance/quoteSummary/MSFT
DEBUG      params={'modules': 'financialData,quoteType,defaultKeyStatistics,assetProfile,summaryDetail', 'corsDomain': 'finance.yahoo.com', 'formatted': 'false', 'symbol': 'MSFT'}
DEBUG      Entering _get_cookie_and_crumb()
DEBUG       cookie_mode = 'basic'
DEBUG       Entering _get_cookie_and_crumb_basic()
DEBUG        reusing cookie
DEBUG        reusing crumb
DEBUG       Exiting _get_cookie_and_crumb_basic()
DEBUG      Exiting _get_cookie_and_crumb()
DEBUG      response code=429
DEBUG      toggling cookie strategy basic -> csrf
DEBUG      Entering _get_cookie_and_crumb()
DEBUG       cookie_mode = 'csrf'
DEBUG       Entering _get_crumb_csrf()
0.2.49
DEBUG        Failed to find "csrfToken" in response
DEBUG       Exiting _get_crumb_csrf()
DEBUG       toggling cookie strategy csrf -> basic
DEBUG       Entering _get_cookie_and_crumb_basic()
DEBUG        loaded persistent cookie
DEBUG        reusing cookie
DEBUG        crumb = 'Edge: Too Many Requests'
DEBUG       Exiting _get_cookie_and_crumb_basic()
DEBUG      Exiting _get_cookie_and_crumb()
DEBUG      response code=429
DEBUG     Exiting _make_request()
DEBUG    Exiting get()
ERROR    429 Client Error: Too Many Requests for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/MSFT?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=MSFT&crumb=Edge%3A+Too+Many+Requests

### Bad data proof

![Screenshot 2024-11-19 2 11 32 PM](https://github.com/user-attachments/assets/20e9e1db-1fb1-4894-acc0-43d9203b59e0)

### `yfinance` version

0.2.49

### Python version

3

### Operating system

Linux

**Comment by quantokenizer** [comment]
I have the same issue on Windows Server 2016 but get a different error message:

```
{
	"name": "AttributeError",
	"message": "'str' object has no attribute 'get'",
	"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[33], line 6
      3 msft = yf.Ticker(\"MSFT\")
      5 # get all stock info
----> 6 msft.info
      8 # get historical market data
      9 hist = msft.history(period=\"1mo\")

File ~/miniforge3/lib/python3.12/site-packages/yfinance/ticker.py:159, in Ticker.info(self)
    157 @property
    158 def info(self) -> dict:
--> 159     return self.get_info()

File ~/miniforge3/lib/python3.12/site-packages/yfinance/base.py:229, in TickerBase.get_info(self, proxy)
    227 def get_info(self, proxy=None) -> dict:
    228     self._quote.proxy = proxy or self.proxy
--> 229     data = self._quote.info
    230     return data

File ~/miniforge3/lib/python3.12/site-packages/yfinance/scrapers/quote.py:508, in Quote.info(self)
    505 @property
    506 def info(self) -> dict:
    507     if self._info is None:
--> 508         self._fetch_info(self.proxy)
    509         self._fetch_complementary(self.proxy)
    511     return self._info

File ~/miniforge3/lib/python3.12/site-packages/yfinance/scrapers/quote.py:598, in Quote._fetch_info(self, proxy)
    596 self._already_fetched = True
    597 modules = ['financialData', 'quoteType', 'defaultKeyStatistics', 'assetProfile', 'summaryDetail']
--> 598 result = self._fetch(proxy, modules=modules)
    599 if result is None:
    600     self._info = {}

File ~/miniforge3/lib/python3.12/site-packages/yfinance/scrapers/quote.py:587, in Quote._fetch(self, proxy, modules)
    585 params_dict = {\"modules\": modules, \"corsDomain\": \"finance.yahoo.com\", \"formatted\": \"false\", \"symbol\": self._symbol}
    586 try:
--> 587     result = self._data.get_raw_json(_QUOTE_SUMMARY_URL_ + f\"/{self._symbol}\", user_agent_headers=self._data.user_agent_headers, params=params_dict, proxy=proxy)
    588 except requests.exceptions.HTTPError as e:
    589     utils.get_yf_logger().error(str(e))

File ~/miniforge3/lib/python3.12/site-packages/yfinance/data.py:410, in YfData.get_raw_json(self, url, user_agent_headers, params, proxy, timeout)
    408 def get_raw_json(self, url, user_agent_headers=None, params=None, proxy=None, timeout=30):
    409     utils.get_yf_logger().debug(f'get_raw_json(): {url}')
--> 410     response = self.get(url, user_agent_headers=user_agent_headers, params=params, proxy=proxy, timeout=timeout)
    411     response.raise_for_status()
    412     return response.json()

File ~/miniforge3/lib/python3.12/site-packages/yfinance/utils.py:104, in log_indent_decorator.<locals>.wrapper(*args, **kwargs)
    101 logger.debug(f'Entering {func.__name__}()')
    103 with IndentationContext():
--> 104     result = func(*args, **kwargs)
    106 logger.debug(f'Exiting {func.__name__}()')
    107 return result

File ~/miniforge3/lib/python3.12/site-packages/yfinance/data.py:333, in YfData.get(self, url, user_agent_headers, params, proxy, timeout)
    331 @utils.log_indent_decorator
    332 def get(self, url, user_agent_headers=None, params=None, proxy=None, timeout=30):
--> 333     return self._make_request(url, request_method = self._session.get, user_agent_headers=user_agent_headers, params=params, proxy=proxy, timeout=timeout)

AttributeError: 'str' object has no attribute 'get'"
}
```
I also tried pulling some data using a Rapid API wrapper for Yahoo Finance, and got a similar error

**Comment by ValueRaider** [comment]
> ERROR 429 Client Error: Too Many Requests

duplicate of #2125
