### ISSUE TITLE
FEAT - More API's and list of APIS

### ISSUE THREAD

**Issue by R5dan** [ranaroussi/yfinance#2157]
Add some more API access, not just Ticker API's

Some ones I thought of:

- [Search API](https://query2.finance.yahoo.com/v1/finance/search?q={query}&lang={lang}&region={region}&quotesCount={count}&newsCount={newsCount}&listsCount={listsCount}&enableFuzzyQuery=false&quotesQueryId=tss_match_phrase_query&multiQuoteQueryId=multi_quote_single_token_query&newsQueryId=news_cie_vespa&enableCb=true&enableNavLinks=true&enableEnhancedTrivialQuery=true&enableResearchReports=true&enableCulturalAssets=true&enableLogoUrl=true&recommendCount=5")
- [Global news](https://query2.finance.yahoo.com/v1/finance/search?q=xyz) based of the error with #1956 however could also use the search API
- [Market Summary](https://query1.finance.yahoo.com/v6/finance/quote/marketSummary?fields=shortName%2CregularMarketPrice%2CregularMarketChange%2CregularMarketChangePercent&formatted=true&lang=en-US&market=EUROPE&region=US)

I am happy to help with these if needed.
These could simply be accessed directly from yfinance 
```python
from yfinance import global_news, search
```

Any other API ideas as well, these were the only ones I could think of

**Comment by ValueRaider** [comment]
These might already be implemented, check `dev` branch and https://ranaroussi.github.io/yfinance/index.html

**Comment by ValueRaider** [comment]
The pull request was created same time #2160, and there was an older unfinished pull request.

Submitting a pull request is best, gives us something to review.

**Comment by R5dan** [comment]
Ok thanks, I wasn't sure as different libraries have different policies.

This issue was created earlier than the merged pull request. I was just mentioning it.

Is there currently capacity in the library for  global news and market summary? I think there is a market status one as well.

**Comment by ValueRaider** [comment]
Market summary & status, sure. 

If global news is already possible with `yf.Search` then just document it.
