### ISSUE TITLE
Change `Screener.set_predefined_body` and `Screener.set_body` to respond with the class

### ISSUE THREAD

**Issue by R5dan** [ranaroussi/yfinance#2158]
I want to change `Screener.set_predefined_body` and `Screener.set_body` to respond with the class.

This would reduce

```python
s = yf.Screener()
s.set_predefined_body("day_gainers")
r=s.response
```
to
```python
r = yf.Screener().set_predefined_body("day_gainers").response
```
or to be able to set it on initialisation
```python
r = yf.Screener(body="day_gainers").response
```

which I think is cleaner and more concise. I would also suggest editing the docs of `predefined_bodies` as they come above `set_predefined_body` to include how to set the Screener to them

**Comment by ValueRaider** [comment]
@ericpien
