### ISSUE TITLE
yfinance earnings date error

### ISSUE THREAD

**Issue by rhnagpal** [ranaroussi/yfinance#2166]
### Describe bug

Earnings was working 3 weeks ago. Have been trying to debug - but it looks like somethings changed.

### Simple code that reproduces your problem

Here's a simple test script:
import yfinance as yf
dat = yf.Ticker("MSFT")
dat.earnings_dates

### Debug log

DEBUG    Entering get_earnings_dates()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py:3802, in Index.get_loc(self, key, method, tolerance)
   3801 try:
-> 3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\_libs\index.pyx:138, in pandas._libs.index.IndexEngine.get_loc()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\_libs\index.pyx:165, in pandas._libs.index.IndexEngine.get_loc()

File pandas\_libs\hashtable_class_helper.pxi:5745, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas\_libs\hashtable_class_helper.pxi:5753, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Earnings Date'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[27], line 4
      2 yf.enable_debug_mode()
      3 dat = yf.Ticker("MSFT")
----> 4 dat.earnings_dates

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\ticker.py:295, in Ticker.earnings_dates(self)
    293 @property
    294 def earnings_dates(self) -> _pd.DataFrame:
--> 295     return self.get_earnings_dates()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\utils.py:104, in log_indent_decorator.<locals>.wrapper(*args, **kwargs)
    101 logger.debug(f'Entering {func.__name__}()')
    103 with IndentationContext():
--> 104     result = func(*args, **kwargs)
    106 logger.debug(f'Exiting {func.__name__}()')
    107 return result

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\yfinance\base.py:629, in TickerBase.get_earnings_dates(self, limit, proxy)
    627 cn = "Earnings Date"
    628 # - remove AM/PM and timezone from date string
--> 629 tzinfo = dates[cn].str.extract('([AP]M[a-zA-Z]*)$')
    630 dates[cn] = dates[cn].replace(' [AP]M[a-zA-Z]*$', '', regex=True)
    631 # - split AM/PM from timezone

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py:3807, in DataFrame.__getitem__(self, key)
   3805 if self.columns.nlevels > 1:
   3806     return self._getitem_multilevel(key)
-> 3807 indexer = self.columns.get_loc(key)
   3808 if is_integer(indexer):
   3809     indexer = [indexer]

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py:3804, in Index.get_loc(self, key, method, tolerance)
   3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:
-> 3804     raise KeyError(key) from err
   3805 except TypeError:
   3806     # If we have a listlike key, _check_indexing_error will raise
   3807     #  InvalidIndexError. Otherwise we fall through and re-raise
   3808     #  the TypeError.
   3809     self._check_indexing_error(key)

KeyError: 'Earnings Date'

### Bad data proof

Error = "Earnings Date'

### `yfinance` version

latest

### Python version

3.1

### Operating system

Windows

**Comment by rhnagpal** [comment]
Why is this closed? Wouldn't this be open till resolved?

**Comment by belligerentbeagle** [comment]
Agreed.... this is still a problem
