### ISSUE TITLE
Missing Split Data

### ISSUE THREAD

**Issue by The-Milad-A** [ranaroussi/yfinance#2174]
### Describe bug

Missing stock splits - I'm looking to separate out old data from new data using latest stock splits. SMCI's pull is missing their recent split a few months back.

### Simple code that reproduces your problem

import yfinance as yf

yf.enable_debug_mode()
stock_object = yf.Ticker('SMCI')
stock.splits

### Debug log

[Nothing, running code out of Jupyter Notebook]

### Bad data proof

Series([], Name: Stock Splits, dtype: float64)

### `yfinance` version

0.2.50

**Comment by The-Milad-A** [comment]
I'm pretty sure this is happening with other stocks as well. Not sure if this relates to other issues related to stock details/info not returning consistently

**Comment by dhruvan2006** [comment]
You are hitting the rate limit and getting `429` responses, this issue might help #2125
