### ISSUE TITLE
yf.download returns multi-index columns

### ISSUE THREAD

**Issue by coulanuk** [ranaroussi/yfinance#2193]
Upgraded to yfinance 2.51 this week
yf.Download for a single ticker now produces columns with an un-wanted multi-index with an altered column order (CHLOV)

**Example**
start_date = '2023-01-01'
end_date = datetime.now().strftime('%Y-%m-%d')
ticker = 'TSLA'
df = yf.download(tickers=[ticker], start=start_date, end=end_date)

df.columns
MultiIndex([( 'Close', 'TSLA'),
            (  'High', 'TSLA'),
            (   'Low', 'TSLA'),
            (  'Open', 'TSLA'),
            ('Volume', 'TSLA')],
           names=['Price', 'Ticker'])

**Workaround**
df.columns = df.columns.to_flat_index()
... and then rename and re-order columns to OHLCV

**Comment by coulanuk** [comment]
Better Workaround
df.columns = df.columns.get_level_values(0)

**Comment by coulanuk** [comment]
Am closing this issue as the API has a solution.
 df = yf.download(tickers=[ticker], start=start_date, end=end_date, multi_level_index=False)
Seems we have lost AdjClose ?

**Comment by dharmatech** [comment]
@coulanuk 

Thank you for pointing out the change and workaround! 👍

**Comment by Ramaseshanr** [comment]
Set multi_level_index=False in your download
df = yf.download(tickers=[ticker], start=start_date, end=end_date, multi_level_index=False)
