### ISSUE TITLE
Inquiry about using yfinance in a non-profit open-source project

### ISSUE THREAD

**Issue by akitxu** [ranaroussi/yfinance#2195]
Dear [Yahoo Finance Team],

I am developing an open-source Python project aimed at simulating and developing conservative investment strategies. The goal is to create an educational, non-profit tool that will be freely available to users through Google Colaboratory and Google Drive.

To obtain the necessary data for the simulations, the project utilizes the yfinance API. I would like to confirm if the use of this API for academic and research purposes, without any commercial benefit, is compliant with your terms of service.

I appreciate your response and any guidance you can provide.

Sincerely,

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add a disclaimer at the beginning of the file to clarify the project's purpose and usage terms.

You can review changes in this commit: https://github.com/mark-addams001881/ranaroussi-yfinance-2195/commit/97de6e6dae7b7a1ba9c86b32d6e66f49a29956db.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ValueRaider** [comment]
# WE ARE NOT AFFILIATED WITH YAHOO
