### ISSUE TITLE
YFInvalidPeriodError "%ticker%: Period 'max' is invalid

### ISSUE THREAD

**Issue by azwanzuharimi** [ranaroussi/yfinance#2196]
### Describe bug

Downloading indices data returning an invalid period as per screenshot sample
![image](https://github.com/user-attachments/assets/7f2c6b58-10db-45ec-b6dc-028f989c9096)
![image](https://github.com/user-attachments/assets/c6f65bcb-8e62-4431-b3b8-0d1b39031622)

### Simple code that reproduces your problem

import yfinance as yf
yf.download("FBM100.FGI")

### Debug log

DEBUG    Entering download()
DEBUG     Disabling multithreading because DEBUG logging enabled
DEBUG     Entering history()
DEBUG      Entering history()
DEBUG       FBM100.FGI: Yahoo GET parameters: {'period1': '1926-01-22 16:13:53+00:00', 'period2': '2024-12-28 16:13:53+00:00', 'interval': '1d', 'includePrePost': False, 'events': 'div,splits,capitalGains'}
DEBUG       Entering get()
DEBUG        Entering _make_request()
DEBUG         url=https://query2.finance.yahoo.com/v8/finance/chart/FBM100.FGI
DEBUG         params={'period1': -1386661567, 'period2': 1735402433, 'interval': '1d', 'includePrePost': False, 'events': 'div,splits,capitalGains'}
DEBUG         Entering _get_cookie_and_crumb()
DEBUG          cookie_mode = 'basic'
DEBUG          Entering _get_cookie_and_crumb_basic()
DEBUG           reusing cookie
DEBUG           reusing crumb
DEBUG          Exiting _get_cookie_and_crumb_basic()
DEBUG         Exiting _get_cookie_and_crumb()
DEBUG         response code=200
DEBUG        Exiting _make_request()
DEBUG       Exiting get()
ERROR     
          1 Failed download:
ERROR     ['FBM100.FGI']: YFInvalidPeriodError("%ticker%: Period 'max' is invalid, must be one of ['1d', '5d']")
DEBUG     ['FBM100.FGI']: Traceback (most recent call last):
            File "c:\Program Files\Python313\Lib\site-packages\yfinance\multi.py", line 272, in _download_one
              data = Ticker(ticker).history(
                      period=period, interval=interval,
              ...<4 lines>...
                      raise_errors=True
              )
            File "c:\Program Files\Python313\Lib\site-packages\yfinance\utils.py", line 103, in wrapper
              result = func(*args, **kwargs)
            File "c:\Program Files\Python313\Lib\site-packages\yfinance\base.py", line 81, in history
              return self._lazy_load_price_history().history(*args, **kwargs)
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
            File "c:\Program Files\Python313\Lib\site-packages\yfinance\utils.py", line 103, in wrapper
              result = func(*args, **kwargs)
            File "c:\Program Files\Python313\Lib\site-packages\yfinance\scrapers\history.py", line 243, in history
              raise _exception
          yfinance.exceptions.YFInvalidPeriodError: %ticker%: Period 'max' is invalid, must be one of ['1d', '5d']
          
DEBUG    Exiting download()


### Bad data proof

_No response_

### `yfinance` version

0.2.51

### Python version

3.13.1

### Operating system

Windows 10

**Comment by R5dan** [comment]
The request is being sent to [here](https://query2.finance.yahoo.com/v8/finance/chart/FBM100.FGI?period1=-1386660337&period2=1735403663&interval=1d&includePrePost=False&events=div%2Csplits%2CcapitalGains)

The error is that in the data:
```json
{
  "chart": {
    "result": [
      {
        "meta": {
          "currency": "MYR",
          "symbol": "FBM100.FGI",
          "exchangeName": "FGI",
          "fullExchangeName": "FTSE Index",
          "instrumentType": "INDEX",
          "firstTradeDate": null,
          "regularMarketTime": 1735289985,
          "hasPrePostMarketData": false,
          "gmtoffset": 0,
          "timezone": "GMT",
          "exchangeTimezoneName": "Europe/London",
          "regularMarketPrice": 12165.17,
          "fiftyTwoWeekHigh": 12186.98,
          "fiftyTwoWeekLow": 12080.04,
          "regularMarketDayHigh": 12186.98,
          "regularMarketDayLow": 12080.04,
          "regularMarketVolume": 0,
          "longName": "FTSE Bursa Malaysia Top 100 Ind",
          "shortName": "FTSE Bursa Malaysia Top 100 Ind",
          "chartPreviousClose": 12062.61,
          "priceHint": 2,
          "currentTradingPeriod": {
            "pre": {
              "timezone": "GMT",
              "end": 1735286400,
              "start": 1735283700,
              "gmtoffset": 0
            },
            "regular": {
              "timezone": "GMT",
              "end": 1735317000,
              "start": 1735286400,
              "gmtoffset": 0
            },
            "post": {
              "timezone": "GMT",
              "end": 1735319700,
              "start": 1735317000,
              "gmtoffset": 0
            }
          },
          "dataGranularity": "1d",
          "range": "",
>          "validRanges": [
>            "1d",
>            "5d"
>          ]
        },
        "timestamp": [
          1735289985
        ],
        "indicators": {
          "quote": [
            {
              "close": [
                12165.169921875
              ],
              "open": [
                12084.2998046875
              ],
              "volume": [
                0
              ],
              "low": [
                12080.0400390625
              ],
              "high": [
                12186.98046875
              ]
            }
          ],
          "adjclose": [
            {
              "adjclose": [
                12165.169921875
              ]
            }
          ]
        }
      }
    ],
    "error": null
  }
}
```
`validRanges` is only set to `1d` or `5d` not `max`. This causes YFinance to throw an error. There is also only one piece of data shown.

When I looked on Yahoo, they also had data going back only a day (even when set to `All`)
