### ISSUE TITLE
Adj Close missing from yf.download output DataFrame

### ISSUE THREAD

**Issue by hpdeandrade** [ranaroussi/yfinance#2197]
Hi.

Fetching some historical data today using `yf.download` I noticed the Adj Close column is missing for all tickers I try to download data for.

Up until last week I would get both Close and Adj Close. 

Wondering why.

Happy 2025 to all.

**Comment by BiggRanger** [comment]
This behaviour changed from 0.2.50 and 0.2.51, you need to add 'auto_adjust=False' to the parameters of yf.download.
`data = yfinance.download(ticker, start=dateStart, end=dateEnd, interval='1d', progress=False, auto_adjust=False)`
Once that is done you will get both 'close' and 'adj close' again.

**Comment by hpdeandrade** [comment]
Thanks! I overlooked this change. Issue closed.
