### ISSUE TITLE
Incorrect date format 

### ISSUE THREAD

**Issue by kentenzer** [ranaroussi/yfinance#221]
Hi, 

I am using yfinance version: 0.1.54. and I am getting incorrect date format at the DataFrame index, see fragment below:

```
yf.Ticker('CDE').history(period='2y', interval='1h')
            Open   High    Low  Close   Volume  Dividends  Stock Splits
Date                                                                    
2018-03-14  8.420  8.480  8.340  8.380   374596          0             0
2018-03-14  8.380  8.430  8.330  8.340   282819          0             0

df.index[0]
Timestamp('2018-03-14 00:00:00'

df.index[1]
Timestamp('2018-03-14 00:00:00'
```

Please note that I am using interval 1h, but I am not able to differentiate between the first and the second index. 

Thanks!

**Comment by hristo-mavrodiev** [comment]
You can try with temporary solution:
```interval ='60m'```
I agree with you there is an issue when using '1h' as a period(reproduced).
![image](https://user-images.githubusercontent.com/61916767/76708145-4b0b1d00-66fd-11ea-82dc-fe0e230b704a.png)
Thanks,
Hristo

**Comment by kentenzer** [comment]
This workaround works! Thanks.

**Comment by silvavn** [comment]
Thia is fixed in the current version.
