### ISSUE TITLE
price change with interval value

### ISSUE THREAD

**Issue by fraricci** [ranaroussi/yfinance#222]
I'm not expert in finance data, but I noticed this weird outcome:

- interval = 1d
`yf.download('VAPX.L',period='1mo',interval='1d').max()`
Open          2005.000000
High          2016.300049
Low           2002.500000
Close         2011.500000
Adj Close     2011.500000
Volume       43077.000000
dtype: float64

- interval = 1h
`yf.download('VAPX.L',period='1mo',interval='1h').max()`
Open            20.115999
High            20.163000
Low             20.115000
Close           20.115000
Adj Close       20.115000
Volume       60103.000000

I'm using max() just to get a limited output.
Why does price seems to be multiplied by a factor 100 when interval is 1d ?

Thanks in advance.

**Comment by mbzand** [comment]
It's a fault in the Yahoo finance data or there are some serious outliners. Look at the chart on a 3 month base:

**Comment by fraricci** [comment]
Oh I see. Thanks!
