### ISSUE TITLE
Rows with no data removed

### ISSUE THREAD

**Issue by JSher1** [ranaroussi/yfinance#226]
I would like to suggest adding a parameter to keep or remove rows with no data.

The reason is, when I compare stocks, some rows will not be there for the date. This causes issues as I then have to check if that day the market was open, which is a difficult task.

I require the blank rows and I just interpolate them as a best guess for the values on that day.

I like your module but I had to write my own(not as involved or as well done) as I need these blank rows

Thanks,
--James

**Comment by silvavn** [comment]
Rows with no data come as None. The removal can be easily done using `df.dropna()`.
