### ISSUE TITLE
Parameter for finalized data needed

### ISSUE THREAD

**Issue by krakysmurf** [ranaroussi/yfinance#228]
Awesome work. yfinance turned 500 lines of code into 20.
I was wondering if you could add a parameter for yfinance.download() that asks if the user only wants finalized data. Passing True will return NaN values for the markets currently opened for trading.

and.. This may be a great challenge, but would be even more awesome if i could download multiple tickers in UTC time.

**Comment by ValueRaider** [comment]
Does anyone else want this feature? If not, I will close.
