### ISSUE TITLE
Unable to fetch stocks of exchanges other than US exchanges

### ISSUE THREAD

**Issue by gauravkiitk** [ranaroussi/yfinance#229]
Are these APIs working only for US exchanges?

**Comment by michel117** [comment]
No, it works for all stocks available on https://finance.yahoo.com/

**Comment by aniketnaikdesai** [comment]
Even I am not able to pull data for stock on Indian NSE exchange. The stock is available on yahoo finance link: https://finance.yahoo.com/quote/MSFT?p=MSFT

I ran the below code:
import yfinance as yf
SBI = yf.Ticker("SBI.NS")
print(SBI)
SBI.info

I got error --> KeyError: 'regularMarketOpen'. I have added the screenshot. 

I also tried "MSFT.BA" (https://finance.yahoo.com/quote/MSFT.BA?p=MSFT.BA) and got the same error.

O/p: 
![Screenshot 2020-03-29 at 12 36 21 AM](https://user-images.githubusercontent.com/50781438/77831523-b4efe180-7155-11ea-9cd1-ab2c03a6796e.png)

**Comment by gauravkiitk** [comment]
@michel117 - Does only few attributes work for some stocks?
I was able to fetch history etc.. but other attributes were returning error as mentioned by @aniketnaikdesai

**Comment by aniketnaikdesai** [comment]
OK one error from my end. I put the ticker symbol as SBI in first try. But MSFT.BA still gave Regular Market Open error. 

So I just reinstalled the library and now I am getting Index out of range for SBIN.NS and MSFT.BA... I saw that in Issue # 150 there is a discussion going on about information missing from Institutional Investor section which is causing the error. I will try that edit and update this issue.

**Comment by aniketnaikdesai** [comment]
you need to edit your base.py line 286 

        if len(holders)>1 :
            self._institutional_holders = holders[1]
            if 'Date Reported' in self._institutional_holders:
                self._institutional_holders['Date Reported'] = _pd.to_datetime(
                    self._institutional_holders['Date Reported'])
            if '% Out' in self._institutional_holders:
                self._institutional_holders['% Out'] = self._institutional_holders[
                    '% Out'].str.replace('%', '').astype(float)/100

**Comment by ryanlr7** [comment]
Yes. Same problem here. 
I tried ticker LAND.L from London exchange. It doesn't work.

**Comment by aniketnaikdesai** [comment]
I am able to pull data for LAND.L.
![Screenshot 2020-03-31 at 11 59 57 AM](https://user-images.githubusercontent.com/50781438/77994232-41adc180-7347-11ea-8f69-58a2d39eff6a.png)

**Comment by gauravkiitk** [comment]
@aniketnaikdesai Are you able to fetch options data for indian stock market?

**Comment by aniketnaikdesai** [comment]
I haven't tried. I don't deal in derivatives market.

**Comment by gauravkiitk** [comment]
@michel117 Any way to fetch options and futures data for indian stock market?

**Comment by gauravkiitk** [comment]
@michel117 @aniketnaikdesai Which field are we getting current stock price?

**Comment by aniketnaikdesai** [comment]
Use issues to only discuss errors and not to ask queries. For current stock price, see the code example below.

import yfinance as yf
SBI = yf.Ticker("SBIN.NS")
SBI.info["currentPrice"]

**Comment by gauravkiitk** [comment]
@aniketnaikdesai Reason why i am asking is, there is no such key 'currentPrice'
It is very basic think which seems to be missing. Can you recheck once? There is no such key.
Please note, i have called get_info first.

itc.info["currentPrice"]
Traceback (most recent call last):

  File "<ipython-input-97-988d975d5d34>", line 1, in <module>
    itc.info["currentPrice"]

KeyError: 'currentPrice'

**Comment by aniketnaikdesai** [comment]
I am able to get the info for SBIN and ITC. See attached image.
![Screenshot 2020-04-10 at 10 19 14 AM](https://user-images.githubusercontent.com/50781438/78963474-31e76780-7b15-11ea-8669-fdcc6f77636d.png)

**Comment by gauravkiitk** [comment]
@aniketnaikdesai Are you using some other version of yfinance? I see below version for me.
Also i cant use itc.info without calling itc.get_info()
Even after calling itc.get_info(), there is no field for 'currentPrice'
Have changed something locally in library or using some other version?

pip show yfinance
Name: yfinance
Version: 0.1.54
Summary: Yahoo! Finance market data downloader
Home-page: https://github.com/ranaroussi/yfinance
Author: Ran Aroussi
Author-email: ran@aroussi.com
License: Apache
Location: c:\programdata\anaconda3\lib\site-packages
Requires: requests, multitasking, numpy, pandas
Required-by:

**Comment by aniketnaikdesai** [comment]
I use my custom code. I have all the edits applied. I don’t use the base/master yfinance, it has not been maintained for many months.

**Comment by gauravkiitk** [comment]
Ohk..thats the difference then :) May be i also need to edit then

**Comment by aniketnaikdesai** [comment]
I would advise to fork a copy and then make the changes. Alternatively, you can merge my code to your branch and go from there.

To install from your branch 

Uninstall the original copy 

Pip uninstall yfinance

Install using below command 

pip install git+https://github.com/<yourusername>/yfinance.git

**Comment by gauravkiitk** [comment]
This is throwing err below: -  Is the command right?

pip install git+https://github.com//yfinance.git
Collecting git+https://github.com//yfinance.git
  Cloning https://github.com//yfinance.git to c:\users\gk\appdata\local\temp\pip-req-build-kcl1k3df
  Running command git clone -q https://github.com//yfinance.git 'C:\Users\gk\AppData\Local\Temp\pip-req-build-kcl1k3df'
  error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version while accessing https://github.com//yfinance.git/info/refs

  fatal: HTTP request failed
ERROR: Command errored out with exit status 128: git clone -q https://github.com//yfinance.git 'C:\Users\gk\AppData\Local\Temp\pip-req-build-kcl1k3df' Check the logs for full command output.

**Comment by aniketnaikdesai** [comment]
Command is wrong 
You did not put your username

pip install git+https://github.com/username/yfinance.git

**Comment by pierrerl-py** [comment]
@aniketnaikdesai have you solved your Regular Market Open error? I am still getting it this error message

**Comment by aniketnaikdesai** [comment]
Can you give the ticker for what you are getting the error. I don’t get any error for Indian equity markets.

**Comment by pierrerl-py** [comment]
Never-mind it was my fault, within my long list of tickers there was a mistake for one of them. Thanks for the quick reply though!

**Comment by NiharGharat** [comment]
Hi @aniketnaikdesai , how did you find about the post fix for stocks ticker like NS? I was using https://dumbstockapi.com/ for tickers, they have NSE and ticker name but for bse, there is integer value which dosent seems to work with eg - 

```
x=yf.Ticker('500020.BSE')
>>> x.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/x/.local/lib/python3.7/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
```

```
 x=yf.Ticker('500020.BS')
>>> x.info
{'regularMarketPrice': None, 'logo_url': ''}
```

**Comment by surajmahangade** [comment]
@NiharGharat  Use Security Id, works fine.
Example:
`msft = yf.Ticker("SBIN.BO")`
