### ISSUE TITLE
can't work, very slow

### ISSUE THREAD

**Issue by RobinChen121** [ranaroussi/yfinance#230]
whey I try the code:
```python 
import yfinance as yf
msft = yf.Ticker("MSFT")
msft.info
```

it is very slow and can't work.  There may be some concerns for the url address.

I am in China, but the yahoo finance website is not blocked.

**Comment by simonvdv** [comment]
Same ticker, valid result in Belgium: "executed in 162ms, finished 19:34:55 2020-03-29"
Perhaps an ISP or proxy problem ? You can manually set a proxy via `proxy="SERVER"` (see the doc)

**Comment by silvavn** [comment]
This error is not caused by yfinance but by other external factors.
