### ISSUE TITLE
Anaconda not recognizing yfinance

### ISSUE THREAD

**Issue by bh32** [ranaroussi/yfinance#232]
Using the "geeksforgeeks" "add a package" method in the Anaconda Administrator Prompt I was able to install  into the miniconda3 as follows:

(base) C:\>pip install yfinance
Requirement already satisfied: yfinance in c:\users\[user]\miniconda3\lib\site-packages\yfinance-0.1.54-py3.7.egg (0.1.54)

Now using Anaconda I can not find yfinance anywhere (ie miniconda3).

I am still learning - and since relying on Anaconda I may have taken the package manager for granted - however would greatly appreciate help.

**Comment by bh32** [comment]
Update - (I was using Jupyter) If I "installed" Jupyter through the "miniconda3 environment" (was using the "root environment") could then successfully import yfinance.

Don't quite understand why - and yfinance still doesn't show up by searching the environments through the Anaconda Navigator, but seems I found a work around.

Will look forward to using this module, thank you for providing it.

**Comment by simonvdv** [comment]
Not related at all with yfinance;) If I do understand you correctly, it looks like you were trying to access the package from you base env while you installed it in another one (which is, and that's the underlying idea of venv's, not something you can/should/want to do). Read conda's manual : [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)

**Comment by bh32** [comment]
Thank you simonvdv, agreed.
