### ISSUE TITLE
Limited Success (lxml not found) - Is the API blocked?

### ISSUE THREAD

**Issue by bh32** [ranaroussi/yfinance#233]
Just installed version 0.1.54 of yfinance.
(Using Python 3.7.3 and running through a Jupyter notebook.)

Going through the types of data I am getting the 'lxml not found' error.

Based on other posted comments it seems that Yahoo has been blocking the traditional API's to get this data - possibly to force use of "premium service" (???), I don't know but seems likely since the ones that work (history, actions, dividends, splits, options) versus the more useful ones that do not work (info, financials, balance_sheet, cash flow etc. - tried all listed).

Please bring me up to speed if I am missing something - but otherwise my thinking is that yfinance is a very useful program that unfortunately is hampered by an uncooperative data website.

**Comment by jabarny** [comment]
I have been able to draw data just fine this morning.
![yfaal](https://user-images.githubusercontent.com/25020070/77944737-79f0c980-728d-11ea-9ca8-44209e066dfa.JPG)

**Comment by bh32** [comment]
Thank you, jabarny, for the screenshot, but what type of data is in the columns? (P/E's in some I'm guessing.)

**Comment by jabarny** [comment]
np.

nope; normal OHLC, volume, and adj. close.

**Comment by bh32** [comment]
Thank you (again).
