### ISSUE TITLE
Financial statements not working

### ISSUE THREAD

**Issue by mchandlernz** [ranaroussi/yfinance#234]
Hello,

It seems the financial statements (income statement, bal sheet, cashflow) are not working as intended.

It's not showing an error, but is not returning any data.

**Comment by jabarny** [comment]
> Hello,
> 
> It seems the financial statements (income statement, bal sheet, cashflow) are not working as intended.
> 
> It's not showing an error, but is not returning any data.

https://github.com/ranaroussi/yfinance/issues/191

check here.
