### ISSUE TITLE
UK LSE stocks 

### ISSUE THREAD

**Issue by lefig** [ranaroussi/yfinance#235]
Hi there,

Thanks for such a great project and for maintaining it so well.

I have a query regarding trusts traded on the London exchange. I trade these. Stocks like MNKS.L, EWI.L.

Historical data is available via the API for these stocks. But calls to info and others generate an exception.

  File "C:\work\python\3.6.7\python-3.6.7.amd64\lib\site-packages\yfinance\base.py", line 286, in _get_fundamentals
    self._institutional_holders = holders[1]
IndexError: list index out of range

What I am looking for is the current quote. The bid ask and not the history.

Is there an API call for the current price?

Thanks

Fig

**Comment by antoinecomp** [comment]
Maybe I'm wrong but it seems that the tool is parametered only for US stocks at the noment. I'm going to dive into it and try to know how to get European ones

**Comment by aniketnaikdesai** [comment]
The index error is due to missing institutional holders information.
Look for the fix in issue #229 or #159 
but there seems to be a _get_fundamentals error also. Look at issue #174

**Comment by lefig** [comment]
Thank you both

**Comment by simonvdv** [comment]
With the fix mentioned by @aniketnaikdesai, I haven't any issue retrieving bid-ask:

`tick = yf.Ticker("MNKS.L")
tick.info['ask']
**769.0**`

@antoinecomp the module is gathering yahoo! finance data -hence the name;)- so you can work on whatever ticker you want, as long as it is followed by yahoo! finance main site (therefore including worldwide markets).
The easiest approach, when unsure of what ticker format to use, is to look it up on the website itself (for large set of companies, I wrote a little webscraping function to gather ticker from company names, let me know if you need it!)
