### ISSUE TITLE
Data for Italian FTSEMIB.MI index is not working on daily data

### ISSUE THREAD

**Issue by eugeniodimarzio** [ranaroussi/yfinance#242]
I see that retrieving data for tickers FTSEMIB.MI it is perfecting working on intraday data e.g. 1 minutese or also for 15min but is not working for daily data. If I run following code:

msft = yf.Ticker("FTSEMIB.MI")
msft.history(period="max")

the outcome of last days is not right:
2018-02-08	22466.60	22466.60	22466.60	22466.60	0	0	0
2018-02-09	22166.80	22166.80	22166.80	22166.80	0	0	0
2020-04-06	16769.13	16958.11	16764.81	16870.38	0	0	0

it seems that it stops ad 2018-02-09 than it reports the today date of 2020-04-06. I tryed also with different start and end parameters but results is the same.

**Comment by simonvdv** [comment]
Check [https://finance.yahoo.com/quote/FTSEMIB.MI](https://finance.yahoo.com/quote/FTSEMIB.MI), it looks like a Yahoo! Finance issue (missing data)...
