### ISSUE TITLE
Missing latest day of data when using Ticker().history('5y')

### ISSUE THREAD

**Issue by pon-poot** [ranaroussi/yfinance#247]
Data of the latest (previous) day is missing when using an argument  like '`5y'` for the history method. When defining `start` and `end`. It does give data of the latest day.

**Comment by aniketnaikdesai** [comment]
Can you give a code example along with the actual stock for which this happened.

**Comment by cleanman2** [comment]
I seem to have a similar problem getting daily closing prices. If I request 2020-05-29 on 2020-05-31, for example, my program will produce an error: uno.RuntimeException: Couldn't convert Date

Here is a test script that prints the data returned.
import yfinance as yf
import pandas as pd
# ~ day = '2020-05-28'
day = '2020-05-29'
aapl = yf.Ticker('AAPL')
hist = aapl.history(start=day)
close = hist.loc[day]['Close']
print('Close = ', close)
'''
day = "2020-05-28" prints: Close =  318.25

day = "2020-05-29" prints: Close =  Date
                                    2020-05-29    317.94
                                    2020-05-29    317.94
                                    Name: Close, dtype: float64
'''
I tried setting the start and end dates the same but that produces a Key error.
I don't know Pandas that well but it seems like when asked to get the top row of actual data it somehow is grabbing the header.  

Thanks you for a very useful program. The fact that I don't see a lot of people having the problem that I do leads me to believe that maybe I am doing something incorrectly. If you need any other info from me please ask.
