### ISSUE TITLE
Failed to get .info of some stocks

### ISSUE THREAD

**Issue by ukalpa** [ranaroussi/yfinance#249]
Hi there,

I am encountering the issue of throwing Exception Error:<class 'ImportError'> when trying to get some stock's info and appreciate if you could have a look at it.

E.g. OPCH https://finance.yahoo.com/quote/OPCH/?p=OPCH

Execute the following code and the system will catch the <class 'ImportError'> error,
```
#!/usr/bin/env python3
import yfinance as yf
item = yf.Ticker('OPCH')
print(item.info)
```

**Comment by aniketnaikdesai** [comment]
Try item.info() not print(item.info()
