### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'float' and 'str'

### ISSUE THREAD

**Issue by snehil2010** [ranaroussi/yfinance#252]
Getting TypeError for the symbol "BZG2.SG". Attached is the complete error log

Below is the code snippet:

try:
	data = yf.download(  
	tickers = "BZG2.SG",
	period = "100y",
	interval = "1d",
	auto_adjust = True,
	threads = True,
	proxy = None)
           
except:
	print("Oops!",sys.exc_info()[0],"occured in function fetch_data()")

And for some reason my except block is not catching this error and the program terminates.

[error_log.txt](https://github.com/ranaroussi/yfinance/files/4464824/error_log.txt)

**Comment by simonvdv** [comment]
Is it working if you use a valid period ?

From the readme:
> # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
> # (optional, default is '1mo')

**Comment by simonvdv** [comment]
Take a look at the Y! Finance original results for the adjusted closing prices before Dec. 2019, I think there is a Yahoo! data bug here (leading to mis-adjustement for OHLC prices when setting `autoadjust `to true) :
[](https://finance.yahoo.com/quote/BZG2.SG/history?period1=1198800000&period2=1586563200&interval=1d&filter=history&frequency=1d)

**Comment by snehil2010** [comment]
> The issue comes from `auto_adjust=True `(and disapear if you let it defaulted to false). Some Adj Close are sent to "Infinity", and the column isn't a float anymore. I'll take a look:)

Thanks @simonvdv 

I am absolutely clueless how to catch this exception. Below is my code snippet and the program terminates as soon as yfinance.download() function is invoked for this particular symbol.

import yfinance as yf
try:
    yf.download(  
        tickers = "BZG2.SG",
        period = "100y",
        interval = "1d",
        auto_adjust = True,
        threads = True,
        proxy = None)
except:
    print("Error")

What am I doing wrong?
