### ISSUE TITLE
Failed download on symbols

### ISSUE THREAD

**Issue by tcalbrecht** [ranaroussi/yfinance#253]
When I try to access this symbol, QCBMPX, I get this response:

```
import yfinance as yf
s = yf.download('QCBMPX', period = 'ytd', interval = '1d')

$ python test.py 
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- QCBMPX: No data found for this date range, symbol may be delisted


```
The symbol appears on the Yahoo site and others.

https://finance.yahoo.com/quote/QCBMPX/
https://markets.ft.com/data/funds/tearsheet/historical?s=QCBMPX

Same with these; QCEQPX,  QCGLPX .

Tom

**Comment by simonvdv** [comment]
Hi, are you able to access data on the Yahoo! Finance website itself ? I don't see any historical/fundamentals/etc (only last price and the ticker name)
[https://finance.yahoo.com/quote/QCBMPX/history?p=QCBMPX](https://finance.yahoo.com/quote/QCBMPX/history?p=QCBMPX)

**Comment by tcalbrecht** [comment]
No, there's no historical data in Yahoo that I can see.

Thanks.

**Comment by lefig** [comment]
Then it won't be available.

I always do a little search first say for MNKS.L to make sure that he exists. Yahoo also uses some strange naming convention at times.

**Comment by mSouvik2022** [comment]
I simply Use this:
![Screenshot 2022-03-29 135014](https://user-images.githubusercontent.com/102585308/160574339-449b83fd-094c-41f1-bf27-d14816bc2fed.png)


pls let me know if this works for you.
