### ISSUE TITLE
Unable to get balance sheet and for all tickers - Module down?

### ISSUE THREAD

**Issue by deepak-george** [ranaroussi/yfinance#254]
Even a simple example given in the documentation is not working. Seem that the module is not working at all.

import yfinance as yf

msft = yf.Ticker("MSFT")
msft.quarterly_balance_sheet
msft.earnings
msft.cashflow

For all the requests I am getting an empty  data frame as output. 
```
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

```

I am on latest version i.e. 0.1.54

**Comment by dsyl007** [comment]
I am also having the same problem.
![Screen Shot 2020-04-13 at 4 56 25 PM](https://user-images.githubusercontent.com/47400187/79160398-b7824600-7da7-11ea-922b-2630d477f06f.png)

**Comment by markbentivegna** [comment]
I am having this issue as well

**Comment by Fabe007** [comment]
I am also getting the same error
![image](https://user-images.githubusercontent.com/63656516/79259368-37fd8100-7e52-11ea-90ee-87f99ba8bd68.png)

**Comment by rodrigobercini** [comment]
This issue is being caused by a url updating issue in base.py, you can check the full story [here](https://github.com/ranaroussi/yfinance/issues/240#issuecomment-609061828).

To fix it, you can try the steps described in the link above or just clone directly from my repository (don't forget to restart the kernel afterwards):
pip install git+https://github.com/rodrigobercini/yfinance.git

Let me know if that works for you!

**Comment by ckdelta** [comment]
> This issue is being caused by a url updating issue in base.py, you can check the full story [here](https://github.com/ranaroussi/yfinance/issues/240#issuecomment-609061828).
> 
> To fix it, you can try the steps described in the link above or just clone directly from my repository (don't forget to restart the kernel afterwards):
> pip install git+https://github.com/rodrigobercini/yfinance.git
> 
> Let me know if that works for you!

Thanks Rodrigo, however I still get Empty DataFrame. Can anyone else confirm if Rodrigo's repo works?

**Comment by MaxMMadsen** [comment]
> > This issue is being caused by a url updating issue in base.py, you can check the full story [here](https://github.com/ranaroussi/yfinance/issues/240#issuecomment-609061828).
> > To fix it, you can try the steps described in the link above or just clone directly from my repository (don't forget to restart the kernel afterwards):
> > pip install git+https://github.com/rodrigobercini/yfinance.git
> > Let me know if that works for you!
> 
> Thanks Rodrigo, however I still get Empty DataFrame. Can anyone else confirm if Rodrigo's repo works?

Rodrigo's repo not working for me either.

**Comment by rodrigobercini** [comment]
Try uninstalling yfinance and then installing from my repo, I've just tested and it seems to be working:

https://colab.research.google.com/drive/1wmJAzTsa1-wmQT2SMAHMl0dBovFNWpbv

**Comment by MaxMMadsen** [comment]
> Try uninstalling yfinance and then installing from my repo, I've just tested and it seems to be working:
> 
> https://colab.research.google.com/drive/1wmJAzTsa1-wmQT2SMAHMl0dBovFNWpbv

It is working now! Thanks.

**Comment by ckdelta** [comment]
> Try uninstalling yfinance and then installing from my repo, I've just tested and it seems to be working:
> 
> https://colab.research.google.com/drive/1wmJAzTsa1-wmQT2SMAHMl0dBovFNWpbv

Yeah, it works, thank you!!

**Comment by dabinglee** [comment]
> 尝试卸载yfinance，然后从我的仓库中安装，我已经测试过了，它似乎可以正常工作：
> 
> https://colab.research.google.com/drive/1wmJAzTsa1-wmQT2SMAHMl0dBovFNWpbv

我安装了你的git，但是我出错了：

  ERROR: Command errored out with exit status 1:
     command: 'd:\code\python\stock\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-dq7ai65a\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~
1\\AppData\\Local\\Temp\\pip-req-build-dq7ai65a\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
 --egg-base 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-pip-egg-info-5jp5rzpp'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-dq7ai65a\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-dq7ai65a\setup.py", line 17, in <module>
        with io.open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-dq7ai65a\\README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

我已经更新了 egg_info

**Comment by narekzamanyan97** [comment]
> This issue is being caused by a url updating issue in base.py, you can check the full story [here](https://github.com/ranaroussi/yfinance/issues/240#issuecomment-609061828).
> 
> To fix it, you can try the steps described in the link above or just clone directly from my repository (don't forget to restart the kernel afterwards):
> pip install git+https://github.com/rodrigobercini/yfinance.git
> 
> Let me know if that works for you!

Worked for me. Thanks a lot.
