### ISSUE TITLE
Potential data discrepancy

### ISSUE THREAD

**Issue by lefig** [ranaroussi/yfinance#255]
Hi there,

I was hoping that one day the API may support getting the latest quote as opposed to history. Just the latest current OHLC. My work around is to download the last 1 day and take the last minute of data. I know, not very efficient. But I make the observation that there are data gaps when downloading in bulk as opposed to single symbols.

For instance:

```
ata = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = "BNKR.L",

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "1d",

        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1m",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'ticker',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = False,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = False,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )
```
I have attached a file called test.txt.

Then when a call is made to the following we have no gaps (pls see test2.txt:

# get historical market data
`df = bnkr.history(period="1d", interval="1m", actions="False")`

My question is what method is most reliable for the last "tick". 
The bulk method is more efficient but perhaps unreliable.

I would welcome your thoughts. Thanks

Fig

[test.txt](https://github.com/ranaroussi/yfinance/files/4467063/test.txt)
[test2.txt](https://github.com/ranaroussi/yfinance/files/4467064/test2.txt)

**Comment by ValueRaider** [comment]
If you want want last trade price, then get last close: `history(period='1wk')['Close'].iloc[-1]`
