### ISSUE TITLE
[Question] Execution Time

### ISSUE THREAD

**Issue by AcudoDev** [ranaroussi/yfinance#257]
Hello,

First of all, I want to thank you for the incredible work you done.

I run these lines:

```
import time
import yfinance as yf

Symbol = "AAPL"

start_time = time.time()
Asset_YF = yf.Ticker(Symbol)
print("- %s seconds" % (time.time() - start_time))

start_time = time.time()
Asset_Info = Asset_YF.info
print("- %s seconds" % (time.time() - start_time))

start_time = time.time()
Asset_Data = Asset_YF.history(period="max")
print("- %s seconds" % (time.time() - start_time))
```
The output:
- 0.005499362945556641 seconds
- 1.2929999828338623 seconds
- 0.41750001907348633 seconds

Around 1.7s of execution time. This is not huge, except in the context of web services. 
I'm wondering if there is any possibility of improving this time. Is there any existing parameter (in your package) I should use to do this ? (ex:multiprocessing)

Thank you in advance,

Best Regards

**Comment by APfi** [comment]
I have the same issue. I'm extracting a couple of info fields from multiple tickers and it takes quite a long time as suggested above. I wonder if there is a way to speed up this. 

Many thanks!

**Comment by omidpouya** [comment]
I am having the same problem for a while. Just checked it with another package `finviz` ... The reason I used 'PEG` ratio for yf is that the info dictionary gives key error for trailingPE when the company does not have a PE ratio yet but it returns PEG with None:

<img width="641" alt="Screen Shot 2021-07-17 at 1 10 37 PM" src="https://user-images.githubusercontent.com/35211112/126048350-4693d618-c528-4aeb-b053-2ffcaaeaae23.png">
