### ISSUE TITLE
Bulk download bug

### ISSUE THREAD

**Issue by lefig** [ranaroussi/yfinance#258]
Hi,

I trade London LSE shares and specifically funds and attempted to download in bulk some of the most popular ones. Several worked but the vast majority did not. The return value was an empty data frame.

data = yf.download(  # or pdr.get_data_yahoo(...
            # tickers list or string as well
            tickers = _symbols,

            # use "period" instead of start/end
            # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
            # (optional, default is '1mo')
            period = "1d",

            # fetch data by interval (including intraday if period < 60 days)
            # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
            # (optional, default is '1d')
            interval = "5m",

            # group by ticker (to access via data['SPY'])
            # (optional, default is 'column')
            group_by = 'ticker',

            # adjust all OHLC automatically
            # (optional, default is False)
            auto_adjust = False,

            # download pre/post regular market hours data
            # (optional, default is False)
            prepost = False,

            # use threads for mass downloading? (True/False/Integer)
            # (optional, default is True)
            threads = True,

            # proxy URL scheme use use when downloading?
            # (optional, default is None)
            proxy = None
        )
4 out of 5 fail:

Yahoo: Downloading failed: EWI.L
Yahoo: Downloading failed: FCIT.L
Yahoo: Downloading failed: FAS.L
Yahoo: Downloading failed: FGT.L

I had assumed his API call was relatively sound but it does not seem to be.

I would appreciate any thoughts.

Fig

**Comment by lefig** [comment]
Just to add. The error...

Failed download:
- EWI.L, FCIT.L, FAS.L: No data found, symbol may be delisted

**Comment by singlecheeze** [comment]
`# Clean up tickers with "." and replace with "-" to make them Yahoo API compatible
    tickers = [ticker.replace(".", "-") for ticker in tickers]`
