### ISSUE TITLE
Connection aborted

### ISSUE THREAD

**Issue by snehil2010** [ranaroussi/yfinance#260]
I am intermittently getting "Connection Aborted" error when I try downloading historical data for symbols in a loop.

Attached is the complete error log
[error_log1.txt](https://github.com/ranaroussi/yfinance/files/4490626/error_log1.txt)

Also, my try-except block is not catching this exception and the program stops as soon as the error occurs. What am I doing wrong?

**Comment by pbrissaud** [comment]
I have the same issue and I don't know how to solve it

**Comment by beglitis** [comment]
Check this to see if it helps with your issue

https://github.com/ranaroussi/yfinance/issues/445

**Comment by pbrissaud** [comment]
Thanks, I don't have a single error since I installed selenium and selenium-requests !
