### ISSUE TITLE
Time Series Incorrect Data

### ISSUE THREAD

**Issue by mikaelhug** [ranaroussi/yfinance#261]
I noticed a strange error. It came about when i started plotting some purchases I have made against stocks data downloaded from yfinance. The strange thing was the price I had payed did not align with the price of the stock curve.. So I investigated and it appears that the further back in history, the more off the time series are. Which is strange, because on Yahoo Finance website, the time series are correct. Here are some examples: 

A Purchase of this Ratos B stock at 94 SEK, not even close to the downloaded data.
<img width="647" alt="Screenshot 2020-04-16 at 22 22 49" src="https://user-images.githubusercontent.com/37077881/79534616-57c3bd80-807b-11ea-988a-63b23259ce14.png">

More interestingly, the curve appears correct but with the wrong scaling (online vs downloaded):
<img width="1274" alt="Screenshot 2020-04-16 at 22 33 55" src="https://user-images.githubusercontent.com/37077881/79534665-7b870380-807b-11ea-9a33-981ddf074a5c.png">

Another example is Apple, online and downloaded does not show the right if you go back:
2010-03-03 show different values
![Screenshot 2020-04-17 at 07 21 47](https://user-images.githubusercontent.com/37077881/79534939-4af39980-807c-11ea-8f66-c3ca036d164e.png)
![Screenshot 2020-04-17 at 07 20 32](https://user-images.githubusercontent.com/37077881/79534941-4b8c3000-807c-11ea-9194-ea46cae1dd1e.png)

**Comment by andrewjylee** [comment]
I wonder if this is the same problem as [218](https://github.com/ranaroussi/yfinance/issues/261)... If the numbers are incorrect that is a huge concern!

**Comment by ValueRaider** [comment]
Nothing wrong, you're looking at dividend-adjusted price. Disable with `auto_adjust=False`
