### ISSUE TITLE
yf.download() verbose mode

### ISSUE THREAD

**Issue by PanoPilot** [ranaroussi/yfinance#266]
Hi there,

small quick question. Is there a kind of verbose parameter for yf.downlaod method to get rid of the message send to output console? like "[*********************100%***********************]  1 of 1 completed"

thx in advance
Best,
Chris

**Comment by daghemo** [comment]
Same question here. Solved by adding progress=False to yf.download().
See also #29 and #322.

**Comment by steghio** [comment]
Hello,

would it be possible to add this info to the readme? I think it would be easier for people to find this common use case.

Thank you and thank you for the library as well

Have a nice day

**Comment by Georgi-Petkov** [comment]
Thank you @daghemo , it took me a while to get rid of this progress message. In QUARTO none of the #| echo: false,
#| warning: false ,#| message: false can deal with this!
