### ISSUE TITLE
How to calculate current EV/EBIT, ROIC & Net Margin using yfinance?

### ISSUE THREAD

**Issue by aimlnerd** [ranaroussi/yfinance#267]
I found EBIT in the balance sheet but couldn't find the other metrics in output of yfinance.

**Comment by MrPrules** [comment]
Hey,

as I'm trying to calculate ROIC too, here are some information:

ev = ticker.info["enterpriseValue"]
ebit = ticker.financials.iloc[7, 0]

You might help me out with ROIC. As I'm a non native English speaker.. I can't connect the variables (from Quandl) to the yahoo finance ones:


[ROIC]   Return on Invested Capital is ratio estimated by dividing [EBIT] by   [InvCapAvg]. [InvCap] is calculated as: [Debt] plus [Assets] minus   [Intangibles] minus [CashnEq] minus [LiabilitiesC]. Please note this   calculation method is subject to change.

All of the variables above should be located in the ticker.balance_sheet DataFrame.
I would go for TotalLiab, Total Assets, Intangible Assets, Cash Eq?, Current Liabilities

Any suggestions?

**Comment by tommycarstensen** [comment]
Probably not the solution you are looking for, but financialModelingPrep has metrics such as ROIC.
