### ISSUE TITLE
Yahoo Finance URL Change

### ISSUE THREAD

**Issue by tjGecko** [ranaroussi/yfinance#271]
Hi Ran,
Good job on the library. I ran into an issue with the URL. I've attached my test code. When I run this code, I noticed that the financials are not resolving correctly (e.g. balance sheet, cashflow, ...). I inspected with a debugger and copied the URL from your base class into the browser to see if it would resolve. No luck. It appears that Yahoo changed the formatting of the URL slightly. 

Here's what I found:

- Your version: https://finance.yahoo.com/quote/MSFT/financials
- Yahoo version: https://finance.yahoo.com/quote/MSFT/financials?p=MSFT

[T_Pull_Yahoo.py.txt](https://github.com/ranaroussi/yfinance/files/4506889/T_Pull_Yahoo.py.txt)

Any ideas?

**Comment by tjGecko** [comment]
Hey Ran,
Don't know what the etiquette is for updating others' repos. I made a fix that appears to work in my code. I'll attach here for your review. Check around line 353 of base.py:

# Code Changes
>         # get fundamentals
>         # https://finance.yahoo.com/quote/MSFT/financials?p=MSFT
>         # ,
>         tj_url = f'{self._scrape_url}/{self.ticker}/financials?p={self.ticker}'
>         data = utils.get_json(tj_url, proxy)
>         # data = utils.get_json(url+'/financials', proxy)


[base.py.txt](https://github.com/ranaroussi/yfinance/files/4506971/base.py.txt)

**Comment by denrasulev** [comment]
@tjGecko probably this [info](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) could help with pull requests :)

**Comment by tjGecko** [comment]
> @tjGecko probably this [info](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) could help with pull requests :)

Thank you! I will educate myself. :)

**Comment by preisleistung** [comment]
> Hey Ran,
> Don't know what the etiquette is for updating others' repos. I made a fix that appears to work in my code. I'll attach here for your review. Check around line 353 of base.py:
> 
> # Code Changes
> > ```
> >     # get fundamentals
> >     # https://finance.yahoo.com/quote/MSFT/financials?p=MSFT
> >     # ,
> >     tj_url = f'{self._scrape_url}/{self.ticker}/financials?p={self.ticker}'
> >     data = utils.get_json(tj_url, proxy)
> >     # data = utils.get_json(url+'/financials', proxy)
> > ```
> 
> [base.py.txt](https://github.com/ranaroussi/yfinance/files/4506971/base.py.txt)

this works for me as well, thanks!

**Comment by francopiccolo** [comment]
> Hey Ran,
> Don't know what the etiquette is for updating others' repos. I made a fix that appears to work in my code. I'll attach here for your review. Check around line 353 of base.py:
> 
> # Code Changes
> > ```
> >     # get fundamentals
> >     # https://finance.yahoo.com/quote/MSFT/financials?p=MSFT
> >     # ,
> >     tj_url = f'{self._scrape_url}/{self.ticker}/financials?p={self.ticker}'
> >     data = utils.get_json(tj_url, proxy)
> >     # data = utils.get_json(url+'/financials', proxy)
> > ```
> 

same here thank you!
