### ISSUE TITLE
 ModuleNotFoundError: No module named 'yfinance' 

### ISSUE THREAD

**Issue by haydonm** [ranaroussi/yfinance#281]
Hi all, 
I am having an issue with yfinance. I first tried to install it through conda which didn't work, so did a pip install, which appeared to work in the anaconda prompt. However when I open Spyder and try to import yfinance as yf it gives me the following error message:

ModuleNotFoundError: No module named 'yfinance'

I've tried uninstalling and reinstalling as well as googling around the problem but and although found a similar thread wasn't able to find anything that helped with finding a solution. 
I am on a windows 64bit, using python 3.7.
Any help will be greatly appreciated!

**Comment by Rohit-mel** [comment]
I am getting the same error how did you manage to solve it?
