### ISSUE TITLE
Getting information for multiple tickers with dots

### ISSUE THREAD

**Issue by cheungcn** [ranaroussi/yfinance#282]
Hi all, I am using these code to get information multiple tickers
```
import yfinance as yf

tickers = yf.Tickers('msft aapl goog')
# ^ returns a named tuple of Ticker objects

# access each ticker using (example)
tickers.msft.info
tickers.aapl.history(period="1mo")
tickers.goog.actions
```

But the tickers I need include dot, such as 0001.HK, 0002.HK 
Then the code becomes

`tickers.0001.HK.info`  

And It cannot run properly.  Anyone has any idea to fix it?

**Comment by sabirjana** [comment]
Hi,
I too facing a similar issue. Please let me know if any solution you get.
Thanks

**Comment by William-Lake** [comment]
Was just looking into this earlier today, the solution I found was to iterate over the `tickers` attribute of the `yf.Tickers` class:

```python
import yfinance as yf

stocks = yf.Tickers('msft 0001.HK')

for ticker in stocks.tickers:

    info = ticker.info

    print(info['sector'])
```

```
Technology
Industrials
```

**Comment by cheungcn** [comment]
I would like to batch download the market capitalization for a list of stocks...
using a for loop takes forever...
