### ISSUE TITLE
Stocks without institutional_holders

### ISSUE THREAD

**Issue by gitplaza** [ranaroussi/yfinance#286]
Stocks like VZ doesn't have institutional_holders, so get Ticker info fails:

import yfinance as yf

tickerData = yf.Ticker("VZ")
info = tickerData.info
print(info)

**Comment by gitplaza** [comment]
In base.py is possible to check the length of the holders:

        if len(holders) > 1:
            self._institutional_holders = holders[1]

**Comment by hvogel0** [comment]
Facing the same issue with brk-b. The following fix works:
try:
  self._institutional_holders = holders[1]
except:
   self._institutional_holders = {}
