### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Platinkurd** [ranaroussi/yfinance#287]
Hey Guys, 
after installing yfinance and doing a first try with the provided examples I get this response:
'AttributeError: partially initialized module 'yfinance' has no attribute 'Ticker' (most likely due to a circular import)'
Has anyone an idea what the error could be, since yfinance is listed as installed....
Thanks alot!

**Comment by bahadirhanfiliz** [comment]
@Platinkurd I have encountered with the similar error module 'yfinance' has no attribute 'Ticker'

It seems I have named the python script with the same name as the module. Have you named your script as yfinance.py ?

**Comment by Platinkurd** [comment]
Yes, indeed that's the problem. Thanks a lot!
