### ISSUE TITLE
Issue With some stock

### ISSUE THREAD

**Issue by Ben2pop** [ranaroussi/yfinance#288]
I tried to get info about the stock "BAM" Brookfield asset management listed on the NYSE
It gives me an Errror: 
IndexError: list index out of range

any idea ? 
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-161-c52d32a3ec1f> in <module>
----> 1 msft.info

~\anaconda3\lib\site-packages\yfinance\ticker.py in info(self)
    136     @property
    137     def info(self):
--> 138         return self.get_info()
    139 
    140     @property

~\anaconda3\lib\site-packages\yfinance\base.py in get_info(self, proxy, as_dict, *args, **kwargs)
    413 
    414     def get_info(self, proxy=None, as_dict=False, *args, **kwargs):
--> 415         self._get_fundamentals(proxy)
    416         data = self._info
    417         if as_dict:

~\anaconda3\lib\site-packages\yfinance\base.py in _get_fundamentals(self, kind, proxy)
    284         holders = _pd.read_html(url)
    285         self._major_holders = holders[0]
--> 286         self._institutional_holders = holders[1]
    287         if 'Date Reported' in self._institutional_holders:
    288             self._institutional_holders['Date Reported'] = _pd.to_datetime(

IndexError: list index out of range

**Comment by rodrigobercini** [comment]
The base code needs an error handler for cases where there are no institutional holders.

There are some PRs that could solve this issue, but while they are not merged, you can install my fork (don't forget to uninstall yfinance and restart the runtime):
pip uninstall yfinance
pip install git+https://github.com/rodrigobercini/yfinance.git

I've just tested for BAM and it's working fine. Cheers!
