### ISSUE TITLE
Error while installing the library with Anaconda

### ISSUE THREAD

**Issue by tszwailam** [ranaroussi/yfinance#289]
Hello,

I used the command on the homepage 
`conda install -c ranaroussi yfinance`
and got the error - 
`InvalidArchiveError('Error with archive C:\\Users\\User\\Anaconda3\\pkgs\\yfinance-0.1.54-py_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')`

Is there anything I could do about that? I have tried deleting the file and reinstalling it, no success.

Thanks!

**Comment by tranthuc-org** [comment]
Được gửi từ Yahoo Mail cho iPhone


Vào Chủ Nhật, tháng 5 3, 2020, 7:10 SA, Daniel Lam <notifications@github.com> đã viết:




Hello,

I used the command on the homepage
conda install -c ranaroussi yfinance
and got the error -
InvalidArchiveError('Error with archive C:\\Users\\User\\Anaconda3\\pkgs\\yfinance-0.1.54-py_0.tar.bz2. You probably need to delete and re-download or re-create this file. Message from libarchive was:\n\nCould not unlink')

Is there anything I could do about that? I have tried deleting the file and reinstalling it, no success.

Thanks!

**Comment by alvaroritter** [comment]
Try installing it with pip instead. Activate the conda environment you would like yfinance to be downloaded to and use `pip install yfinance --upgrade --no-cache-dir`
Hope I could help

**Comment by CTred** [comment]
> Try installing it with pip instead. Activate the conda environment you would like yfinance to be downloaded to and use `pip install yfinance --upgrade --no-cache-dir`. You can simply use your standard anaconda prompt for this, since pip is installed with conda by default.
> Hope I could help

If you do use pip, be sure it is installing to your virtual environment in conda.
