### ISSUE TITLE
Cannot retrieve financial data from yfinance (with img)

### ISSUE THREAD

**Issue by pakkinlau** [ranaroussi/yfinance#291]
My setting: jupyter lab + latest install yfinance

Tried following description of the package. 
Cannot retrieve financial data from yfinance
![image](https://user-images.githubusercontent.com/19696000/81097600-b96c9e80-8f3a-11ea-855b-ac26bdfc8190.png)

Also, the data seems not consistent with the data shown in yahoo finance
![image](https://user-images.githubusercontent.com/19696000/81097868-0f414680-8f3b-11ea-95c2-f725099159f6.png)
![image](https://user-images.githubusercontent.com/19696000/81097900-1cf6cc00-8f3b-11ea-8603-db7a95d6b97f.png)

I want to retrieve quarterly earnings data from yfinance package.
Is that possible? Thank you

**Comment by alvaroritter** [comment]
This is due to an issue in base.py which leads to empty dataframes being returned. There are several issue posts regarding this problem and one solution, which atleast worked for me, by  @hristo-mavrodiev in pull request #272 
You should be able to fork your project or navigate to the file where you downloaded the yfinance package and fix the code in base.py manually. 
Hope I could help

**Comment by hristo-mavrodiev** [comment]
For correct PEG ratio you need JavaScript enabled or use this with proxy server.
Check this project it's using Selenium for proper JavaScript loading. Peg ratio should be ok.
https://pypi.org/project/yahoostats/

**Comment by eyalk5** [comment]
The bug is not solved in my case @hristo-mavrodiev

**Comment by tranthuc-org** [comment]
Ok

**Comment by hristo-mavrodiev** [comment]
Feel free to show the code example.

```bash
!pip install git+https://github.com/hristo-mavrodiev/yfinance.git@dev
```
```pyrhon
import yfinance as yf
msft = yf.Ticker("MSFT")
msft.financials
```

**Comment by eyalk5** [comment]
yeh, It doesn't work. 
You have an error there.
It uses an incorrect url.

```
diff --git a/yfinance/base.py b/yfinance/base.py
index 01d5d32..e659d10 100644
--- a/yfinance/base.py
+++ b/yfinance/base.py
@@ -280,8 +280,8 @@ class TickerBase():
         data = utils.get_json(url, proxy)

         # holders
-        url = "{}/{}/holders".format(self._scrape_url, s
elf.ticker)
-        holders = _pd.read_html(url)
+        urlH = "{}/{}/holders".format(self._scrape_url,
self.ticker)
+        holders = _pd.read_html(urlH)
         self._major_holders = holders[0]
         self._institutional_holders = holders[1]
         if 'Date Reported' in self._institutional_holder
s:
```

**Comment by hristo-mavrodiev** [comment]
Looks the same as https://github.com/hristo-mavrodiev/yfinance/commit/824bb0a76259cc9ccea7879a9330fd526c7ef859

**Comment by eyalk5** [comment]
I verified that I have used your branch. 	Unfortunately, I have used your master branch.
