### ISSUE TITLE
For the guys who successfully load balance sheet by patching the package, how to find the base.py?

### ISSUE THREAD

**Issue by pakkinlau** [ranaroussi/yfinance#292]
For the guys who successfully load balance sheet by patching the package, how to find the base.py?
And how to change it on jupyter lab? Thank you

**Comment by rodrigobercini** [comment]
The easiest way to fix it temporarily is via fork, check the [GitHub Help for more info](https://help.github.com/en/github/getting-started-with-github/fork-a-repo). After you fork the project, you can change the base.py with the fix.

I've done that already, so alternatively, you could just use install my fork instead.

**Comment by kin529** [comment]
> The easiest way to fix it temporarily is via fork, check the [GitHub Help for more info](https://help.github.com/en/github/getting-started-with-github/fork-a-repo). After you fork the project, you can change the base.py with the fix.
> 
> I've done that already, so alternatively, you could just use install my fork instead.

Thank you! It works!

**Comment by kin529** [comment]
![image](https://user-images.githubusercontent.com/19696000/81222012-391b6b80-9016-11ea-84f9-2c36d8145942.png)

@rodrigobercini 
I am using your fork. Only 4 rows of earnings data I could extract from it.
Could I register yahoo premium somewhere, use that API, and login to extract more data?

**Comment by rodrigobercini** [comment]
> ![image](https://user-images.githubusercontent.com/19696000/81222012-391b6b80-9016-11ea-84f9-2c36d8145942.png)
> 
> @rodrigobercini
> I am using your fork. Only 4 rows of earnings data I could extract from it.
> Could I register yahoo premium somewhere, use that API, and login to extract more data?

Check [yahooquery](https://github.com/dpguthrie/yahooquery) for premium integration.
