### ISSUE TITLE
Stock data returns NaN’s

### ISSUE THREAD

**Issue by wesdevpro** [ranaroussi/yfinance#293]
When my app calls for long periods of data- particularly One year and up - y finance returns NaN’s.

**Comment by rodrigobercini** [comment]
Could you provide an example?

**Comment by xcompile** [comment]
Got a similar situation. It might be cause by a configuration issue or the environment the script is running in.
In my case I only see NaNs returned in a docker deployment(python:3.7.7-slim-buster, yfinance 0.1.54).
Running the same query local(Python 3.7.6,yfinance 0.1.54) doesn't cause NaNs.

**symbols**
RIG MUR VTR BABA AGI BOOT UNM MIME AER IPHI OMF MRO VIPS CLR PFSI AYX CS PBR-A WYND BBD THC SWCH OCN UAL ARWR AL INSG PFE GGB CC HLX BLMN SIG ASND CABO ECPG QRTEA PBF VIRT FCX

**timeframe**
2015-07-01 to: 2020-05-16

**with NaNs**
_AYX_
GET /v8/finance/chart/AYX?period1=1435708800&period2=1589596628&interval=1d&includePrePost=False&events=div%2Csplits HTTP/1.1" 200 None

_SWCH_
GET /v8/finance/chart/SWCH?period1=1435708800&period2=1589596515&interval=1d&includePrePost=False&events=div%2Csplits HTTP/1.1" 200 None

**Comment by jrwrigh** [comment]
![image](https://user-images.githubusercontent.com/20801821/85341843-6a58d980-b4a6-11ea-95c4-3e7926e1e29f.png)
Here's an example of the Dow Jones Industrial. All the blank areas are NaN values

**Comment by rodrigobercini** [comment]
I'm failing to reproduce your issue. Perhaps try to install yfinance in a fresh environment?

![image](https://user-images.githubusercontent.com/18664907/85413909-cf154200-b541-11ea-934a-25540af23895.png)

**Comment by GF-Huang** [comment]
> I'm failing to reproduce your issue. Perhaps try to install yfinance in a fresh environment?
> 
> ![image](https://user-images.githubusercontent.com/18664907/85413909-cf154200-b541-11ea-934a-25540af23895.png)

You need download a batch of tickers. Single or a small number of tickers does not trigger this issue.

**Comment by ighgusp** [comment]
I have the same problem. It appears when downloading a lot of tickers and it randomly omits datapoints. When running the download several times and filling nan values the number of NaN decreases constantly like this  df0.fillna(df1).fillna(df2) etc..

**Comment by Lisok** [comment]
I also have the same issue. When downloading historical data for one ticker at the time using ticker.history(), everything works fine and no NaN values are present. However, when I try to download data for 2 or more tickers at the time (e.g. yf.download("^OMX ^GSPC" , period = "5y", group_by = "tickers"), I end up with multiple NaN values for both series. I can't seem to find a good fix for this?

**Comment by wesdevpro** [comment]
@rodrigobercini I apologize for my lack of help with this issue as I'm very busy with college. As a quick fix in my web app, I remove any NaN values from the data. I'm not exactly sure which stocks cause this issue, nor do I know of any correlation between these stocks.
