### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by zameerbharwani** [ranaroussi/yfinance#296]
Why is there no data for 2017/01/02? That's a Monday and looks like the markets were open. Thanks!

<img width="1016" alt="Screen Shot 2020-05-07 at 2 05 36 PM" src="https://user-images.githubusercontent.com/9021568/81329001-d48afb80-906b-11ea-98af-86ae7ff5eabf.png">

**Comment by rodrigobercini** [comment]
I think the markets were closed on that day.

[> U.S. stocks on Tuesday started the first trading day of 2017
](https://www.marketwatch.com/story/dow-on-pace-to-open-more-than-100-points-higher-on-2017s-first-trading-day-2017-01-03)
