### ISSUE TITLE
Catching the "No data found for this date range, symbol may be delisted" error

### ISSUE THREAD

**Issue by diggledoot** [ranaroussi/yfinance#298]
How do you catch this error? I can't seem to catch even when surrounding it in try catch block. Anyone else run into this? My code below if you wanna test:

```
tickerdata = yf.Ticker("7086.KL")#not case sensitive

try:
    history = tickerdata.history(start="2019-06-01", end="2020-05-01")
except ValueError as ve:
    print("Error")
```

Thanks for reading.

**Comment by rodrigobercini** [comment]
Hey there!

I'm having issues accessing this data on the yahoo website itself, so it might be an internal error of Yahoo.

https://finance.yahoo.com/quote/7086.KL/history?period1=1584144000&period2=1589414400&interval=1wk&filter=history&frequency=1wk

Are you experiencing this with a different ticker?

**Comment by diggledoot** [comment]
@rodrigobercini It's alright I've fixed the issue. Can be seen [here](https://stackoverflow.com/questions/61690798/exception-handling-with-yahoo-finance)
