### ISSUE TITLE
Getting select info

### ISSUE THREAD

**Issue by MerinoSheep** [ranaroussi/yfinance#303]
Are there alternative commands to info() that allows select .info  or are there parameters to .info that will achieve the same goal, I would like to just get what market a stock is in without getting the entire dictionary that comes from .info

**Comment by alvaroritter** [comment]
As you said, `ticker.info` is a dictionary with `market` being one of the dictionary keys. Therefore `ticker.info["market"]` should do the trick and allow you to extract the market for a given stock.
