### ISSUE TITLE
Adjusting dividends to stock splits is inconsistent

### ISSUE THREAD

**Issue by FrostyTM** [ranaroussi/yfinance#307]
When i pull the historical dividend data for a stock, sometimes the dividends get adjusted sometimes they do not.

Code to reproduce:
```
ticker = 'V'


history = yf.Ticker(ticker).history(auto_adjust=True, start='2014-06-01', end='2015-06-01', back_adjust=False ,interval='1mo')['Dividends']
```

If you run this a few times ( like 10) you will notice that the result is not consistent.

Proof:
http://prntscr.com/shkenz

Any ideas how to fix this?

**Comment by Anth0rx** [comment]
Another problem is that dividends in the Yahoo Finance datasets are sometimes adjusted for stock splits and sometimes not.

**Comment by ValueRaider** [comment]
Does this still happen? I tried to reproduce as you described but couldn't. If still happens, is 1d data always good? A possible fix is also fetching 1d and copying dividends and splits.
