### ISSUE TITLE
Wrong option expiring dates and premium values

### ISSUE THREAD

**Issue by Lusi0** [ranaroussi/yfinance#317]
![uhoh](https://user-images.githubusercontent.com/30559030/83080015-f4da2480-a031-11ea-8b5a-b3c9c4854c6b.png)
inconsistencies with the dates of options expiring and the prices for the premiums between the database on yahoo and the returned values are very widespread

**Comment by kirill77** [comment]
I believe this one-day difference is because of the difference in time zones. One can figure out how to convert the timestamp according to which time-zone you operate in.

**Comment by staythecurse** [comment]
@kirill77 is correct about it being a timezone issue

This is a bug.  The options data from Yahoo! is returned in UTC time but the ticker.py code does not preserve this and instead converts the timestamp to a local datetime.  The code uses "datetime.fromtimestamp(exp)" when it should use "datetime.utcfromtimestamp(exp)".  I have made this change on my local installation and it does correct the issue. 

![image](https://user-images.githubusercontent.com/68197423/89574299-8794fd80-d7f1-11ea-86a8-3f5cbbf246f8.png)


This appears to be the only instance of this function being used
![image](https://user-images.githubusercontent.com/68197423/89574830-62ed5580-d7f2-11ea-8271-346831121fa4.png)

**Comment by ValueRaider** [comment]
If someone submits a pull request, I can merge it in.
