### ISSUE TITLE
Tickers not working

### ISSUE THREAD

**Issue by abacus66** [ranaroussi/yfinance#320]
Hi

I am trying  to pull some price data and I have some Tickers that fail.

For example - RIO.L, RB.L and  TSCO.L work, but BHP.L, ULVR.L, REL.L and VOD.L don't

any idea why?

**Comment by abacus66** [comment]
applied missing instutional holder fix

**Comment by calum-mcg** [comment]
@abacus66 - how did you implement the missing institution holder fix?
