### ISSUE TITLE
Can't get cashflow data back

### ISSUE THREAD

**Issue by acsegroup** [ranaroussi/yfinance#328]
tried to read "cashflow" back but result shows the message below

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

Could anyone help?

Thanks

**Comment by rodrigobercini** [comment]
Hey there!

Which ticker are you trying to query? Could you provide the code you are using?

**Comment by acsegroup** [comment]
> Hey there!
> 
> Which ticker are you trying to query? Could you provide the code you are using?

Hi,
I am using Microsoft(MSFT), please see the code(image) below.

![image](https://user-images.githubusercontent.com/66262395/83678103-19f00980-a5d5-11ea-9815-268fb34180ca.png)

not only the 'cashflow', I can not read the following data neither,

msft.financials
msft.quarterly_financials
msft.balance_sheet
msft.quarterly_balance_sheet
msft.quarterly_cashflow
msft.earnings
msft.quarterly_earnings

not sure what I did wrong, can you have a look if you have time please?

Thanks

**Comment by ekinig** [comment]
Same here.

**Comment by rodrigobercini** [comment]
I'd advise you to use [yahooquery ](https://github.com/dpguthrie/yahooquery ) while yfinance is not functional for fundamentals.

It's not ideal, but it's a temporary solution.

**Comment by dabinglee** [comment]
> I'd advise you to use [yahooquery ](https://github.com/dpguthrie/yahooquery) while yfinance is not functional for fundamentals.
> 
> It's not ideal, but it's a temporary solution.

hey men 
I also encountered the same problem, solved it?

**Comment by dabinglee** [comment]
> I'd advise you to use [yahooquery ](https://github.com/dpguthrie/yahooquery) while yfinance is not functional for fundamentals.
> 
> It's not ideal, but it's a temporary solution.

https://colab.research.google.com/drive/1IHlVeSldVlUUyVKd5MPjY5Zyu1OKnSaz


I installed your git, but I got an error:

  ERROR: Command errored out with exit status 1:
     command:'d:\code\python\stock\venv\scripts\python.exe' -c'import sys, setuptools, tokenize; sys.argv[0] ='"'"'C:\\Users\\ADMINI ~1\\AppData\\Local\\Temp\\pip-req-build-dq7ai65a\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~
1\\AppData\\Local\\Temp\\pip-req-build-dq7ai65a\\setup.py'"'"';f=getattr(tokenize,'"'"'open'"'"', open) (__file__);code=f.read().replace('"'"'\r\n'"'"','"'"'\n'"'"');f.close();exec (compile(code, __file__,'"'"'exec'"'"'))' egg_info
 --egg-base'C:\Users\ADMINI~1\AppData\Local\Temp\pip-pip-egg-info-5jp5rzpp'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-dq7ai65a\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-dq7ai65a\setup.py", line 17, in <module>
        with io.open(path.join(here,'README.rst'), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory:'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-dq7ai65a\\README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I have updated egg_info

**Comment by doomed51** [comment]
Unwittingly created #343 that is a duplication of this. 

does this have anything to do with the Yahoo Finance Premium service? looks like data downloads are behind a paywall not sure if that may be interfering with this...

**Comment by cmskzhan** [comment]
Has anyone managed to merge https://github.com/ranaroussi/yfinance/pull/179 and solved the problem?

**Comment by rodrigobercini** [comment]
> Has anyone managed to merge #179 and solved the problem?

I made similar fixes to #179 and could partially fix the problem.

With this merge, I could fetch financial data such as cashflow, but it returns inconsistent data for non-US tickers.

**Comment by cmskzhan** [comment]
> > Has anyone managed to merge #179 and solved the problem?
> 
> I made similar fixes to #179 and could partially fix the problem.
> 
> With this merge, I could fetch financial data such as cashflow, but it returns inconsistent data for non-US tickers.

I'm using colab to import this package. Will be have the PR merged and released soon?

**Comment by rodrigobercini** [comment]
No, and I don't think it'll be me merged soon.

You can create your own fork, do the changes and install it via pip. Alternatively, feel free to install my fork, I've applied #179 and some other fixes.
pip install git+https://github.com/rodrigobercini/yfinance

Just be aware that this returns inconsistent  data for non-US tickers.
