### ISSUE TITLE
Download ONLY specific field (like High price) for Mass download

### ISSUE THREAD

**Issue by 99coder99** [ranaroussi/yfinance#330]
@ranaroussi 
Thanks for this cool utility.

I was wondering if it will be possible to download only one (or a select no. of fields) using the following:

```
import yfinance as yf
data = yf.download("SPY AAPL", start="2017-01-01", end="2017-04-30",
                   group_by="ticker")
```

The above downloads 6 fields (`Open | High | Low | Close | Adj Close | Volume`) for all the tickers.

What parameter(s) should be added in the above code if I need only download Close or Adj Close or both these fields (and not all six) for the given list of tickers.

Thanks

**Comment by milkywade** [comment]
Hey - did you RTFM. Ran covered this already here: [https://aroussi.com/post/python-yahoo-finance](https://aroussi.com/post/python-yahoo-finance)

**Comment by rodrigobercini** [comment]
> Hey - did you RTFM. Ran covered this already here: https://aroussi.com/post/python-yahoo-finance
> 
> Concretely `data['SPY']['Close']` should just get you the 'close' column for the stock with symbol 'SPY'
> 
> Going forward, you might want to get used to pandas - https://pandas.pydata.org/pandas-docs/stable/index.html

I'm not sure if this solves OP's problem. Especially because @user631 specifies that this issue is related to "mass Download"
`data['SPY']['Close']` will filter the dataframe to the 'Close' column, but all the columns will still be downloaded.

**Comment by milkywade** [comment]
uh, indeed, I'm sorry, download only one field did not make sense to me so wrongly assumed question was on normal usage

**Comment by rodrigobercini** [comment]
@milkywade no worries, I actually had the same idea when I first saw this issue :smile:

As for OP, I think there's no way of downloading just the Close column since the whole dataframe is fetched via a single endpoint request.

**Comment by y3khan** [comment]
Does anyone have a solution to this. Is there a way to download just one field such as the close column

**Comment by ttyo** [comment]
> 
Yes,
Building on [' rodrigobercini commented on 10 Jun 2020'] above, for Cotton Futures, e.g., Close only:
CT_df = ticker.history(period='10y',frequency='1dy')['Close']
CT_df :
Date
2011-12-27     87.910004
2011-12-28     90.680000
2011-12-29     91.629997
2011-12-30     91.800003
2012-01-03     95.800003
                 ...    
2021-12-17    107.300003
2021-12-20    105.540001
2021-12-21    107.269997
2021-12-22    108.830002
2021-12-23    109.120003
Name: Close, Length: 2514, dtype: float64
