### ISSUE TITLE
Current price / close price

### ISSUE THREAD

**Issue by cmcginty** [ranaroussi/yfinance#331]
Is there a quick way just to grab the current price when the market is open and the "close" price when the market is close? Scanning through the API, i only see `bid`,`ask`, `previousClose`, and `history()`, but nothing just combines that data to single field.

**Comment by milkywade** [comment]
yep, not clear to me neither how do we get intraday data vs historic data.

Apparently the functions would seem to be the same but the behaviour would change ?

There is no example that I could find on [the author's page](https://aroussi.com/post/python-yahoo-finance) neither

**Comment by cmcginty** [comment]
Hi, I think I have found the correct solution to this.

The historical close price updates during trading to display the current value.

```
q = yf.Ticker("MSFT")
data_frame = q.history("1d")
price = data_frame["Close"].values[0]
```
