### ISSUE TITLE
Silent mode? yfinance.download()

### ISSUE THREAD

**Issue by lamhoson** [ranaroussi/yfinance#336]
Any silent mode option for .download()?  
Do not echo to console and a bit faster.

**Comment by sonicxml** [comment]
Are you looking for the `progress=False` argument to `yf.download`?

**Comment by lamhoson** [comment]
Yes, thank you very much!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Trevin Gandhi <notifications@github.com>
发送时间: Sunday, June 28, 2020 12:57:15 AM
收件人: ranaroussi/yfinance <yfinance@noreply.github.com>
抄送: Big Horse <hoson@live.hk>; Author <author@noreply.github.com>
主题: Re: [ranaroussi/yfinance] Silent mode? yfinance.download() (#336)


Are you looking for the progress=False argument to yf.download?

―
