### ISSUE TITLE
get cashflow null dataframe

### ISSUE THREAD

**Issue by dabinglee** [ranaroussi/yfinance#338]
I can't get the data
I saw a project compiled by a friend myself, I tried to compile
pip install git+https://github.com/rodrigobercini/yfinance.git
but failed

(venv) D:\windows\soft\git_code\yfinance>pip install git+https://github.com/rodrigobercini/yfinance.git
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/rodrigobercini/yfinance.git
  Cloning https://github.com/rodrigobercini/yfinance.git to c:\users\admini~1\appdata\local\temp\pip-req-build-m23hr4cs
  Running command git clone -q https://github.com/rodrigobercini/yfinance.git 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-m23hr4cs'
    ERROR: Command errored out with exit status 1:
     command: 'd:\code\python\stock\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-
req-build-m23hr4cs\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-m23hr4cs\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"',
 open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ADMINI~1\
AppData\Local\Temp\pip-pip-egg-info-slz7aivr'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-m23hr4cs\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-m23hr4cs\setup.py", line 17, in <module>
        with io.open(path.join(here, 'README.rst'), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-m23hr4cs\\README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Feeling missing files README.rst

help me

**Comment by rodrigobercini** [comment]
hey there!
I've updated my fork, it should be working now. Just be aware that the fork extracts inconsistent data for non-US tickers.

**Comment by dabinglee** [comment]
> hey there!
> I've updated my fork, it should be working now. Just be aware that the fork extracts inconsistent data for non-US tickers.

cool
