### ISSUE TITLE
Empty DataFrame returned

### ISSUE THREAD

**Issue by doomed51** [ranaroussi/yfinance#343]
This was working ~15 days ago but something seems to have changed. 

The calls to financials, balance_sheet and cashflow have started to return empty DataFrames, running very simple code to test, see below: 

>>import yfinance as yf
>>msft = yf.Ticker("MSFT")
>>msft.financials 

Output:

>>Empty DataFrame
>>Columns: [Open, High, Low, Close, Adj Close, Volume]
>>Index: []

i've tried a few different tickers but get the same response. Anyone else having this issue?

**Comment by doomed51** [comment]
this looks to be a duplicate of #328

**Comment by rodrigobercini** [comment]
Hey there, you can try applying the fixes described in this PR #179. 

Just notice that this fix returns inconsistent data for non-US tickers.
