### ISSUE TITLE
Intraday Data

### ISSUE THREAD

**Issue by TancrediCP** [ranaroussi/yfinance#344]
Any interval which is less than a day does not seem to work. Error message is confusing since it states that Ticker may have been delisted which is not the case. This can be easily checked by changing the interval to be more than or equal to a day. 

tickerSymbol = 'AAPL'
tickerData = yf.Ticker(tickerSymbol)
#get the historical prices for this ticker
tickerDf = tickerData.history(period='1d', interval = '60m', start='2019-05-04', end='2019-05-04')

If it is Yahoo which is tightening up documentation should be changed.

**Comment by rodrigobercini** [comment]
There are 3 issues with your code.

1) You should set the period parameter OR start/end, they are overlapping instructions to the API.

2) Your start/end date is set in 2019, intraday data is only available for the past 60d.

3) The end parameter has an "up to but no including" attribute. So, basically your current request is Null.

Find below a working version of your request.

`tickerDf = tickerData.history(interval = '60m', start='2020-05-04', end='2020-05-05')`

![image](https://user-images.githubusercontent.com/18664907/85876091-97a9ce00-b7ab-11ea-8a03-7f2b9a090275.png)

Cheers!
