### ISSUE TITLE
How to find time elapsed in sending the request and receiving response when data is downloaded using yf.download

### ISSUE THREAD

**Issue by 9harshit** [ranaroussi/yfinance#348]

**Comment by rodrigobercini** [comment]
from datetime import datetime
startTime = datetime.now()
`YOUR REQUEST HERE`
print(datetime.now() - startTime)

**Comment by 9harshit** [comment]
> from datetime import datetime
> startTime = datetime.now()
> `YOUR REQUEST HERE`
> print(datetime.now() - startTime)

This does not take HTTP request time in consideration only program related execution time
