### ISSUE TITLE
Errors  when trying to retrieve 'marketCap'

### ISSUE THREAD

**Issue by steve-06** [ranaroussi/yfinance#351]
I've been trying to retrieve 'marketCap' info for a list of stock tickers. After a few I get  a KeyError (as in KeyError: 'regularMarketOpen') for a datafield that is totally irrelevant to what I am trying to retrieve. At other times I get  "IndexError: list index out of range". Is there an error handling setting I am missing or is it something else? Any suggestions?

**Comment by siavashadpey** [comment]
it seems your issue is similar to #353. Take a look at PR #354.

**Comment by emilge** [comment]
@steve-06 were you able to retrieve "marketCap" values ?
