### ISSUE TITLE
Only 7 days worth of 1m granularity data are allowed to be fetched per request.

### ISSUE THREAD

**Issue by cryptid11** [ranaroussi/yfinance#356]
how to get around this fastly? 

my objective is doing this:
data = yf.download("SPY AAPL BLA BLA", start="2020-06-01", end="2020-06-21", interval = "1m", group_by="ticker")

**Comment by rodrigobercini** [comment]
7 days is the Yahoo's limit for 1m granularity

**Comment by cryptid11** [comment]
wrong, it's one month

**Comment by animyrch** [comment]
I think there is confusion with the error message. The error message should rather read as "You can not fetch a period of more than 7 days given 1m granularity data".

Indeed, Yahoo's limit for historical data is 1 month given 1m granularity data. But within that 1 month, each requested period should also be limited to 7 days max.
