### ISSUE TITLE
"QuoteSummaryStore" not found with docker

### ISSUE THREAD

**Issue by thoriuchi0531** [ranaroussi/yfinance#358]
I've been using yfinance in docker environment successfully, however recently running into issue.
This happens when calling `yfinance.Ticker('IDTL.L').info` (or any other non-US tickers) even after applying the fix #179 and #354.
After digging into the issue, it appears the root cause is 

`html = _requests.get(url=url, proxies=proxy).text` in `utils.py`, where `url` is 'https://finance.yahoo.com/quote/IDTL.L'.

There is a check later on to see if `QuoteSummaryStore` exists in `html`, and this never passes in a docker environment. This works fine in a local environment without docker.

Does anyone know if the page source or the behaviour of `url` has changed recently?

Thanks for your help! Let me know if I made obvious mistakes or should post more information. 
Cheers

----
Dockerfile
```
FROM python:3.8.2-slim-buster

WORKDIR /usr/src/app

RUN pip install yfinance lxml

COPY . .

CMD ["python"]
```

**Comment by ValueRaider** [comment]
yfinance doesn't scrape QuoteSummaryStore anymore
