### ISSUE TITLE
stock data not available for companies registered in indian stock exchanges like nse/bse

### ISSUE THREAD

**Issue by aswinme** [ranaroussi/yfinance#362]
tickers is not working for companies registered in nse(national stock exchange)/bse(bombay stock exchange).
eg TCS with yahoo ticker symbol as tcs.ns didn't work. Please make yfinance available for Indian stock market too

**Comment by swankyshahir** [comment]
use TCS.NS or TCS.BO in caps. It works.

**Comment by aswinme** [comment]
> use TCS.NS or TCS.BO in caps. It works.

No swankyshahir ,it didn't work. I used TCS.NS

**Comment by Rambatino** [comment]
It works.
