### ISSUE TITLE
Just a general question

### ISSUE THREAD

**Issue by mesyagut** [ranaroussi/yfinance#367]
Hi guys, I wanted to thank Ran for a great module. But I am just wondering if anyone maintain the codebase and approve pull requests here? The last merge was 6 months ago and there is a few issues ongoing like holdings code failing, etc. Just wondering if this codebase is actively maintained (pull requests are being reviewed and approved on a timely manner) or there is another fork of yfinance that is more actively looked at?

**Comment by rodrigobercini** [comment]
> Hi guys, I wanted to thank Ran for a great module. But I am just wondering if anyone maintain the codebase and approve pull requests here? The last merge was 6 months ago and there is a few issues ongoing like holdings code failing, etc. Just wondering if this codebase is actively maintained (pull requests are being reviewed and approved on a timely manner) or there is another fork of yfinance that is more actively looked at?

Hey there!

I'm not sure what are Ran plans regarding yfinance, but as I noticed that it's currently returning inconsistent data for non-US tickers (as well as other issues such as the holdings code failing), I've switched to [yahooquery](https://github.com/dpguthrie/yahooquery). The syntax is pretty much the same, but it's being actively maintained. 

Cheers!

**Comment by mesyagut** [comment]
Hey Rodrigo, it's an amazing alternative. Thanks.
