### ISSUE TITLE
option_chain result is not a dataframe and does not convert to json

### ISSUE THREAD

**Issue by aspenforest** [ranaroussi/yfinance#368]
```
ticker = yf.Ticker(symbol)
data = ticker.option_chain(date=date)
print(type(data))
```

results:

`<class 'yfinance.ticker.Options'>`

and I can't convert the var data to a json string with to_json() method, cause it's not a pandas dataframe.

How can I serialize the yfinance option_chain table into a string so I could send it over the network?

**Comment by nickdesaulniers** [comment]
It [looks like](https://github.com/ranaroussi/yfinance/blob/476cf81beb55efec78eb0719ce1a42e9fbd9421a/yfinance/ticker.py#L87-L104) `Ticker#option_chain` returns a `named_tuple` of two `DataFrames`.  You can access the two members `calls` and `puts` which are `DataFrames`.

**Comment by nickdesaulniers** [comment]
For example, if you wanted to return BOTH calls and puts as one list, with a new column to differentiate the type of contract, you might do something like:
```python
option_chain = yt.Ticker('GOOG').option_chain('2022-06-16')
puts = option_chain.puts
puts['type'] = 'PUT'
calls = option_chain.calls
calls['types'] = 'CALL'
puts.append(calls).to_json(orient='records')
```
will give you a nice list of objects.

**Comment by aspenforest** [comment]
I ditched yfinance and wrote my own yahoo finance scraper which is way more elegant in implementation and achieves more than the yfinance module. The code is proprietary unfortunately... :D

**Comment by nickdesaulniers** [comment]
Then I guess we'll just have to take you on your word that it's more elegant. ;)

**Comment by aspenforest** [comment]
yfinance is 7 files of 56kb on disk and 1284 lines of code, my lib is two files of 16kb on disk and 449 lines of code AND links into a local uvicorn/fastapi server to serve data to consumer programs.
