### ISSUE TITLE
Recommendation trading and analyst price target

### ISSUE THREAD

**Issue by yoeldk** [ranaroussi/yfinance#369]
Hi @ranaroussi , 

First I'd like to thank you for this great library!

How hard will it be to also add the "recommendation rating" and "analyst price target" for a given stock? Don't mind doing it myself though I might need some guidance.

Thanks!
Yoel

**Comment by alik604** [comment]
I don't have much skill to offer, but I would be willing to assist in adding these two features ( and real-time pricing like [how this guy did](https://github.com/condereis/realtime-stock))

**Comment by kaahanmotwani** [comment]
I am also interested in this functionality! Let me know if the Yahoo API provides this information
