### ISSUE TITLE
yahoo provides botched data for scraping?

### ISSUE THREAD

**Issue by kirill77** [ranaroussi/yfinance#370]
I am looking at quarterly operating income for FDX (Fedex). The yfinance scrapes the numbers from URL: "https://finance.yahoo.com/quote/FDX/financials". If you look at page source of that URL, it contains something like "operatingIncome":{ "raw":218000000, "fmt":"218M","longFmt":"218,000,000"}, which is what yfinance scrapes and returns. However, when you look at the web page in browser, the number shown by javascript of that page (in browser) has nothing to do with that. On the other hand, "totalRevenue" numbers in page source and in java-formed version do match.

Could Yahoo be presenting botched data for scraping intentionally?
![jsonVersion](https://user-images.githubusercontent.com/10299672/86520547-8475ae80-bdfa-11ea-8075-5efa23c69db1.jpg)
![javaVersion](https://user-images.githubusercontent.com/10299672/86520548-8d668000-bdfa-11ea-93c6-e54b60d73674.jpg)

**Comment by beglitis** [comment]
Hey, did you reach a conclusion?

**Comment by kirillNVIDIA** [comment]
No, I haven't figured it out.

**Comment by kirill77** [comment]
No, I haven't figured it out

**Comment by ValueRaider** [comment]
Try new version 0.2. `yfinance` was scraping the wrong table, but now matches website.
