### ISSUE TITLE
When Retrieving One Ticker Download ignores group_by Flag

### ISSUE THREAD

**Issue by kkemmler** [ranaroussi/yfinance#372]
Using data = yf.download(symbols, start=startTime, end=endTime, group_by="ticker")

A call where there is only one symbol in symbols string does not return data grouped by ticker. Returns all dates, but cannot retrieve data using symbol.

**Comment by cammclean182** [comment]
if it helps you can add the ticker to the columns /multiindex manually

where tickers = ['SPY'] and the dataframe is called yfinance_data i added the following line to my code:

`yfinance_data.columns = pd.MultiIndex.from_product([[str(tickers[0])], yfinance_data.columns])`

**Comment by kkemmler** [comment]
Thank you, and I did something similar by checking for len ==1 and in that case not retrieving close data with ticker. Wrote this bug not sure if the return is as expected or not.

A fantastic module yfinance is!
