### ISSUE TITLE
API Freezing after ~100 calls in an hour

### ISSUE THREAD

**Issue by AaronShabanian** [ranaroussi/yfinance#377]
Hi there, I'm soley using this API to receive live quotes of certain stocks. After a couple quotes the API freezes for around 10 minutes then displays an error

**Comment by ukoshti** [comment]
I am having the same problem and it seems to me that this is a new issue as it was working fine up until yesterday.

**Comment by milkywade** [comment]
have you tried to throttle ? Anyway, I've tried north of 500 in 1h, 1x/day, reliably, for weeks so maybe it's an issue in your network or with your internet provider

**Comment by ArthurYdalgo** [comment]
That's odd... I did a stress test and I was able to do a 1000 calls in a row. No freezing whatsoever.
