### ISSUE TITLE
Not able to retrieve 1m data beyond 30 days in NSE

### ISSUE THREAD

**Issue by hrudhai98** [ranaroussi/yfinance#383]
I am trying to get 1 minute data for NSE stocks for the last 35 days but it does not let me request for data beyond 30 days

**Comment by harshitrathod** [comment]
How you are getting data can you post your code here and output also

**Comment by hrudhai98** [comment]
Hey, so this is my code

import yfinance as yf
df9 = yf.download("ADANIPORTS.NS", interval="1m", start="2020-06-10", end="2020-06-12")

and this is the output

1 Failed download:
- ADANIPORTS.NS: 1m data not available for startTime=1591727400 and endTime=1591900200. The requested range must be within the last 30 days.

This data was requested on 16th July 2020
