### ISSUE TITLE
Error Cloning On Win10

### ISSUE THREAD

**Issue by lispeedyg** [ranaroussi/yfinance#387]
Hi,
I've been trying to try your solution on VS 2017.  However, I'm having issues cloning the Repo.  It continually errors with an error:
![image](https://user-images.githubusercontent.com/8366831/87808252-60b55e00-c827-11ea-95e6-3edbb378941a.png)

I'm fairly new at cloning Repo's.  So, sorry if this has already been addressed.  Please let me know if there's something I can do differently to get this working.

Thanks,
Gus

**Comment by lispeedyg** [comment]
Does anyone have any suggestion(s)?

**Comment by PShah4916** [comment]
same issue my cdisk isnt full and my file path for the clone is on a :C folder
