### ISSUE TITLE
Pre-Market data

### ISSUE THREAD

**Issue by Will695** [ranaroussi/yfinance#390]
Hi,

Is there a way to download pre-market data?

**Comment by acurvers** [comment]
i have the same question

**Comment by andre-ac** [comment]
Same question here. @Will695 @acurvers did you find a way? I would only need live pre-market data, not historical

**Comment by Will695** [comment]
@andre-ac Yeah, i use alpaca.markets api to stream

**Comment by Will695** [comment]
Yeah I found a way use alpaca.markets it's live premarket data
