### ISSUE TITLE
Price data to 13 decimal places

### ISSUE THREAD

**Issue by Gr8IDa** [ranaroussi/yfinance#391]
When downloading price history, I find that the data goes out to 13 decimal places.  When I manually download a .csv from Yahoo! Finance, it only goes out to 6.  Are the extra decimal places accurate, necessary, and appropriate?  Yes, I could just round off the data, but before doing so, I'd like to know if there is a guiding principle behind this so I can treat the issue appropriately.

**Comment by Bruno-Hanzen** [comment]
Those decimal places are useful for back-ajusting ("mimicking" the true historical prices).
You can use the "rounding" option if you want less digits.

**Comment by mesyagut** [comment]
> Those decimal places are useful for back-ajusting ("mimicking" the true historical prices).
> You can use the "rounding" option if you want less digits.

Hi Bruno-Hanzen, can you elaborate more? If we are talking stocks, what does this actually mean the price precision below 1 cent?

**Comment by mesyagut** [comment]
Just more on this. I know some of the prices on Yahoo Finance are shown with below 1 cent precision. But if you go to a broker, can you actually execute for that price? My understanding is the broker will quote the price to 1 cent precision.

**Comment by Gr8IDa** [comment]
Thank you for your replies.  I'd like to share a little more since I originally posted this question.

First, I believe the lengthy decimal places are useful for large trades settling at multiple prices.  For example, if I sold 5 million shares of a stock, some of those shares would settle at $x and some would settle at $x.01, some at $x.02 and so on.  If you then take the average price across the 5mm shares, it could feasibly be a blended price that carries out beyond the penny.

Second, in manually calculating the adjusted prices, I am finding differences between the file provided from the Yahoo! download and my calculation.  Yahoo! provides details on how they calculate the adjusted close, which makes it easy to do it yourself.  I recently took the July dividend on DIA and calculated the adjusted share price as of 6/22/06 to check it.  You need the adjusted prices before and after the July dividend to do this, which I had in my files.  Here's a summary
a. The 6/22/06 Adjusted share price as of 7/17/20 = 78.6245956420898
b. The 6/22/06 adjusted close as of 7/29 = 78.5625839233398
c. DIA div on 7/17/20 = 0.211
d. Closing price on 7/16/20 = 267.470001220703
e. Adjustment factor = (1-(Dividend / Prior day close)) = 1-(c /d) = 0.999211126485075
f. Calculated 6/22/06 adjusted close =  Prior adjusted close x Adjustment factor =  a x e = 78.5625707809661

Unfortunately, f does not equal b, which causes subsequent downloads of historical adjusted returns to yield different 1-day return histories causing a model to be unstable.

**Comment by Bruno-Hanzen** [comment]
For example, according to yahoo historical prices, MSFT first close prices (in March 1986) were 0.06, 0.06, 0.07, 0.06. The real prices were  28, 29, 29.5, 28.75.
You need more than 2 digits after the decimal point to reconstruct those prices.
