### ISSUE TITLE
regularMarketOpen and regularMarketPrice returning same number for ticker ^GSPC

### ISSUE THREAD

**Issue by lpmbgithub** [ranaroussi/yfinance#394]
Hi - was using yfinance to pull pricing for the S&P500 Index (^GSPC).

I've noticed that two fields that I would expect to differ significantly are actually the same:  

'regularMarketOpen': 3218.58
'regularMarketPrice': 3218.58

There's no way that's the case - the current price of the index on the Yahoo Finance website itself is 3,215.63 - is there an issue with scraping the website?

```
    spx = yf.Ticker('^GSPC')
    print(spx.info)
```

{'previousClose': 3235.66, '**regularMarketOpen': 3218.58**, 'twoHundredDayAverage': 3012.6265, 'trailingAnnualDividendYield': None, 'payoutRatio': None, 'volume24Hr': None, 'regularMarketDayHigh': 3227.26, 'navPrice': None, 'averageDailyVolume10Day': 4198066250, 'totalAssets': None, 'regularMarketPreviousClose': 3235.66, 'fiftyDayAverage': 3150.4216, 'trailingAnnualDividendRate': None, 'open': 3218.58, 'toCurrency': None, 'averageVolume10days': 4198066250, 'expireDate': None, 'yield': None, 'algorithm': None, 'dividendRate': None, 'exDividendDate': None, 'beta': None, 'circulatingSupply': None, 'startDate': None, 'regularMarketDayLow': 3200.05, 'priceHint': 2, 'currency': 'USD', 'regularMarketVolume': 2460013758, 'lastMarket': None, 'maxSupply': None, 'openInterest': None, 'marketCap': None, 'volumeAllCurrencies': None, 'strikePrice': None, 'averageVolume': 5349383333, 'priceToSalesTrailing12Months': None, 'dayLow': 3200.05, 'ask': 3253.51, 'ytdReturn': None, 'askSize': 0, 'volume': 2460013758, 'fiftyTwoWeekHigh': 3393.52, 'forwardPE': None, 'maxAge': 1, 'fromCurrency': None, 'fiveYearAvgDividendYield': None, 'fiftyTwoWeekLow': 2191.86, 'bid': 3177.74, 'tradeable': False, 'dividendYield': None, 'bidSize': 0, 'dayHigh': 3227.26, 'exchange': 'SNP', 'shortName': 'S&P 500', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EDT', 'isEsgPopulated': False, 'gmtOffSetMilliseconds': '-14400000', 'quoteType': 'INDEX', 'symbol': '^GSPC', 'messageBoardId': 'finmb_INDEXGSPC', 'market': 'us_market', '**regularMarketPrice': 3218.58**, 'logo_url': ''}

**Comment by DrTonyC** [comment]
I've observed a similar problem.  I've been unable to retrieve accurate data for the following INDEX quotes
that I've tried:
^DJI  'shortName': 'Dow Jones Industrial Average'
^IXIC  'shortName': 'NASDAQ Composite'
^GSPC  'shortName': 'S&P 500'
If this is an acknowledged issue, can a fix be expected?

**Comment by lpmbgithub** [comment]
Additionally, there's an issue with the data itself in terms or retrieving the current price:

Here are my results for ES=F again - I took a screenshot of the price from the yahoo site directly (https://au.finance.yahoo.com/quote/ES%3DF/history?p=ES%3DF) of **3225.50** and this value is not found in the result set so EITHER we are not retrieving this field period OR we are not retrieving it correctly.

Would love to offer to help.

{'previousClose': 3252.5, 'regularMarketOpen': 3256.75, 'twoHundredDayAverage': 3008.635, 'trailingAnnualDividendYield': None, 'payoutRatio': None, 'volume24Hr': None, 'regularMarketDayHigh': 3257, 'navPrice': None, 'averageDailyVolume10Day': 416584545, 'totalAssets': None, 'regularMarketPreviousClose': 3252.5, 'fiftyDayAverage': 3141.0813, 'trailingAnnualDividendRate': None, 'open': 3256.75, 'toCurrency': None, 'averageVolume10days': 416584545, 'expireDate': 1600387200, 'yield': None, 'algorithm': None, 'dividendRate': None, 'exDividendDate': None, 'beta': None, 'circulatingSupply': None, 'startDate': None, 'regularMarketDayLow': 3223.25, 'priceHint': 2, 'currency': 'USD', 'regularMarketVolume': 123245, 'lastMarket': None, 'maxSupply': None, 'openInterest': 2622246, 'marketCap': None, 'volumeAllCurrencies': None, 'strikePrice': None, 'averageVolume': 183864157, 'priceToSalesTrailing12Months': None, 'dayLow': 3223.25, 'ask': 3223.75, 'ytdReturn': None, 'askSize': 0, 'volume': 123245, 'fiftyTwoWeekHigh': 3397.5, 'forwardPE': None, 'maxAge': 1, 'fromCurrency': None, 'fiveYearAvgDividendYield': None, 'fiftyTwoWeekLow': 2174, 'bid': 3223.5, 'tradeable': False, 'dividendYield': None, 'bidSize': 0, 'dayHigh': 3257, 'exchange': 'CME', 'shortName': 'E-Mini S&P 500 Sep 20', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EDT', 'isEsgPopulated': False, 'gmtOffSetMilliseconds': '-14400000', 'underlyingSymbol': 'ESU20.CME', 'quoteType': 'FUTURE', 'symbol': 'ES=F', 'underlyingExchangeSymbol': 'ESU20.CME', 'headSymbol': 'ES=F', 'market': 'us24_market', 'regularMarketPrice': 3256.75, 'logo_url': ''}
