### ISSUE TITLE
AttributeError: 'Tickers' object has no attribute 'msft'

### ISSUE THREAD

**Issue by GrainsofSalt** [ranaroussi/yfinance#407]
This code snippet yields respective error:

Code:
`tickers = yf.Tickers('msft aapl goog')

tickers.msft.info
tickers.aapl.history(period="1mo")
tickers.goog.actions`

Error:
AttributeError: 'Tickers' object has no attribute 'msft'

Not sure why this is happening as I am copy and pasting right off  the main web page.

**Comment by trenton3983** [comment]
- I'm pretty sure it's a typo.
- `tickers` is the variable holder the data for each ticker
- The README is missing the the correct method call, which is also `tickers`
- Additional, the ticker symbols data is accessed with uppercase letters as shown in the code.

## This code works

```python
import yfinance as yf

tickers = yf.Tickers('msft aapl goog')
print(tickers.tickers.MSFT.info)
print(tickers.tickers.AAPL.history(period="1mo"))
print(tickers.tickers.GOOG.actions)
```

**Comment by GrainsofSalt** [comment]
This worked! Thank you

**Comment by Anselmoo** [comment]
> * I'm pretty sure it's a typo.
> * `tickers` is the variable holding the data for each ticker
> * The README is missing the correct method call, which is also `tickers`
> * Additional, the ticker symbols data is accessed with uppercase letters as shown in the code.
> * TAB completion at the `.` will show the correct available methods
> 
> ## This code works
> ```python
> import yfinance as yf
> 
> tickers = yf.Tickers('msft aapl goog')
> print(tickers.tickers.MSFT.info)
> print(tickers.tickers.AAPL.history(period="1mo"))
> print(tickers.tickers.GOOG.actions)
> ```

@trenton3983 thx for the comment, but how to deal with tickers wich have special characters like *Crude Oil* => `CL=F` or `MHT.F` this cannot be resigned to a class attribute?
