### ISSUE TITLE
Moscow market

### ISSUE THREAD

**Issue by sepy97** [ranaroussi/yfinance#412]
Hi! thanks for the lib, its great! Can't get data from Moscow market (e.g. MOEX.ME, ROSN.ME) though :( 
installed the library through pip, those tickers are presented on yahoo finance website...

> line 286, in _get_fundamentals
>     self._institutional_holders = holders[1]
> IndexError: list index out of range

Thank you in advance

**Comment by pieterjandotpy** [comment]
It has nothing to do with the markets in Moscow, see my fix here: #416
