### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by jonathanli2012** [ranaroussi/yfinance#416]
`tick1 = yf.Ticker("ABC")
print(tick1.info)`

`    print(tick.info)
  File "/home/jon/.local/lib/python3.8/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/home/jon/.local/lib/python3.8/site-packages/yfinance/base.py", line 415, in get_info
    self._get_fundamentals(proxy)
  File "/home/jon/.local/lib/python3.8/site-packages/yfinance/base.py", line 286, in _get_fundamentals
    self._institutional_holders = holders[1]
IndexError: list index out of range`

**Comment by pieterjandotpy** [comment]
I had the same issue and was able to fix this by inserting an if statement like this at line 286:

        if len(holders) > 1:
            self._institutional_holders = holders[1]
            if 'Date Reported' in self._institutional_holders:
                self._institutional_holders['Date Reported'] = _pd.to_datetime(
                    self._institutional_holders['Date Reported'])
            if '% Out' in self._institutional_holders:
                self._institutional_holders['% Out'] = self._institutional_holders[
                    '% Out'].str.replace('%', '').astype(float)/100

**Comment by davidchisnall** [comment]
I can confirm the above fix works. Without this, some high profile things can’t be accessed (e.g. BRK-B). Is it possible to have a new release with this fix soon?
