### ISSUE TITLE
Financials information and more attributes are empty

### ISSUE THREAD

**Issue by segelmache** [ranaroussi/yfinance#419]
Today, when requesting the stock financials from Apple 'APPL', I got an empty dataframe :-/

**Comment by pieterjandotpy** [comment]
The ticker of Apple is 'AAPL', that should work.

**Comment by segelmache** [comment]
Hey @pieterjandotpy,
thanks for your reply - i made a typo in my post above, sorry :) My code is:

```
>> import yfinance as yf
>> AAPL = yf.Ticker("AAPL")
>> print(AAPL.financials)
```
and I get an empty dataframe:
```
None
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []
```

Same output - btw - when trying to get the balance sheet:
```
>> print(AAPL.balance_sheet)
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []
```

The Issue also occurs with other Ticker symbols.

**Comment by pieterjandotpy** [comment]
Apparently this issue was encountered before but doesn't not seemed to be solved :( See issue #386

**Comment by derary66** [comment]
How is the progress of this issue? I met this issue these days as well:-(
I tried other tickers, same result, empty data frame returned, with wrong field names.
Does any of previous versions work without this issue?

**Comment by pieterjandotpy** [comment]
Actually, parameters like Open, High, Low, Close and Volume can all be retrieved by using `.info` with the correct key:

```
import yfinance as yf
AAPL = yf.Ticker("AAPL")

open = AAPL.info['open']
close = AAPL.info['previousClose']
volume = AAPL.info['volume']
```

**Comment by silver8ack** [comment]
> Actually, parameters like Open, High, Low, Close and Volume can all be retrieved by using `.info` with the correct key:
> 
> ```
> import yfinance as yf
> AAPL = yf.Ticker("AAPL")
> 
> open = AAPL.info['open']
> close = AAPL.info['previousClose']
> volume = AAPL.info['volume']
> ```

That's not at all what the OP is looking for.  None of the financial data methods work... earnings, financials...

**Comment by pieterjandotpy** [comment]
> That's not at all what the OP is looking for. None of the financial data methods work... earnings, financials...

It's exactly the data the OP is asking for. If you want a table with those values for more points in time, just use:
```
import yfinance as yf
AAPL = yf.Ticker("AAPL")
data = AAPL.history('1y', '1d')
```
@silver8ack This is a free API, you can't expect everything to work 100%. If you have any constructive, useful feedback, let us know.

**Comment by segelmache** [comment]
Hi people,
i actually was hoping to get the hole balancesheet, cashflow and income statement information with this API. However, it doesn't seem to work, so I wrote some functions to get that infos. Plz feel free to use them. PS: some of the variable names are still in german, so don't wonder ;-)

```
import pandas as pd
import requests
from bs4 import BeautifulSoup

    def get_financials(url):   
        page_source = requests.get(url)
    
        soup_html = BeautifulSoup(page_source.text, 'html.parser')
        tabelle_soup = soup_html.find('div', class_="M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)")
        
        # Get Title Row
        überschriften = tabelle_soup.find('div', class_="D(tbr) C($primaryColor)")
        überschriften = überschriften.findAll('span')
        title_row = list()
        for ü in überschriften:
            title_row.append(ü.text)
        
        tabelle = pd.DataFrame(None, columns = title_row)
        restliche_zeilen = tabelle_soup.findAll('div', class_="D(tbr) fi-row Bgc($hoverBgColor):h")
        for zeile in restliche_zeilen:
            spalten = zeile.findChildren('div',recursive=False)
            zeilenwerte = list()
            for spalte in spalten:
                zeilenwerte.append(spalte.text)
            tabelle.loc[len(tabelle)] = zeilenwerte
        tabelle = tabelle.set_index(title_row[0])
        return tabelle.T

    def get_income_statement(symbol):
        url = 'https://finance.yahoo.com/quote/' + symbol + '/financials'
        return get_financials(url)
    
    def get_balance_sheet(symbol):
        url = 'https://finance.yahoo.com/quote/' + symbol + '/balance-sheet'
        return get_financials(url)        
    
    def get_cashflow(symbol):
        url = 'https://finance.yahoo.com/quote/' + symbol + '/cash-flow'
        return get_financials(url)                 
    
    symbol  = 'MSFT'
    #Functions return dataframe
    income_statement = get_income_statement(symbol)
    balance_sheet = get_balance_sheet(symbol)
    cash_flow = get_cashflow(symbol)
```

**Comment by leonchen417** [comment]
Check out issue 191, there is a fix in base.py line 283
https://github.com/ranaroussi/yfinance/issues/191
:)

**Comment by cesar-moya** [comment]
#191 Fixed my issue. thanks!

**Comment by ThePlugJumbo** [comment]
> Hi people,
> i actually was hoping to get the whole balancesheet, cashflow and income statement information with this API. However, it doesn't seem to work, so I wrote some functions to get that infos. Plz feel free to use them. PS: some of the variable names are still in german, so don't wonder ;-)
> 
> ```
> import pandas as pd
> import requests
> from bs4 import BeautifulSoup
> 
>     def get_financials(url):   
>         page_source = requests.get(url)
>     
>         soup_html = BeautifulSoup(page_source.text, 'html.parser')
>         tabelle_soup = soup_html.find('div', class_="M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)")
>         
>         # Get Title Row
>         überschriften = tabelle_soup.find('div', class_="D(tbr) C($primaryColor)")
>         überschriften = überschriften.findAll('span')
>         title_row = list()
>         for ü in überschriften:
>             title_row.append(ü.text)
>         
>         tabelle = pd.DataFrame(None, columns = title_row)
>         restliche_zeilen = tabelle_soup.findAll('div', class_="D(tbr) fi-row Bgc($hoverBgColor):h")
>         for zeile in restliche_zeilen:
>             spalten = zeile.findChildren('div',recursive=False)
>             zeilenwerte = list()
>             for spalte in spalten:
>                 zeilenwerte.append(spalte.text)
>             tabelle.loc[len(tabelle)] = zeilenwerte
>         tabelle = tabelle.set_index(title_row[0])
>         return tabelle.T
> 
>     def get_income_statement(symbol):
>         url = 'https://finance.yahoo.com/quote/' + symbol + '/financials'
>         return get_financials(url)
>     
>     def get_balance_sheet(symbol):
>         url = 'https://finance.yahoo.com/quote/' + symbol + '/balance-sheet'
>         return get_financials(url)        
>     
>     def get_cashflow(symbol):
>         url = 'https://finance.yahoo.com/quote/' + symbol + '/cash-flow'
>         return get_financials(url)                 
>     
>     symbol  = 'MSFT'
>     #Functions return dataframe
>     income_statement = get_income_statement(symbol)
>     balance_sheet = get_balance_sheet(symbol)
>     cash_flow = get_cashflow(symbol)
> ```

This is the best solution I have found for free balance sheet data thank you so much mein guter Freund!
