### ISSUE TITLE
Data fetched from api does not match website's data

### ISSUE THREAD

**Issue by matbarc** [ranaroussi/yfinance#420]
The closing price for February for the following symbols: CZZ, CSAN3.SA, BBD, BBDO, BBDC3.SA, BBDC4.SA, GGB, GGBR4.SA, GGBR3.SA seems to be slightly off when fetched from the api as opposed to the one's displayed on the website.

**Comment by beglitis** [comment]
Hi, can you actually paste some numerical examples? Did you try to debug through the code to see why is that the case?
