### ISSUE TITLE
Retrieve more ETF data

### ISSUE THREAD

**Issue by pieterjandotpy** [ranaroussi/yfinance#422]
I would like to retrieve more data from ETFs, in specific the **sector weightings (%)** of a specific ETF, found in the tab **Holdings** on the Yahoo website: https://finance.yahoo.com/quote/IWDA.AS/holdings?p=IWDA.AS

Is this possible in the current API?
If not, does someone know how I could add this to the API? I'm guessing it would be in `base.py`, but I'm not sure where. All help is welcome!

**Comment by yoshrubin** [comment]
yea would be cool to get more info regarding ETFs regarding the holdings etc...

**Comment by idanre1** [comment]
upvote this issue
