### ISSUE TITLE
New issues on retrieving financial statement data

### ISSUE THREAD

**Issue by derary66** [ranaroussi/yfinance#423]
I tries to use the following codes to retrieve the financial statement data of Apple stock. Issue: it returns empty data with wrong data frame structure!

import yfinance as yf
aapl = yf.Ticker("AAPL")
aapl.financials

Returns are as follows:
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

I also tried the following codes, results are the same:-(
aapl.quarterly_financials
aapl.balance_sheet
aapl.cashflow
aapl.earnings

Notes: the other functions of yfinance still work well in my computer!

Dear Ran, can you kindly help? Many thanks!

**Comment by derary66** [comment]
Can any one help on this? Or any other alternative solutions to retrieve the financial statements of stocks from Yahoo Finance? I am eager to use this function for a quick demo. Thanks!

**Comment by cesar-moya** [comment]
It used to be working fine up to a few months ago, today I checked and indeed most dataframes are coming empty except for the ticker. please help!

**Comment by cesar-moya** [comment]
Look at https://github.com/ranaroussi/yfinance/issues/191. I did this and it fixed the issue.
