### ISSUE TITLE
Minute data end at 3:59 p.m.

### ISSUE THREAD

**Issue by nectario** [ranaroussi/yfinance#427]
When I query historical minute data, the closing time for the day is 3:59 p.m. Why isn't 4:00 p.m. included? I need the data to be from 9:30 a.m. - 4:00 p.m. inclusive.

**Comment by andr3w321** [comment]
Regular trading hours end at 3:59:59pm. No regular trading data takes place during the 4:00pm minute. The 3:59pm minute close is the close for the day.
