### ISSUE TITLE
Bulk download bug

### ISSUE THREAD

**Issue by StuartMesham** [ranaroussi/yfinance#433]
I cannot bulk download tickers with . in the name. Steps to reproduce the problem are below:

`import yfinance as yf`

Running:
`yf.Ticker('STX40.JO').history(period="1mo", interval='1d')`

Works fine, whereas running:

`yf.Tickers(['IEV', 'SPY', 'STX40.JO']).history(period="1mo", interval='1d')`

Results in:

`AttributeError: 'Tickers' object has no attribute 'STX40.JO'`

I have stepped through the code with the debugger and the data is being successfully downloaded and parsed, but I suspect the issue is due to python attributes not being able to have . in their names. I did try using `'STX40-JO'` for the ticker name, but this results in the error `STX40-JO: No data found, symbol may be delisted`

The same is true for exchange rates, for example the ticker `'USDEUR=X'` has the same behaviour as above.

**Comment by k51iswhereiam** [comment]
Cool
