### ISSUE TITLE
small suggestion

### ISSUE THREAD

**Issue by YairMZ** [ranaroussi/yfinance#436]
I added the following code snippet to the Tickers class definition:

```
    def __iter__(self):
        self.n_iter = 0
        return self

    def __next__(self):
        if self.n_iter < len(self.symbols):
            self.n_iter += 1
            return getattr(self.tickers, self.symbols[self.n_iter-1])
        else:
            raise StopIteration

```

This allows iterating over the Tickers such as:

```
tickers_list = yf.Tickers(['DE', 'KEYS'])
    for ticker in tickers_list:
        print(ticker.info)
```

Sadly I don't know how to formally suggest this change. Could you guide me as to what is the formal way?
Alternatively, Could you perhaps add it yourself?

**Comment by ValueRaider** [comment]
1. Fork this project
2. Implement in your fork, ideally in a branch
3. Create a new [Pull Request](https://github.com/ranaroussi/yfinance/pulls), from your fork to here
