### ISSUE TITLE
setting multiple tickers does not work

### ISSUE THREAD

**Issue by ThomasBurgess2000** [ranaroussi/yfinance#440]
Here is my code:

```
import yfinance as yf

tickers = yf.Tickers("msft qqq dis spy amd googl lmt ko vti spief")
print(tickers)
print(type(tickers))

print(tickers.MSFT.info)
print(tickers.MSFT.info["ask"])
print(tickers.MSFT.info['bid'])
```

And here's the output:

```
yfinance.Tickers object <MSFT,QQQ,DIS,SPY,AMD,GOOGL,LMT,KO,VTI,SPIEF>
<class 'yfinance.tickers.Tickers'>
Traceback (most recent call last):
  File "C:\Users\thoma\Desktop\Plain Text\Ledger\yahoofinance.py", line 7, in <module>
    print(tickers.MSFT.info)
AttributeError: 'Tickers' object has no attribute 'MSFT'
```

It does this whether I capitalize MSFT or not.

**Comment by Rmcortez12** [comment]
I was actually just looking at this myself. with a set up similar to yours @ThomasBurgess2000 
it looks like tickers is actually a list. If you do something like this it should work. 
`tickers.tickers.MSFT.get_info()`

**Comment by ThomasBurgess2000** [comment]
> 
> 
> I was actually just looking at this myself. with a set up similar to yours @ThomasBurgess2000
> it looks like tickers is actually an object for tickers. If you do something like this it should work.
> `tickers.tickers.MSFT.get_info()`
> this will give you the ticker at the corresponding index -> `tickers.symbols[0]`

This works! This doesn't seem to be the way it's supposed to be, but it'll work for now.

**Comment by ThomasBurgess2000** [comment]
I ended up doing this so I wouldn't have to rewrite everything: 

```
tickers_fake = yf.Tickers("msft qqq dis spy amd googl lmt ko vti spief")
tickers = tickers_fake.tickers

print(tickers.MSFT.info)
```
This will also make it easy to change once it is fixed in the library.

**Comment by Rambatino** [comment]
Or just 
``` python
tickers = yf.Tickers("msft qqq dis spy amd googl lmt ko vti spief").tickers
```

**Comment by ThomasBurgess2000** [comment]
And then if you want the ticker of each tickers it's:

```
tickers = yf.Tickers(list_of_equities).tickers

for ticker in tickers:
    print (ticker.ticker)
```

This library man...

**Comment by Rambatino** [comment]
It's quite frustrating in it's design, as non-US tickers with a period in them obviously can't be used in a named tuple and it just breaks.

**Comment by niekh06** [comment]
Is there a solution to the issue stated by Rambatino regarding non-US tickers? I have a list of non-US tickers al ending with '.AS' which I can enter into the multiple tickers object (type 'tickers.Tickers'). However, due the ticker names I can't call on them...

**Comment by ValueRaider** [comment]
`tickers.tickers["MSFT"]` etc
