### ISSUE TITLE
Abandoned by the author?

### ISSUE THREAD

**Issue by beglitis** [ranaroussi/yfinance#443]
Hi everyone, clearly this module is very useful to lots of people who would like to get stock data but as individuals cannot afford the prices of the mainstream data providers. It seems to me that this module has been abandoned by the author and therefore 

a) there is no fixes merged in the main branch
b) people tend to fix the same issue over and over as they come across it (the holders issue for example)
c) there is no code consistency across fixes or any code refactoring to make the code more streamlined and bullet proof

Should there be some sort of a plan to resurrect this module or maybe fork it and actively maintain the fork?

Kind regards,

Nick

**Comment by blunderedbishop** [comment]
If anyone wants to take the lead I'll definitely follow along as an active contributor.

**Comment by dpuljic01** [comment]
Count me in too.  I'm waiting for that holders fix to be merged for awhile, let's get it going :)

**Comment by cbleuler** [comment]
Does the license allow for a fork which is maintained by someone else without the authors approval?

**Comment by bradmetz** [comment]
I was going to try and contact the original author to see about transferring responsibility.  If we can find a way to keep the project active, @admirallenny and I are willing to train maintaining it.

**Comment by blunderedbishop** [comment]
> 
> 
> Does the license allow for a fork which is maintained by someone else without the authors approval?

It does. It still would be nice to ask him though

**Comment by beglitis** [comment]
I sent a message to Ran via LinkedIn, will let you guys know when I hear back.

**Comment by bradmetz** [comment]
@beglitis that's awesome!  Let us know if you get a response and I will hold off pinging him a second time.

**Comment by bradmetz** [comment]
@beglitis did you get a response from the original author?

**Comment by beglitis** [comment]
@bradmetz Nothing yet I'm afraid

**Comment by beglitis** [comment]
Still nothing, ok the guy might be on holiday, not checking his LinkedIn profile etc. We could in theory fork this project anyway and then if Ran gets back to us we can either merge things to this project or come up with some other solution? I think Ran is probably focusing more on his commercial projects if I understand his profiles in social media correctly.

**Comment by dpuljic01** [comment]
Looks like you @beglitis already have some fork with good changes on your profile. I like it. I'll get involved as soon as I finish my masters thesis, in about 2 weeks :)

**Comment by beglitis** [comment]
@dpuljic01 good luck with your thesis, what is it on?

**Comment by dpuljic01** [comment]
Thank you. It's a full stack web app called financial dashboard. It shows general info about market and quotes and allow users to create their portfolio, add holdings and get some stats/graphs about their portfolio. It's not yet 100% done but I would appreciate if you would take a look at it and provide me some feedback as I will continue to work on this after I graduate  🙏
Here is the repo with a live demo in a README: https://github.com/dpuljic01/financial-dashboard 
It was first written in `Flask (Dash)`, but I switched to `Flask/Vue.js`. The main challenge was to get all this info and to have stable deployment with using only free resources / tools (This is where `yfinance` helped a lot).

**Comment by elamey** [comment]
Thank you all for considering doing this. It is very much appreciated! When/if you decide to fork, could you please post the name/path of the newly supported fork? Thank you very much!

**Comment by bradmetz** [comment]
Hey @beglitis , if your plan still to take on a maintained fork of this project?  If so, cool i will follow along.  However, if you can't, me and @admirallenny's offer to run a maintained fork is still on the table.  I just want to make sure you have first crack since you started the thread :)

**Comment by ranaroussi** [comment]
Hi @beglitis @bradmetz and @admirallenny - I would love to add you as maintainers to this project as I can't seem to find a lot of time recently.

LMK if you're interested!

**Comment by beglitis** [comment]
@ranaroussi Hi Ran, thank you for replying, glad is all good. It would be great to keep things going without forking so since @bradmetz and @admirallenny have kindly volunteered it would work quite well if you were to add them as maintainers. I am not sure if I will have enough time myself to commit to the project but as always I am happy to send review requests etc

**Comment by ranaroussi** [comment]
All three of you are now maintainers. I'll re-join when I have more time. THANKS!!

**Comment by bradmetz** [comment]
@ranaroussi Thats awesome thanks!  

I will start going through the back log of PRs.  At a quick glance there appears to be a fair bit of duplicate PRs and issues so the initial challenge will be to dedup some of these.  I will admit I am new to maintaining a project with many contributors so please be patient.  I plan on starting from the top and working my way back.  I am certainly open to any advice, guidance, tips, etc as I get started on this.

**Comment by admirallenny** [comment]
Considering that we now have contact with the original author as well as additional moderators, I consider this issue closed.
