### ISSUE TITLE
Dates returned from API are in the wrong format.

### ISSUE THREAD

**Issue by teague-hagerty** [ranaroussi/yfinance#446]
When the API returns a field that has a date in it, the date is unable to be read.

ie:
```
import yfinance as yf

msft = yf.Ticker("MSFT")

msft.info
```

returns a number of things, one of which being:
"'lastFiscalYearEnd': 1593475200,"

does anyone know how to get this to format properly?

**Comment by dpuljic01** [comment]
@wolfpack2021 You can convert epoch time to human readable one, like this.
```
import time
...
info = msft.info
last_fiscal_year_end =  time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(info["lastFiscalYearEnd"]))
print(last_fiscal_year)
```
This yields with result
`>> 2020-09-11 23:58:05`
