### ISSUE TITLE
Options Strike price for stocks with that had a recent stock split incorrect. 

### ISSUE THREAD

**Issue by jasonyunjoonpark** [ranaroussi/yfinance#454]
The strike prices for options data for companies that had a recent stock split are not reflecting the adjusted stock split strike prices. For example, AAPL and TSLA recently had a stock split and if you check the strike prices for specific expirations, they will contain records with strike prices pre- stock split and also contain record with strike prices after- stock split. How can I fix this so all strike prices for any ticker reflect the correct after stock-split strike prices?

**Comment by BonzoFestoon** [comment]
Same issue for special dividends. Take a look at the F Sept 2023 monthly contract.

**Comment by ValueRaider** [comment]
Create an issue using the new template, need more info.
