### ISSUE TITLE
Question: is there a way to get EBITDA?

### ISSUE THREAD

**Issue by midnightdim** [ranaroussi/yfinance#455]
EBITDA doesn't seem to be returned by get_info(), but it's shown on Yahoo Finance website.

**Comment by midnightdim** [comment]
For those who are interested, I simply added scraping code very similar to the code related to holders to scrape the data from "Statistics" page and got the values I needed.

**Comment by ymyke** [comment]
@midnightdim Can you share your code?

**Comment by midnightdim** [comment]
@ymyke It's kind of obsolete now, I switched to yahoqueery: https://github.com/dpguthrie/yahooquery
Provides a better access to Yahoo data.
