### ISSUE TITLE
Suppress ticker download logging 

### ISSUE THREAD

**Issue by thezentrader** [ranaroussi/yfinance#458]
Is there a way to suppress the default logging when downloading data for a ticker?

`[2020-09-21 16:30:40,888: WARNING/ForkPoolWorker-9] [*********************100%***********************]  1 of 1 completed`

**Comment by DavidVu96** [comment]
you could change the logging level to DEBUG or something and hide it away

**Comment by thezentrader** [comment]
Thank you. Closing this issue.

**Comment by impredicative** [comment]
Another way to disable its messages is to redirect its stdout to a buffer which is then discarded.

```
import contextlib
import io

with contextlib.redirect_stdout(io.StringIO()):
    ...  # Call yf here.
```
