### ISSUE TITLE
obj.recommendations does not work for some tickers, such as "xom"

### ISSUE THREAD

**Issue by hughgithub** [ranaroussi/yfinance#460]
First of all. Thanks!!!

Issue occurs for some tickers only, for example this one:
tickerObj = yf.Ticker('xom')
Obj_reco=tickerObj.recommendations

produces this error:

Anaconda3\lib\site-packages\yfinance\base.py", line 286, in _get_fundamentals
    self._institutional_holders = holders[1]

IndexError: list index out of range

**Comment by akashkj** [comment]
This seem to be already handled in latest code, based on length check.
`        if len(holders)>=3:`
