### ISSUE TITLE
Missing timestamp information in history datetime index

### ISSUE THREAD

**Issue by hoofnail** [ranaroussi/yfinance#464]
When using the `history()` function each datetime index in the returned DataFrame object has the the timestamp `00:00:00`.

### Example:
```python
import yfinance as yf

ticker = yf.Ticker("TSLA")
hist = ticker.history(period="7d", interval="1h")[["Close"]]
```
### Result:
                        Close
Date
2020-09-17  430.55
2020-09-17  432.18
2020-09-17  421.99
2020-09-17  422.87
2020-09-17  424.83

So the necessary time information is missing.

**Comment by nicoloridulfo** [comment]
I have the same problem, I changed from "1h" to "60m" and it fixed it.

**Comment by jabowery** [comment]
This should be documented in the readme.
