### ISSUE TITLE
Income statement, cash flow, balance sheet data is unavailable

### ISSUE THREAD

**Issue by flinge** [ranaroussi/yfinance#465]
```
import yfinance as yf

msft = yf.Ticker("MSFT")
msft.balance_sheet
msft.quarterly_balance_sheet
msft.cashflow
```

**Comment by MichelCarroll** [comment]
Found the issue. 

A commit a few months ago is overriding the `url` variable, making the API try to fetch data from:
https://finance.yahoo.com/quote/MSFT/holders/financials 
instead of:
https://finance.yahoo.com/quote/MSFT/financials

Working on a fix.

**Comment by MichelCarroll** [comment]
Actually, there's already a nice PR addressing this issue: https://github.com/ranaroussi/yfinance/pull/239

**Comment by mohammednaseefop** [comment]
@flinge @MichelCarroll  Is this issue resolved?

**Comment by flinge** [comment]
@mohammednaseefop Still does not work for me, but may it's a versioning issue? Somehow lib version in PIP and when imported do not match 🤷‍♂️
`~ ❯❯❯ pip3.8 list | grep yfinance
yfinance               0.1.55
~ ❯❯❯ python3
Python 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yfinance as yf
y>>> yf.__version__
'0.1.54'
>>> yf.Ticker('MSFT').financials
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []
>>> 
`

**Comment by mohammednaseefop** [comment]
@flinge 
Check this #191
There is a fix in base.py line 283
