### ISSUE TITLE
is it possible to get quarterly_financials and recommendations to show more than 4 quarters? 

### ISSUE THREAD

**Issue by veekon** [ranaroussi/yfinance#471]
Would be amazing if _quarterly_financials_ and _recommendations_ showed full history

**Comment by hugow182** [comment]
Yeah, it would.

**Comment by AjinkyaBankar** [comment]
@veekon did you get an answer?

**Comment by ValueRaider** [comment]
yfinance only returns what Yahoo website has - 4 quarters
