### ISSUE TITLE
KeyError: 'regularMarketPrice' not working for SPX

### ISSUE THREAD

**Issue by yupanqui** [ranaroussi/yfinance#477]
Hi, I'm using 0.1.55 version and get the above error on .info for SPX, others securities (spy, aapl,...) are ok.
Any hint to overcome the issue?
Thanks in advance

**Comment by LazaroHurtado** [comment]
please use "^SPX" instead of "SPX" as the ticker

**Comment by yupanqui** [comment]
Thanks for your comment Lazaro, but I actually used ^SPX and wrote SPX in my query just for simplicity

**Comment by LazaroHurtado** [comment]
So does that mean your issue is resolved?

**Comment by yupanqui** [comment]
Actually no, but I walked around using pandas datareader and pulling SPX
data from stooq. Wonder why can't do the same with yfinance.

Il mer 14 ott 2020, 15:59 Lazaro Hurtado <notifications@github.com> ha
scritto:

**Comment by LazaroHurtado** [comment]
What exactly are you doing to call .info on SPX and what are you trying to get?
