### ISSUE TITLE
yf.download() appears to sleep before ingesting data. Seems to be IP-related? 

### ISSUE THREAD

**Issue by idea404** [ranaroussi/yfinance#478]
yf.download() function lags for a number of seconds before performing the download which by the looks of the progress bar, takes miliseconds. 

When I ran the same operation on a AWS server, the download was carried out instantly. However, on my machine it lags before continuing. 

Is this related to some limit as my personal machine runs many more requests as the server? Where can I read more on this if there is such a limit?

**Comment by Dennis7799** [comment]
Pulling the data still is slow on my machine after using a proxy server in the request. (proxy='http://51.75.147.40:3128') 

So this doesn't seem to be IP-related. Any ideas anyone?

**Comment by Dennis7799** [comment]
It seems to be some kind of 24-hour sleep function as downloads now occur at normal speeds again.

**Comment by andr3w321** [comment]
I'm not sure if these are the API rate limits that are applied to the yahoo finance API, but yahoo lists their general API limits as 2000 requests/hour/IP address here https://developer.yahoo.com/yql/guide/overview.html#usage-information-and-limits
