### ISSUE TITLE
Are dividends all wrong for AAPL?

### ISSUE THREAD

**Issue by WurtzJd** [ranaroussi/yfinance#481]
It is the first time I use the library, so I may miss something. As far as I understand, dividends returned by yfinance are "cash dividends", not "stock dividends".

Looking at the ticker ABT for the date 2020-10-14, I can confirm that `yfinance.Ticker("ABT").dividends` gives the same result than [streetinsider](https://www.streetinsider.com/dividend_history.php?q=ABT) : $0.36

Now moving on to AAPL for the date 8/7/2020, yfinance.Ticker("AAPL").dividends` gives 0.205 but  [streetinsider](https://www.streetinsider.com/dividend_history.php?q=AAPL)  gives $0.82. A discrepency seems to exist at all dates for this ticker.

Or am I missing something?

**Comment by andr3w321** [comment]
AAPL did a 4:1 stock split on 8/31/20. Streetinsider is calculating the dividend/share on the pre-split basis (4 * 0.205 = 0.82)

**Comment by WurtzJd** [comment]
Got it, thank you
