### ISSUE TITLE
Inaccurate quotes before 2018

### ISSUE THREAD

**Issue by ric-domingues** [ranaroussi/yfinance#484]
First, let me say I am a huge fan and big-time user of `yfinance`  🙌 

However, in the past few days I noticed some mismatches between quotes obtained through `yfinance` and other data sources (Yahoo, Google, IexCloud). The discrepancies appear to originate before 2018. I haven't checked for many tickers, but for the few I did, the differences were there.  Does any one know why is that?

Here's a screenshot illustrating what I am referring to.

<img width="805" alt="Screen Shot 2020-10-23 at 2 13 37 PM" src="https://user-images.githubusercontent.com/52256681/97039611-b2623880-153a-11eb-8e65-d07cf32b705c.png">

**Comment by ValueRaider** [comment]
Dividend-adjusted price. Disable with `auto_adjust=False` (see README)
