### ISSUE TITLE
Instead of getting the granularity message can we get an error

### ISSUE THREAD

**Issue by ieshaan12** [ranaroussi/yfinance#486]
The idea is to capture the error as an invalid thing instead of having to do it as something different for reading stdout to check for possible errors.
- //SomeStockName: 1h data not available for startTime=//SomeStartTime and endTime=//SomeEndTime. The requested range must be within the last 730 days.
Can we change this to an error?

**Comment by ieshaan12** [comment]
Possibly making a new class derived from the exception class.

**Comment by ValueRaider** [comment]
Try `history(raise_errors=True)`
