### ISSUE TITLE
Financial Data not fetched

### ISSUE THREAD

**Issue by theonlyanil** [ranaroussi/yfinance#489]
My code:
```python
import yfinance as yf
msft = yf.Ticker('msft')
msft.financials
```

It returns empty dataframe:
```bash
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []
```

This is same for:

1. msft.financials
2. msft.quarterly_financials
3. msft.balance_sheet
4. msft.quarterly_balance_sheet
5. msft.cashflow
6. msft.quarterly_cashflow
7. msft.earnings
8. msft.quarterly_earnings

**Comment by elishields** [comment]
I am also experiencing this issue.

**Comment by Ashtonlim** [comment]
There is a bug in the code where the URL is configured wrongly.
The issue is found here in base.py
`data = utils.get_json(url+'/financials', proxy)`

just replace with the code below and it should work!

    url = "{}/{}/financials".format(self._scrape_url, self.ticker)
    data = utils.get_json(url, proxy)

**Comment by theonlyanil** [comment]
scraping is slow. Use query2 instead of query1. Basically yfinance is technically deprecated.

**Comment by theonlyanil** [comment]
Check this out: https://query2.finance.yahoo.com/v10/finance/quoteSummary/escorts.ns?modules=balanceSheetHistory

**Comment by WalkerWalker** [comment]
Having the same issue.

**Comment by WalkerWalker** [comment]
> scraping is slow. Use query2 instead of query1. Basically yfinance is technically deprecated.

ohno.  Is there some alternative ways to get historical financial data through API?

**Comment by theonlyanil** [comment]
Fixed it myself: https://pypi.org/project/yahfin

**Comment by ranaroussi** [comment]
Hi @theonlyanil - why not contribute to yfinance and add your code via pull request?

**Comment by vrnvorona** [comment]
Why are we using query1 instead of 2?
I have faced issues with some stocks being outdated because of it.

**Comment by ranaroussi** [comment]
@vrnvorona - The difference between `query1` and `query1` is that `query1` used `HTTP/1.0` while `query2` uses `HTTP/1.1`. The data is the same.

In any case - `v. 0.1.61` used `query2` as its faster when using proxy or persistent connections :)
