### ISSUE TITLE
1h & 60m time interval

### ISSUE THREAD

**Issue by odufb** [ranaroussi/yfinance#490]
hi all,

I get data from 1h & 60m time intervals in  0830-0930 format. Is it possible to get data  in 0800-0900 format. 
I hope question is meaninful 
best regards,

**Comment by KennSmithDS** [comment]
Hi All,

I'm not sure if this a related issue, but when I try to pull anything other than daily data, the dataframe index values returned are not unique and all still in the date format, not in datetime with the hour or minute granularity.  Also I am unable to readjust them to the appropriate datetime with hour format.

For example:

`df_test = yf.download(tickers='NFLX', period='100d', interval='1h')`
`df_test.tail(20)`

![nflx_date_not_hour](https://user-images.githubusercontent.com/30271891/97770700-d69db680-1af2-11eb-8044-51f162d9edbc.PNG)

**Comment by KennSmithDS** [comment]
If I run the comparable syntax for the pandas_datareader, the '1h' still has issues, but the '1m' yields expected data:

`df_test = pdf.get_data_yahoo(tickers='NFLX', period='100d', interval='1m') `

![nflx_pdf_min](https://user-images.githubusercontent.com/30271891/97771020-14500e80-1af6-11eb-875e-ba22b9459193.PNG)

**Comment by odufb** [comment]
@KennSmithDS  please  check issue #125.
my problem is different 
![Adsız](https://user-images.githubusercontent.com/32509250/97774376-4732ea80-1b68-11eb-90bc-870b9ee6bbd5.png)
as you see above picture time interval  like this
 2020-10-26 **09:30**:00-04:00  -  2020-10-26 **10:30**:00-04:00
is it possible get data like
 2020-10-26 **09:00**:00-04:00  -  2020-10-26 **10:00**:00-04:00

thanks for all replies.

**Comment by mcsoini** [comment]
> as you see above picture time interval like this
> 2020-10-26 **09:30**:00-04:00 - 2020-10-26 **10:30**:00-04:00
> is it possible get data like
> 2020-10-26 **09:00**:00-04:00 - 2020-10-26 **10:00**:00-04:00

This is how the yahoo api returns it. Try [https://query1.finance.yahoo.com/v8/finance/chart/AAPL?range=1mo&interval=1h](https://query1.finance.yahoo.com/v8/finance/chart/AAPL?range=1mo&interval=1h) and convert the integer timestamp using `datetime.datetime.fromtimestamp(1602599400)`. Then you get the 30 minute time `datetime.datetime(2020, 10, 13, 16, 30)`.

If you figure out why the api returns it like that, please let me know.

**Comment by ValueRaider** [comment]
Market opens at 9:30 so that's when first interval begins.
