### ISSUE TITLE
Get current stock price and nothing else?

### ISSUE THREAD

**Issue by creizlein** [ranaroussi/yfinance#491]
How would you go around getting the current stock price for a given symbol or a set of symbols?
I could navigate the info collection which has a lot of details, including prev close, close, open and such, but i couldnt found the specific "actual stock price" for that moment.

I am trying to get current stock price every 10 minutes by running a script periodically but i do not care about open/close prices, just the actual price for that moment.

And please sorry if this is not the correct place to ask these questions, thanks in advance

**Comment by karava** [comment]
I'm facing a similar issue. Interestingly if I get a ticker's info from inside a Jupyter Notebook, I can see the 'currentPrice' being provided. But when I run it as a Python script the 'currentPrice' field is missing in the info dictionary.

**Comment by creizlein** [comment]
currentPrice is returned inside the QuoteSummaryStore / financialData JSON Path which is not included in the info array

items = ['summaryProfile', 'summaryDetail', 'quoteType', 'defaultKeyStatistics', 'assetProfile', 'summaryDetail']
financialData has the currentPrice property

I believe that the merge of the json into info should include financialData  as well

**Comment by karava** [comment]
@creizlein thanks for your reply. Any tips how to access this property? I couldn't see a financialData property?

**Comment by vignesh11slm** [comment]
You can try using the bid/ask property, i think it should solve the issue

**Comment by jemshit** [comment]
[This answer](https://github.com/ranaroussi/yfinance/issues/331#issuecomment-641517501) gives current price in detail _(e.g: 14.09000012)_, while #701 adds `financialData` into `info` which has `currentPrice` with 2 fractions _(e.g:14.09)_

**Comment by ValueRaider** [comment]
Don't use `info` for this, too slow.

`Ticker.history(period="1d")["Close"][-1]`

The last close value is current price, or at least the last traded price.
