### ISSUE TITLE
msft.info historical data

### ISSUE THREAD

**Issue by Luzaan** [ranaroussi/yfinance#502]
Good Day,

I recently started using this, and thank you so far. It would seem this could help.

How do I specify the date for historical data required from msft.info?

As an example, how can I get the P/E Ratio or the PEG Ratio from Google 10 years back?

Thank you in advance!
Kind Regards

**Comment by kelanwilks** [comment]
msftTicker = yf.Ticker("MSFT")
info = msftTicker.info
peRatio = info['trailingPE']

You can use print(info) to see all of the different options.
