### ISSUE TITLE
Minor typo in README.rst NOTE: backward-competability should be backward-compatibility

### ISSUE THREAD

**Issue by danieljllo** [ranaroussi/yfinance#504]
Minor typo in README.rst NOTE:
- It currently says **backward-competability**
- It should say **backward-compatibility**

_I don't know how to do a pull request on GitHub, but I might take this opportunity to learn and fix this typo myself._

**Comment by jamesprinc3** [comment]
This link might be helpful to you: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Do remember to mention this issue in the PR so the issue doesn't linger once it has been fixed.
