### ISSUE TITLE
Unable to download since 11/25

### ISSUE THREAD

**Issue by rymoore** [ranaroussi/yfinance#522]
I've been using yFinance to download historical data on a daily basis for about 1000 stocks for the last several months. Since November 25th, my calls now get to about "123 of 1000" and then stall out. Anyone else having this issue? Have I been blacklisted by Yahoo? 

Here's the call that is failing:
`hist = yf.download(sp_list, start="2020-11-01", group_by = 'ticker', threads = True)`

**Comment by beglitis** [comment]
Try this see if it helps

https://github.com/ranaroussi/yfinance/pull/449

**Comment by rymoore** [comment]
I replaced my pip `yfinance` reference with `https://github.com/beglitis/yfinance/archive/master.zip` but see the same behavior. Am I missing something, or might I be blocked by IP?

**Comment by jeheran** [comment]
Same pb

**Comment by jeheran** [comment]
The script announces 100% but is never-ending. 
![image](https://user-images.githubusercontent.com/39467268/100739466-64f9a680-33d7-11eb-99c0-979a3f0a01c2.png)

**Comment by Waffleboy** [comment]
+1

**Comment by silvavn** [comment]
Yahoo outage, not yfinance problem.
