### ISSUE TITLE
Missing data for certain days

### ISSUE THREAD

**Issue by larrynung** [ranaroussi/yfinance#524]
I found missing data for certain days，like 2020-11-26。

```
import yfinance as yf
data = yf.download("0050.tw", start="2020-11-25", end="2020-11-30")

data
```

Date                Open	        High	        Low	                Close	        Adj                   Volume		
2020-11-25	115.699997	115.699997	113.900002	113.949997	113.949997	4028700
2020-11-27	114.500000	114.849998	114.099998	114.650002	114.650002	5220065

**Comment by ussfletcher** [comment]
US markets aren't open every day of the year. In this case it was Thanksgiving.

**Comment by larrynung** [comment]
But this stock should be in Taiwan markets。

**Comment by larrynung** [comment]
thanks for your answer
