### ISSUE TITLE
DF not recognizing Date as a column

### ISSUE THREAD

**Issue by kelanwilks** [ranaroussi/yfinance#530]
Using ticker.history(), then trying to access 'Date' gives you a keyerror. Additionally, using row[0] gives you the open price.

**Comment by kelanwilks** [comment]
When you convert DF to Dict
{
	'Open': {Timestamp('2020-12-14 00:00:00'): 122.5999984741211}, 
	'High': {Timestamp('2020-12-14 00:00:00'): 123.3499984741211}, 
	'Low': {Timestamp('2020-12-14 00:00:00'): 121.56999969482422}, 
	'Close': {Timestamp('2020-12-14 00:00:00'): 121.77999877929688}, 
	'Volume': {Timestamp('2020-12-14 00:00:00'): 79075988}, 
	'Dividends': {Timestamp('2020-12-14 00:00:00'): 0.0}, 
	'Stock Splits': {Timestamp('2020-12-14 00:00:00'): 0.0}
}

**Comment by simonvdv** [comment]
This is a Pandas question, no yfinance. You're trying to access an index ('Date') by its name (instead of the index attribute, as in df.index). See Pandas docs or stackoverflow for more info
https://stackoverflow.com/questions/52139506/accessing-a-pandas-index-like-a-regular-column

**Comment by kelanwilks** [comment]
@simonvdv thank you!
