### ISSUE TITLE
How to get last dividend date instead of value?

### ISSUE THREAD

**Issue by coder-amogh** [ranaroussi/yfinance#531]
**First of all, thank you so much for thing amazing library!**

My issue is: I'm not able to get the last date at which the dividend was declared.

### What I'm doing:

```
import yfinance as yf

t = yf.Ticker("HDFCBANK.NS")

s = t.dividends

print(s[-1])
```

But I get: `7.5`. I'm expecting it to return `2019-08-01`.

I need to get the date at which the last dividend was declared. I tried various things, and searched Googled for too long, but I didn't find any solution...

Please help!

**Comment by kelanwilks** [comment]
Try this:

t = yf.Ticker("HDFCBANK.NS")
dividends = t.dividends
date = dividends.keys()[-1]
print(date)

This will print 2019-08-01 00:00:00, which you'll have to parse, but all the right info is there.

**Comment by coder-amogh** [comment]
> Try this:
[code]
> This will print 2019-08-01 00:00:00, which you'll have to parse, but all the right info is there.

Wow, thanks that worked perfectly!

I have to use `str(date)` to parse it into the datetime object I want because `date` it's a Pandas datetime object, but it's fine. 

Thanks again! :+1:
