### ISSUE TITLE
set timeout for requests

### ISSUE THREAD

**Issue by lucas03** [ranaroussi/yfinance#539]
Hey,
it's a good practice to set `timeout` parameter on `requests`. Otherwise it does not timeout and causes issues on webserver or async tasks. Is there a plan to add timeout, so clients can set it and handle in app gracefully?
AFAIK this is used in library now:
```
data = _requests.get(url=url, params=params, proxies=proxy)
```

**Comment by lightondust** [comment]
I am working on this.

https://github.com/ranaroussi/yfinance/compare/master...lightondust:timeout

how about set the default timeout to 10s and enable users to set their timeout parameters like this

```
ticker = yf.Ticker('code', timeout=15)
```

reference

https://2.python-requests.org/en/latest/user/advanced/#timeouts

**Comment by lucas03** [comment]
`get` method on `requests` accepts a lot of parameters. How about have a more general approach:
```
requests_kwargs = {"timeout": 15}
ticker = yf.Ticker("code", requests_kwargs)
```
and then just:
```
data = _requests.get(url=url, params=params, proxies=proxy, **requests_kwargs)
```

**Comment by krikru** [comment]
I'm also experiencing that my script freezes. I'm not sure whether it occurs when I create the `Ticker` object from a symbol or when I call the `history` method on the ticker, but I need to fix this somehow. Is there some easy way to work around the fact that there is no timeout at the moment? Do I have to use threads which I then kill if they take too long?

**Comment by lucas03** [comment]
use version that has a timeout I guess. Like lightondust MR, there is a way to install these packages from github and ping commit version there.

**Comment by thiagotguimaraes** [comment]
Any news here? 
I am also having the same problem :)

**Comment by char101** [comment]
Ideally it should use a `Session` object so that multiple requests can be pipelined in the same connection. For a quick hack we can do this:

```python
import requests
import yfinance as yf
import functools

session = requests.Session()
# accept gzip compressed data for less bandwidth
session.headers.update({
    'Accept-Encoding': 'gzip, deflate',
})
session.request = functools.partial(session.request, timeout=30)
# replace requests library in yfinance
yf.base._requests = session
yf.utils._requests = session
yf.ticker._requests = session
```

**Comment by jemshit** [comment]
[This](https://github.com/psf/requests/issues/2011#issuecomment-64440818) or [This](https://github.com/psf/requests/issues/2011#issuecomment-490050252) might be used on session object to modify timeout

**Comment by micktg** [comment]
@char101 
This works for me, thanks for that. No more freezing in my script.

The weird thing for me was, that the script suddenly stopped collecting data from Yahoo Finance for no apparent reason (for instance, there was no timeout error). The threads were still active and running, but nothing was happening, also no Error message was shown. I even could reload the part of the script (triggered via REST API call) and it started again to pull data from Yahoo.

**Comment by Padmanabh-M** [comment]
> @char101 This works for me, thanks for that. No more freezing in my script.
> 
> The weird thing for me was, that the script suddenly stopped collecting data from Yahoo Finance for no apparent reason (for instance, there was no timeout error). The threads were still active and running, but nothing was happening, also no Error message was shown. I even could reload the part of the script (triggered via REST API call) and it started again to pull data from Yahoo.


Can you share the finance equivalent code?
