### ISSUE TITLE
How to deal with days when the markets are closed

### ISSUE THREAD

**Issue by noib3** [ranaroussi/yfinance#541]
I'm trying to create a function that, given a ticker and a date, returns the close price of that ticker on that day. I'm having troubles in dealing with days when the markets are closed (saturdays and sundays, holidays etc...).

My goal is to return the value of the previous trading day (e.g. if I pass either a saturday or a sunday, it returns the value of the previous friday). However there's an annoying error message that I can't seem to get rid of. Also, the following solution is not that elegant.

Is it possible to add some flag whose default value is `False`, but if set to `True` it makes `yf.Ticker` follow the behaviour I just described?

This is my current implementation:

```python
#!/usr/bin/env python3

import yfinance as yf
from datetime import date, timedelta

def price_at_close(ticker: str, date: date) -> float:
  """
  Returns the price of a given stock at market close of a given date. If the
  markets were closed on that day (e.g. Saturdays and Sundays, Holidays, etc.)
  it returns the close price of the previous trading day.
  """
  try:
    return float(yf.Ticker(ticker).history(start=date,
                                           end=date,
                                           rounding=2).Close)
  except:
    return price_at_close(ticker, date - timedelta(days=1))

if __name__ == "__main__":
  print(price_at_close("AMD", date(2020, 12, 25)))
  print(price_at_close("AMD", date(2020, 12, 26)))
```

which outputs:
```
91.81
- AMD: No data found for this date range, symbol may be delisted
91.81
```

**Comment by bionicles** [comment]
What happens if you make it recursively invoke itself on the prior day if that exception occurs?

**Comment by noib3** [comment]
@bionicles Isn't that what the code I posted does?

**Comment by totekp** [comment]
Thanks for posting. Something similar would come in handy. The code below fixes some bugs above. The error message meant the dataframe was empty, so you need to subtract days from end date. Then date need to be datetime.

```python
def price_at_close(ticker: str, date: datetime, prices=None) -> float:
    """
    Returns the price of a given stock at market close of a given date. If the
    markets were closed on that day (e.g. Saturdays and Sundays, Holidays, etc.)
    it returns the close price of the previous trading day.
    """
    assert isinstance(date, datetime)
    if prices is None or date < prices.index[0]:
        end = date + timedelta(days=1)
        start = end - timedelta(days=10)
        prices = yf.Ticker(ticker).history(start=start, end=end, rounding=2)
    closep = Try(lambda: prices["Close"][date]).get_result()
    if closep is None:
        return price_at_close(ticker, date - timedelta(days=1), prices=prices)
    else:
        return closep
```

**Comment by noib3** [comment]
@totekp What's `Try`?

**Comment by totekp** [comment]
It's a handy monad. You can implement it or replace it with code that checks prices contains the date.

**Comment by fry1026** [comment]
Thanks for the code snippeds above. I've simplified it to just check back for the current day and the last 7 days to see when we had a closing price, then take that the price.

``` python
def price_at_close(ticker: str, date: datetime) -> float:
    end = date + timedelta(days=1)
    start = end - timedelta(days=10)
    prices = yf.Ticker(ticker).history(start=start, end=end, rounding=2)
    for i in range(7):
        if date - timedelta(days=i) in prices['Close'].keys():
            print(f"Close price displayed {date-timedelta(days=i)}")
            return prices['Close'][date - timedelta(days=i)]
```
