### ISSUE TITLE
Incorrect revenue for some stocks

### ISSUE THREAD

**Issue by maruf-h** [ranaroussi/yfinance#543]
When I pull earnings for some stocks the revenue seems incorrect. The Net income is correct but cant figure out why the revenue is off
Example:
tickers = yf.Ticker('td.to')
tickers.earnings

Output:
<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Revenue</th>\n      <th>Earnings</th>\n    </tr>\n    <tr>\n      <th>Year</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>2017</th>\n      <td>33986000000</td>\n      <td>10396000000</td>\n    </tr>\n    <tr>\n      <th>2018</th>\n      <td>36412000000</td>\n      <td>11262000000</td>\n    </tr>\n    <tr>\n      <th>2019</th>\n      <td>38036000000</td>\n      <td>11668000000</td>\n    </tr>\n    <tr>\n      <th>2020</th>\n      <td>36404000000</td>\n      <td>11895000000</td>\n    </tr>\n  </tbody>\n</table>

The revenue differs from whats listed in yahoo. the following stocks also have the same problem: bmo.to, ry.to, bns.to, cm.to. They are all Canadian banks. Not sure if the ending period is causing the problem.

Any insight is appreciated

Thanks.

**Comment by tzhern** [comment]
Found this issue as well.

**Comment by rrpsid** [comment]
I also found an issue that Capital Expenditures seem off for Canadian stocks in general.
