### ISSUE TITLE
Missing fundamental data

### ISSUE THREAD

**Issue by MaxMMadsen** [ranaroussi/yfinance#547]
Hi,

All fundamental data are missing.

Methods .history and .info works, but cashflow, balance_sheet, earnings, financials etc. return empy DataFrames.

I have tried with fresh environment and only yfinance installed, but to no avail. 

\Max

**Comment by beglitis** [comment]
See this discussion

https://github.com/ranaroussi/yfinance/pull/480#issuecomment-757560202
