### ISSUE TITLE
Incorrect data retrieved on ULVR.L for 6th Jan 2021 while OK in Yahoo Historical

### ISSUE THREAD

**Issue by manuelwithbmw** [ranaroussi/yfinance#552]
Hello Ran

Incorrect data (1/100 of actual O,H,L,C -and consequently wrong RSI calculated thru a library using OHLC values-) are retrieved with yfinance for ULVR.L on the day 6th Jan 2021, while they are OK as seen in Yahoo Historical.
How can we handle this situation, where is data actually stored? I thought Historical from yahoo was exactly what we were downloading.

Thanks for this very useful library

M

**Comment by kelanwilks** [comment]
@manuelwithbmw Can you give an example with exact numbers?

**Comment by manuelwithbmw** [comment]
> @manuelwithbmw Can you give an example with exact numbers?

Sure, this is what I get when I retrieve last 10 days data on a dataframe print(df.tail(10)), OHLC and RSI seem affected:
![Screenshot 2021-01-16 at 09 23 44](https://user-images.githubusercontent.com/63164573/104807117-93dba880-57dc-11eb-811c-e48f2838fda4.png)

**Comment by beglitis** [comment]
I have seen this myself before.I don't think this is stock specific but exchange specific (if I recall correctly). I simply had to integrate additional logic in my code to multiply x 100 the values for these specific dates that were broken. So how do you find those dates systematically? Simply write some code that flags up unreasonable percentage changes to the daily timeseries e.g. if (pt - pt-1)/pt-1 > 50% then have the code report this and if the difference is due to this glitch then add the date to your list of dates for which you are multiplying with 100. Code that flags up unreasonable price changes on a regular (say daily) basis is standard in the industry.

**Comment by manuelwithbmw** [comment]
Yes, this is exactly what I did in my code to overcome the problem, thanks. It is very strange and unusual as I download and treat yfinance data regularly and this is the first time I see a difference between what is actually visible on yahoo on Historical Value and what is retrieved in my dataframes. Many oher times Yhaoo has a flawed data and as such you retrieve it from yfinance, so I normally connect with yahoo help desk and get it fixed for me.

![Screenshot 2021-01-16 at 10 49 00](https://user-images.githubusercontent.com/63164573/104808787-cc817f00-57e8-11eb-86cd-c77bbbf8a369.png)

Thank you

**Comment by manuelwithbmw** [comment]
OK, I found another similar error (23 Sept 2020, only on the Low value) on another LSE stock (BAB.L), so definitely the data retrieval from yfinance can occasionally deviate (errors) from Historical Data on Yahoo. Maybe the yfinance library works first exporting/saving data externally from Yahoo on a data warehouse, and it may introduce some errors that are unchecked, before making data available via yfinance. Possibly @ranaroussi  knows about this? 

![Screenshot 2021-01-16 at 11 44 14](https://user-images.githubusercontent.com/63164573/104809840-87f9e180-57f0-11eb-8d3f-796533d29dd8.png)

![Screenshot 2021-01-16 at 11 44 43](https://user-images.githubusercontent.com/63164573/104809848-99db8480-57f0-11eb-9309-e305e2861926.png)

**Comment by beglitis** [comment]
The package just returns what it gets from the website. There is no fancy logic or any data warehousing. I am sure if you grab the URL that yfinance uses and open it with your browser you will see that Yahoo just returned the incorrect value. It would be great if these incorrect numbers could be flagged up to Yahoo and corrected at source but obviously this is a free service (actually, it is not a service at all as we are just scrapping the data) and therefore one cannot have great expectations. Agreed that in a professional setting you would just ring them up.

**Comment by manuelwithbmw** [comment]
Maybe the scrapping process may at times introduce an error. Anyway, when the data is really incorrect on the charts-historical data of Yahoo itself, I just flag this up, sending an email to **finance@cc.yahoo.com** (help desk) and they check and correct it in a day or two. In these cases, they see the OHLC correctly stored so they cannot do anything. 
True, you are right, it is still a free service and we take it as it is with minor adjustments, I am not sure how the yfinance package really works behind the scenes

**Comment by beglitis** [comment]
I'll take a look at the raw data and report back however I am 99.9999% confident yfinance just returns the number its getting from Yahoo

**Comment by manuelwithbmw** [comment]
Maybe the default settings of the kwargs: **auto_adjust**, **back_adjust**, **rounding** in the yfinance function **history** are responsible for altering some of the quote. I may try to play with those for ULVR.L and BAB.L and see if results changes

def history(self, period="1mo", interval="1d",
                start=None, end=None, prepost=False, actions=True,
                auto_adjust=True, back_adjust=False,
                proxy=None, rounding=False, tz=None, **kwargs):
        """
        :Parameters:
            period : str
                Valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
                Either Use period parameter or use start and end
            interval : str
                Valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
                Intraday data cannot extend last 60 days
            start: str
                Download start date string (YYYY-MM-DD) or _datetime.
                Default is 1900-01-01
            end: str
                Download end date string (YYYY-MM-DD) or _datetime.
                Default is now
            prepost : bool
                Include Pre and Post market data in results?
                Default is False
            auto_adjust: bool
                Adjust all OHLC automatically? Default is True
            back_adjust: bool
                Back-adjusted data to mimic true historical prices
            proxy: str
                Optional. Proxy server URL scheme. Default is None
            rounding: bool
                Round values to 2 decimal places?
                Optional. Default is False = precision suggested by Yahoo!
            tz: str
                Optional timezone locale for dates.
                (default data is returned as non-localized dates)
            **kwargs: dict
                debug: bool
                    Optional. If passed as False, will suppress
                    error message printing to console.

**Comment by ValueRaider** [comment]
I've added a repair feature to `yfinance` to fix these 100x or NaN errors. Enable with `history(repair=True)`.

If there are other price issues that could be fixed, submit a pull request.

**Comment by manuelwithbmw** [comment]
Thank you very much @ValueRaider !
