### ISSUE TITLE
running runtest.py Tracebacks

### ISSUE THREAD

**Issue by daxm** [ranaroussi/yfinance#553]
All I've done is fork this project, install requirements, and run runtest.py.

Output:
>> MSFT ... OK
>> IWO ... OK
>> VFINX ... OK
>> ^GSPC ... OK
>> BTC-USD ... OK
>> F ... Traceback (most recent call last):
  File "/home/daxm/PycharmProjects/yfinance/runtest.py", line 64, in <module>
    test_yfinance()
  File "/home/daxm/PycharmProjects/yfinance/runtest.py", line 46, in test_yfinance
    assert(ticker.institutional_holders is None)
AssertionError

I'll look into this too but just wanted to start an issue just in case.

**Comment by daxm** [comment]
I "fixed" it in PR #554.  After I learn more about your code I might come back and change this to more appropriate handle the assert (or, rather, better handle what the Traceback is exposing about the code).

**Comment by silvavn** [comment]
outdated
