### ISSUE TITLE
Congrats and a simple question

### ISSUE THREAD

**Issue by seonake** [ranaroussi/yfinance#560]
Nice work! I really like it.
Just one question: Even if I set "End date" = today, i only will get data from yestarday and backwards, right?
So, it is not possible real time or data from today (for me, doesnt really matter if it is delayed)
Many thanks,

**Comment by totekp** [comment]
For today, adding +1 day should work. Ex. `yf.Ticker("SPY", end=endDate+timedelta(days=1))`. Sometimes I notice two rows with same date and one of the row has na column values. Then I add `.dropna()` to resolve issue.

**Comment by JuCarm** [comment]
This is probably linked to issue #545
