### ISSUE TITLE
Question on financials display

### ISSUE THREAD

**Issue by etobmike** [ranaroussi/yfinance#561]
Hi, I applied the update to base.py, however when pulling financials the categories do not appear in the same order as the statements intend. Is this happening to anyone else or is it a problem with my system?

For example, Research and Development appears at the top rather than Revenue

![image](https://user-images.githubusercontent.com/42377660/105214028-7892d500-5b1d-11eb-8e50-2d70ee62b1a0.png)

Thanks,

**Comment by silvavn** [comment]
You can sort the DataFrame to solve this issue.
