### ISSUE TITLE
Incorrect data for MSFT

### ISSUE THREAD

**Issue by radulucaciu** [ranaroussi/yfinance#563]
Hi,

it looks like the library is pulling incorrect data for MSFT although the Yahoo Historical data looks correct. Please see the following example with values starting with `Jan 02 2019` in the attached screenshots. 

`Volume` seems to be correct but all other columns are off.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/4388191/105572533-5e950480-5d60-11eb-8ee9-7d9236c6bba2.png">

<img width="930" alt="image" src="https://user-images.githubusercontent.com/4388191/105572548-6f457a80-5d60-11eb-94b1-597a0704a101.png">

**Comment by totekp** [comment]
Big issue, I reproduced issue, and issue doesn't appear on recent data. I plan to investigate the differences with excel. We should add test with your example too.

**Comment by beglitis** [comment]
They don't look wrong to me. The history has the adjusted prices which is what you would normally need for historical data. No?

**Comment by radulucaciu** [comment]
@beglitis in my specific case where I am running historical simulations, non-adjusted would be preferred. 

However, I didn't notice that `Close` from the library is actually `Adj Close` from historical until you mentioned it, so at least we know it's a choice, not a bug. 

Maybe this can be converted into a feature request?

**Comment by JuCarm** [comment]
You could use the auto_adjust=True/False option to select exactly what you want, have a look at the documentation.

**Comment by radulucaciu** [comment]
Thank you, I think this issue can be closed
