### ISSUE TITLE
Missing data for several days ETH-USD

### ISSUE THREAD

**Issue by partylikeits1983** [ranaroussi/yfinance#567]
![Screenshot from 2021-01-25 23-01-06](https://user-images.githubusercontent.com/77119221/105798915-3fb19080-5f61-11eb-8d84-996028b107f5.png)
First I thought yahoo was limiting queries to my ip but I replicated the issue on gcp. Is yfinance depreciated? What's up with this?
![Screenshot from 2021-01-25 22-54-03](https://user-images.githubusercontent.com/77119221/105798789-f103f680-5f60-11eb-867d-9274e665fcfd.png)
![Screenshot from 2021-01-25 22-55-24](https://user-images.githubusercontent.com/77119221/105798793-f3665080-5f60-11eb-9676-3188173b3c4b.png)

**Comment by partylikeits1984** [comment]
When I pull data for other tickers there isn't any missing data.

**Comment by JuCarm** [comment]
I have the same issue today (2021-01-27) with BTC-USD.
Could that be because these are categorized by finance.yahoo.com as "Cryptocurrency - CCC" ?
I have no problem with GBTC, categorized as "Equity - PNK".
Would be nice to see a fix for this though.

**Comment by ValueRaider** [comment]
Best yfinance can do is [price repair](https://github.com/ranaroussi/yfinance/wiki/Price-repair). Otherwise, this is a Yahoo issue.
