### ISSUE TITLE
Dividends only include ex-dividend date

### ISSUE THREAD

**Issue by DerekLJ** [ranaroussi/yfinance#568]
aapl = yf.Ticker("AAPL")
aapl.dividends

The dates returned are the ex-dividend date. The payment date is not returned.

Payment dates are available on https://www.nasdaq.com/market-activity/stocks/aapl/dividend-history

**Comment by JuCarm** [comment]
Is the payment date somewhere on finance.yahoo.com ?
yfinance pulls all its data from finance.yahoo.com (the y in yfinance stands for yahoo), so you cannot get something that's not there.

If it's not there, and you need it, then I guess you'll have to get it from nasdaq.com.

**Comment by DerekLJ** [comment]
The most recent payment date is on Yahoo.
https://finance.yahoo.com/quote/AAPL/key-statistics?p=AAPL
Dividend Date 3 | Nov 12, 2020

Is this page's content available through yfinance? I was able to get it from the project yahoo_fin, but I would prefer to use yfinance.

**Comment by ValueRaider** [comment]
`yfinance` doesn't scrape the statistics sub-page, someone needs to implement it.

**Comment by lucas03** [comment]
Yeah, yahoo finance doesn't seem to have pay dates. Maybe only for latest dividend.

**Comment by ValueRaider** [comment]
I've quickly implemented something simple in branch `feature/stats`, via `Ticker.stats` property. If you want to improve then submit pull requests to it.

**Comment by kacperstyslo** [comment]
I think this might help
```python
import yfinance as yf
ticker = yf.Ticker("AAPL")
ticker.calendar
```
```
# Output
{'Dividend Date': datetime.date(2024, 2, 15),
 'Ex-Dividend Date': datetime.date(2024, 2, 9),
 'Earnings Date': [datetime.date(2024, 5, 2), datetime.date(2024, 5, 6)],
 'Earnings High': 1.62,
 'Earnings Low': 1.46,
 'Earnings Average': 1.51,
 'Revenue High': 96598000000,
 'Revenue Low': 87901000000,
 'Revenue Average': 90988100000}
```

**Comment by cemanughian** [comment]
Dividend payable dates are not available for some tickers. See below example:

```
import yfinance as yf
ticker = yf.Ticker("BITO")
ticker.calendar
```

Produces
```
HTTP Error 404:
{}
```

I see the dates [elsewhere online](https://www.proshares.com/resources/distributions/distribution-schedule) so they are documented. Please advise.

**Comment by ValueRaider** [comment]
https://help.yahoo.com/kb/finance-for-web/report-problems-feedback-ideas-yahoo-finance-sln28397.html
