### ISSUE TITLE
Error message with period='max'

### ISSUE THREAD

**Issue by JuCarm** [ranaroussi/yfinance#570]
When running :
data = yf.download('ABTC-USD.SW', period='max', interval='1d', auto_adjust=True)
I am getting the following error :
1 Failed download:
- ABTC-USD.SW: 1d data not available for startTime=-2208988800 and endTime=1611763275. Only 100 years worth of day granularity data are allowed to be fetched per request.

The line of code does work with ticker 'ABTC.SW' though.

**Comment by JuCarm** [comment]
This may be linked to issue #545

**Comment by JustANutshell** [comment]
until it's fixed you can just use `period='99y'` instead `period='max'`

**Comment by ppeloton** [comment]
Hi, issue is that start parameter is set to 1.1.1900 and yahoo finance forbids data requests over a time period longer than 100 years. I suggest to set start parameter to 1.1.1950 (other earlier dates would also work, but does yahoo finance provide data before 1950?):
I  created a pull request: https://github.com/ranaroussi/yfinance/pull/648 to fix this issue

**Comment by silvavn** [comment]
Solved by #648
