### ISSUE TITLE
Hanging while downloading data

### ISSUE THREAD

**Issue by jokkemoose** [ranaroussi/yfinance#571]
Hi guys, 

Another yfinance hickup?
When downloading stocks data, it hangs on the Hist_data = temp.history command. 
Any idea what's wrong? 
And it hangs randomly for just a random stock. Sometimes it stops at the 10th stock, sometimes at another one. 

` 
Amount_of_API_Calls = 0
Stock_Failure = 0
Stocks_Not_Imported = 0
failedstocks = []
i=0
stocks = pd.DataFrame
while (i < len(tickers)) and (Amount_of_API_Calls < 4000):
    try:
        stock = tickers[i]  # Gets the current stock ticker
        temp = yf.Ticker(str(stock))
        Hist_data = temp.history(period="5y") 
        Amount_of_API_Calls += 1 
        Stock_Failure = 0
        i += 1  # Iteration to the next ticker
        print("Importing stock data:" + str(i))
    except ValueError:
        print("Yahoo Finance Backend Error, Attempting to Fix")  
        if Stock_Failure > 5: 
            i+=1
            Stocks_Not_Imported += 1
        Amount_of_API_Calls += 1
        Stock_Failure += 1
        failedstocks.append(tickers[i])
print("The amount of stocks we successfully imported: " + str(i - Stocks_Not_Imported))
failedstocks = list(set(failedstocks))
`

**Comment by jokkemoose** [comment]
now I'm getting: 
RuntimeError: *** YAHOO! FINANCE IS CURRENTLY DOWN! ***
Our engineers are working quickly to resolve the issue. Thank you for your patience.

So they are working on it :-)

**Comment by beglitis** [comment]
This error message is coming from yfinance and not Yahoo themselves. The error behind the scenes can be related to anything. I strongly believe that errors like these are due to Yahoo detecting scrappers and blocking them. There is a RR of mine that you can find in the project's base that switches the agent to chrome with selenium. This has solved the problem for me.

**Comment by claudinho85** [comment]
Hi @beglitis how did you configure RR to some the problem? I'm stucked on that problem and I cannot go on :-(

Thanks a lot

**Comment by ValueRaider** [comment]
Options:

- stop spamming
- [fetcher smarter](https://github.com/ranaroussi/yfinance#smarter-scraping)
- [yfinance_cache](https://github.com/ValueRaider/yfinance-cache)
