### ISSUE TITLE
RuntimeError: *** YAHOO! FINANCE IS CURRENTLY DOWN! ***

### ISSUE THREAD

**Issue by jokkemoose** [ranaroussi/yfinance#572]
Hi all,

I have been using yfinance a while with success. I haven't changed anything on the number of queries or number of tickers, but since today I get this "RuntimeError: *** YAHOO! FINANCE IS CURRENTLY DOWN! ***" message all the time. I read some tickers, and even pause 5 seconds after 50 queries or so, but it doesn't help. Is it a general issue? Any workaround possible? 

Johan.

**Comment by beglitis** [comment]
See this

https://github.com/ranaroussi/yfinance/issues/445

**Comment by Sneg42** [comment]
Same for me. some times working fine< some times with this error :"RuntimeError: *** YAHOO! FINANCE IS CURRENTLY DOWN! ***". When restart code, can work fine.
