### ISSUE TITLE
Duplicate data on period='1d'

### ISSUE THREAD

**Issue by pratik-choudhari** [ranaroussi/yfinance#573]
On running `history(period='1d')` for any stock, duplicate data is returned. Here is the screenshot of output. Everything is same except volume. Is this being done deliberately?

![aapl_stock](https://user-images.githubusercontent.com/40862682/106360464-8f67d180-633e-11eb-869f-4a153405e042.png)

**Comment by akhtariali** [comment]
Facing the same issue. 

```
# yfinance returns the same date twice if the period is 1d
if(period == "1d"):
  price_action = price_action.tail(1)
```

Will do.

Should I make a pull request? @ranaroussi

**Comment by pratik-choudhari** [comment]
I dont think maintainers are active in this repo

**Comment by scott-n58** [comment]
yeah . . . . . 
df = df[:-1] 
from here:
https://stackoverflow.com/questions/26921651/how-to-delete-the-last-row-of-data-of-a-pandas-dataframe

i would strongly encourage Mr. Aroussi to better support his creations . . . . .

**Comment by beglitis** [comment]
> Facing the same issue.
> 
> ```
> # yfinance returns the same date twice if the period is 1d
> if(period == "1d" and interval == "1d"):
>   price_action = price_action.head(1)
> ```
> 
> Will do.
> 
> Should I make a pull request? @ranaroussi

Can you point out where is the bug in the code?

**Comment by scott-n58** [comment]
this is a problem whether period = '1d' 
or
start_date = "YYYY-MM-DD", end_date = "YYYY-MM-DD"

the code result returns duplicate record of last trading day.

**Comment by akhtariali** [comment]
> > Facing the same issue.
> > ```
> > # yfinance returns the same date twice if the period is 1d
> > if(period == "1d" and interval == "1d"):
> >   price_action = price_action.head(1)
> > ```
> > 
> > 
> > Will do.
> > Should I make a pull request? @ranaroussi
> 
> Can you point out where is the bug in the code?

@beglitis 
It's an issue from Yahoo! Finance side.

Check this, e.g.,
https://query1.finance.yahoo.com/v8/finance/chart/TSLA?symbol=TSLA&interval=1d&range=1d

It returns two rows of data.

**Comment by beglitis** [comment]
I thought so that is why I asked where is the bug in the code. :)

**Comment by akhtariali** [comment]
Yea but adding the if statement above fixes the problem.

**Comment by Victor-Botelho** [comment]
Having the same problem for one ticker specifically. All others I've worked quite well. Been using the library everyday for a couple of weeks and just noticed this, so it might or might not have just started acting like this. Still not sure. Sure would be nice to have an official fix.

![bbdc4](https://user-images.githubusercontent.com/74219912/120491670-cf43d180-c38f-11eb-8715-185a9203f166.png)

**Comment by yiwenxu6** [comment]
The same issue here! Could the maintainer help solve this? It seems that whenever you try to download using period '1d' or '5d' (I also tested other intervals, and they all passed my tests) during the weekend set the start to be the Friday that just passed, it will duplicate. A related bug is that if you set the start to be Saturday, it will still include the data of Friday (but a single data). I guess that's the reason it duplicates: one indeed for Friday and the other for Saturday. The latter is definitely a bug!

**Comment by mathieugouin** [comment]
Just to chime in that I'm having the same issue.

**Comment by ValueRaider** [comment]
Is this still happening?
