### ISSUE TITLE
Weekly data issue - 29 Jan is Friday and it is not start of week

### ISSUE THREAD

**Issue by vijay-r** [ranaroussi/yfinance#576]
![29Jan](https://user-images.githubusercontent.com/7065756/106389546-b72e6680-641e-11eb-8b0b-af97098f7a4f.png)

**Comment by Aaron6611** [comment]
I am also having the same issue using the 1wk interval where the week starts on Friday. Based on your screenshot I wonder if this is a yfinance issue or an issue on Yahoo's end?

**Comment by silvavn** [comment]
Because either:
1. You are collecting on friday
2. friday was a holiday.
Solution: filter your pandas dataframe using the weekday == 0 flag if you want mondays only.
