### ISSUE TITLE
`history(period="max")` returns weird data

### ISSUE THREAD

**Issue by lyenliang** [ranaroussi/yfinance#580]
I'm using `yfinance 0.1.55`. The following code returns weird result.

```
import yfinance as yf

stock = yf.Ticker('TLT')
data = stock.history(period="max")
print(data['Close'][-5:])
```

The output of the above code is 

```
Date
2021-01-26      0.23
2021-01-27      0.23
2021-01-28      0.23
2021-01-29      0.23
2021-02-01    152.00
Name: Close, dtype: float64
```

`TLT`'s close price isn't `0.23` at `2021-01-29`.  It's `152`.

Does anyone know why this bug happens?

**Comment by wordcount** [comment]
Date
2021-01-26    153.20
2021-01-27    153.59
2021-01-28    152.74
2021-01-29    151.82
2021-02-01    152.00
2021-02-02    151.02
2021-02-03    149.68
2021-02-04    149.28

seems fixed

**Comment by cygenb0ck** [comment]
ah, so i am not the only one ...

From my observation so far, it depends on the queried period. I observed it when looking at ticker symbol "VIXL.MI".
Getting the history up to one year looks fine, but when i get 2y or older, this bogous values appear.

**Comment by cygenb0ck** [comment]
looks like yahoo is doing something - the history obtained for the symbol above contains a bigger useable range than yesterday.

at least a useable-range-detection is not that hard to implement ;-)
