### ISSUE TITLE
yf.download() with many Tickers throws ConnectionError and hangs

### ISSUE THREAD

**Issue by lasse-meixner** [ranaroussi/yfinance#584]
When downloading data for > 500 Tickers I often get a long error with final line:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='query1.finance.yahoo.com', port=443): Max retries exceeded with url: /v8/finance/chart/LH?range=1mo&interval=1wk&includePrePost=False&events=div%2Csplits (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bc5e3f3d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known').

The download continues up to the last few tickers (leaving as many as errors thrown).
I verified that my connection is stable. This only ever occurs for large downloads that take some time. 

I assume that the hanging at the end is due to some download-threads not being closed due to this Connection Error.
How can I avoid this?

**Comment by hansiniupadhyay** [comment]
threads not closed properly due to download error and hence the download doesn;t complete

**Comment by ValueRaider** [comment]
Still happening?
