### ISSUE TITLE
Data missing - 2021-02-05

### ISSUE THREAD

**Issue by Waffleboy** [ranaroussi/yfinance#587]
Using yf.download for the date `2021-02-05` with interval `5M` and duration `7D` with many tickers leads to many missing rows, tried multiple times.

Tried downloading in chunks of 250, also same.

But downloading individual tickers for that day, but that will take **forever**. Why does this happen?

**Comment by ValueRaider** [comment]
If this is still happening, why do you think 'missing rows' is bad? 5m is a short interval, maybe no trades occurred?
