### ISSUE TITLE
JSON related error while attempting to download a list of securities with yfinance

### ISSUE THREAD

**Issue by manuelwithbmw** [ranaroussi/yfinance#591]
Hi,
all of a sudden, I am receiving a JSON related error while attempting to download a list of securities with yfinance using a loop into a list of tickers.
Traceback is below. This appear to be random, if I repeat the same request, it will stop in a different place of the loop

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yfinance/base.py", line 156, in history
    data = data.json()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    **raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**

Any suggestions please? The same download routine has always run ok until today, and I do not explicitly refer to JSON in my code so I guess this relates to how YFINANCE works?

Thank you for your help

**Comment by beglitis** [comment]
I just started getting the same error myself. I am debugging through it right now.

**Comment by aracoara** [comment]
I've got the same here

**Comment by beglitis** [comment]
It is a Yahoo issue. It doesn't like that we are scrapping data and it returns 500s. Retrying solves the issue

```
0%DROME.AT
ELGEK.AT
ATTICA.AT
HAIDE.AT
MSHOP.AT
SPACE.AT
Failed to get data for PPA.AT. Status code was 500. Retrying (no 1)...
Failed to get data for PPA.AT. Status code was 500. Retrying (no 2)...
PPA.AT
.Failed to get data for REVOIL.AT. Status code was 503. Retrying (no 1)...
REVOIL.AT
ELPE.AT
```

This is my code but I am running it with the chrome driver (base.py around line 160):

```
        response = None
        counter = 0
        while response != 200 and response != 404:
            driver = Chrome(options=chrome_options, executable_path=chrome_driver)
            data = driver.request('GET', url, params=params, proxies=proxy)
            driver.close()
            _time.sleep(counter)
            response = data.status_code
            if response != 200:
                counter += 1
                print('Failed to get data for {}. Status code was {}. Retrying (no {})...'.format(self.ticker, str(response), str(counter)))
```

**Comment by gaardhus** [comment]
I'm also getting a lot of random errors thrown when I try to collect ticker.info, doesn't occur on ticker.history() though.

```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-81-c3ba00ff4560> in <module>()
----> 1 ticker.info

C:\Users\tobia\anaconda3\envs\DS_env\lib\site-packages\yfinance\ticker.py in info(self)
    136     @property
    137     def info(self):
--> 138         return self.get_info()
    139 
    140     @property

C:\Users\tobia\anaconda3\envs\DS_env\lib\site-packages\yfinance\base.py in get_info(self, proxy, as_dict, *args, **kwargs)
    444 
    445     def get_info(self, proxy=None, as_dict=False, *args, **kwargs):
--> 446         self._get_fundamentals(proxy)
    447         data = self._info
    448         if as_dict:

C:\Users\tobia\anaconda3\envs\DS_env\lib\site-packages\yfinance\base.py in _get_fundamentals(self, kind, proxy)
    283         # holders
    284         url = "{}/{}/holders".format(self._scrape_url, self.ticker)
--> 285         holders = _pd.read_html(url)
    286 
    287         if len(holders)>=3:

C:\Users\tobia\anaconda3\envs\DS_env\lib\site-packages\pandas\util\_decorators.py in wrapper(*args, **kwargs)
    294                 )
    295                 warnings.warn(msg, FutureWarning, stacklevel=stacklevel)
--> 296             return func(*args, **kwargs)
    297 
    298         return wrapper

C:\Users\tobia\anaconda3\envs\DS_env\lib\site-packages\pandas\io\html.py in read_html(io, match, flavor, header, index_col, skiprows, attrs, parse_dates, thousands, encoding, decimal, converters, na_values, keep_default_na, displayed_only)
   1099         na_values=na_values,
   1100         keep_default_na=keep_default_na,
-> 1101         displayed_only=displayed_only,
   1102     )

C:\Users\tobia\anaconda3\envs\DS_env\lib\site-packages\pandas\io\html.py in _parse(flavor, io, match, attrs, encoding, displayed_only, **kwargs)
    896 
    897         try:
--> 898             tables = p.parse_tables()
    899         except ValueError as caught:
    900             # if `io` is an io-like object, check if it's seekable

C:\Users\tobia\anaconda3\envs\DS_env\lib\site-packages\pandas\io\html.py in parse_tables(self)
    215         list of parsed (header, body, footer) tuples from tables.
    216         """
--> 217         tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
    218         return (self._parse_thead_tbody_tfoot(table) for table in tables)
    219 

C:\Users\tobia\anaconda3\envs\DS_env\lib\site-packages\pandas\io\html.py in _build_doc(self)
    734                     pass
    735             else:
--> 736                 raise e
    737         else:
    738             if not hasattr(r, "text_content"):

C:\Users\tobia\anaconda3\envs\DS_env\lib\site-packages\pandas\io\html.py in _build_doc(self)
    715         try:
    716             if is_url(self.io):
--> 717                 with urlopen(self.io) as f:
    718                     r = parse(f, parser=parser)
    719             else:

C:\Users\tobia\anaconda3\envs\DS_env\lib\site-packages\pandas\io\common.py in urlopen(*args, **kwargs)
    135     import urllib.request
    136 
--> 137     return urllib.request.urlopen(*args, **kwargs)
    138 
    139 

C:\Users\tobia\anaconda3\envs\DS_env\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

C:\Users\tobia\anaconda3\envs\DS_env\lib\urllib\request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

C:\Users\tobia\anaconda3\envs\DS_env\lib\urllib\request.py in http_response(self, request, response)
    639         if not (200 <= code < 300):
    640             response = self.parent.error(
--> 641                 'http', request, response, code, msg, hdrs)
    642 
    643         return response

C:\Users\tobia\anaconda3\envs\DS_env\lib\urllib\request.py in error(self, proto, *args)
    567         if http_err:
    568             args = (dict, 'default', 'http_error_default') + orig_args
--> 569             return self._call_chain(*args)
    570 
    571 # XXX probably also want an abstract factory that knows when it makes

C:\Users\tobia\anaconda3\envs\DS_env\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    501         for handler in handlers:
    502             func = getattr(handler, meth_name)
--> 503             result = func(*args)
    504             if result is not None:
    505                 return result

C:\Users\tobia\anaconda3\envs\DS_env\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 503: Service Unavailable
```

**Comment by larshorn** [comment]
I'm getting the same error, please help!

**Comment by beglitis** [comment]
I think we are fighting a war we can't win. Yahoo will keep finding ways of detecting scrappers and blocking them.

**Comment by manuelwithbmw** [comment]
I could not imagine anything more annoying than this :-/ thought yfinance library was allowed to download and use that data, meant to replace an old similar API?

**Comment by manuelwithbmw** [comment]
@etrepum could you help on this issue?

**Comment by huntersair** [comment]
I'm also getting the same error. When running a loop, it just hangs (at an early random point) followed by the error shown in OP's comment. 

In the manual datascrapper I have (which was surprisingly working until yesterday), a similar problem happens where I get timed out.

**Comment by manuelwithbmw** [comment]
> I'm also getting the same error. When running a loop, it just hangs (at an early random point) followed by the error shown in OP's comment.

**same happens to me**
> 
> In the manual datascrapper I have (which was surprisingly working until yesterday), a similar problem happens where I get timed out.

**Comment by beglitis** [comment]
> I could not imagine anything more annoying than this :-/ thought yfinance library was allowed to download and use that data, meant to replace an old similar API? My experience is that if I try to do it for just a few securities it is ok, if you go for more than 5-10 you get that error but it is not a connection related error and it always happen at different times, after a few secs or more.

yfinance is not an official yahoo module. It just scraps the website. Yahoo is definitely not supporting this officially.

**Comment by etrepum** [comment]
The JSON error says that you are trying to parse an empty string. Looks like you are being rate limited by the API.

**Comment by manuelwithbmw** [comment]
> The JSON error says that you are trying to parse an empty string. Looks like you are being rate limited by the API.
Thank you for your reply Bob. So nothing that can be done with a code workaround? The problem is over yahoo data sourcing?

**Comment by papakipos** [comment]
I also had this issue yesterday, but it resolve for me. It's working normally now. Are you back on your feet as well?

**Comment by manuelwithbmw** [comment]
Solved for me as well, finger crossed, let's see if it stays this way. Maybe they had put a temporary cap on the API rate.

**Comment by jfgingras** [comment]
Usually, even for paid services, there is a API rate. If you have done web scraping, you know you have to "throttle" your request. I don't like the way the history/download function of the Tickers class is conceived because it doesn't rate limit the call to the Yahoo API.

I have built a "custom" mass download function with a "throttle" to avoid been temporaly ban by Yahoo. With this, I was able to downlad the whole S&P 500 and S&P TSX constituants max historical data without errors.

Here's how I do it:

```
def download_tickers(index_info):
    df = pd.read_csv('constituants.csv')

    if isinstance(df, (pd.DataFrame)):
        for i in range(len(df.index)):
            ticker = yf.Ticker(df["Symbol"][i])
            df_ticker = ticker.history(period='max')
            df_ticker.to_csv("{}.csv",format(ticker.ticker), date_format='%Y%m%d%H%M%S')
            rnd_sec = random.randrange(3, 13)
            print('Sleeping for '+str(rnd_sec)+' secondes...')
            time.sleep(rnd_sec)
```

I have a list of all stocks I want to download in a file called 'constituants.csv'. I load this file as a panda DataFrame and for each tickers, I download the full history, save it to a file named after the stock Symbol, then sleep between 3 to 13 secondes, then I download the next ticker.

With this, I never encounter any rate cap limit imposed by Yahoo.

Hope this help.

**Comment by beglitis** [comment]
This issue has gone away for me too. It was probably something intermittent from the Yahoo end. Adding a random delay between downloads is probably OK (although not necessary) however in my case at least it is not practical since I download data for more than 10,000 stocks daily. In my case it is for a platform I am building that will probably move over to different datasets as for a systematic investment process Yahoo's solution is not realistic e.g. you don't get consistent data for stocks that were live in the past but not now.

**Comment by manuelwithbmw** [comment]
> With this, I never encounter any rate cap limit imposed by Yahoo.
 > Hope this help.

Yes issue disappeared on Yahoo end but I find your solution reasonable and helpful, merci bcp @jfgingras. I usually don't download data, I just consume it, but what you suggest is helpful.

@beglitis have you checked this service? https://marketstack.com

**Comment by beglitis** [comment]
> > With this, I never encounter any rate cap limit imposed by Yahoo.
> > Hope this help.
> 
> Yes issue disappeared on Yahoo end but I find your solution reasonable and helpful, merci bcp @jfgingras. I usually don't download data, I just consume it, but what you suggest is helpful.
> 
> @beglitis have you checked this service? https://marketstack.com

I had a look at marketstack as well as other providers (eod historical - https://eodhistoricaldata.com/). Haven't decided yet but I think for $80 a month the EOD historical proposition is quite good (it includes loads of exchanges, fundamental data, US dead stocks and they are looking to extend this to non-US exchanges, crypto etc) plus 100,000 requests per month and I believe they would be willing to send you historical data in bulk to begin with without a major hit in the number of requests (I need to confirm that). 

To be fair, we can't complain. All in datasets from e.g Reuters (refinitiv data etc) are in the millions.

**Comment by manuelwithbmw** [comment]
This issue happened again for me today :-/

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/yfinance/base.py", line 156, in history
    data = data.json()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AC557** [comment]
Same here:(

Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\Achityala\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\Achityala\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Achityala\Anaconda2\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Users\Achityala\Anaconda2\lib\site-packages\yfinance\multi.py", line 168, in _download_one_threaded
    actions, period, interval, prepost, proxy, rounding)
  File "C:\Users\Achityala\Anaconda2\lib\site-packages\yfinance\multi.py", line 183, in _download_one
    rounding=rounding, many=True)
  File "C:\Users\Achityala\Anaconda2\lib\site-packages\yfinance\base.py", line 157, in history
    data = data.json()
  File "C:\Users\Achityala\Anaconda2\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Achityala\Anaconda2\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Achityala\Anaconda2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Achityala\Anaconda2\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by manuelwithbmw** [comment]
I swiftly fixed it just by updating my yfinance version to the last release via:
**pip3 install --upgrade yfinance**

**Comment by AC557** [comment]
It works! Thanks Manuel!
But I am confused- I thought it was a problem with Yahoo Finance; that they are not happy with people extracting data this way. Would you be have some more insight on why it starts working again after the upgrade pls?
