### ISSUE TITLE
.financials returns blank dataframe

### ISSUE THREAD

**Issue by jessejuntura** [ranaroussi/yfinance#593]

**Comment by kpad-git** [comment]
I see the same thing. You may want to try the yahooquery package which seems to get financial data better (although it has some issues with price/dividend/split data that yfinance seems to be better with)

**Comment by opticode** [comment]
The url started with on line 376 in base.py is the '/holders' one, so appending '/financials' to it gives the wrong url:
```
        # get fundamentals
        data = utils.get_json(url+'/financials', proxy)
```

**Comment by JCraigWasTaken** [comment]
Bump this, the example in the read me doesn't work anymore either

**Comment by silvavn** [comment]
This was fixed by last iteration, can you confirm?

**Comment by opticode** [comment]
@silvavn Yes it was 👍
