### ISSUE TITLE
Error for ticker PSTH

### ISSUE THREAD

**Issue by Covent530** [ranaroussi/yfinance#597]
When i call info on ticker "PSTH" i get the following error:

"None of ['endDate'] are in the columns"

import yfinance as yf
psth = yf.Ticker("PSTH")
psth.info

Every other ticker I have tried works just fine... Any ideas?

**Comment by jfgingras** [comment]
That's beacause the ticker PSTH doesn't have Annual Income Statement, Balance Sheet and Cash Flow. Some "sanity check" should be added to the librairy. There's little you can do except to modify the code to add those validations or wait for someone to make a Pull Request.
