### ISSUE TITLE
yf.download hangs/stuck downloading last few syms

### ISSUE THREAD

**Issue by hansiniupadhyay** [ranaroussi/yfinance#598]
The last few symbols does not get downloaded and the download is stuck with no error message.
Call:
price=yf.download(sym_list,startdate,enddate)

sym_list is a list of 8318 syms
![yfinance stuck](https://user-images.githubusercontent.com/79159854/108094661-0abec800-704d-11eb-97c5-3341c403b5d9.PNG)

**Comment by hansiniupadhyay** [comment]
Looks like this is because the threads are not closing properly for sym data that yfinance wasn't able to download. How can I overcome this and close the threads that didn't close properly since the data wasn't downloaded ?

**Comment by GF-Huang** [comment]
Same issue.

![image](https://user-images.githubusercontent.com/4510984/108501247-f815ee80-72eb-11eb-9b9c-64b21e36e622.png)

**Comment by hansiniupadhyay** [comment]
For now updating the base.py is working for me: Replace below code in base.py

        # Getting data from json
        url = "{}/v8/finance/chart/{}".format(self._base_url, self.ticker)
        data = _requests.get(url=url, params=params, proxies=proxy)
        # if "Will be right back" in data.text:
        qqq=0
        while "Will be right back" in data.text and qqq<3:
            # raise RuntimeError("*** YAHOO! FINANCE IS CURRENTLY DOWN! ***\n"
            #                    "Our engineers are working quickly to resolve "
            #                    "the issue. Thank you for your patience.")
            _time.sleep(2)
            qqq=qqq+1
            data = _requests.get(url=url, params=params, proxies=proxy)
            if "Will be right back" not in data.text:
                break
        if "Will be right back" in data.text:
            raise RuntimeError("*** YAHOO! FINANCE IS CURRENTLY DOWN! ***\n"
                                "Our engineers are working quickly to resolve "
                                "the issue. Thank you for your patience.")
        data = data.json()

**Comment by hansiniupadhyay** [comment]
I wonder what the owner of the library thinks of this. I hope he responds to the thread.

 I figured this was happening because few of the threads were not closing correctly and hence the process not finishing completed. This happens for random syms where the data is not downloaded successfully.

**Comment by GF-Huang** [comment]
I was surprised at how much PRs there was and wondered if the project was still alive.

**Comment by beglitis** [comment]
The project is not really but the community is. Since we are all coders you can imagine we have forked the code and we fix bits and pieces in our own code bases depending on the issues we come across and the findings by others.

**Comment by GF-Huang** [comment]
I had try your fix code, not work, still stuck at the ends.

**Comment by hansiniupadhyay** [comment]
Oh ! Somehow doing this made my code run correctly without getting hung. Other solution which I haven't tried myself but would be my next possible solution is below:

# Getting data from json
url = "{}/v8/finance/chart/{}".format(self._base_url, self.ticker)
data = _requests.get(url=url, params=params, proxies=proxy)
msgg='Data Not Downloaded'
if "Will be right back" in data.text:
	shared._DFS[self.ticker] = utils.empty_df()
	shared._ERRORS[self.ticker] = msgg
	print('- %s: %s' % (self.ticker, msgg))
	return shared._DFS[self.ticker]
data = data.json()

**Comment by hansiniupadhyay** [comment]
Oh ! the above solution worked for me. Other thing you can try is below

# Getting data from json
url = "{}/v8/finance/chart/{}".format(self._base_url, self.ticker)
data = _requests.get(url=url, params=params, proxies=proxy)
msgg='Data Not Downloaded'
if "Will be right back" in data.text:
	shared._DFS[self.ticker] = utils.empty_df()
	shared._ERRORS[self.ticker] = msgg
	print('- %s: %s' % (self.ticker, msgg))
	return shared._DFS[self.ticker]
data = data.json()

**Comment by hansiniupadhyay** [comment]
Oh ! the above solution worked for me. Other thing you can try is below.

```

# Getting data from json
url = "{}/v8/finance/chart/{}".format(self._base_url, self.ticker)
data = _requests.get(url=url, params=params, proxies=proxy)
msgg='Data Not Downloaded'
if "Will be right back" in data.text:
	shared._DFS[self.ticker] = utils.empty_df()
	shared._ERRORS[self.ticker] = msgg
	print('- %s: %s' % (self.ticker, msgg))
	return shared._DFS[self.ticker]
data = data.json()
```

**Comment by GF-Huang** [comment]
It throws exception at line 151, and your code never catch that, so how does your code works?

![image](https://user-images.githubusercontent.com/4510984/108563976-5919e280-733d-11eb-98df-cc54ac994b46.png)

![image](https://user-images.githubusercontent.com/4510984/108563856-27088080-733d-11eb-86a2-c821ae40f242.png)

**Comment by hansiniupadhyay** [comment]
Okay try putting a try/except block around it....

`requesterr='Error Requesting Data'
try:
    data = _requests.get(url=url, params=params, proxies=proxy)
except Exception:
    shared._DFS[self.ticker] = utils.empty_df()
    shared._ERRORS[self.ticker] = requesterr
    print('- %s: %s' % (self.ticker, requesterr))`

**Comment by hansiniupadhyay** [comment]
I'm just trying to handle the exception the way 'symbol may be delisted' exception/error is handled, in the same file (base.py)

**Comment by hansiniupadhyay** [comment]
@GF-Huang  : Did you happen to resolve the error ?

**Comment by GF-Huang** [comment]
I modify to this, works well.

![image](https://user-images.githubusercontent.com/4510984/108793636-f33c8d80-75be-11eb-8686-57269bf536d9.png)

**Comment by hansiniupadhyay** [comment]
Great ! Glad you found the solution. Good luck.

**Comment by ste0009** [comment]
> I modify to this, works well.
> 
> ![image](https://user-images.githubusercontent.com/4510984/108793636-f33c8d80-75be-11eb-8686-57269bf536d9.png)

Sorry, but I have very little knowledge other than some basic Pandas usage. How would the fix be added to this code:

ipo_test = yf.download(ipos_list_1, start="2020-09-14", end="2021-03-09")

Thank you!

**Comment by Ozymandias1700** [comment]
I am also having this issue, and none of the fixes in this thread have helped resolve it.

**Comment by ValueRaider** [comment]
Project is active again. If problem still exists and someone has a solution then submit a PR.
