### ISSUE TITLE
Is there a way to get a list of all the stocks listed on NYSE and Nasdaq?

### ISSUE THREAD

**Issue by danielhanbitlee** [ranaroussi/yfinance#606]
Is there a way to get a list of all the stocks listed on NYSE and Nasdaq using this API? I want to exclude OTC and OTCMKS.

Any help would be appreciated.

**Comment by cflensbatina** [comment]
Use this link and select the index you need: https://www.nasdaq.com/market-activity/stocks/screener

Download the CSV file and the ticker column will have what you need.

**Comment by danielhanbitlee** [comment]
Thank you for sharing this resource!

**Comment by cflensbatina** [comment]
Sure. It was a hard problem for me to solve a year ago.
