### ISSUE TITLE
can't compare datetime.datetime to datetime.date

### ISSUE THREAD

**Issue by tombohub** [ranaroussi/yfinance#615]
If setting `start = datetime.datetime(2020,2,2)` it will cause error: 

```
can't compare datetime.datetime to datetime.date
```

while doing the same for end `end = datetime.datetime(2020,2,2)` it will give no error.

**Comment by tomazbm** [comment]
What is your code?

for yf.Ticker I use:

```
start = datetime.datetime(2020,2,4)
end = datetime.datetime(2020,3,2)

msft = yf.Ticker('msft').history(start=start,end=end)
print(msft)
```
And it works:

for yf.download:

```
start = datetime.datetime(2020,2,4)
end = datetime.datetime(2020,3,2)

msft = yf.download('msft', start=start, end=end)

```
and works as well.

But if you pass start and end like this:
```
start = datetime.datetime(2020,2,4)
end = datetime.datetime(2020,3,2)

msft = yf.Ticker('msft',start=start, end=end)
print(msft)
```
... you will get error, because Ticker doesn't take start as an argument.

**Comment by tombohub** [comment]
I honestly forgot what I was doing and cannot replicate the error anymore.

Thanks for your help, I will close this until I remember
