### ISSUE TITLE
Problems with qualitative calls

### ISSUE THREAD

**Issue by ghost** [ranaroussi/yfinance#618]
Not sure what's causing it, but whenever I call the .balance_sheet(), .cashflow(), or .financials() methods, or any of the quarterly_ associations, a blank dataframe is returned.

**Comment by Finc4Fun** [comment]
Having the same issue. I'm very new to this (first python project). I did pip install yfinance successfully. I can get msft.info but for some reason .balance_sheet isnt working. 

When I input:
import yfinance as yf
msft = yf.Ticker("MSFT")
print(msft.balance_sheet)

I get:
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

**Comment by Finc4Fun** [comment]
> Not sure what's causing it, but whenever I call the .balance_sheet(), .cashflow(), or .financials() methods, or any of the quarterly_ associations, a blank dataframe is returned.


Seems to be the same issue as 595, 593 but I haven't found a solve yet.

**Comment by tomazbm** [comment]
I am having same problem
