### ISSUE TITLE
Any way to get "dividend pay date"?

### ISSUE THREAD

**Issue by lucastagnitta** [ranaroussi/yfinance#631]
Hi there, 
very quick question: is there any way to get the dividend pay date? 
Many thks for your help
regards
LUCA

**Comment by tomazbm** [comment]
I know you can get the last payed if it helps.:

`msft = yf.Ticker('msft')
last_dividend = msft.info['lastDividendDate']`

**Comment by lucastagnitta** [comment]
hi tomaz, thks
actually, I was looking for the dividend pay date. Just to give u an example: 
https://finance.yahoo.com/quote/MSFT/key-statistics?p=MSFT
Dividend Date: Mar 10, 2021, that's different from lastDividendDate (Feb 17, 2021)
Thks anyway 
LUCA

**Comment by tomazbm** [comment]
Hi Luca,

You have  `msft.info['exDividendDate']` 

It's the date before which you must buy stocks in order to get dividends for next cycle.

But please check this site : https://www.investopedia.com/terms/e/ex-dividend.asp
as I have no practical expirence with dividends.

**Comment by silvavn** [comment]
```python
hchc = yf.Ticker('hchc')
df = hchc.history(start='2019-1-1')
```

if you display the dataframe it will contain a `Dividends` column.
The non-zero columns are those that have a dividend pay.

**Comment by ValueRaider** [comment]
I know this is old issue but shouldn't have been closed. The pay date is now available in a branch for testing, see here for details and feedback: https://github.com/ranaroussi/yfinance/issues/568#issuecomment-1399261622
