### ISSUE TITLE
Missing data for Australian (.ax) stocks

### ISSUE THREAD

**Issue by jsbritton01** [ranaroussi/yfinance#633]
![MissingData](https://user-images.githubusercontent.com/62267735/111409028-47eca780-872a-11eb-9e0b-2a03f00b4746.PNG)

I've noticed that for Australian stocks (ticker codes ending in ".ax") the only data appearing after 12th March 2021 is the day of the download (see attached photo).

**Comment by jlsajfj** [comment]
Seems to be ok, maybe a blip in the Yahoo side?
![image](https://user-images.githubusercontent.com/7155643/111692791-37116400-8806-11eb-9e81-9e5123e3026b.png)

**Comment by jsbritton01** [comment]
Thanks for that. Yes, I noticed it came good.
cheers
Jeff

**Comment by silvavn** [comment]
closing since problem is solved
