### ISSUE TITLE
It's pulling data from day earlier than the 'start'

### ISSUE THREAD

**Issue by tombohub** [ranaroussi/yfinance#638]
Today is 2021-03-21

If I choose start to be 2021-03-20, yinance pull data from 2021-03-19:

```python
spy = yf.Ticker('spy')
df = spy.history(start='2021-03-20')
df
```

result:
| Date                |   Open |   High |    Low |   Close |        Volume |   Dividends |   Stock Splits |
|:--------------------|-------:|-------:|-------:|--------:|--------------:|------------:|---------------:|
| 2021-03-19 00:00:00 | nan    | nan    | nan    |  nan    | nan           |       1.278 |              0 |
| 2021-03-19 00:00:00 | 389.88 | 391.56 | 387.15 |  389.48 |   1.13624e+08 |       0     |              0 |

Is this Yahoo finance thing or yfinance?

**Comment by PericlesTheGit** [comment]
I might be wrong, here. But are you taking into account time zones?
