### ISSUE TITLE
Fundamentals not available out of the box, there's a handy fix

### ISSUE THREAD

**Issue by martingaleh** [ranaroussi/yfinance#639]
http://disq.us/p/2bhc8g4
```
import yfinance as yf

msft = yf.Ticker("MSFT")
msft.financials
```
Doesn't work, but this fix, which I stole from the comments works:
- Please go to the installation location of yfinance, e.g., python3.6/site_packages/yfinance.
- Open base.py
- Find the comment # get fundamentals (should be line 353)
- comment this line: data = utils.get_json(url+'/financials', proxy)
- add these two lines:
url = "{}/{}/financials".format(self._scrape_url, self.ticker)
data = utils.get_json(url, proxy)

I bet someone tried to fix this in a merge request.  I'm not smart enough to fix that.  But if anyone else has an issue, here's a work around.

**Comment by silvavn** [comment]
This seems to be solved with the latest merges, can you double check and confirm?

**Comment by tinix84** [comment]
it seems I still have some problems
![image](https://user-images.githubusercontent.com/16301528/113627043-37618a00-9663-11eb-9234-f14504cf328e.png)

on the contrary lib yahoo_fin seems OK
import yahoo_fin.stock_info as si
si.get_financials(ticker)

**Comment by maedosan31** [comment]
> it seems I still have some problems
> ![image](https://user-images.githubusercontent.com/16301528/113627043-37618a00-9663-11eb-9234-f14504cf328e.png)
> 
> on the contrary lib yahoo_fin seems OK
> import yahoo_fin.stock_info as si
> si.get_financials(ticker)

can you get more data than last 4 quarters so quarter over quarter growth can be measured ?

**Comment by tinix84** [comment]
@maedosan31 Can you explain me how? Or what do you refer to? which method should I call?

**Comment by maedosan31** [comment]
> @maedosan31 Can you explain me how? Or what do you refer to? which method should I call?

If I use get quarterly financials then I get the data for the last 4 quarters ( revenue, profit, etc. ) , I would like to get atleast 8 quarters of data so I can compute the year over year performance for each quarter. Is it possible to get this data through yfinance or any other library ? 
![Uploading Screenshot_20210412_080023.jpg…]()

**Comment by jemshit** [comment]
@tinix84 what version do you use?
