### ISSUE TITLE
pandas.read_html() call does not respect custom session

### ISSUE THREAD

**Issue by occasionallydavid** [ranaroussi/yfinance#645]
Per comment on #625, using a custom Session to redirect requests currently doesn't work as documented, as pandas does not internally use the requests session.

Filing this fresh to ensure it's being recorded, as it's a bug that wasn't part of the original PR.

This is missing:

```diff
         # holders
         try:
-            holders = _pd.read_html(ticker_url+'/holders')
+            resp = self.session.get(ticker_url + '/holders')
+            resp.raise_for_status()
+            holders = _pd.read_html(resp.content)
         except Exception as e:
             holders = []
```

**Comment by ranaroussi** [comment]
Was added in v 0.1.59
