### ISSUE TITLE
Analyst recommendations function crashes only when input does not contain required key

### ISSUE THREAD

**Issue by xyqshelly** [ranaroussi/yfinance#660]
We tried to find the very specific part of the exception that's causing problems in the `analyst_recommendations` function by developing unit tests and doc tests. All pandas functions worked properly. It seems that the function will only throw an exception if the data passed to the function does not contain the required keys or the data type is not "dict". If this is the only issue, it might be possible to develop a better solution than using `except Exception: pass`, such as checking the type of data and testing if the data contains the required keys before executing the function.

The PR #309 tried to solve this problem by adding an if condition: ` if data ["upgradeDowngradeHistory"] ["history”] `

**Comment by ValueRaider** [comment]
Looks like your fix was not merged. Can you provide simple test code that crashes, then can open a fresh PR.
