### ISSUE TITLE
Missing Beta Info Just for ETFs 

### ISSUE THREAD

**Issue by pmgh2345** [ranaroussi/yfinance#662]
For some reason, the issue I had opened in December was just closed despite the fact that the issue persists with the latest versions of yfinance as listed in both conda (0.1.55) and pip(0.1.59).  Is there something I'm missing?

Literally ANY etf will return a beta of NoneType and it is extremely inconvenient.

**Comment by ValueRaider** [comment]
Yahoo only displays "Beta (5Y Monthly)"

`info[]` contains "beta3Year" with equal value. Does this solve?
