### ISSUE TITLE
Ticker History returns data from one day before requested date, on March/April boundary

### ISSUE THREAD

**Issue by philiproche** [ranaroussi/yfinance#673]
\>>> tickerData
yfinance.Ticker object \<CRWD>

\>>> tickerDf = tickerData.history(period='1d', start='**2021-03-30**', end='2021-04-01')
\>>> tickerDf
              Open    High     Low   Close   Volume  Dividends  Stock Splits
Date                                                                        
**2021-03-29  177.69  182.73  171.20  173.85  3050500          0             0**
2021-03-30  171.08  176.24  168.76  175.28  4278000          0             0
2021-03-31  179.24  184.99  178.71  182.51  4253100          0             0

**Comment by GIS-PuppetMaster** [comment]
时区问题，传入datetime而不是str就好了
