### ISSUE TITLE
Does Yahoo block people?

### ISSUE THREAD

**Issue by martinemilander** [ranaroussi/yfinance#674]
Hi

I am unable to download like I used to just a couple of days ago. I used to download historical prices and option chains a few times a week for a few thousand stocks.

When I tried doing this a couple of days ago yfinance seemed slow and didn't return very much data, perhaps 50% of what I requested. I use version 0.1.55.

Does anyone else experience the same? Is it a problem with yfinance or has Yahoo begun to block activity such as mine?

Regards

**Comment by HeadbangerFinance** [comment]
I've experienced exactly the same and for me it started on Thursday (April 1st). I've also been using version 0.1.55 and updating to most recent version didn't help (I'm running Python 3.8). 
Never had any problems before (and have been downloading price data several times daily) but really slow and a lot of missing data now...almost unusable to be honest.

**Comment by pythozugen** [comment]
I have the same experience. I don't think the issue is at yfinance. I think it is at Yahoo, since I have the same problems when I use other modules, e.g. Pandas Datareader or Yahooquery.

**Comment by ValueRaider** [comment]
Options:

- stop spamming
- [fetcher smarter](https://github.com/ranaroussi/yfinance#smarter-scraping)
- [yfinance_cache](https://github.com/ValueRaider/yfinance-cache)
