### ISSUE TITLE
Industry/Sector 

### ISSUE THREAD

**Issue by GreekQuant** [ranaroussi/yfinance#676]
I want to fetch the industry and or sector for the tickers I use to download the adj.close prices using:

`data = yf.download(tckrs)['Adj Close'].dropna()`

hence in bulk I can bring prices but it seems that i have to loop through the tickers to get from .info the industry or sector accordingly and it takes so much even for like 8 tickers. Imagine wanting to build a portfolio with 100+ .

Any workaround?

**Comment by jemshit** [comment]
What alternative could there be without accessing it through info dictionary?

**Comment by TMcCode** [comment]
Wondering about this too. Have a list of 2k tickers that I'm hoping to run a loop through to get industry and sector. 

But w/ a dictionary this takes an insane amount of time. Before yahoo made the changes a few weeks ago I had used 

`from pandas_finance import Equity`

which had a separate call for industry, sector and description: 

`sector = []

for i in range(len(unchecked_tickers)):
        try:
            data = Equity(unchecked_tickers[i]).sector
            sector.append(data)
        except:
            sector.append('0')

unchecked_earnings_df["Sector"] = sector`
