### ISSUE TITLE
Problem passing session argument to the Tickers constructor (fetching multiple Ticker objects)

### ISSUE THREAD

**Issue by mcpacific** [ranaroussi/yfinance#677]
I see that caching calls to the API is supported for single Ticker requests, but I can't seem to get it to work when fetching multiple Ticker objects using `tickers = yf.Tickers('msft aapl goog')`. Is this possible?

I have tried the following but I get a TypeError:

```
import requests_cache
session = requests_cache.CachedSession('yfinance.cache')
session.headers['User-agent'] = 'my-program/1.0'
tickers = yf.Tickers('msft aapl goog', session=session)

TypeError: __init__() got an unexpected keyword argument 'session'
```

**Comment by olearyw** [comment]
I'm also having issues setting a user agent for numerous ticker requests.

has this problem been solved?
