### ISSUE TITLE
Fail to download data from non-alphabetical tickers

### ISSUE THREAD

**Issue by theflyingwingman** [ranaroussi/yfinance#692]
Hi,
Since 2020-04-09 I have seen issues with downloading data from tickers containing non-alphabetical characters, e.g. "EUR=X", "LOR.DE", or "VOLV-B.ST". Data prior to April 9 is downloaded fine, at least for some tickers. Tickers with only alphabetical characters also seem fine.
I've tested with python 3.7, yfinance version v0.1.59 as well as some release prior to 0.1.55, with the same issue.
I also see the same issue with another library (yahoo-finance-pynterface), so perhaps this is an issue due to yahoo changing character encoding or no longer accepting non-alphabetical tickers?

**Comment by TheArcanePowers** [comment]
I'm not seeing any errors with `yfinance.Ticker().history(period="max")`, where is this happening?

<img width="255" alt="LORDE" src="https://user-images.githubusercontent.com/45922776/116695491-998a8200-a9b8-11eb-8ad6-b5b5158fea13.png"><img width="269" alt="VOLVB" src="https://user-images.githubusercontent.com/45922776/116695495-9abbaf00-a9b8-11eb-94fb-4979dfbf1800.png"><img width="227" alt="EURX" src="https://user-images.githubusercontent.com/45922776/116695499-9b544580-a9b8-11eb-8401-54ee870d22d9.png">

**Comment by theflyingwingman** [comment]
Thank you for checking!
Perhaps the error is on my side, like getting my IP blocked by Yahoo. I've heard that happens.
I will see if I can find the cause. I'll close this issue since it seems unrelated to yfinance.
