### ISSUE TITLE
Ticker('ticker').history( interval = "1mo") brings up divdends

### ISSUE THREAD

**Issue by prettypls** [ranaroussi/yfinance#693]
It's as the title says. Grabbing historical data also includes dividends. I want to be able to grab just the price data without the dividends. Any way to do this?

**Comment by AnanDoh** [comment]
If your data is in a pandas dataframe you can just do this. 

.history( interval = "1mo").drop(columns=['Dividends', 'Stock Splits'])

If its not id suggest making it so for easier use
