### ISSUE TITLE
fiftyTwoWeekLow is pulling inaccurate data

### ISSUE THREAD

**Issue by monkey-n-mango** [ranaroussi/yfinance#697]
When accessing information via the info function, the information returned for column "fiftyTwoWeekLow" is returning the incorrect information.

Reference stock ticker ACCD and cross verify with online sources to verify.

![image](https://user-images.githubusercontent.com/21172532/116544634-03216800-a8b5-11eb-9469-6bc8522af14c.png)

![image](https://user-images.githubusercontent.com/21172532/116544743-251aea80-a8b5-11eb-9f62-4080389c94ed.png)

**Comment by silvavn** [comment]
The problem is the data source and not the library itself. 
You are comparing Google Data With Yahoo Data.

As of June 05 **yahoo** shows: 
![image](https://user-images.githubusercontent.com/37382997/120905720-420faf80-c611-11eb-8851-65a03e13dd58.png)
