### ISSUE TITLE
Add function to map MIC to yahoo suffix

### ISSUE THREAD

**Issue by mxdev88** [ranaroussi/yfinance#702]
In most cases, Yahoo Finance builds its symbol from the ticker symbol + a [yahoo market suffix](https://help.yahoo.com/kb/finance-for-web/SLN2310.html;_ylt=AwrJKiCZFo9g3Y8AsDWPAwx.;_ylu=Y29sbwMEcG9zAzEEdnRpZAMEc2VjA3Ny?locale=en_US)

It would be quite useful if the ```yfinance``` had a built in way to map [MIC code](https://www.iso20022.org/market-identifier-codes) to Yahoo suffixes.

For example,
```py
suffix = yf.market_suffix(mic='XPAR')
```

This would allow to 'easily' build many of the yahoo symbols from systems that use MIC as market identifiers.

e.g. 'XPAR' => '.PA', 'XNYM' => '.NYM',  'XCBT' => '.CBT', and so on...

@ranaroussi, if that makes sense I can contribute a PR.

**Comment by ValueRaider** [comment]
As only you have requested this, best if you implement outside `yfinance` to minimise code bloat.

**Comment by PythonPeterr** [comment]
@mxdev88  did u find a fix for this?

**Comment by mxdev88** [comment]
> [@mxdev88](https://github.com/mxdev88) did u find a fix for this?

I'm mapping myself. Glad to see i'm not the only one anymore 🙂

**Comment by PythonPeterr** [comment]
Can u share it with me pls :)?

**Comment by ValueRaider** [comment]
@mxdev88 Can you publish code on Github so we can evaluate adding to yfinance?

**Comment by mxdev88** [comment]
> [@mxdev88](https://github.com/mxdev88) Can you publish code on Github so we can evaluate adding to yfinance?

@ValueRaider @PythonPeterr created a [PR](https://github.com/ranaroussi/yfinance/pull/2579). It's really only a mapping between official MIC code and Yahoo suffix.
