### ISSUE TITLE
Is there a way to add to the cached data so only the latest (uncached) OHLC data is downloaded?

### ISSUE THREAD

**Issue by olearyw** [ranaroussi/yfinance#704]
Can someone please explain how the session = session feature works?

For this specific ticker "4771.T", when I use session = session, I get a dataframe which is missing the latest day of data (as below)

![image](https://user-images.githubusercontent.com/59157444/117283095-ceab3e80-aea8-11eb-812c-0bbe89551b87.png)

**Comment by olearyw** [comment]
UPDATE. I understand that it is only loading the cached data from when I first made the call. Is there a way to add to the cached data for the most up to date dates which aren't in the cache?

Or do I have to clear the cached data everytime I make the call?

**Comment by silvavn** [comment]
You could just download the last few days and update the current DataFrame.
