### ISSUE TITLE
Cost of revenue value is not correct

### ISSUE THREAD

**Issue by portefeuille** [ranaroussi/yfinance#710]
I'm taking [this ticker](https://finance.yahoo.com/quote/VOC.MC/financials?p=VOC.MC) as an example.

For 2020-30-12, we have Cost of Revenue = 79,020,000

When I do this : 

```
>>> import yfinance as yf
>>> stock = yf.Ticker("VOC.MC")
>>> stock.financials
```

I get Cost of Revenue = 178,061,000.

Gross Profit is also incorrect.

Thank you

**Comment by moritzwilksch** [comment]
Is this a possible dupe with #700
