### ISSUE TITLE
2016-01-04 prices are wrong

### ISSUE THREAD

**Issue by csfreebird** [ranaroussi/yfinance#72]
Today, I compare the data retrieved by yfinance with yahoo site. I found they are different.
the data from yfinance:
```
from pandas_datareader import data as pdr
import fix_yahoo_finance as yf
yf.pdr_override()
data = pdr.get_data_yahoo("AAPL", start="2016-01-04", end="2016-01-05")
[*********************100%***********************]  1 of 1 downloaded
>>> data
                  Open        High    Low       Close  Adj Close    Volume
Date                                                                      
2016-01-04  102.610001  105.370003  102.0  105.349998  99.117409  67649400
```
but the data observed from yahoo site is below:(the high, low, close and volume are not same)
![yahoo2](https://user-images.githubusercontent.com/870486/59148191-2a0ff000-8a38-11e9-83ae-418c8481391f.png)

**Comment by ranaroussi** [comment]
According to this, the prices looks ok:
https://finance.yahoo.com/quote/AAPL/history?period1=1451772000&period2=1451944800&interval=1d&filter=history&frequency=1d

**Comment by csfreebird** [comment]
My friend sees the data using another financial product. It's the same as history data from Yahoo.
I guess there is something wrong with Yahoo interactive stock chart page.
Will close this issue and thank you.
