### ISSUE TITLE
Question Regarding Income Statement/Shares Outstanding/EPS Data

### ISSUE THREAD

**Issue by chinmayandhare** [ranaroussi/yfinance#723]
Hi! I had a question if we can get income statement as well with yfinance. I was looking to pull EPS data/ Basic Average Shares data (for 3-4 years) for companies from companies income statement, but did not see an option to do that.  Is there any way we can do that? I looked into balancesheets, financials, earnings & even cashflow, but did not see eps or number of shares data anywhere in them. (I do know from stock.info we get shares outstanding & eps for current year, but wanted to look at the data for 3-4 years from income statement)

Thank you.

**Comment by pankaj-kvhld** [comment]
@chinmayandhare DId you manage to solve this?

**Comment by chinmayandhare** [comment]
Hi Pankaj. I wanted this extra data or a way to get it.
