### ISSUE TITLE
Balance Sheet Treasury Stock Data is INCORRECT

### ISSUE THREAD

**Issue by chinmayandhare** [ranaroussi/yfinance#724]
Hi, the treasury stock data that balance sheet is pulling is incorrect. 
<img width="737" alt="Screen Shot 2021-05-27 at 8 07 34 PM" src="https://user-images.githubusercontent.com/84943063/119915092-55db5780-bf27-11eb-8459-645d68f1dd4f.png">
<img width="1096" alt="Screen Shot 2021-05-27 at 8 08 11 PM" src="https://user-images.githubusercontent.com/84943063/119915102-5aa00b80-bf27-11eb-92c7-6bf3183af90a.png">

**Comment by silvavn** [comment]
Code to reproduce issue:
```python
import yfinance as yf
stock = yf.Ticker("MSFT")
dfBS = stock.balance_sheet
print(dfBS)
```

**Comment by olippuner** [comment]
Please recheck your statement. Please, point out what the expected problem should be.
Your second screenshot has no header titles. 
Just checking keyfigure "Total Liab" I get a 100% match. 
Despite your incomplete information, I guess there is no error. Eg. 183,007 USD / 10^6  == 183007000000 USD (USD?)
Just do the matching work correctly ....

**Comment by chinmayandhare** [comment]
The total liab is correct. I meant the treasury stock data in the same balance-sheet is wrong. In the photo shared, if you take a look at 3186000000. This is actually accumulated & comprehensive income as shown on morningstar balance sheet for msft stock.  I am pointing to the treasury stock data. Rest of the numbers are good.

**Comment by chinmayandhare** [comment]
Also there is no way to pull sharesoutstanding data for previous years. I pointed this out as well but did not get any response to my question. Is it possible to include that data in yfinance. (Shares Outstanding of Previous Years)

Thank you.

**Comment by ValueRaider** [comment]
Regarding 'shares outstanding' - yes it is possible, see experimental git branch `feature/share-count`, feedback needed.
