### ISSUE TITLE
Windows download and extraction always fails

### ISSUE THREAD

**Issue by viai957** [ranaroussi/yfinance#725]
windows download always fails while downloading and installation through anaconda prompt using "conda install -c ranaroussi yfinance"  I tried recreating and redownloading the file but it did not work 
![image](https://user-images.githubusercontent.com/29157342/120225032-23e92e80-c262-11eb-9f6f-122ad0846c17.png)

**Comment by silvavn** [comment]
Please clone the repo until we do a new release.
