### ISSUE TITLE
Ticker function returns NULL in a loop

### ISSUE THREAD

**Issue by snehil2010** [ranaroussi/yfinance#729]
HI,

I am invoking Ticker() function is a loop for fetching data for around 50000 symbols. While it works fine for first 500~ symbols, its starts returning NULL values after that.

Manually executing the same function (outside the loop) seems to work fine. Any idea what could be the issue?

PS - This was working fine until two weeks ago

**Comment by bkcollection** [comment]
I am facing the same issue using pandas DataReader to pull historical data and it only works fine for the first few data and then it will display null for the last historical data.
Not sure if there are a way to overcome it.

**Comment by Okohedeki** [comment]
@snehil2010 Do you have an example on how you are implementing the code?
