### ISSUE TITLE
.financials and .quarterly_financials 

### ISSUE THREAD

**Issue by sbhadade** [ranaroussi/yfinance#745]
@ranaroussi    .financials and .quarterly_financials  end points return nothing ? Also .institutional_holders and .major_holders returns nothing ...Please update

**Comment by Tienduyvo** [comment]
I can confirm this. Did yahoo change something?

**Comment by Umberto3** [comment]
Same here. Triyng to load ticker.info for Swiss stocks XY.SW returns "logo_url" and no info. It worked perfectly yesterday!
