### ISSUE TITLE
yfinance has completely stopped working

### ISSUE THREAD

**Issue by matt-wetmore** [ranaroussi/yfinance#748]
I can't find any info on this issue, but I have no idea why it's happening.  Been using yfinance to pull data from a few hundred stocks each day, and it's been working fine for a few months.  Then last night, suddenly every single ticker symbol gives a "SymbolWarning: Failed to read symbol" error.  Every single one.  Tried running the code again, tried waiting until this morning to run it, it's still happening.  Is it possible yahoo is blocking my IP address or something?  I tried adding a time.sleep method of 1 second between each stock to avoid this, but it doesn't seem to have done anything, so I removed it.

Code below:
`import pandas_datareader as web
from datetime import datetime
import pandas as pd

start = datetime(2020,9,1)
end = datetime(2021,12,31)
stock = [ 'ACHC',   'ACIW', [many more stocks listed here cut for simplicity], 'TECH',  'SAM']
 

df = web.DataReader(stock, 'yahoo', start, end)
df.to_excel(f'excelfilename.xlsx')`

**Comment by jonathanng** [comment]
This works:

https://github.com/ranaroussi/yfinance/pull/749

**Comment by kcgiese** [comment]
Historical data is still available but calls to 'Ticker' fail with a 404 Not Found error. It started between 4 and 7 pm EDT July 1.

**Comment by matt-wetmore** [comment]
Ah, so this is something with Yahoo itself?  Or just yfinance?  It isn't unique to me, in other words?

What can be done to fix it?

**Comment by lazarcon** [comment]
```pip install git+https://github.com/ranaroussi/yfinance.git@refs/pull/749/merge```
#749 works for some, but not all tickers, examples:
US - work fine
UK: BHP.L does not work, GSK.L does work.
Germany: BAYN.DE - works yet BAYN.F does not.
Switzerland: SREN.SW - does not work

**Comment by attapalace** [comment]
any solution yet

**Comment by lazarcon** [comment]
unfortunately not.

**Comment by ranaroussi** [comment]
yfinance 0.1.60.0 was just released and it should solve this issue

**Comment by matt-wetmore** [comment]
Just upgraded, still giving me the SymbolWarning error on every single stock.

**Comment by impredicative** [comment]
@matt-wetmore If you just want to suppress the warning:

```python
import contextlib
import io
import yfinance as yf

with contextlib.redirect_stdout(io.StringIO()):
    yf.download(...)
```

This suppression is ugly but it looks to work for me.
