### ISSUE TITLE
Not able to get info

### ISSUE THREAD

**Issue by Sanjay-Ganapathi** [ranaroussi/yfinance#750]
yfinance is not giving info for stocks other than US.This issue has started from today
`
bsoft = yf.Ticker('BSOFT.NS')

bsoft.info
`

Response:
`{'logo_url': ''}`

**Comment by fneyron** [comment]
Same issue here. Has there been no recent commit, I guess this is due to a change in Yahoo Finance website.

**Comment by AndreiDavydov** [comment]
Same issue for 'APEI', 'IMEU.AS', 'MSM', 'EMAE.PA', 'VWRL.AS', 'VOW.DE' from my side. 
`{'logo_url': ''}` is default callback for unknown ticker, I guess.

**Comment by CyberDeus** [comment]
Had the same issue. #749 has solved it for me:

**Comment by fneyron** [comment]
> Had the same issue. #749 has solved it for me

Exact, `pip install git+https://github.com/ranaroussi/yfinance.git@refs/pull/749/merge` work well

TY

**Comment by Sanjay-Ganapathi** [comment]
Closing the issue 
Solved #749
