### ISSUE TITLE
Empty info for some stocks

### ISSUE THREAD

**Issue by dsotr** [ranaroussi/yfinance#752]
Using "ENI.MI" returns empty info:

```
import yfinance as yf
yf.Ticker("ENI.MI").info
```
returns `{'logo_url': ''}`

Other stock work correctly, e.g. 

```
yf.Ticker("GOOG").info
```

There seems to be a problem with ".MI" codes as, for example, "STLA.MI", "NEXI.MI" have the same issue.

**Comment by Sanjay-Ganapathi** [comment]
https://github.com/ranaroussi/yfinance/issues/750#issuecomment-873364073
Worked for me

**Comment by MikkelBoedker** [comment]
Having the same issue for some tickers such as "CRH", "ESCA" and "DHIL", while others work fine

**Comment by DefJes** [comment]
Having the same problem with Canadian tickers that have .TO on the end. Seems like it's an issue with any tickers requiring a "."

**Comment by Sanjay-Ganapathi** [comment]
> Having the same problem with Canadian tickers that have .TO on the end. Seems like it's an issue with any tickers requiring a "."

Upgrade to newer version released yesterday (0.1.60)
Everything working as intended

`pip install --upgrade yfinance`

**Comment by DefJes** [comment]
That worked, thank you.

**Comment by dsotr** [comment]
Worked, thanks!
