### ISSUE TITLE
Feature Request: Include Adjusted Close in history function

### ISSUE THREAD

**Issue by anarchy89** [ranaroussi/yfinance#753]
Is it possible to have a column with the adjusted close as well when I run this function

yfinance.Ticker("AAPL").history(period='max')

Currently, the columns are  Open    High     Low   Close     Volume  Dividends  Stock Splits, However When I do yf.download, I get Open High Low Close Adj Close and Volume.

Is this possible?

**Comment by ranaroussi** [comment]
Just use:
`yf.Ticker("AAPL").history(period='max', auto_adjust=False)`
