### ISSUE TITLE
Balance_sheet not working currently?

### ISSUE THREAD

**Issue by Rapid1898-code** [ranaroussi/yfinance#755]
Hello - i think yahoo finance changed something and the balance_sheet isn´t working anymore - could this be?

```
import yfinance as yf
ticker = "AAPL"
dataYF = yf.Ticker(ticker)
print(dataYF.balance_sheet)
```

Output is currently only a empty []
(but this worked appr. one week ago without problems)

**Comment by Gdango** [comment]
It's working for me now.

![image](https://user-images.githubusercontent.com/24763732/124427562-677efe80-dd20-11eb-9eae-2b202b86cf82.png)

**Comment by Rapid1898-code** [comment]
With the above code its still not working for me - empty list.

It only works when i define a header like that - without header it isn´t working - in the past this was possible.

```
import requests_cache
session = requests_cache.CachedSession('yfinance.cache')
session.headers['User-agent'] = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
ticker = "AAPL"
dataYF = yf.Ticker(ticker, session=session)
print(dataYF.balance_sheet)
```

**Comment by JESSE-star-byte** [comment]
Had the same problem, session fixed it for me also!

> With the above code its still not working for me - empty list.
> 
> It only works when i define a header like that - without header it isn´t working - in the past this was possible.
> 
> ```
> import requests_cache
> session = requests_cache.CachedSession('yfinance.cache')
> session.headers['User-agent'] = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
> ticker = "AAPL"
> dataYF = yf.Ticker(ticker, session=session)
> print(dataYF.balance_sheet)
> ```

**Comment by Rapid1898-code** [comment]
But how can i do this solution without the caching?
(i don´t need the caching and dislike the big file which is then stored locally... i only need the header to work...)

When i simply delete / uncoment the requests_cache line - of course the header is also not working anymore...

How can i do this only for the headers?

```
import requests_cache
session = requests_cache.CachedSession('yfinance.cache')
session.headers['User-agent'] = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
ticker = "AAPL"
dataYF = yf.Ticker(ticker, session=session)
print(dataYF.balance_sheet)
```
