### ISSUE TITLE
Explicit handling of delisted stocks, example TRST.TO

### ISSUE THREAD

**Issue by kucharskim** [ranaroussi/yfinance#757]
Not sure is this intended or not, but recently code change and does NOT throws exception now for delisted stocks. Could delisted stocks be explicitly handled via specific return information or specific exception?

**Comment by kucharskim** [comment]
Ok, so before it was KeyError exception:

```
        ticker = yfinance.Ticker(symbol)
        try:
                inf = ticker.info
        except KeyError:
                # delisted
```

**Comment by kucharskim** [comment]
I see this problem is in my code, as return value changed. Before it was `KeyError` now it's:
      {'logo_url': '', 'regularMarketPrice': None}

**Comment by silvavn** [comment]
Has the problem been solved?
yes: kindly close
no: provide what you currently see and what you expect to see and a code example.

**Comment by kucharskim** [comment]
Well, I'm not sure what to expect. I guess consistent or agreed upon behavior for delisted stocks, so I can handle it properly on my end.

**Comment by smijoseph** [comment]
I have the similar problem when run into delist symbol under multithread downloading. The data frame add one extra 00:00:00 column after the ticket. I solve the problem by modify the multi.py line 114 to add _realign_dfs() as follow 
    if shared._ERRORS and show_errors:
        **_realign_dfs()**
        print('\n%.f Failed download%s:' % (
            len(shared._ERRORS), 's' if len(shared._ERRORS) > 1 else ''))
        # print(shared._ERRORS)
        print("\n".join(['- %s: %s' %
                         v for v in list(shared._ERRORS.items())])) 

if the delist error exception  can be raised. It will be handled correctly in exception code.

**Comment by ValueRaider** [comment]
`info` is now `None` for delisted tickers, so will trigger exceptions. Solved?
