### ISSUE TITLE
Yfinance not working 

### ISSUE THREAD

**Issue by Lermanator** [ranaroussi/yfinance#763]
Hi, I was using yfinance in google collab and all of a sudden i keep getting the same error
![image](https://user-images.githubusercontent.com/68395873/125122387-5852d480-e0c3-11eb-838f-fe1d0e13b2ce.png)

It is not just for me, since I had my friend run the code in google collab on his computer and it also did not work.

The code is not the issue as well.

**Comment by twister077** [comment]
Still the same here

**Comment by burnsd079** [comment]
I am experiencing the same error @Lermanator is experiencing using code that was properly decoding JSON this morning.

**Comment by aditya113141** [comment]
Same here. It was working a few hours ago.

**Comment by mingwugmail** [comment]
Can you guys search your error massage on issues first, instead of uploading screenshot images?

See issue #764

**Comment by Lermanator** [comment]
> Can you guys search your error massage on issues first, instead of uploading screenshot images?
> 
> See issue #764
> 
> #760

I saw those before, but I said google collab. How do we update in google collab?

**Comment by Lermanator** [comment]
![image](https://user-images.githubusercontent.com/68395873/125126871-bb476a00-e0c9-11eb-9a74-fc3bc40efd78.png)
I tried doing !pip install yfinance -U to get the most updated version, but it's still not working

**Comment by Lermanator** [comment]
> ![image](https://user-images.githubusercontent.com/68395873/125126871-bb476a00-e0c9-11eb-9a74-fc3bc40efd78.png)
> I tried doing !pip install yfinance -U to get the most updated version, but it's still not working

Nevermind, run the !pip install yfinance -U and restart runtime and everything works!
