### ISSUE TITLE
Unable to get any stock price data - JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Aditya-Bahl** [ranaroussi/yfinance#767]
import yfinance as yf

apple = yf.Ticker("AMZN")

hist = apple.history(period="max", start="2021-05-20", end="2021-06-04")

**Comment by Aditya-Bahl** [comment]
It was working fine, but now just gives the JSON Decode Error.

**Comment by 315jordan09** [comment]
Looks like I am getting the same error.
Seems like a server may be down? Not really sure.

This is the line I am running:
return yf.download(tickers = ticker, period = "5d", group_by = 'ticker', threads = False)

This is the error I am getting:
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by 315jordan09** [comment]
Solution:
pip3 install yfinance --upgrade --no-cache-dir
or use pip if you are not using pip3

**Comment by Aditya-Bahl** [comment]
It worked for me in PyCharm, but is still not working in my Conda environment even after running those pip commands.

**Comment by jim-schwoebel** [comment]
Yup same issue!

**Comment by jim-schwoebel** [comment]
Thank you also for building this scraper. It is awesome.

**Comment by jim-schwoebel** [comment]
pip3 install yfinance --upgrade --no-cache-dir solved it for me too!

**Comment by stephenhky** [comment]
yeah, just works for me by simply upgrading it.

**Comment by SimonHuddart** [comment]
I'm having the same issue and upgrading the package did not appear to fix it.

**Comment by juanpacajigas** [comment]
The upgrade did it for me. Thanks!
