### ISSUE TITLE
 Error when doing a = yf.Ticker("AAPL").info

### ISSUE THREAD

**Issue by java-final-project-ml** [ranaroussi/yfinance#774]
html = session.get(url=url, proxies=proxy, headers=user_agent_headers).text

  File "/opt/anaconda3/envs/python/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)

  File "/opt/anaconda3/envs/python/lib/python3.7/site-packages/requests/api.py", line 60, in request
    with sessions.Session() as session:

  File "/opt/anaconda3/envs/python/lib/python3.7/site-packages/requests/sessions.py", line 414, in __init__
    self.mount('https://', HTTPAdapter())

 super(HTTPAdapter, self).__init__()

TypeError: super(type, obj): obj must be an instance or subtype of type******

**Comment by stevenwong** [comment]
Looks like Yahoo is blocking requests without a user agent. Returns 403 when I ran the code above. I've worked around it inserting this into `base.py`

```
        # Yahoo returns 403 error code. So pretend we're a Chrome user
        agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        headers = {'User-Agent': agent}
        data = self.session.get(url=url, params=params, proxies=proxy, headers=headers)
```

**Comment by mnalevanko** [comment]
The workaround by @stevenwong works just fine. Thanks!

**Comment by joshpearce** [comment]
The issue seems to be more than just the user agent. I'm seeing a sporadic error from yahoo, saying that 1 minute resolution is not available for more than a 7 day period, but I am not asking for 1 minute, I'm asking for 1 day over 3 months. If I extract the url used by yfinance, and send it with curl, it works some of the time, and other times I get the error.

**Comment by BDTrooper** [comment]
Had the same problem for around ten days, upgrading to 0.1.62 solved the issue (beside the json error) for me.

**Comment by ScottSharmal** [comment]
> Had the same problem for around ten days, upgrading to 0.1.62 solved the issue (beside the json error) for me.

Hello. What do you mean "0.1.62 solved the issue (beside the json error)"? You had the JSON error for 10 days and 1.62 fixed the issue? Or you're still seeing the JSON issue after the 1.62 update? thank you

**Comment by BDTrooper** [comment]
To clarify: 10-7 days ago i had the error mentioned here, then i got a nearly empty ticker.info dict (only with something like web_url =), today the json error.
With the upgrade the json error is gone and the ticker info dict shows the content as usual.

**Comment by engineertree5** [comment]
> Looks like Yahoo is blocking requests without a user agent. Returns 403 when I ran the code above. I've worked around it inserting this into `base.py`
> 
> ```
>         # Yahoo returns 403 error code. So pretend we're a Chrome user
>         agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
>         headers = {'User-Agent': agent}
>         data = self.session.get(url=url, params=params, proxies=proxy, headers=headers)
> ```

What line within the base.py file are you modifying? @mnalevanko @stevenwong 415?

**Comment by linhongbin** [comment]
@mnalevanko answer works for me too.

Go to round line 150 and replace the original content with
```python
        agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        headers = {'User-Agent': agent}
        url = "{}/v8/finance/chart/{}".format(self._base_url, self.ticker)
        data = self.session.get(url=url, params=params, proxies=proxy, headers=headers)
```

**Comment by stevenwong** [comment]
Just noticed that #764 mentions the JSON error (when you download history). Maybe it's already fixed in the latest version.

**Comment by Philip030601** [comment]
hello,  

> @mnalevanko answer works for me too.
> 
> Go to round line 150 and replace the original content with
> 
> ```python
>         agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
>         headers = {'User-Agent': agent}
>         url = "{}/v8/finance/chart/{}".format(self._base_url, self.ticker)
>         data = self.session.get(url=url, params=params, proxies=proxy, headers=headers)
> ```

Can you please tell me which code in the original I need to replace with the new code.  Old code around line 50 is as follows: ```
![image](https://github.com/ranaroussi/yfinance/assets/104045601/bfccc506-6f48-4552-ab10-efcf9a4f1865)
 ```

**Comment by Philip030601** [comment]
Much 

> Looks like Yahoo is blocking requests without a user agent. Returns 403 when I ran the code above. I've worked around it inserting this into `base.py`
> 
> ```
>         # Yahoo returns 403 error code. So pretend we're a Chrome user
>         agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
>         headers = {'User-Agent': agent}
>         data = self.session.get(url=url, params=params, proxies=proxy, headers=headers)
> ```

hello,  Hope your are doing well. Just ran accross same problem.  Can you please tell me which code in the original I need to replace with the new code. Old code around line 150 is as follows:  
![image](https://github.com/ranaroussi/yfinance/assets/104045601/1b95e4cc-9d99-4566-be66-2ac92d468ad1)
