### ISSUE TITLE
Does not work !

### ISSUE THREAD

**Issue by Unixware** [ranaroussi/yfinance#775]
Is this project for real ? 

running just the .info returns ...nothing! 

`$ python -m pdb  ./stock.py 
> /home/chris/stock.py(1)<module>()
-> import yfinance as yf
(Pdb) n
> /home/chris/stock.py(3)<module>()
-> msft = yf.Ticker("MSFT")
(Pdb) n
> /home/chris/stock.py(6)<module>()
-> msft.info
(Pdb) n
--Return--
> /home/chris/stock.py(6)<module>()->None
-> msft.info
(Pdb) n
--Return--
> <string>(1)<module>()->None
(Pdb) 
`

yfinance Version: 0.1.63

**Comment by sfavorite** [comment]
Appears to be related to [$774](https://github.com/ranaroussi/yfinance/issues/774)

**Comment by Unixware** [comment]
thanks... weird does not return anything useful at least ... darn yahoo...
