### ISSUE TITLE
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 

### ISSUE THREAD

**Issue by dipenduc39** [ranaroussi/yfinance#777]

**Comment by dipenduc39** [comment]
![Screenshot (394)](https://user-images.githubusercontent.com/42491963/125308160-4cc70e00-e34e-11eb-860f-fb62a50ccf39.png)

**Comment by sergio-twistlab** [comment]
see #764 

upgrading should fix the issue.

**Comment by dataxp** [comment]
see #764

Upgrading yfinance to 0.1.62 should fix the problem

**Comment by cpd55** [comment]
Trying to download `data = yf.download(name, start=start_from, end=end_to)`
I have upgraded to **0.1.62** then **0.1.63** but getting:

```
Traceback (most recent call last):
  File "C:\anaconda3\envs\b\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\anaconda3\envs\b\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\anaconda3\envs\b\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\anaconda3\envs\b\lib\site-packages\yfinance\multi.py", line 166, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "C:\anaconda3\envs\b\lib\site-packages\yfinance\multi.py", line 178, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "C:\anaconda3\envs\b\lib\site-packages\yfinance\base.py", line 156, in history
    data = data.json()
  File "C:\anaconda3\envs\b\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\anaconda3\envs\b\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\anaconda3\envs\b\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\anaconda3\envs\b\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
```

**Comment by ScottSharmal** [comment]
> Trying to download `data = yf.download(name, start=start_from, end=end_to)`
> I have upgraded to **0.1.62** then **0.1.63** but getting:
> 
> ```
> Traceback (most recent call last):
>   File "C:\anaconda3\envs\b\lib\threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "C:\anaconda3\envs\b\lib\threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\anaconda3\envs\b\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
>     return callee(*args, **kwargs)
>   File "C:\anaconda3\envs\b\lib\site-packages\yfinance\multi.py", line 166, in _download_one_threaded
>     data = _download_one(ticker, start, end, auto_adjust, back_adjust,
>   File "C:\anaconda3\envs\b\lib\site-packages\yfinance\multi.py", line 178, in _download_one
>     return Ticker(ticker).history(period=period, interval=interval,
>   File "C:\anaconda3\envs\b\lib\site-packages\yfinance\base.py", line 156, in history
>     data = data.json()
>   File "C:\anaconda3\envs\b\lib\site-packages\requests\models.py", line 900, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "C:\anaconda3\envs\b\lib\json\__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "C:\anaconda3\envs\b\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\anaconda3\envs\b\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
> ```

Same here. Been trying for 2 days to resolve and still nothing.

**Comment by kcgiese** [comment]
I had this problem but installing 0.1.63 has fixed it.

**Comment by yfast** [comment]
I have the latest version 0.1.63 and I cannot access various data including ticker.history().
I receive the same JSONDecodeError every time I try.
Is it a systemwide problem?

**Comment by manishbararia** [comment]
I am also getting the same error. Looks like 0.1.63 also isnt solving the problem. Has anyone been able to resolve this yet?

**Comment by vProto** [comment]
I have the same issue here. Can you please advise on a fix?

**Comment by manishbararia** [comment]
I updated to 0.1.63, and it worked for me. Thanks!

> I am also getting the same error. Looks like 0.1.63 also isnt solving the problem. Has anyone been able to resolve this yet?

**Comment by manishbararia** [comment]
I updated to 0.1.63, and it worked for me. Thanks!

**Comment by mcknil** [comment]
I'm on 0.1.63, and get a similar error (but in different slightly different line of the code?)
my traceback looks like 
    hx = yf.download(ticker, start=start_retrieve_str, end=end_retrieve_str, interval=interval, threads=False)
  File "/opt/anaconda3/lib/python3.7/site-packages/yfinance/multi.py", line 106, in download
    rounding=rounding)
  File "/opt/anaconda3/lib/python3.7/site-packages/yfinance/multi.py", line 185, in _download_one
    rounding=rounding, many=True)
  File "/opt/anaconda3/lib/python3.7/site-packages/yfinance/base.py", line 157, in history
    data = data.json()
  File "/opt/anaconda3/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/opt/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/opt/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ftamimi** [comment]
This worked for me after upgrading to 0.1.163 - thank you

**Comment by vProto** [comment]
Worked for me too. Cheers.

**Comment by prashantnagrecha** [comment]
worked for me as well. just make sure you checkmark to select 0.1.63 in intellij otherwise it will upgrade.

**Comment by yfast** [comment]
I had the same problem.
I use Jupyter Notebook.
Try entering the following code in Jupyter Notebook:
!pip install yfinance

**Comment by akitxu** [comment]
I have the same problem; i use python 3.8.10 and yfinance 0.1.63

**Comment by akitxu** [comment]
I have the same problem; i use python 3.8.10,  yfinance 0.1.63 and jupyter lab 3.0.16

**Comment by dipenduc39** [comment]
Upgrade to 0.1.62 solve my problem ..
