### ISSUE TITLE
download date problem

### ISSUE THREAD

**Issue by wanghan7678** [ranaroussi/yfinance#78]
Hi I'm trying to run the below codes:

data = yf.download("AAPL", start="2019-07-4", end="2019-07-05")
print(data)

But it gives the below results:
              Open    High     Low   Close  Adj Close    Volume
Date                                                           
2019-07-03  203.28  204.44  202.69  204.41     204.41  11362000

It should give a 2019-07-05 data but it was 07-03 instead.

**Comment by zhenwenc** [comment]
This is an issue on the source: https://finance.yahoo.com/quote/AAPL/history?period1=1562155200&period2=1562241600&interval=1d&filter=history&frequency=1d
