### ISSUE TITLE
How to check if element exist or not?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [ranaroussi/yfinance#782]
Based on your example in `README.md` I tried to get data about this ETF

https://www.boerse-frankfurt.de/etf/vanguard-ftse-developed-asia-pacific-ex-japan-ucits-etf-usd-accumulating

```
>>> vgek = yf.Ticker('VGEK')
>>> vgek.info
{'regularMarketPrice': None, 'logo_url': ''}

```

But it is "empty".

1. How can I Check if a `Ticket()` object is valid in the meaning of it received data?
2. What happens in background? How do I know which "type" of stocks/ETFs/etc I can handle with yfinance and which not? For e.g. why can't I get data for my example ETF here?

**Comment by scottalreadytaken** [comment]
In this case you are looking for VGEK.DE. 
The autosuggest in the yahoo finance search bar will display valid tickers so you can manually tailor a list.  
I’m not sure if there is an automated way to check tickers before trying to obtain the data. It’s always good to log failures and maybe follow up on them manually as they can change for many reasons. For example if they are delisted.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
A bit late but I was able to check this and the features of your package.
It works well. The history() is the most important for me. Thank you so much!

With that I can create my own watchlist-like application on a server.
E.g. I am interested in situations where the current course is 5% (just an example value) higher/lower then the course one week ago. In my opinion I can watch tendencies or curve kinks.
