### ISSUE TITLE
Temporary missing entries on 1-hour candle data (v 0.1.63)

### ISSUE THREAD

**Issue by stefangab23** [ranaroussi/yfinance#789]
Just after the close of the market on 19/07/2021 I experienced some problems with getting the prices for the last 30 minutes when the interval parameter is set to '1h'. This happened only for some companies (e.g. ADM).
I attached below two captures:
- The DataFrames I was receiving at that moment (so the data was available when using a '30m' interval but unavailable for the '1h' interval)
![image_2021_07_19T22_19_32_545Z](https://user-images.githubusercontent.com/49208340/126305974-d5671600-5de1-4bfa-87e6-ab30c67ddce3.png)

- The DataFrame that I should have been received (extracted 13 hours after the market was closed)
![image_2021_07_20T09_56_16_103Z](https://user-images.githubusercontent.com/49208340/126306017-f3fba327-94ea-47b7-8566-2f437b89044e.png)

Anyone else faced this problem in the past? Should I consider this as a recurrent issue? Is the '30m' interval more correct or trustworthy?

Thank you for your help!!

**Comment by symm3tri** [comment]
I think I have a similar problem. When getting 30m data intraday for ^VIX, the data doesn't seem to update until halfway through the bar. Format in the image below is SPY data followed by VIX data (SPY, VIX, SPY, VIX, SPY, VIX) recorded at 10 minute intervals, with the bar start time replaced by the real time, when applicable.

![image](https://user-images.githubusercontent.com/88150252/127508089-4f5666c8-f164-4c5c-b611-2c7fbe152058.png)

**Comment by ValueRaider** [comment]
Problem still happening?
