### ISSUE TITLE
Why doesn't this package depend on yfinance itself?

### ISSUE THREAD

**Issue by ccharles** [ranaroussi/yfinance#79]
This library [appears to depend on `yfinance`][1]. Is there a reason that that dependency isn't specified in its `setup.py`?

**Edit:** That question has now been deleted. Here's a copy of what it said for posterity, with a few small edits for context:

> I'm trying to push my app [to Heroku] that uses module: `fix-yahoo-finance`, however in order to install that module i need to install module called `yfinance` first.
> So I placed `yfinance` module at top of requirements.txt list and the other one at the bottom. However when I push my app to heroku it still gives me an error:
> 
>     remote:          Downloading https://files.pythonhosted.org/packages/a5/f3/aba3b563452faaea71b4161754991e3143751ec9141d83c4bce05992332a/fix-yahoo-finance-0.1.37.tar.gz
>     remote:            Complete output from command python setup.py egg_info:
>     remote:            Traceback (most recent call last):
>     remote:              File "<string>", line 1, in <module>
>     remote:              File "/tmp/pip-build-k3a2lnr1/fix-yahoo-finance/setup.py", line 19, in <module>
>     remote:                from fix_yahoo_finance import __version__
>     remote:              File "/tmp/pip-build-k3a2lnr1/fix-yahoo-finance/fix_yahoo_finance/__init__.py",
>     line 22, in <module>
>     remote:                import yfinance
>     remote:            ModuleNotFoundError: No module named 'yfinance'
>     remote:
>     remote:            ----------------------------------------
>     remote:        Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k3a2lnr1/fix-yahoo-finance/
> 
> So I wonder what Im doing wrong. And how to fix this issue?

[1]: https://stackoverflow.com/q/56971743/354577

**Comment by ranaroussi** [comment]
Install yfinance instead of fix_yahoo_finance and use:

```import yfinance as yf```

**Comment by dan-singh** [comment]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-30-7b70635dcb62> in <module>
----> 1 import yfinance as yf

ModuleNotFoundError: No module named 'yfinance'

**Comment by jessyambz** [comment]
I also need to know how to fix that!

**Comment by TenzinSean** [comment]
same problem

**Comment by iktk2021** [comment]
same problem
