### ISSUE TITLE
Could not extract financial statements for certain stock tickers

### ISSUE THREAD

**Issue by tys203831** [ranaroussi/yfinance#795]
Cannot retrieve financial report such as income statement, balance sheet, cash flow of tickers of certain exchange market. For example, Bursa Malaysia.

Example tickers to test: 0200.KL

`import yfinance as yf`
`rev = yf.Ticker("0200.KL")`
`rev.financials`
`rev.balance_sheet`
`rev.cashflow`

You would find that these would not work for Bursa Malaysia's stock tickers.

**Comment by ManidharVutla** [comment]
Yes, can't retrieve financial information for  nyse ticker symbols (msft, ntap,...) as well.

**Comment by mrkgoh** [comment]
> Cannot retrieve financial report such as income statement, balance sheet, cash flow of tickers of certain exchange market. For example, Bursa Malaysia.
> 
> Example tickers to test: 0200.KL
> 
> `import yfinance as yf`
> `rev = yf.Ticker("0200.KL")`
> `rev.financials`
> `rev.balance_sheet`
> `rev.cashflow`
> 
> You would find that these would not work for Bursa Malaysia's stock tickers.

Is it working for you now? Or is it still open?
