### ISSUE TITLE
Ticker column has additional characters....

### ISSUE THREAD

**Issue by ScottSharmal** [ranaroussi/yfinance#796]
Pulling weekly and daily data. Have a "Ticker" column in both pulls. The daily is fine. But the weekly ticker column says this in every ticker. yfinance.Ticker object <AAPL> or yfinance.Ticker object <TSLA>

Would like column to say AAPL or TSLA. Here is part of code. 

        data = yf.download(ticker, group_by="Ticker", period="5Y", interval="1wk",prepost = True)
        data['ticker'] = yf.Ticker(ticker)

Was fine a few weeks ago. Any ideas? thanks.

**Comment by ValueRaider** [comment]
What exactly is problem? What are you expecting to happen?
