### ISSUE TITLE
Data inconsistency between yfinance and Yahoo Finance website for old data

### ISSUE THREAD

**Issue by jebjoya** [ranaroussi/yfinance#798]
Running the code:

`import yfinance`
`yfinance.Ticker("SPY").history(start="2000-03-10", end="2000-03-25", interval="1d")`

Returns the following:

![image](https://user-images.githubusercontent.com/10108452/127172909-67b5a5b8-d7c4-4514-9e94-fb9139b6b8bb.png)

Reviewing that same information on Yahoo Finance at [this URL](https://uk.finance.yahoo.com/chart/SPY) clearly shows the prices to be around the $150 mark, rather than the $90-100 mark that is returned by yfinance - for instance, for 20th March 2000, we see:

![image](https://user-images.githubusercontent.com/10108452/127173296-40475e7d-a58a-4c73-a1d3-7c2206a6229d.png)

Note all prices and the Volume appear to be inconsistent.  Any ideas what's going on with this old data?  (For reference, it's causing some issues visualising historical all-time-high information about the market)

**Comment by tys203831** [comment]
I think because for yfinance, the Close is actually the Adj Close. Meanwhile, yahoo finance chart is plotted using Close price instead of Adj Close.
