### ISSUE TITLE
New feature request - add "expense ratio"

### ISSUE THREAD

**Issue by moedi85** [ranaroussi/yfinance#801]
It would be great if "expense ratio" from the Yahoo Finance Summary tab would be added to the info that can be obtained from .info

**Comment by carlos-ventura** [comment]
Since this feature has been long due and nothing is changing just download the clone the repo
Edit base.py file and add the following after `# get info and sustainability
        data = utils.get_json(ticker_url, proxy, self.session)` is defined:

expenseRatio = (data
                        .get('fundProfile', {})
                        .get('feesExpensesInvestment', {})
                        .get('annualReportExpenseRatio', None))

        try:
            self._info['annualReportExpenseRatio'] = expenseRatio
        except Exception:
            pass

**Comment by Courvoisier13** [comment]
This should be implemented. it's very easy as well.

**Comment by ValueRaider** [comment]
@moedi85 @carlos-ventura  @Courvoisier13 Ran has granted me permissions to merge PRs etc, but help is appreciated in creating and/or reviewing PRs - anyone can do this.
