### ISSUE TITLE
No data returned for the current day - only on some hosts.

### ISSUE THREAD

**Issue by blackhaz** [ranaroussi/yfinance#805]
Two almost identical FreeBSD machines (in different data centers). When requesting:

ticker = yf.Ticker(symbol)
    data = ticker.history(period="max", auto_adjust = False)
    
For example, for symbol="WDC", one machine with Python 3.7 gets:
....
2021-08-06  67.580002  68.839996  66.839996  ...  4473500        0.0           0.0
2021-08-09  68.779999  68.790001  66.769997  ...  2599778        0.0           0.0

While the other machine with Python 3.8 has 2021-08-06 as the last row, basically it doesn't see today's data at all. Repeats on different days, so it is a recurring problem. Both machines have yfinance-0.1.63 installed. Literally pulling my hair out. Any ideas? 

P.S. When doing curl, I get this on the machine that does not see the last row:
$ curl https://query2.finance.yahoo.com/v8/finance/chart/WDC
{"chart":{"result":[{"meta":{"currency":"USD","symbol":"WDC","exchangeName":"NMS","instrumentType":"EQUITY","firstTradeDate":278692200,"regularMarketTime":1628280002,"gmtoffset":-14400,"timezone":"EDT","exchangeTimezoneName":"America/New_York","regularMarketPrice":68.76,"chartPreviousClose":67.07,"previousClose":67.07,"scale":3,"priceHint":2,"currentTradingPeriod":{"pre":{"timezone":"EDT","start":1628496000,"end":1628515800,"gmtoffset":-14400},"regular":{"timezone":"EDT","start":1628515800,"end":1628539200,"gmtoffset":-14400},"post":{"timezone":"EDT","start":1628539200,"end":1628553600,"gmtoffset":-14400}},"dataGranularity":"1m","range":"1d","validRanges":["1d","5d","1mo","3mo","6mo","1y","2y","5y","10y","ytd","max"]},"indicators":{"quote":[{}]}}],"error":null}}blackhaz@mu:~ $ 

When doing curl on another machine that sees the last row, I can see much more data. For example:

% curl https://query2.finance.yahoo.com/v8/finance/chart/WDC
{"chart":{"result":[{"meta":{"currency":"USD","symbol":"WDC","exchangeName":"NMS","instrumentType":"EQUITY","firstTradeDate":278692200,"regularMarketTime":1628528686,"gmtoffset":-14400,"timezone":"EDT","exchangeTimezoneName":"America/New_York","regularMarketPrice":67.985,"chartPreviousClose":68.76,"previousClose":68.76,"scale":3,"priceHint":2,"currentTradingPeriod":{"pre":{"timezone":"EDT","start":1628496000,"end":1628515800,"gmtoffset":-14400},"regular":{"timezone":"EDT","start":1628515800,"end":1628539200,"gmtoffset":-14400},"post":{"timezone":"EDT","start":1628539200,"end":1628553600,"gmtoffset":-14400}},"tradingPeriods":[[{"timezone":"EDT","start":1628515800,"end":1628539200,"gmtoffset":-14400}]],"dataGranularity":"1m","range":"1d","validRanges":["1d","5d","1mo","3mo","6mo","1y","2y","5y","10y","ytd","max"]},"timestamp":[1628515800,1628515860,1628515920,1628515980,1628516040,1628516100,1628516160,1628516220,1628516280,1628516340,1628516400,1628516460,1628516520,1628516580,1628516640,1628516700,1628516760,1628516820,1628516880,1628516940,1628517000,1628517060,1628517120,1628517180,1628517240,1628517300,1628517360,1628517420,1628517480,1628517540,1628517600,1628517660,1628517720,1628517780,1628517840,1628517900,1628517960,1628518020,1628518080,1628518140,1628518200,1628518260,1628518320,1628518380,1628518440,1628518500,1628518560,1628518620,1628518680,1628518740,1628518800,1628518860,1628518920,1628518980,1628519040,1628519100,1628519160,1628519220,1628519280,1628519340,1628519400,1628519460,1628519520,1628519580,1628519640,1628519700,1628519760,1628519820,1628519880,1628519940,1628520000,1628520060,1628520120,1628520180,1628520240,1628520300,1628520360,1628520420,1628520480,1628520540,1628520600,1628520660,1628520720,1628520780,1628520840,1628520900,1628520960,1628521020,1628521080,1628521140,1628521200,1628521260,1628521320,1628521380,1628521440,1628521500,1628521560,1628521620,1628521680,1628521740,1628521800,1628521860,1628521920,1628521980,1628522040,1628522100,1628522160,1628522220,1628522280,1628522340,1628522400,1628522460,1628522520,1628522580,1628522640,1628522700,1628522760,1628522820,1628522880,1628522940,1628523000,1628523060,1628523120,1628523180,162.... and so on...

Same curl requests.

**Comment by m4ccbr** [comment]
Hi,

I noticed the same thing today and I believe Yahoo is now tracking IP address. 
I believe it looks at some sort of black list before it provides any data, but this is just stupid, I would love to meet the brilliant mind that thought that had this great idea , because now I am forced to look at socks proxy.


regards,

**Comment by TravelTrader** [comment]
Same problem here. Local system is getting the data of the 08/09/2021 but my server system just receives 08/06/2021 as the last date.
Has anyone found another solution than using a proxy already?

**Comment by chemcoder-2020** [comment]
I ran into the same issue today which led to a no-trading day =.= I put a "sleep(1)" in my recursive loop and all is well. Maybe yahoo is tracking the frequency of data request?

**Comment by arielbell** [comment]
> > I ran into the same issue today which led to a no-trading day =.= I put a "sleep(1)" in my recursive loop and all is well. Maybe yahoo is tracking the frequency of data request?
> 
> This works for me as well. As far as I saw, they block or return something wrong (e.g. 100 times the avg. volume in the last day + missing entries) after around 300 consecutive requests.

Can you provide an example of the code you use?
I'm getting the same problem and I'm unable to fix it.

**Comment by chemcoder-2020** [comment]
Ok. So the issue came back. The better solution was to use OpenVPN and combined tunnels (ipv4 and ipv6) to hide your ip.
