### ISSUE TITLE
No daily data for 2021-08-02

### ISSUE THREAD

**Issue by allexch** [ranaroussi/yfinance#809]
version 0.1.163

After weekend I found, that in daily data constantly missing info on 02.08.2021 (Monday) on vast majority of tickers. Wtf?
This is ordinary trading day, no pauses and stops were detected.

See screenshot:
![image](https://user-images.githubusercontent.com/41727187/128851540-ba094bd0-a12c-4000-bb98-e314906809c6.png)

MSFT and AAPL are ok. But others..

**Comment by allexch** [comment]
Seemed to be not the library issue, but the Yahoo API glitch. I've tried to make direct response to the corresponding URL: ```https://query2.finance.yahoo.com/v8/finance/chart/ADBE?period1=1441054800&period2=1628370000&interval=1d&includePrePost=True&events=div%2Csplits ```
 and I've got nan values for this date in json. So that line is dropping later in library code with df.dropna() 
 
 Moreover, it is not repeating. Today ADBE is ok. But if I download f.e. 200 tickers simultaneously, al least one of them comes with nans for 2021-08-02, that leads to removing such line from dataframe for all downloaded tickers (date is index column).

**Comment by ohjason81** [comment]
I'm seeing the same not only for 2021-08-02 but also 2021-08-12. Strange...

**Comment by arielbell** [comment]
I'm seeing the same behaviour.
Seems like an inconsistency exist in the data retrieved from yahoo.
The strange part, is when I use their website, the data exist and is correct.

When retrieved with other stocks using the package, I see lots of missing data, in 2 days - 2/8/21 and 12/8/21.
@ranaroussi  - any ideas? do you think Yahoo is intentionally doing it?

**Comment by ohjason81** [comment]
Ok, I tried again some 12 hours later and I no longer got missing data for those dates. So Yahoo is definitely doing some kind of rate-limiting/throttling/blacklisting

**Comment by BigScaryExec** [comment]
I am still (August 22, 2021 at 3:30pm CT) having the same issue with August 2, 2021 data missing from the download.  I am downloading 2183 US listed stocks, and only 1175 have data for August 2, 2021.  All other days have complete data for a year (from August 21, 2021 through August 21, 2020, non-inclusively).

I have not seen this problem before.

Using this line of code: data_1_interim = yf.download(tickers = MYLIST ,start=startdate, end=enddate, threads = True, progress = False)
