### ISSUE TITLE
Certain ticker raises shape problem

### ISSUE THREAD

**Issue by tonyl518** [ranaroussi/yfinance#81]
When trying to download from a list of tickers, some tickers works fine but some does not.
They raise the problem associated with dataframe concatenation:

**Shape of passed values is (1421, 3030), indices imply (1413, 3030)**

It seems like for some tickers, the number of dates is not the same with some others

**Comment by ranaroussi** [comment]
Can you post the list of tickers you were using so I can dig deeper?

**Comment by ranaroussi** [comment]
Closing for now. Please reopen issue if the problem persists.

**Comment by tobigs** [comment]
I've recently run into this error too. (GSK.L)
Shape of passed values is (2, 31), indices imply (1, 31)
Other ticker like 1299.HK work perfectly fine.

**Comment by Narusi** [comment]
I got the same issue with Apple stock:
aapl = yf.Ticker('AAPL')
aapl.info

results in 
ValueError: Shape of passed values is (3, 31), indices imply (1, 31)

**Comment by rawmean** [comment]
Here is another example. AMZN, AAPL and some other tickers result in the same error. 
This seems to be related to a pandas dataframe conversion problem. 
can you please look into this?

```
tsla = yf.Ticker("TSLA")
tsla.info
```

`ValueError: Shape of passed values is (2, 31), indices imply (1, 31)`
