### ISSUE TITLE
Cannot get specific balance sheet data

### ISSUE THREAD

**Issue by Brandnewson** [ranaroussi/yfinance#813]
I can't seem to get the just one field of data from the dataframe

Specifically, I want to get "Total Current Assets" to be a variable for me to use in calculations. Any known way?

**Comment by ChrisChross** [comment]
This is how i did it: 
```
def return_specific(ticker):
    total_assets = ticker.balance_sheet
    df = total_assets.T
    return df["specific_column"]
```

you could get the date by index. However, i wonder if it is possible to declare the time period for the balance_sheet. Any ideas?
