### ISSUE TITLE
Yfinance does not provide continuous data on somedays

### ISSUE THREAD

**Issue by MANIRATHA** [ranaroussi/yfinance#817]
API does not provide data while on some days while the market is running. I did not get data on 10-08-21 and 17-08-21. This has been a persisting issue for over a year now.
```python
import yfinance as yf
from datetime import datetime as dt
from datetime import timedelta
def get_data():
    st_date = dt.now() 
    ed_date = st_date - timedelta(1)
    st_date = st_date + timedelta(1)
    stk = yf.Ticker("L&TFH.NS")
    df = stk.history(start=st_date, end=ed_date, interval="15m")
```

**Comment by BaserUstun** [comment]
Same is true for me. I just try to get the TRY=X data and it consistently comes wrong. Same wrong value. Then it is solved by no reason and it happens after two or three weeks.

**Comment by Simosh-Skariah** [comment]
Second half of market data (5 mins candles) was missing today until now for .NS symbols.
