### ISSUE TITLE
AttributeError: partially initialized module 'yfinance' has no attribute 'Ticker' (most likely due to a circular import)

### ISSUE THREAD

**Issue by jaspindersingh1** [ranaroussi/yfinance#823]
This error keep appearing. 
Steps taken:
pip install yfinance
script:
import yfinance as yf
msft = yf.Ticker("MSFT")
msft = msft.history(period="1d")
print(msft)

**Comment by adp-source** [comment]
> 

I'm new with Python and also having this issue. How do you resolve this?
