### ISSUE TITLE
yfinance does not return data for Indian (NSE) stocks

### ISSUE THREAD

**Issue by GautamGupta26** [ranaroussi/yfinance#825]
I have been using yfinance to pull historical data for Indian stocks by appending ".NS" (extension for Indian National Stock Exchange) to the symbol, and it was working wonderfully.
Here is the example that was previously working:
import yfinance as yf
symbol = yf.Ticker('INFY.NS')
symbol.info

However, now the above code doesn't work. It apparently works only for US stocks - in above example it will work for US Infosys if ".NS" is removed.

Can you update the code so that Indian Stocks are also returned by yfinance.

**Comment by rajeshyogeshwar** [comment]
I tried downloading data for stocks listed on NSE using yfinance version 0.1.63 and it's working. I am attaching the snapshot as well. Can you possibly try it again?

![yf_infy](https://user-images.githubusercontent.com/7311146/133736181-aeeabc4e-872a-41f2-89d7-a3d3e0df47e4.png)

**Comment by GautamGupta26** [comment]
Hey Rajesh

Yes, you are right. I have now updated it to the latest version, and it is again working flawlessly. Thanks to Ran Aroussi, and thanks to you buddy for helping me out. Cheers...
