### ISSUE TITLE
Using query1 API instead of the HTML server to retrieve the data

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [ranaroussi/yfinance#835]
https://medium.com/nerd-for-tech/all-you-need-to-know-about-yfinance-yahoo-finance-library-fa4c6e48f08e

It looks like ticker.info is retrieved from the HTML website of finance.yahoo.com instead of the API website query1.finance.yahoo.com. Is there a query at query1.finance.yahoo.com that can return the entry of "floatShares"?

**Comment by eabase** [comment]
See discussion on #903 for hints
