### ISSUE TITLE
How to get marketcap of many tickers? when i get that ,error is as follows

### ISSUE THREAD

**Issue by xueyongtu** [ranaroussi/yfinance#839]
HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/A/financials (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000134E53E6700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by atk5025** [comment]
this looks like you've tried to access the API too many times recently. Stop hitting the API for a little bit then try again.

**Comment by ValueRaider** [comment]
Duplicate of #742
