### ISSUE TITLE
Retrieving 3 values in Ticker.info or speeding up Ticker.info 

### ISSUE THREAD

**Issue by Originn** [ranaroussi/yfinance#851]
Hi,

Raised it in stackoverflow

https://stackoverflow.com/questions/69551248/improving-the-speed-of-yahoo-finance-yf-in-finding-ticker-info-values?noredirect=1#comment122947332_69551248

Would appriciate your help!

**Comment by MaxRan92** [comment]
Thank you very much @ranaroussi for the stats() function, way faster than .info!
