### ISSUE TITLE
Balance Sheet > 'Intangible Assets' values appear to be incorrect

### ISSUE THREAD

**Issue by focus8** [ranaroussi/yfinance#854]
Date: 15/10/2021
I am running yFinance 0.1.63
I am UK based.
The issue is that Balance Sheet values displayed on the webpage do not match the values 'scraped' by yFinance
URL: https://uk.finance.yahoo.com/quote/CNC.L/balance-sheet?p=CNC.L
Ticker: 'CNC.L'

I have checked the company Annual Reports and the 'Intangible Assets' values on the Yahoo Finance web page are correct  i.e.,  £7206000 (2020) £7991000 (2019) £7991000 (2018) £7398000 (2017).
The values 'scraped' by yFinance i.e., £17923 (2020) £8223 (2019) £4800 (2018) £10198 (2017) are incorrect.

I have searched the web page source code for the incorrect values and the correct values and found them all i.e., "7,206", "7,991", "7,398" and "17923", "8223","10198".

![image](https://user-images.githubusercontent.com/92581874/137481390-aa719dbc-4165-4d8f-bfdb-5bb1a83a58b5.png)

![image](https://user-images.githubusercontent.com/92581874/137481458-cbd47946-d9c4-4fd1-8971-fa103a0fae45.png)

**Comment by ValueRaider** [comment]
Fixed in `yfinance` 0.2
