### ISSUE TITLE
Documentation enhancements

### ISSUE THREAD

**Issue by elmar-hinz** [ranaroussi/yfinance#856]
I like to address my mayor issue with the documentation. It's about the relation between _Ticker_ and _download_. Only by diving into the code I could answer this for myself.

Question: Does _downloads_ deliver the same content as _Ticker_ or does it ship an independent and different view upon the data?

Answer: Neither, nor. It only fetches the _history_ part of _Ticker_.  It is a facade to one method of the _Ticker_ behind it and it delivers the very same data as this method does return.

This is the information I was missing in the documentation. I may be wrong in detail, yet this is how I read the sources. 

(I leave out that details about multiple ticker symbols and threading here to keep it simple.)

**Comment by Morriz** [comment]
really, is there any documentation at all?

**Comment by ValueRaider** [comment]
https://github.com/ranaroussi/yfinance/wiki

**Comment by Morriz** [comment]
Of course. Doh!
