### ISSUE TITLE
yf.Tickers to download info for multiple tickers and dynamically access each of them

### ISSUE THREAD

**Issue by liweidong1218** [ranaroussi/yfinance#86]
Hi, 

Thanks for creating such an useful tool! 

I want to ask how would you dynamically access each objects if you have a list of tickers to download using yf.Tickers? Looks like I have to specify each ticker manually to access. For example, "tickers.AAPL.info". 

Thank you!

**Comment by ranaroussi** [comment]
Hi,

The ``Tickers`` method was just a shortcut to create many ``Ticker`` objects... 😃 

That being said, I've updated the latest version to include a download method, so:

```python
import yfinance as yf

tickers = yf.Tickers("AAPL SPY")

data = tickers.download(...)
# ^^ returns dataframe

# individual ticker objects can be accessed via:
tickers.tickers.AAPL.info
tickers.tickers.AAPL.options
...
```
