### ISSUE TITLE
Is there a way to pull Change and % Change info for tickers?

### ISSUE THREAD

**Issue by zalamco** [ranaroussi/yfinance#861]
I am using the following code to pull market data in python:

msg = yf.Ticker("QQQ")
msg2 = msg.info['regularMarketPrice']

However I did not notice any change or %change in the JSON file, so I can't really read it. Any idea where it is?

**Comment by ValueRaider** [comment]
Bad idea to get price data from `info[]`, use `history()` or `download()` instead.
