### ISSUE TITLE
what are the limits to this API?

### ISSUE THREAD

**Issue by koolinoor** [ranaroussi/yfinance#862]
for example. how many .info requests can I send in one minute, or hour?
the same goes for price data, e.g. 1min interval

**Comment by evgesha14** [comment]
same question here

**Comment by eabase** [comment]
Did you look? 

![image](https://user-images.githubusercontent.com/52289379/146657564-be7a2bd9-c674-422a-986e-904902aae7f8.png)

Related issue #841

**Comment by yonlugoh** [comment]
@eabase And which plan would this API allow for? From my investigation, its definitely not the basic one
