### ISSUE TITLE
Supressing scientific notation

### ISSUE THREAD

**Issue by Originn** [ranaroussi/yfinance#868]
I am running the yf.download to access crypto prices. Depending on the symbol, the output of that symbol will be in scientific notation e.g. 5.0946520786965266e-05. 

Used round=True, but I also get a rounded scientific notation e.g. 5.3e-05.

Is there a way to include in code that yfinance can do the conversion while running yf.download?

**Comment by balioglum** [comment]
You can write `pd.options.display.float_format = '{:.0f}'.format`  before the actual code which pulls the data. You can adjust the decimal length via `{:.0f}'` . 1f means one point decimal, 2f means two points, etc..

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Can you give us some reproduceble example code please?
And what do you want to do with that number? Do you just wan't to display it or do you want to calculate with it?

The output depends on the underlying `pandas` library and how it interprets the value. I would recommend to read about `pandas` (and its underlying `numpy` package) datatypes.

For example if you an ' pandas.DataFrame' object from `yfinance.Ticker.history()` you can do `obj.High.dtype` to see that it is a `float64` type.

You can round it with `obj.High = obj.High.round()` or make a string out of it `obj.High = obj.High.astype(str)`.
