### ISSUE TITLE
Precision issues with adjusted historical closing prices.

### ISSUE THREAD

**Issue by rtaft** [ranaroussi/yfinance#87]
The actual closing price for AAPL on 1980-12-12 is 28.75.
Using yfinance, the result is $0.51.  Adjusting for splits gives us:
0.51 * 56 = 28.56
This is off by 0.19.
The reason is because you are using 'priceHint' to round the closing values.  The actual downloaded value is 0.513393
0.513393 * 56 = 28.750008
I'm not sure why this is being rounded, but it is causing presplit closing values to be inaccurate.  The more splits a company has had, the bigger the effect on the actual value.

**Comment by rtaft** [comment]
@ranaroussi This appears to have been closed without correction or explanation.  This is a legitimate loss of precision bug.

**Comment by ranaroussi** [comment]
Sorry about that... Just add `rounding=False` in your download calls.

**Comment by rtaft** [comment]
@ranaroussi sorry, I was looking at the changes from the recent releases since this was just closed, I didn't realize it was addressed back in August.
