### ISSUE TITLE
Exception in Thread when yf.download only in jupyter notebook

### ISSUE THREAD

**Issue by Mxgra** [ranaroussi/yfinance#870]
Hello,

I'm getting the Exception in Thread-Error: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) when calling yf.download in a jupyter notebook which runs with a python3.8 kernel inside a pyenv.

This was a known issue which was fixed with version 1.63. I'm on 1.64

When calling the function out of a terminal everything works fine.

I reinstalled, without cache, yfinance globally, locally, from the jupyter notebook itself, and set up a new pyenv nothing helped.

Anyone had a similiar error or can point me in a direction? Thanks

**Comment by meerrettichen** [comment]
I am running the same issue since yesterday. on Sunday it worked normally.

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-5-f196b6719c4a> in <module>
     22 stockName = stock
     23 
---> 24 df = get_stockdata(stockName, st_str, et_str)
     25 #save_stockdata(stockName,df,et_str)
     26 #print (save_stockdata)

**Comment by missing0313** [comment]
I have the same question too. And my version is 0.1.64.

**Comment by Mxgra** [comment]
I was able to fix it, and really the problem still was the version of yfinance. As I said above, I made a new pyenv especially for this case but it didn't worked in jupyter notebook. What I forgot was to make the pyenv available as kernel to the notebook. After I did that, everything worked fine through jupyter👍 There are a lot of guides how to make an pyenv a kernel for jupyter on google.

**Comment by meerrettichen** [comment]
Amazing! Thanks Max!

发自我的iPhone
