### ISSUE TITLE
yfinance returns empty dataframes when large amounts of tickers

### ISSUE THREAD

**Issue by matto1395** [ranaroussi/yfinance#872]
I am trying to compute statistics for thousands of tickers, but when i run my code it returns a lot of empty dataframes. But if i try to collect data fro only one or few tickers it works fine. Could someone help me?

**Comment by evgesha14** [comment]
Having a similar issue with empty dataframes in options. Not thousands of tickers though, just 150 at a time

**Comment by dperez2021** [comment]
Has anyone found a solution?
Also do you guys think that using a time.sleep code would help with the empty dataframes? I was trying to implement it under the impression that the yfinance maybe crashing due to frequency of pulling large data.

Let me know

**Comment by joingreat** [comment]
Did you ever try a loop for pulling one by one? 

```
for x in tqdm(codeList):
    
    try:
        data = pdr.get_data_yahoo(x, start="2021-01-01", end='2022-01-15')
```

This would be ok on my site.
