### ISSUE TITLE
Can´t find Next Earnings Date?

### ISSUE THREAD

**Issue by Rapid1898-code** [ranaroussi/yfinance#873]
Hello - i am searching for the next earnings date in the results?

This is on the Summary-page on Yahoo finance.
eg. Jan25, 2022 for AAPL

Is this information currently not available with YFinance - haven´t found this in data.info so far?

**Comment by lassebenni** [comment]
Hi, should be in
```
ticker = yfinance.Ticker('AAPL')
earnings_date = ticker.calendar.iloc[0][0]
```

**Comment by Rapid1898-code** [comment]
Thanks that is exactly what i was searching for.
