### ISSUE TITLE
Unreliable Yahoo finance Data 

### ISSUE THREAD

**Issue by ghost** [ranaroussi/yfinance#876]
I think there is a serious issue with Yahoo's API which I think affects the library and the reliability of downloading data. 

Users should be warned about that. Here is an example: 

#### Download Gold Prices 

```
stock = yf.Ticker("SGLN.L")
hist = stock.history(period="max")
hist[['Close']].plot()
```

Here is the plot: 

![image](https://user-images.githubusercontent.com/26636184/140703510-989552ae-2d15-4bbe-87af-f7f7862fa380.png)

There are many stocks I spotted that have issues.

**Comment by Rocco-hash** [comment]
Agree, I also noted this issue in the pulling the option data, it changes hour to hour when the option market is closed causing significant doubt of the reliability of the option chain data

**Comment by eabase** [comment]
Because yf (AFAIK) is using webscraping to obtain data, I suppose it also could be cache issue?
