### ISSUE TITLE
Does .news work?

### ISSUE THREAD

**Issue by kabonker** [ranaroussi/yfinance#879]
I was going through all the functions listed and they all worked except 

msft.news  

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-46-0b57cc696dd3> in <module>
----> 1 msft.news

AttributeError: 'Ticker' object has no attribute 'news'

Is that still valid?  If not, you might want to update the sample on the landing page.. 

msft.info works..  
thanks
this is a very useful package.

**Comment by nfaltir** [comment]
Its working for me. But all I am getting is a json object, I am still trying to figure out how to retrieve ONLY the article TITLE and PUBLISHER name.

```python
 msft_news = yf.Ticker("msft").news
```

**Comment by kabonker** [comment]
Strange, I just ran it again and it worked.      It actually returns a list, then you can just loop through the list and parse the json.   
for my_news_json in  my_news_list:
    print(my_news_json['publisher'])
    print(my_news_json['title'])

**Comment by kabonker** [comment]
Not sure why it started working, but was able to get the news..   thanks...     Not sure if anyone has written the beautiful soup to get the text from the stories and video links that would be cool.

**Comment by JeffOfTheSixPaths** [comment]
What fixed it for me was upgrading yfinance with
```pip install yfinance --upgrade --no-cache-dir```
