### ISSUE TITLE
quarterly_financials() doesn't always report the most recent quarter.

### ISSUE THREAD

**Issue by wjsaxx** [ranaroussi/yfinance#884]
.quarterly_financials() doesn't always report the most recent quarter.  For instance, sometimes MSFT returns 6/30/21 and sometimes 9/30/21.  Does this with most all tickers.

**Comment by umang314** [comment]
Please fix this issue.

**Comment by asafravid** [comment]
It’s not a yfinance issue
Yahoo finance picks the data randomly from various websites, some of which are less updated
yfinance just used the Yahoo Finance API

**Comment by wjsaxx** [comment]
Thanks so much for the reply.  Great job on yFinance!

**Comment by ValueRaider** [comment]
`yfinance` 0.2 has redone financials handling, is this issue gone?
