### ISSUE TITLE
Oficial documentation

### ISSUE THREAD

**Issue by AucaCoyan** [ranaroussi/yfinance#886]
The Readme.md is surely a good intro to the library, but I believe a good documentation is in need.
Also, it would be awesome if `docstrings` are done in the process.

Surely I can help!

**Comment by AucaCoyan** [comment]
No, since then, I couldn't found it. The Docs are inline with the code. You should have some sort of intellisense from your ide when you hover on something (vs code has it).

If someone finds documentation, please comment down below!

**Comment by ValueRaider** [comment]
If anyone still wants to contribute to docs then is appreciated, I can review & merge.

**Comment by AucaCoyan** [comment]
Thanks! Have a great day
