### ISSUE TITLE
Shares Outstanding in Balance Sheet

### ISSUE THREAD

**Issue by giorgossideris** [ranaroussi/yfinance#892]
In Balance Sheet at Yahoo Finance the bottom rows refer to the Shares Oustanding of the company. This information is not returned by yfinance. 
I think it would be a useful addition.

**Comment by Skylar00** [comment]
So is there any method I can use to get the Shares Outstanding now? I guess before it is one of the components returned from the function Ticker.info. Some intro from the web gives such method. But from the latest release, it seems to be removed from the function Ticker.info.

**Comment by giorgossideris** [comment]
There is a corresponding attribute in Ticker.info, called <code>sharesOutstanding</code> (last in the screenshot below). 

![image](https://user-images.githubusercontent.com/56915448/143022989-fe8e6f07-f765-4965-a704-714ef6a197d1.png)

Though, as I mention in the issue, I cannot find a way to get the historical Shares Outstanding.

**Comment by marekh19** [comment]
I'm currently facing the same issue. I tried to figure out a way to calculate the last 4 fiscal years shares outstanding from other data in balance sheet but wasn't able to find anything helpful. I guess there is no other way to calculate historical earnings per share and PE ratio.

**Comment by giorgossideris** [comment]
@marekh19 Yes, I think it would be useful for many people. I will try to add this feature and I will open a pull request hopefully in the next days.

**Comment by marekh19** [comment]
@giorgossideris sounds great! looking forward

**Comment by joshfester** [comment]
Historical shares outstanding would be fantastic. I have been desperately searching for this

**Comment by CyrillBleuler** [comment]
Hi everyone, i found this issue when i was searching for a way to get the historical shares outstanding. 
Is this feature now implemented? I couldnt find it in the data i collected over the api. 
If the feature is impemented can someone help me how i can get the data
Thank you alot for your time

**Comment by giorgossideris** [comment]
Hello @CyrillBleuler! This feature is currently available! You can find the shares outstanding under the <code>shares</code> attribute of a <code>Ticker</code> object.

**Comment by catfishbartender** [comment]
Awesome job everyone getting the `shares` attribute incorporated. I'm having success pulling historical shares for larger companies like AAPL or MSFT but unable to pull for smaller companies like KR, MCD, or BAC. I see they're listed on YahooFinance on the Income Stmt as Basic/Diluted Average Shares but unsuccessful in pulling with `shares` - any suggestions? thanks!

**Comment by giorgossideris** [comment]
Hello @catfishbartender and thank you for identifying this problem. The reason behind it is that for the tickers you mentioned, there are some empty values returned by the API that are not handled. So, I opened a relative issue [here](https://github.com/ranaroussi/yfinance/issues/999) and created a pull request that fixes it [here](https://github.com/ranaroussi/yfinance/pull/1000). Hopefully, it will be accepted soon, and you will be able to get the data you want.

**Comment by CyrillBleuler** [comment]
I hope this merge will be accepted soon, i am currently working on a project in which i want to collect this data. And thank you a lot giorgio for putting in the effort.

**Comment by kkafkas** [comment]
Hello guys, is there a way to fetch the quarterly outstanding shares instead of the annual ones? this is quite important to calculate important ratios such as PE any thoughts? Couldn't find an alternative way to calculate this field

**Comment by nokemono** [comment]
I tried this feature in AAPL and could not find any info.shares.

**Comment by LucaFalasca** [comment]
I tried this code
`stock = yf.Ticker("AMZN")`
`print(stock.shares)`
but I get this error
`YFNotImplementedError: Have not implemented fetching 'shares' from Yahoo API`

So, is this not implemented yet?
