### ISSUE TITLE
.balancesheet method does not have 'Total Debt' like Yahoo Finance

### ISSUE THREAD

**Issue by longsondt** [ranaroussi/yfinance#895]
I am trying to use yfinance to access the 'Total Debt' row of a company in order to calculate the Effective Interest Rate, but it just won't show up when using .balancesheet, or .balance_sheet, or .get_balance_sheet on the created ticker object.

For example, with AAPL, on yahoo Finance: 
![image](https://user-images.githubusercontent.com/94946621/143170790-9e3052b8-0396-475a-a91d-7c264ad09373.png)
You can see the 'Total Debt' row

But if using: 
```
import yfinance as yf
ticker_object = yf.Ticker('AAPL')
balancesheet = ticker_object.balancesheet
print(balancesheet)
```
![image](https://user-images.githubusercontent.com/94946621/143170839-2fe59c89-7a3b-46d7-aa11-2e4eff6032c5.png)
'Total Debt' is no where to be seen. 

Another work around I found is that I can just take the 'Short Long Term Debt' and then add 'Long Term Debt' from the table, but there are two problems:

- For companies like MSFT, if you do that, it wouldn't add up to the 'Total Debt' displayed on Yahoo Finance.
- For some companies like SNOW, or FB, the 'Short Long Term Debt' and 'Long Term Debt' rows would not even appear when using yfinance.
Therefore, I think being able to access the 'Total Debt' row from the table on Yahoo Finance is the quickest way to solve this issue. It's just that I cannot find it using yfinance.

I am also aware that there is a 'Total Debt' key in the dictionary when using .info on the ticker object, but that is the most recent quarter value and not the annual value that I am looking for.

**Comment by ValueRaider** [comment]
Fixed in `yfinance` 0.2
