### ISSUE TITLE
Accessing multiple tickers documentation

### ISSUE THREAD

**Issue by jeffreyhwatson** [ranaroussi/yfinance#897]
I'm using the latest update of conda's yfinance in a jupyter lab notebook, and I've found this part the documentation to be a bit off:
```
# access each ticker using (example)
tickers.tickers.MSFT.info
tickers.tickers.AAPL.history(period="1mo")
```
Accessing the individual tickers with that code didn't work for me. I was only able to access them using the following:
```
tickers.tickers['MSFT'].info
tickers.tickers.['AAPL'].history(period="1mo")
```
I couldn't find an example of this issue being brought up before; if I missed it I apologize.

**Comment by devanshamin** [comment]
@jeffreyhwatson  The datatype of tickers object in Tickers() class is `dict`. Fill you look at the tickers.py file from lines 43 to 45 has been commented. If you uncomment them, your issue will be solved.

https://github.com/ranaroussi/yfinance/blob/1297cd10e878c8984de157dfa3cedf2a1694379e/yfinance/tickers.py#L42

```python
from collections import namedtuple as _namedtuple

class Tickers():

   def __init__(self, tickers):
        ...
        #self.tickers = ticker_objects
        self.tickers = _namedtuple("Tickers", ticker_objects.keys(), rename=True)(*ticker_objects.values())
```
