### ISSUE TITLE
No Exception raised when network not available -> requests ConnectionError

### ISSUE THREAD

**Issue by soderdaen** [ranaroussi/yfinance#905]
When no internet connection is available for some time (10-20s), the program throws ConnectionErrors form request package and stucks on doing nothing and not cointinuing.
It seems like no Exception raising/handling is implemented.
Please implement this for proper internet outage error handling.

EDIT: can be easily simulated when disconnecting from wifi/ethernet with following code:

```
import requests
import yfinance as yf
import time
import yfinance.shared as shared

tickerlist = ["MSFT", "TSLA", "BABA", "DE", "BIDU", "FSLY", "REPYY", "CRWD", "NET", "AMD", "BNTX", "CRWD", "WING"]

while True:
        for ticker in tickerlist:
            try:
                data =yf.download(ticker, progress = False)  #timeout = 3,
                print("Price for " + ticker + " : " + str(data.Close.iloc[-1].round(2)))
            except Exception as e:
                print(e)
                print("Unfortunately no error raising and handling")

```

**Comment by jaki729** [comment]
Handling dynamic internet connectivity issues requires continuous monitoring of the network connection. 
This code defines a check_internet function that attempts to connect to a known IP address (8.8.8.8 is Google's DNS server) and port (53 is the standard DNS port) within a specified timeout period. If successful, it returns True, indicating an active internet connection.

The script continuously checks for internet connectivity using this function. If the connection is available, it performs the stock data retrieval process. If there's no internet connectivity, it waits for 5 seconds and then rechecks.

Adjust the timeout values or add more comprehensive error handling logic as needed for your use case.

import requests
import yfinance as yf
import time
import socket

tickerlist = ["MSFT", "TSLA", "BABA", "DE", "BIDU", "FSLY", "REPYY", "CRWD", "NET", "AMD", "BNTX", "CRWD", "WING"]

def check_internet(host="8.8.8.8", port=53, timeout=3):
    try:
        socket.setdefaulttimeout(timeout)
        socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect((host, port))
        return True
    except socket.error:
        return False

while True:
    if check_internet():
        print("Internet connection is available.")
        for ticker in tickerlist:
            try:
                data = yf.download(ticker, progress=False, timeout=10)
                print("Price for " + ticker + " : " + str(data.Close.iloc[-1].round(2)))
            except requests.exceptions.RequestException as e:
                print(f"Connection error or timeout occurred for {ticker}: {e}")
                print("Handling the connection issue here...")
                # Your handling code goes here
            except Exception as e:
                print(f"An unexpected error occurred for {ticker}: {e}")
                # Other exception handling if needed
    else:
        print("No internet connection. Rechecking in 5 seconds.")
        time.sleep(5)

**Comment by ValueRaider** [comment]
Since issue was created, timeouts were added to fetches so `stucks on doing nothing and not cointinuing` should never happen.
