### ISSUE TITLE
Adjusted Close Price Inaccurate as of 12.10.2021

### ISSUE THREAD

**Issue by bruce1095** [ranaroussi/yfinance#906]
I’ve having an issues with adj close data for Apple, Nvidia, and Tesla which seemed to start on Friday night. The adjusted close prices no longer reflect the stock splits and my graphs are way off. Does anyone know what’s causing this? My start date was 2018-01-01 and end date was 12-10-2021. This issues seems to have emerged overnight. 

Thank you

**Comment by bruce1095** [comment]
*End date was 2021-12-10

**Comment by bruce1095** [comment]
![image](https://user-images.githubusercontent.com/37047661/145681183-c8bfe00b-ba25-4a05-bd9a-b3939f8ee99b.png)

![image](https://user-images.githubusercontent.com/37047661/145681185-4328a14e-6428-4a98-b268-f0252e66b3a1.png)


Here are the correct chart prior to Friday's error with adjusted price, but now they have huge declines on the split date, create a visual inaccuracy.

**Comment by ericyue** [comment]
same bug. it seems yahoo not fix yet.

**Comment by aronsky** [comment]
They lost the split information. That is to say, the price is no longer adjusted to splits, and split info is missing. Hopefully it's restored soon...

**Comment by bruce1095** [comment]
The adjusted price issue has been fixed as of 12.14.2021
