### ISSUE TITLE
Data for some dates lost

### ISSUE THREAD

**Issue by RichAndy** [ranaroussi/yfinance#908]
Try to download statisticts for last 7 days ('2021-12-07' - 2021-12-15 )
First 200-300 tickers are loaded correctly

              Open    High     Low   Close  Adj Close   Volume
Date                                                          
2021-12-07 135.740 136.480 134.480 136.140    136.140  1975350
2021-12-08 136.780 138.500 133.020 134.020    134.020  2964661
2021-12-09 133.800 134.740 128.820 130.440    130.440  4765940
2021-12-10 130.800 130.980 126.300 127.220    127.220  2488303
2021-12-13 128.200 129.000 120.120 120.480    120.480  4913341
2021-12-14 120.860 123.340 118.100 118.960    118.960  3179560
2021-12-15 125.420 125.460 122.060 122.880    122.880  3761684

But for other tickers some dates are lost for example data for 2021-12-13 and 2021-12-14
              Open    High     Low   Close  Adj Close   Volume
Date                                                          
2021-12-07 171.110 173.350 170.400 171.290    171.290  5898700
2021-12-08 171.220 171.790 169.840 170.250    170.250  5614400
2021-12-09 169.290 171.170 167.990 168.100    168.100  5171600
2021-12-10 168.500 170.240 167.330 169.060    169.060  4791100
2021-12-15 165.000 165.670 161.820 163.900    163.900  7144617
Try 1 to download MU
Try 2 to download MU

After that I try to download data from scratch for "problem" tickers and it works correctly. So the issue is reproduced after downloading 200-300 tickers only.
One more point retry doesn't resolve the issue

=== Code ==
start_date = '2021-12-07'
end_date = '2021-12-16'
try:
    for id_try in range(1,3):
      ticker_data_df = yf.download(ticker, start=start_date, end=end_date, progress=False, show_errors=False, threads=False)
      if len(ticker_data_df) < 7:
        print("Try", id_try, "to download", ticker)
      else:
        break
  except ValueError: 
    print("Exception catched on ticker", ticker)
    continue;
  #else:
    # Do nothing

**Comment by RichAndy** [comment]
As workaround sleep(3) allows me to minimize the number of the problem tickers, but anyway the issue exists.

**Comment by asafravid** [comment]
Try to randomize the sleep seconds (float value) between 5-10 seconds each time

**Comment by turbo1618** [comment]
I am noticing the same issue that just started 

I am only pulling the Adj Close price. I am missing most of the values for 12/13/21 and 12/14/21.

'''
df = yf.download(tickers, period = "14d",)['Adj Close']
'''

I have a file that pulls 98 tickers and the problem did NOT occur. I have three other files with 262, 205, and 3010 tickers and the problem persists.

**Comment by RichAndy** [comment]
> Try to randomize the sleep seconds (float value) between 5-10 seconds each time

Thanks for workaround, it works much better than simple sleep(3) - only 3-4 tickers of 400 still lost.

**Comment by deriklogov** [comment]
Did you try to use proxy or something so a lot of requests wont come from same IP ?
I am having same issues, on 1h interval some data hours disappear one day and then reappear another day, very unstable.
Looking for solution

**Comment by RichAndy** [comment]
> Did you try to use proxy or something so a lot of requests wont come from same IP ? I am having same issues, on 1h interval some data hours disappear one day and then reappear another day, very unstable. Looking for solution

NO, I didn't try to use a proxy. But I've added some printing after each ticker download (it is a kind of sleep probabaly) and issue has disapiared... or maybe it was fixed)

**Comment by eabase** [comment]
The yahoo API website has capped number of requests:
* There is a daily cap (without API key) to be **`100 requests/day`**, and
* a minute limit of **`300 requests/minute`**

This means that, on full speed,  you'd use up your total daily cap in 20 seconds! So yeah, you need to limit those. as much as possible. 

NOTE: This is when using API, so since yfinance is not using the full API (AFAIK), then we can generally get around this, but _surely_ there are some DoS protection on the site to not make too much req's/minute from same IP.
