### ISSUE TITLE
Question Balance Sheet

### ISSUE THREAD

**Issue by ChrisDelClea** [ranaroussi/yfinance#909]
Hey Guys,

thanks for this need wrapper. 
I wanted to get the maximium years of balance sheet data.
While msft.balance_sheet only return 4 years of data.
How can i accomplish the max period? 

Best regards 
Chris

**Comment by git-shogg** [comment]
@ChrisDelClea, as far as I am aware yfinance will be unable to do this. It is only capable of showing you the same detail that is available through the yahoo finance webpage.
