### ISSUE TITLE
Error "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by Prog-LucasAlves** [ranaroussi/yfinance#914]
Hello , 
I am using version 0.1.67of yfinance and python 3.9.5, and presents the following error when trying to collect the data from the assets.

![Captura de tela 2021-12-30 085704](https://user-images.githubusercontent.com/68572723/147749953-68efccb6-0278-422a-8c2f-be3bca623b67.png)

**Comment by mcgaritym** [comment]
Same here

**Comment by D1al-T0ne** [comment]
Having the same issue this morning, running version 0.1.63.
This issue has occurred in the past #760 that lead to the push of #764, and again also occurred later #877

**Comment by Rational-IM** [comment]
I was having the same issue. Looking at issue #877 I saw a suggestion to disable "threading". I added to my code "threads = False" plus a time.sleep and it is working now:

data_to_match = yf.download(symbol, period='22d', interval='1d', auto_adjust = True, progress = False, threads = False)
time.sleep(0.25)

It would be great to understand why this error started to show up in the first place.

**Comment by SpoonManR** [comment]
Been seeing this since yesterday in NJ.  Though if I switch VPN to London it works fine so might be a server/capacity issue with Yahoo US infrastructure.

**Comment by mcgaritym** [comment]
I managed to fix this issue by splitting my data into chunks (and then requesting data through yf.Ticker(), ticker.history()). Was encountering this issue when try to get data on 1000+ stock tickers. Splitting my data into chunks of 10 stock tickers seemed to do the trick. 

As others have mentioned (inserting a time.sleep() and switching VPNs), this seems to be a capacity issue. Recommend trying to reduce the number of requests somehow (e.g. splitting up data, inserting sleep statements, switch VPN, etc)

**Comment by svanka2005** [comment]
Now getting this error

1 Failed download:

**Comment by D1al-T0ne** [comment]
Fetching data on 1700+ stocks, setting threading=False, time.sleep() did not solve the issue.
Put in a try, except allowed for the data to be fetched, can't provide percent of fetched/missed data at this time.

**Comment by sujithkv1992** [comment]
I was getting the JSONDecodeError even after thread=False, time.sleep(). So here is a hack that worked for me. Put a try..except around the code. And in the except block, append the failed ticker to a skipped_list and continue. And later fetch the data only for the items inside the skipped_list. It did work with only thread=false and no sleep() was required.

**Comment by svanka2005** [comment]
> I was getting the JSONDecodeError even after thread=False, time.sleep(). So here is a hack that worked for me. Put a try..except around the code. And in the except block, append the failed ticker to a skipped_list and continue. And later fetch the data only for the items inside the skipped_list. It did work with only thread=false and no sleep() was required.

here is my code...

  try:            
        data = web.get_data_yahoo(row.item(), yrback, today, progress=False,threads = False)
        #time.sleep(5)
    except:
        print(row.item())

I am getting this..
1 Failed download:
- MDY: No data found for this date range, symbol may be delisted

Appreciate your help.

**Comment by frslm** [comment]
I've just updated from 0.1.63 to 0.1.68, which [mentions](https://github.com/ranaroussi/yfinance/releases/tag/0.1.68) that it fixes the `JSONDecodeError` - perhaps that'll work for everyone here too?

**Comment by svanka2005** [comment]
> I've just updated from 0.1.63 to 0.1.68, which [mentions](https://github.com/ranaroussi/yfinance/releases/tag/0.1.68) that it fixes the `JSONDecodeError` - perhaps that'll work for everyone here too?

JSONDecodeError is gone.  now getting 1 Failed download: error

**Comment by svanka2005** [comment]
> I was getting the JSONDecodeError even after thread=False, time.sleep(). So here is a hack that worked for me. Put a try..except around the code. And in the except block, append the failed ticker to a skipped_list and continue. And later fetch the data only for the items inside the skipped_list. It did work with only thread=false and no sleep() was required.

This seems working now. Thanks.
