### ISSUE TITLE
Failed download:

### ISSUE THREAD

**Issue by svanka2005** [ranaroussi/yfinance#916]
Looks like yfinance is not working. Getting below error. Please advise.

FDN: No data found for this date range, symbol may be delisted

**Comment by AC557** [comment]
Yes I am getting the same error. seems to happen randomly on not to the same security. Appears to be an issue with Yahoo Finance rather than the API itself.

**Comment by AC557** [comment]
...and this is the error I am getting:

['QQQ', 'XIU.TO', 'IEF', 'CBO.TO', 'XPF.TO', 'CWB', 'XLE', 'GLD', 'LIT', 'SPY', 'CLF.TO', 'CPD.TO', 'REM', 'XRE.TO', 'CAD=X']
[*********************100%***********************]  15 of 15 completed

1 Failed download:
- CPD.TO: No data found for this date range, symbol may be delisted
