### ISSUE TITLE
fix - "period=max" returns "failed download"

### ISSUE THREAD

**Issue by snafu4** [ranaroussi/yfinance#919]
period='max' should adjust for interval.  For example, 

```
yf.download(ticker, interval='1h', period='max')

```
returns

```1h data not available for startTime=1070236800 and endTime=1640909113. The requested range must be within the last 730 days.```

In the above case, it should return the last 730 days worth of data.

**Comment by mdkberry** [comment]
you probably found it, but I ended up here before I saw this:

"Please note: Yahoo Finance currently limits historical data downloads depending on the resolution of data required:

    Minute Data: 7 days
    2 Minute Data: 60 days
    5 Minute Data: 60 days
    15 Minute Data: 60 days
    30 Minute Data: 60 days
    Hourly Data: 730 days
    Daily/Weekly/Monthly: No limit"

**Comment by ValueRaider** [comment]
You can workaround this with e.g. `period="60d"`. If you really need yfinance to convert max then consider submitting a fix.
