### ISSUE TITLE
anaconda couldn't finish dowanload 08/24/2019

### ISSUE THREAD

**Issue by zhghao** [ranaroussi/yfinance#92]
I tried several times (remove downloaded bz2 file and re-download), doesn't work out

Downloading and Extracting Packages
yfinance-0.1.44      | 535 KB    | ############################################################################ | 100%

InvalidArchiveError('Error with archive C:\\********\\Anaconda3\\pkgs\\yfinance-0.1.44-py_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink (errno=22, retcode=-25, archive_p=2332365645376)')

**Comment by crsarav** [comment]
same here

**Comment by ranaroussi** [comment]
Does this also happen when installing using Pip?

**Comment by edmilsonsgjk** [comment]
via conda doesn't work

![Capturar-erro-conda.png](https://www.imagemhost.com.br/images/2019/09/07/Capturar-erro-conda.png)

**Comment by ranaroussi** [comment]
Is installing via `pip` works?

**Comment by ranaroussi** [comment]
Is this still going on?

**Comment by alex-movila** [comment]
still same issue

**Comment by bobbayj** [comment]
Can confirm this is still an issue with `conda` installations!

Can use pip to get around this, but would rather it sit in the conda environment 😢

**Comment by eltresmola** [comment]
> I tried several times (remove downloaded bz2 file and re-download), doesn't work out
> 
> Downloading and Extracting Packages
> yfinance-0.1.44 | 535 KB | ############################################################################ | 100%
> 
> InvalidArchiveError('Error with archive C:\********\Anaconda3\pkgs\yfinance-0.1.44-py_0.tar.bz2. You probably need to delete and re-download or re-create this file. Message from libarchive was:\n\nCould not unlink (errno=22, retcode=-25, archive_p=2332365645376)')

Try to "Run as Administrator" your command prompt

**Comment by zenmark29** [comment]
I was just installing this today on Windows 10. 

1. I tried to install using conda - "conda not found".
2. I installed yfinance with pip - worked perfectly
3. I launched the Anaconda Powershell prompt and tried it: "package not found"

But, it installed with pip and it works fine. Thanks!

**Comment by georgewayne** [comment]
Yes, it is still a problem as of today (2/10/2020).  Windows 10. Tried with run as admin with no avail.

Error message "InvalidArchiveError('Error with archive C:********\Anaconda3\pkgs\yfinance-0.1.44-py_0.tar.bz2. You probably need to delete and re-download or re-create this file. Message from libarchive was:\n\nCould not unlink..."

**Comment by peng-an** [comment]
Same on windows10.
> conda install -c ranaroussi yfinance
InvalidArchiveError('Error with archive C:\\Users\\..。\\yfinance-0.1.54-py_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')

**Comment by peng-an** [comment]
Same on windows10.

```bash
conda install -c ranaroussi yfinance
InvalidArchiveError('Error with archive C:\Users\..。\yfinance-0.1.54-py_0.tar.bz2. You probably need to delete and re-download or re-create this file. Message from libarchive was:\n\nCould not unlink')
```

**Comment by pedromonzu** [comment]
Same problem, I tryed to install pip and then install yfinance in conda, but the webscrapping doesn't work, the Dataframes are empty:

![image](https://user-images.githubusercontent.com/63439692/80671889-8d0bda80-8a81-11ea-8acd-3e225169f7c3.png)

**Comment by Yesman007** [comment]
I ran Anaconda Powershell Prompt as administrator and it worked.

**Comment by moniz-r** [comment]
As mentioned by [@alvaroritter](https://github.com/ranaroussi/yfinance/issues/289) when having this error even trying with the simple pip, you can install it with the Anaconda Prompt window in your selected environment with the following code:

$ pip install yfinance --upgrade --no-cache-dir

**Comment by vickylance** [comment]
Any update on this?

**Comment by helpme1** [comment]
This problem still exists today 18Sep2020

**Comment by sbnimbalkar** [comment]
I tried installing yfinance on Windows 10 using Conda and was greeted with the same error. So the problem persists as on October 20, 2020.

**Comment by shivkonar1802** [comment]
InvalidArchiveError('Error with archive C:\\Users\\Daniel\\anaconda3\\pkgs\\yfinance-0.1.54-py_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')

How do i resolve this error?

**Comment by jhardiman1** [comment]
Problem is persisting as of 19 Nov 2020.

I am getting the InvalidArchiveError using Win 10 and conda 4.9.2, and so doesn't show up as an installed package in my environment. I then tried installing with `pip install yfinance`, which installs the package, but as @pedromonzu says, all the dataframes are empty.

On MacOS 10.14.6 and conda 4.5.4, the package installs to the environment, but I am faced with the same issue as above where the dataframes are still empty.

**Comment by Rayjiao123** [comment]
Windows 10 and with Conda I got the same error. I tried pip install but the package cannot be imported. Problem persists as of 22/11/2020.

**Comment by oski89** [comment]
Same error massge for me, using conda.

InvalidArchiveError('Error with archive C:\\Users\\Fromage\\anaconda3\\pkgs\\yfinance-0.1.54-py_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')

**Comment by plsloan** [comment]
+1 Same error for me.

**Comment by maxmax91** [comment]
Same problem here. Installed with pip as well. No way to make it work.

**Comment by aashishnk** [comment]
@maxmax91 @plsloan @oski89 @Rayjiao123 @helpme1 

Please check my below answer for this issue. It might help you.
https://github.com/conda/conda/issues/9913#issuecomment-750322822

**Comment by RobustCoder** [comment]
I have a Windows 10 for Workstations machine that is fully patched.

I did a brand new install of Anaconda Navigator today (version 1.10.0).  That has conda version 4.9.2.

I am seeing the exact same error as everyone else here:

`InvalidArchiveError...yfinance-0.1.54-py_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')`

aashishnk: I followed your link, which _ultimately_ worked for me.  Thanks much for figuring that out!  But your description was insufficient!  It took the subsequent comment from bakiba to set me down the right path.

Here are the complete steps that I did:

```
1) in Windows Explorer go to
	C:\Users\alfred\anaconda3\pkgs

2) create a new directory
	yfinance-0.1.54-py_0

3) copy into that directory the file
	C:\Users\alfred\anaconda3\pkgs\yfinance-0.1.54-py_0.tar.bz2
that should have been downloaded by the initial failed command

4) right click on
	C:\Users\alfred\anaconda3\pkgs\yfinance-0.1.54-py_0\yfinance-0.1.54-py_0.tar.bz2
and select 7-Zip --> Extract here
That should extract the file
	yfinance-0.1.54-py_0.tar

5) right click on
	yfinance-0.1.54-py_0.tar
and select 7-Zip --> Extract here
That should extract the desired items.

6) delete the files
	yfinance-0.1.54-py_0.tar.bz2
	yfinance-0.1.54-py_0.tar
inside
	C:\Users\alfred\anaconda3\pkgs\yfinance-0.1.54-py_0

7) in the original Anaconda base environment Terminal, rerun
	conda install -c ranaroussi yfinance
```

~~~~~~~~~~

None of us should have to be doing this hack, however.

Is there a bug with conda or yfinance?  Lack of Windows permissions?

**Comment by rcd71** [comment]
WORKING!!!! Buenas tardes, finalmente he conseguido instalarlo y dejarlo funcionando siguiendo las indicaciones anteriores de RobustCoder con alguna modificación. No me funcionaba con lo indicado por RobustCoder porque cuando ejecutaba el paso 7) me borraba el directorio "yfinance-0.1.54-py_0" creado en el punto 2)
Los pasas a seguir son:
1) Seguir todos los pasos indicado por RobustCoder hasta el paso 6)
2) Ir al directorio D:\Anaconda3\pkgs\yfinance-0.1.54-py_0\site-packages (cada uno en el path que lo tenga), y copiar las dos carpetas que hay
3) Pegarlas en el directorio D:\Anaconda3\Lib\site-packages (cada uno en el path que lo tenga)
4) Es posible, a mi me pasó, que el código de un error porque necesita también el paquete Multitasking, si os pasa tambien tenéis que hacer lo mismo que con YFinance, osea, ir a D:\Anaconda3\pkgs\multitasking-0.0.9-py_0\site-packages y copiar las dos carpetas que hay y pegarlas en D:\Anaconda3\Lib\site-packages

Espero que os ayude, saludos desde España.

**Comment by heavycello** [comment]
Hey! so rcd71 is totally right, if you just copy the site-packages folder from step 5) that's in pkgs and paste it into Lib, complete step 7) and it works! Personally, I didn't have to do Multitasking install manually. Good luck out there!

Translation for credit: thanks rcd71!
[from google translate]
"
WORKING !!!! Good afternoon, I have finally managed to install it and leave it working following the RobustCoder instructions above with some modification. It didn't work for me with what was indicated by RobustCoder because when I executed step 7) it would delete the directory "yfinance-0.1.54-py_0" created in point 2)
The steps to follow are:

Follow all the steps indicated by RobustCoder up to step 6)
Go to the directory D: \ Anaconda3 \ pkgs \ yfinance-0.1.54-py_0 \ site-packages (each one in the path that has it), and copy the two folders there
Paste them in the directory D: \ Anaconda3 \ Lib \ site-packages (each one in the path that has it)
It is possible, it happened to me, that the code of an error because it also needs the Multitasking package, if it happens you also have to do the same as with YFinance, I mean, go to D: \ Anaconda3 \ pkgs \ multitasking-0.0.9 -py_0 \ site-packages and copy the two existing folders and paste them in D: \ Anaconda3 \ Lib \ site-packages
I hope it helps you, greetings from Spain."

**Comment by heavycello** [comment]
For synopsis: 
1) download the latest yfinance build at: https://anaconda.org/ranaroussi/yfinance/files
2) find your pkgs in folder in the Anaconda3 path, and make sure any yfinance files are deleted.
3) make a new folder called: yfinance-0.1.54-py_0
4) paste the yfinance-0.1.54-py_0.tar.bz2 file (or newer) and use a program like 7-Zip to extract the .tar file
5) use 7Zip again to extract the folders from the ,tar file
6) in the site-packages folder, copy the two yfinance folders that are here.
7) find the Anaconda3/Lib/site-packages folder and paste the yfinance folders here.
8) make sure to delete the .tar and .tar.bz2 files from the original pkgs/yfinance-0.1.54-py_0 folder.
9) run  conda install -c ranaroussi yfinance 
10) did it work? celebrate! I spent way more time on this than I planned ;) if it didn't work, than perhaps try the same process with the multitasking-0.0.9-py_0 package as well. 

hope this summary helps. Thanks RobustCoder and rcd71 for the fix!

**Comment by Olivair** [comment]
Still doesn't work for me unfortunately even after running the process several times. _pip install_ has the known empty dataframe issue.

**Comment by alexanu** [comment]
Thank you, Heavycello! I was going crazy with this shit. I needed to do the same steps for "Multitasking" and at the end it worked.

**Comment by bowling-knight** [comment]
Hi All,
I ran into this issue trying to run yfinance through an Anaconda installed Spyder notebook. This was the error I received:

_"No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect."_

After some digging I found that I was not able to install yfinance via conda even with >conda install -c ranaroussi yfinance

**Instead of installing via conda, I installed pip in my environment (not base) and then called >pip install yfinance**

**Comment by ianepreston** [comment]
I'm also having issues installing via conda. The manual steps don't really work for me, as I'm trying to build a conda package that has this as a dependency. For conda I think the ideal solution would be to make a package available on conda-forge. @ranaroussi I've got some experience with developing conda-forge recipes for pure python packages. If I put something together would you be ok with that? I could either maintain it or hand over ownership of the repository to you, whichever you prefer. It's very light in terms of maintenance, you'll generally just get an automatic PR from a bot whenever you push a new version of this package to PyPI. Let me know if you'd like me to go ahead with this, I'm happy to do it, but want to make sure I have your blessing first.

Thanks

**Comment by ValueRaider** [comment]
I would like to see this issue resolved, one way or another, so it can be closed.

What is the current status? Conda fails in my Shell environment so I can't investigate, and makes me reluctant to change anything in this repository.
