### ISSUE TITLE
Incomplete data

### ISSUE THREAD

**Issue by MoenirMasood** [ranaroussi/yfinance#925]
I am using the latest version of the package: yfinance. However, when downloading quotes from the yfinance.dowload function provides incomplete data i.e. I tried dowloading BTC-USD 1h quotes from 27-09-2021 untill 28-11-2021 however the 23:00:00 quotes for every day are missing in the data. I am eager to find out how to solve this problem, please help!

**Comment by ValueRaider** [comment]
Duplicate of #902
