### ISSUE TITLE
include the Capital Gain data in actions

### ISSUE THREAD

**Issue by happfield** [ranaroussi/yfinance#926]
For mutual funds, a lot of the times the action is "Captial Gain". Can you please include the "capital gain" column in the history data?
We get the capital gain data by use params["events"] = "capitalGain,div,splits"  instead of "div,splits".  Then the post processing of the captial gain data should be the same as dividends data.

**Comment by tggbco** [comment]
+1 for this feature, it would be very useful. Thank you!

**Comment by ValueRaider** [comment]
@thirumalairajr this request might be interesting to you

**Comment by thirumalairajr** [comment]
@ValueRaider Sure, I have raised a PR https://github.com/ranaroussi/yfinance/pull/1166 for this, can you please review it ?

**Comment by ValueRaider** [comment]
@thirumalairajr I have already reviewed. Also this request is different, suggesting to modify `Ticker.history()`, maybe it returns different (better?) capital gains data.

**Comment by thirumalairajr** [comment]
Yeah I have raised a new PR https://github.com/ranaroussi/yfinance/pull/1166 in which I have added `Capital Gains` column to `Ticker.history()` * `Ticker.actions` dataframes. I have also added a new `Ticker.capital_gains` property for getting Capital Gains data as a series. 

Are these changes fine or am I missing something?
