### ISSUE TITLE
How to get the stock list?

### ISSUE THREAD

**Issue by joingreat** [ranaroussi/yfinance#928]
I have try three stocks and the symbol returns well:

import yfinance as yf
symbol = yf.Ticker('INFY.NS')
symbol = yf.Ticker('APPL')
symbol = yf.Ticker('0700.HK')
symbol.info

However, how to get the stock list in India,US and HK market stock code contained in yfiance?

**Comment by asafravid** [comment]
You need to use the ticker assigned by yahoo finance

**Comment by joingreat** [comment]
When I try a random code from HK market, '02015.HK',which returns a blank result:

data = pdr.get_data_yahoo('02015.HK', start="2021-07-01", end='2022-01-17')
data

1 Failed download:
- 02015.HK: No data found, symbol may be delisted
- 
Open	High	Low	Close	Adj Close	Volume
Date	

Is there a way to make sure which stock list is collected in yfiance , and then next ?

**Comment by ProgrammingDao** [comment]
You can try https://finance.yahoo.com/quote/<your ticker>

**Comment by joingreat** [comment]
@ProgrammingDao 

this also return the ticker one by one,I have try ,however this would not return as expect.

as the beginning of this issue,
symbol = yf.Ticker('INFY.NS')
would return the data of symbol 'INFY.NS' , but how to get the other symbol as input ?

US market has more than 7000 stocks, so there would not be a way to get in yfinance?

I have find the other way to get this stock list and then send into yfinance.

**Comment by asafravid** [comment]
@joingreat simply get those (and many others) using https://github.com/portfolioplus/pytickersymbols support/usage along with https://github.com/portfolioplus/pysymbolscanner

Also see how I get it directly from the nasdaq ftp website in https://github.com/asafravid/sss

**Comment by joingreat** [comment]
yeah, I got it. this list should get **before** using yfinance.

And now I close this issue.

**Comment by joingreat** [comment]
yeah, I got it. this list should get BEFORE using yfinance.

And now I close this issue. Thanks.
