### ISSUE TITLE
Inconsistent results with download() and history() functions

### ISSUE THREAD

**Issue by dpizzle** [ranaroussi/yfinance#929]
When running the below commands, data is only returned when the request is sent to certain Yahoo hosts.

I am running `yfinance (0.1.69)`

**Not working**

This is when the requests are sent to `87.248.114.11:443` or `87.248.114.12:443` as per tcpdump.

```
>>> yf.Ticker('0UW4.L').history()
- 0UW4.L: None
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []
```

**Working**

This is when the requests are sent to `69.147.82.60:443` or `69.147.82.61:443` as per tcpdump.

```
>>> yf.Ticker('0UW4.L').history()
            Open  High   Low  Close  Volume  Dividends  Stock Splits
Date
2022-01-12  0.92  0.92  0.92   0.92    2000          0             0
```

The requests from the `history()` and `download()` commands appear to use the 4 Yahoo IP addresses, so the output from the command is inconsistent.

**Comment by yinjin1314** [comment]
Thank you, I am facing similar questions. But how to change the right Yahoo IP addresses.

**Comment by asafravid** [comment]
Use interpolation to fix

**Comment by ValueRaider** [comment]
Does this still happen in latest version?

**Comment by ndamclean** [comment]
I just noticed this problem.

I ran the following in a Jupyter notebook to illustrate the difference.

Stock price history diverges wildly before early 2022.

```python
import pandas as pd
import yfinance as yf

ticker = "BHRB"
start_date, end_date = "2019-01-01", "2024-11-01"

stock = yf.Ticker(ticker)
share_price_download = yf.download(ticker, start_date, end_date).Close
share_price_download.index = share_price_download.index.tz_localize(None)
share_price_yf_history = stock.history(start=start_date, end=end_date).Close
share_price_yf_history.index = share_price_yf_history.index.tz_localize(None)

pd.merge(
    pd.DataFrame(share_price_download.rename("close - yf.download")),
    pd.DataFrame(share_price_yf_history.rename("close - yf.Ticker.history")),
    left_index=True,
    right_index=True,
).plot()
```
![image](https://github.com/user-attachments/assets/b707f1ea-8429-4604-b4b3-90ac3b1e644b)

**Comment by ValueRaider** [comment]
That's different.
