### ISSUE TITLE
Unable to run yfinanec

### ISSUE THREAD

**Issue by Jaghadish** [ranaroussi/yfinance#934]
even after installing yfinance through pip install yfinance - the module does not seem to be imported

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_16116/3726981220.py in <module>
----> 1 import yahoo_finance as yf

ModuleNotFoundError: No module named 'yahoo_finance'

**Comment by joingreat** [comment]
whats your pip code for install?

after successful installed, this code would be ok:

import yfinance as yf

**Comment by Jaghadish** [comment]
hi - I did pip install yfinance
i reinstalled jupyter notebook and tried opening too - didnt work
P.S: this was working and i updated matplotlib following a suggestion and it caused a problem since then and I am not able to run yfinance on my machine anymore - any leads on the same?

**Comment by joingreat** [comment]
Now you have only the matplotlib problem?

try pip uninstall matplotlib  and install again .

**Comment by Jaghadish** [comment]
hi
thank you so much for the help @joingreat  - it was a mistake in my end - i had installed yfinance in wrong location
