### ISSUE TITLE
Index Components

### ISSUE THREAD

**Issue by BeThaGlo** [ranaroussi/yfinance#935]
Hi,
would it be possible to add functionality allowing access to an index's component stocks. So for example,  a get_components() method for a Ticker for the S&P500 (^GSPC)?
Thanks a lot!

**Comment by ProgrammingDao** [comment]
It seems possible with utils.get_json(ticker_url + '/components', proxy, self.session) and then more specifically by extracting the components with data['components']['components'] at yfinance.utils line 108.
