### ISSUE TITLE
yfinance.download data not the latest price after some downloads

### ISSUE THREAD

**Issue by PTTsai** [ranaroussi/yfinance#942]
Hi, 
I am a beginner of using python and yfinance.  (python:3.9.9, pandas:1.3.4, yfinance:0.1.69)
I wrote a example code for getting the latest price of some symbols in spyList[] (about 500 symbols).

`while True:`
    `for ticker in spyList:`
            `data = yf.download(tickers=ticker, period='5d', interval='5m')`
            `#data = pdr.get_data_yahoo(ticker, period='5d', interval='5m')`
            `print(data)`

After some downloads, the price of symbol become outdated. (hour level offset)
Even I used the pdr.get_data_yahoo(), it still happened.

Is there any solution or suggests to solve this situation? 
Many thanks.

**Comment by ValueRaider** [comment]
If this is still happening, provide more information. What is the output? How do you know it's wrong?
