### ISSUE TITLE
version 0.1.70 pypi release

### ISSUE THREAD

**Issue by moshfrid** [ranaroussi/yfinance#944]
The newest release which fixes the incompatibility with the new version of pandas isn't on pypi

**Comment by PeterSlickers** [comment]
the newest release identifies itself as version="0.1.69" in file "yfinance-0.1.70/yfinance/version.py".

**Comment by ProgrammingDao** [comment]
I opened a pull request for it at : https://github.com/ranaroussi/yfinance/pull/947

**Comment by ranaroussi** [comment]
Released. Sorry about that :)

**Comment by ProgrammingDao** [comment]
Thank you @ranaroussi
