### ISSUE TITLE
MIssing data for 27th of December (American market)

### ISSUE THREAD

**Issue by seminaro** [ranaroussi/yfinance#946]
I have upgraded to the latest version. The data from 27th of January seem to be missing for most of american stocks (e.g., AAPL).
It goes directly from 2022-01-26 to 2022-01-28.

European market works fine.

**Comment by spot92** [comment]
I believe that is a Yahoo Finance issue and not a package issue. If you go to the Yahoo Finance website, the data is missing in the Historical Data tab of every ticker I have checked.

**Comment by spot92** [comment]
If you refresh the page, it will sometimes be there and sometimes not. I would recommend trying to pull the data later today and see if the issue is fixed.
