### ISSUE TITLE
Get ticker based on stock name

### ISSUE THREAD

**Issue by sharepointmike** [ranaroussi/yfinance#948]
Hi there,

Is there some possibility to get the ticker symbol based on the stock name.

Like ("microsoft").ticker gives me "MSFT"

Thanks a lot

**Comment by aridaybordon** [comment]
I don't think that is possible for a simple reason.

Stocks from the same company may have different values depending on the exchange while __tickers are a unique way of identifying both the stock and the exchange__ (for a more detailed explanation [see this](https://en.wikipedia.org/wiki/Ticker_symbol#Interpreting_the_symbol)).

**Comment by asafravid** [comment]
Use the nasdaq ftp website and search in the csvs
You can see in www.github.com/asafravid/sss

**Comment by sharepointmike** [comment]
> I don't think that is possible for a simple reason.
> 
> Stocks from the same company may have different values depending on the exchange while **tickers are a unique way of identifying both the stock and the exchange** (for a more detailed explanation [see this](https://en.wikipedia.org/wiki/Ticker_symbol#Interpreting_the_symbol)).

Indeed, did not think about that. Would be some manual work involved. I not only use nasdaq
