### ISSUE TITLE
option_chain not converting date in UTC?

### ISSUE THREAD

**Issue by cobujo** [ranaroussi/yfinance#95]
When attempting to get options chains for explicit dates (some date other than the soonest expiration), I'm getting a key error.  I'm using the format as shown in the README.

`# get option chain for specific expiration
opt = msft.option_chain('YYYY-MM-DD')`

I went digging and noticed that at line 144 of __init__.py it's using datetime.fromtimestamp() to convert the unix epoch to the desired format, as shown.
`            for exp in r['optionChain']['result'][0]['expirationDates']:
                self._expirations[_datetime.datetime.fromtimestamp(
                    exp).strftime('%Y-%m-%d')] = exp
            return r['optionChain']['result'][0]['options'][0]`

However this is returning the local time, which is why the date is not found on the results page hence the key error.
Should datetime.utcfromtimestamp() be used here instead?

I'm very new, so if I'm misusing this or missing something I'm all ears.  Thanks!

**Comment by ranaroussi** [comment]
Fixed in 0.1.46. Use `msft.option_chain('YYYY-MM-DD', tz="UTC")` for tz conversion.
