### ISSUE TITLE
Discrepancy in the downloaded stock data

### ISSUE THREAD

**Issue by garg-aayush** [ranaroussi/yfinance#951]
I just downloaded stock data (RELIANCE.NS) using yfinance. When I compared this downloaded data with the actual data available at [NSE website](https://www.nseindia.com/get-quotes/equity?symbol=RELIANCE). The values are quite different!

And I am unable to figure out why is it so. Can you please help with it?

#### yfinance data
![yfinance_data](https://user-images.githubusercontent.com/17342823/152027435-560fff7f-c0b6-483e-bca9-fe7cc7dcea2c.png)

#### Actual data from [NSE website](https://www.nseindia.com/get-quotes/equity?symbol=RELIANCE)
![test2](https://user-images.githubusercontent.com/17342823/152028377-d3dadc6d-c0e6-4a9a-9d19-3fd24c0279c6.png)

**Comment by aridaybordon** [comment]
The historical data extracted using yfinance is imported directly from [Yahoo Finance](https://finance.yahoo.com/). This discrepancy seems more a problem with the webserver than a problem with the yfinance package.

**Comment by danielsparing** [comment]
You're seeing [auto-adjusted data](https://www.investopedia.com/terms/a/adjusted_closing_price.asp), including e.g. dividends.

You probably to want to use `ticker.history( ... , auto_adjust = False)`
