### ISSUE TITLE
Not able to download full data

### ISSUE THREAD

**Issue by Anurag-Patil-1999** [ranaroussi/yfinance#953]
yfinance.download('ABBOTINDIA.NS', 
                                        period = "2d",
                                        interval = "1d", 
                                        progress = False, 
                                        threads = True)["Close"]

giving result for data for 1 day only, instead of 2 days which i requested.

![image](https://user-images.githubusercontent.com/98999496/152469880-346b093c-4de5-4b62-8a3d-e9f5a1ce8c33.png)

**Comment by logyuan** [comment]
I also found that the data for 2022/02/03 was missing when I request all the other stocks. Hope this isssue will be fixed soon.

**Comment by arbitrager44** [comment]
I am having a similar problem. I can get multiple day closes but if I select an intra-day interval, I only get the close for each day.

**Comment by RY93** [comment]
Same issue with this INDIA VIX (^INDIAVIX) symbol.

**Comment by KrishnaRachh** [comment]
Anyone found solution for this? Pls help

**Comment by kmungantiwar** [comment]
@ranaroussi 

simple code run during market hours on 2022-03-04 provides output but skips the data for 2022-03-03. Below is the code and output

data = yf.download('RELIANCE.NS', start='2022-02-20', interval='1d',rounding=True).reset_index()

![image](https://user-images.githubusercontent.com/77494760/156711772-40b00a63-bd8f-406d-9a94-9ae85e4abc6f.png)

**Comment by ValueRaider** [comment]
Problem still happening?

**Comment by Anurag-Patil-1999** [comment]
@ValueRaider yes, this problem is still happening occasionally.

**Comment by Anurag-Patil-1999** [comment]
1 observation, whenever this issue happens, if i want data till n date, then it always misses entries of (n-1) date. Don't know how much it can help in debugging.

**Comment by ValueRaider** [comment]
What's your `yfinance` version?

**Comment by Anurag-Patil-1999** [comment]
yfinance==0.2.3

**Comment by ValueRaider** [comment]
Step 1 is confirming what is to blame - Yahoo vs `yfinance`. Add debug code to print the dates Yahoo returns.
