### ISSUE TITLE
History returns one additional row after the end date, if time interval specified is less than 1d

### ISSUE THREAD

**Issue by manjunathmayya** [ranaroussi/yfinance#956]
History returns one additional row after the end date, if time interval specified is less than 1d

**Code used:**
```
import yfinance as yf
symbol = yf.Ticker('SPY')
symbol_history = symbol.history(start='2022-02-01', end='2022-02-03', interval='30m', action=False)
print(symbol_history)
```

![image](https://user-images.githubusercontent.com/41788269/153982930-fb7a1d0d-1fb5-4f0a-9ee8-ac351339e2f3.png)

Here you can see the last row is from 14th Feb. But the end date is 3rd Feb.

The issue is not seen, if interval is not specified, or if the interval is 1d or more. See below code and result.

`symbol_history = symbol.history(start='2022-02-01', end='2022-02-03', interval='1d', action=False)`

![image](https://user-images.githubusercontent.com/41788269/153982786-e93220a9-2e0b-4568-83d4-a1af72210c47.png)

**Comment by PTruong9090** [comment]
I found that adding 'adjust=False' fixes the problem
`(start='2022-02-09', end='2022-02-10', interval='5m', action=False, adjust=False)`

**Comment by manjunathmayya** [comment]
Thanks for your reply.
But all of a sudden, the same code seems to be working now.

Below is the result from the same code which had issue when I posted.
`symbol.history(start='2022-02-01', end='2022-02-03', interval='30m', action=False)`

![image](https://user-images.githubusercontent.com/41788269/154233992-bc1a4191-c6ca-4393-a947-0cdc07b8b38d.png)

**Comment by ValueRaider** [comment]
PR https://github.com/ranaroussi/yfinance/pull/1026 should have fixed it. Close issue if solved.
