### ISSUE TITLE
yfinance how to get data if the ticker is same for different exchanges

### ISSUE THREAD

**Issue by brianivander** [ranaroussi/yfinance#957]
I want to get historical price data using python and yfinance for Indonesian stocks. I see that there are many stocks that have the same name across different countries, for example AUTO (can be Indonesian company Astra Otoparts Tbk PT or NASDAQ's Autoweb Inc)

When I do yf.download('AUTO'), it's returning me a price data of Autoweb Inc, instead of Indonesian stock Astra Otoparts Tbk PT.

How can we select which exchange we want the ticker from?

Thanks.

![image](https://user-images.githubusercontent.com/19526473/154004986-714b79b0-1442-4bb4-9d67-d92ea19a4f4d.png)

I posted on [stackoverflow too](https://stackoverflow.com/questions/71121619/yfinance-how-to-get-data-if-the-ticker-is-same-for-different-exchanges )

**Comment by git-shogg** [comment]
For anyone else wondering about this one. You will be able to work out what the ticker should be for yfinance by searching for your ticker in google (e.g. for me the google search was "Santos asx yahoo finance") when you open it in yahoo you'll find that the symbols appended to the end of the ticker represent the Stock Exchange (e.g. STO.AX for Australia ASX listed stocks).
