### ISSUE TITLE
Throttling question

### ISSUE THREAD

**Issue by wjsaxx** [ranaroussi/yfinance#960]
My experience is I can query ticker.history() once per second for 3,000+ times without issue.  My data set is the Russel 1000 and Russel 2000.

When I query ticker.info(), ticker.quarterly_cashflow(), ticker.quarterly_financials(), ticker.calendar() I have to pause 4 seconds between my 3,000+ ticker queries or the calls will fail.  I suspect due to throttling as I can keep things going when I increase my sleep between calls.

Is this the typical experience?  Is there anything that can be done to manage throttling?  I am logged into my Yahoo account.  If I subscribe to Yahoo Finance does that have any effect on throttling?

**Comment by Bertron01** [comment]
Ive noticed that the magic number for me is 300 or so tickers before it downloads at a ticker per second. I am currently experimenting with pausing at every 300 symbols, but can't find the sweet spot in amount of time to wait before the throttling is reset.

**Comment by aspenforest** [comment]
With [YFrake](https://github.com/aspenforest/yfrake), you can make up to 2000 requests in 1.5 seconds to all endpoints, depending on the size of the data being returned from the servers.

**Comment by ValueRaider** [comment]
`yfinance` is requesting all non-price data in one go - info, calendar, and financials, when you access one of them. Unnecessary. This PR splits info & calendar from financials, speeding up the former: https://github.com/ranaroussi/yfinance/issues/971

But financials will always be slow. Can you cache locally? They change rarely.

FYI I'm working on a smart caching wrapper, will cache locally and update only when new data expected in Yahoo: https://github.com/ValueRaider/yfinance-cache

**Comment by ValueRaider** [comment]
Options:

- stop spamming
- [fetcher smarter](https://github.com/ranaroussi/yfinance#smarter-scraping)
- [yfinance_cache](https://github.com/ValueRaider/yfinance-cache)
