### ISSUE TITLE
quarterly_financials methods do not get same quarters of last year

### ISSUE THREAD

**Issue by jyh2378** [ranaroussi/yfinance#961]
Yahoo finance homepages shows 5 quarters of financial information.

![image](https://user-images.githubusercontent.com/33739495/154796124-63810975-1413-40e2-ac15-06f61d4a3fd8.png)
 
But yfinance's financials methods show only 4 quarters information and didn't get same quarters of last year.

![image](https://user-images.githubusercontent.com/33739495/154796182-f2ba452c-fd1f-4a0b-aac4-dc7fed156455.png)

**Comment by git-shogg** [comment]
@jyh2378 if you haven't resolved this one already. Just wanted to flag that the TTM is Trailing Twelve Months, it's not quarterly information. You can use my pull request (https://github.com/ranaroussi/yfinance/pull/776) to grab this detail from the income statement. Note that the functions are slightly different in my PR, so just run the two lines below (it's all in the README):

msft = yf.Ticker("MSFT")
msft.income_statement

This will bring back those TTM figures. Furthermore, the PR also makes sure that no critical information from the income statement is missed. For example if you pull the income statement using the current version of yfinance for WFC you'll miss out on a lot of the detail (e.g. special charges), the PR I have raised ensures all of this is captured.

**Comment by ValueRaider** [comment]
Fixed in `yfinance` 0.2
