### ISSUE TITLE
Income statement false data

### ISSUE THREAD

**Issue by DavidIsrayelyan** [ranaroussi/yfinance#964]
Hello. 

Im querying data about Wells Fargo & Company (WFC), with yfinance.Ticker('wfc').financials I receive not right "Total Revenue" value, that shown in web page. Please help to find out why is that. 

Thank you.

**Comment by git-shogg** [comment]
Would recommend taking a look at my pull request. Works fine for the income statement of WFC. 
Cheers,
https://github.com/ranaroussi/yfinance/pull/776

**Comment by DavidIsrayelyan** [comment]
I will check it up, thank you. 
Cheers.

**Comment by Leemur312** [comment]
ppl help plz to buy a wells fargo card

**Comment by ValueRaider** [comment]
Fixed in `yfinance` 0.2
