### ISSUE TITLE
List of tickers based on exchange?

### ISSUE THREAD

**Issue by Originn** [ranaroussi/yfinance#967]
Would it be possible to exctract a Json format list of all tickers listed on a specific exchange i.e NYSE?

**Comment by asafravid** [comment]
You can download from nasdaqs ftp as csv and convert to json

**Comment by mathieugouin** [comment]
@asafravid Would you mind sharing the link, I'm interested :)

**Comment by asafravid** [comment]
Google it
ftp://ftp.nasdaqtrader.com/
