### ISSUE TITLE
Not pulling previous day historical data -y finance

### ISSUE THREAD

**Issue by focussedmonk** [ranaroussi/yfinance#969]
My algo is not pulling the previous day historical price thru yfinance.

So checked the yahoo historical data and they seem to miss the previous data on the website as well.
The same happened yesterday....seems like a repetitive issue...

Kindly fix.

Below is data from yahoo finance missing previous day data:"

(https://query1.finance.yahoo.com/v7/finance/download/NATIONALUM.NS?period1=1615958847&period2=1647494847&interval=1d&events=history&includeAdjustedClose=true)

Date	Open	High	Low	Close*	Adj Close**	Volume
Mar 17, 2022	118.20	118.90	114.00	114.10	114.10	10,319,978
Mar 16, 2022	-	-	-	-	-	-
Mar 15, 2022	116.70	116.70	112.75	113.65	113.65	27,015,131
Mar 14, 2022	122.00	122.90	116.70	117.75	117.75	18,735,248
Mar 11, 2022	122.55	125.40	121.35	121.90	121.90	21,491,624

**Comment by focussedmonk** [comment]
Looks like a different kind of problem now....the last traded session is repeating twice (March 17th)
The data reader is able to pull data **only till the 16th** and NOT the 17th.....! 

Below is a sample for Hindalco.ns
But same for all stocks .....

Date | Open | High | Low | Close* | Adj Close** | Volume
-- | -- | -- | -- | -- | -- | --
Mar 17, 2022 | 575.05 | 584.40 | 573.85 | 576.80 | 576.80 | 11,579,157
Mar 17, 2022 | 575.05 | 584.40 | 573.85 | 576.80 | 576.80 | 11,581,454
Mar 16, 2022 | 568.70 | 575.40 | 563.30 | 572.70 | 572.70 | 10,485,661

**Comment by ValueRaider** [comment]
> So checked the yahoo historical data and they seem to miss the previous data on the website as well.

yfinance only returns what Yahoo has. If Yahoo is missing data then nothing yfinance can do.

> the last traded session is repeating twice (March 17th)

Was this happening on Yahoo website?
