### ISSUE TITLE
Last traded session repeating twice...data reader is NOT able to pull last traded session price hence

### ISSUE THREAD

**Issue by focussedmonk** [ranaroussi/yfinance#974]
....the last traded session is repeating twice (March 17th)
The data reader is able to pull data only till the 16th and NOT the 17th.....!

Below is a sample for Hindalco.ns
But same for all stocks .....

Date	Open	High	Low	Close*	Adj Close**	Volume
Mar 17, 2022	575.05	584.40	573.85	576.80	576.80	11,579,157
Mar 17, 2022	575.05	584.40	573.85	576.80	576.80	11,581,454
Mar 16, 2022	568.70	575.40	563.30	572.70	572.70	10,485,661

**Comment by ValueRaider** [comment]
Does this still happen?
