### ISSUE TITLE
Can threads be used while using Ticker module?

### ISSUE THREAD

**Issue by Originn** [ranaroussi/yfinance#975]
I have the following function:

```
`def lookup(symbol):
    try:
        keys=['shortName', 'regularMarketPrice', 'symbol']
        filtered_response={k:yf.Ticker(symbol).stats()["price"].get(k) for k in keys}
        return filtered_response
    except (KeyError, TypeError, ValueError):
        return None`
```

which will take 3 seconds to perform on each symbol. I am trying to use concurrent.futures but it got messy. Is there a native way to use threads in this module?

Raised the question here as well
https://stackoverflow.com/questions/71561088/multiprocessing-issue-using-concurrent-futures?noredirect=1#comment126479033_71561088

**Comment by Originn** [comment]
I am trying to think of a way to do it faster then, maybe by only taking regularMarketPrice, and cache the shortName and symbol per session. This will cut the time by a third. The issue is that the website will load slowly if I have multiple stocks on my index page (think of a portfolio that is updating the price using the function above). Would you think it's possible using import requests_cache?

**Comment by aspenforest** [comment]
Might wanna take a look at [YFrake](https://github.com/aspenforest/yfrake). It can perform 2000 requests in 1.5 seconds. Would recommend manual throttling through, to prevent getting blacklisted as @asafravid said.

**Comment by asafravid** [comment]
Sounds interesting 
You can try that
I agree that a lot of information is redundant and static for that matter so coaching can help but eventually this is html parsing 
So if a cache mechanism exists and you can utilize it Thereof creating a feature for yfinance with a pull request that can be blessed

keep us posted

**Comment by Originn** [comment]
I will definitely think on the cache idea of static info. 

YFrake looks intresting and I need to look into it further. Can it be used to gather the three values mentioned above 'shortName', 'regularMarketPrice', 'symbol' ?

**Comment by aspenforest** [comment]
@Originn are you using Python 3.10?

**Comment by asafravid** [comment]
Hey @aspenforest YFrakes looks super duper cool! I’m studying it to incorporate in my open source stock scanner https://github.com/asafravid/sss

nice work and will be in touch with you 🙏🏼

**Comment by Originn** [comment]
@aspenforest I don't think it's the issue, I am using Python 3.9.10.

**Comment by aspenforest** [comment]
@Originn allow me to reiterate, that YFrake does *not* work on *any* Python version lower than 3.10, that includes 3.9.10. It does not matter how recent the release was. It matters what PEP-s it supports. There is nothing more I can say to make it work for you.
