### ISSUE TITLE
Date range not consistant

### ISSUE THREAD

**Issue by edisomsz** [ranaroussi/yfinance#978]
Hello, I have a date inconsistency
```
all_tickers_list = ["ACP.WA", "AAPL"]
df = yf.download(all_tickers_list, start = "2022-03-30")
data = df['Close']
```

gives:
```
                  AAPL     ACP.WA
Date
2022-03-29  178.960007        NaN
2022-03-30  177.770004  80.849998
2022-03-31  176.759995  80.650002
```

When data is downloaded separately ACP.WA starts properly on 30, whereas AAPL starts on 29. What could be the case?

**Comment by ValueRaider** [comment]
I'm testing a timezone fix, it should address your issue: https://github.com/ValueRaider/yfinance/tree/fix/timezone

You'll have to play with `sys.path.insert` to load this over PIP. Give it a play.

**Comment by ValueRaider** [comment]
Fix is now in PIP
