### ISSUE TITLE
How to disable progress of download

### ISSUE THREAD

**Issue by kf6spf** [ranaroussi/yfinance#979]
When running a set of tickers through the download function it generates a progress bar. Is there a simple "Off" switch of variable setting to disable this so it downloads silently?

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

**Comment by vic-sua** [comment]
Using 'progress = False' when calling the function should solve this issue.

**Comment by kf6spf** [comment]
Ah! Thanks!
