### ISSUE TITLE
Yfinance period='Max' option bug

### ISSUE THREAD

**Issue by LucGuj** [ranaroussi/yfinance#980]
The yfinance version 0.1.70 shows a bug when it comes to download historical data using the period='max' option. In fact if I run the code below I get data starting from 1950 while the data go back to 1928 (colab link: https://colab.research.google.com/drive/1eByqpQGTxKH7KmYUy-FDri6HyYALKzzw#scrollTo=spxN65Qi4EJ4). As further validation if I run the same code using yfinance 0.1.63 I get the proper historical data starting from 1928 (colab link: https://colab.research.google.com/drive/1XvUF6ngMskT-aKduMTi_jgsvsRvSYLz_#scrollTo=iR3GS3f9kU3D) 

```
import yfinance as yf

ticker = '^GSPC'
Stock = yf.Ticker(ticker)
Stock_Data = Stock.history(period="max",auto_adjust = False)

Stock_Data
```

![image](https://user-images.githubusercontent.com/14195165/161288556-99482bb5-fe2e-48d2-af79-ca5ee89dd74f.png)

![image](https://user-images.githubusercontent.com/14195165/161288758-de167003-313a-4b2e-863a-26c213c8bb3f.png)

Thanks in advance for your support and help
Luca

**Comment by ppeloton** [comment]
Raised https://github.com/ranaroussi/yfinance/pull/1169 request to fix issue
