### ISSUE TITLE
Is this repo archived?

### ISSUE THREAD

**Issue by julianwagle** [ranaroussi/yfinance#981]
There are over 400 issues right now and there haven't been any meaningful updates all year. Is this an archived repo and if so, who has the best fork for project continuity?

**Comment by aspenforest** [comment]
@julianwagle check out [yfrake](https://github.com/aspenforest/yfrake).
It is also a Yahoo market data scraper, but on steroids. It's not a fork of yfinance, because yfinance codebase was too messy for me to try to clean up.

**Comment by ValueRaider** [comment]
@julianwagle This looks like only fork with recent updates: https://pypi.org/project/yfinance-ez . I'm going to switch soon and probably contribute some PRs.

**Comment by ValueRaider** [comment]
@julianwagle I have been given permissions to merge PRs etc, so can start working through backlog. But I would greatly appreciate help reviewing, critiquing etc. Anyone can assign themselves to PRs and suggest changes.
