### ISSUE TITLE
Multiple-thread problem

### ISSUE THREAD

**Issue by simon0057** [ranaroussi/yfinance#982]
I used the below codes for pulling multiple stocks data. It worked well before, but recently the loading bar is paused with no error message. It just stop and seems no response at all.
I tried many times, and every-time it stops at different stock codes.
How can I fix it..?

ticker_list = ['AAPL', 'ABBV', 'ABC', 'ABMD', 'ABNB', 'ABT',....]  

for ticker in tqdm(ticker_list):
    df= yf.Ticker(ticker)
    df_history = df.history(start='2021-01-01', end = '2022-12-31')
    print(ticker)
....

Results:
AAPL 
  0%|▍        | 1/682 [00:00<02:57,  3.84it/s
ABBV
  0%|▊         | 2/682 [00:00<02:18,  4.90it/s
ABC
  0%|█▏     | 3/682 [00:00<02:08,  5.29it/s]

**Comment by PinkZanny** [comment]
Hi @simon0057 , this used to happen to me whenever there were problems with the connection/data retrievement process. Try to debug it by first eliminating the progress bar (I use alive_bar, which cannot detect error inputs such as "No data found for the Ticker: X"), then use a try/except statement to jump over errors, I'll provide an example to you:
`for ticker in tqdm(ticker_list):
        try:
                df=yf.Ticker(ticker)
                df_history=df.history(start='startdate', end='enddate')
                print(ticker)
       except:
                print("Ticker:", ticker, "error.")`

Or else you could directly redirect the loop by cleaning data in realtime.
