### ISSUE TITLE
Downloading muliple data stuck at 98/99%

### ISSUE THREAD

**Issue by cheungcn** [ranaroussi/yfinance#983]
Has anyone experience this in these few days?
No matter I download 100/200/etc nos of stock data. 
The progress bar always stucks at 98/99%.  The initial download speed is quite fast

Anyone has idea why it happens?

**Comment by tmsnc** [comment]
I have the same issue here, version  0.1.70

**Comment by saurabh502** [comment]
same issue

**Comment by ValueRaider** [comment]
If still a problem can someone post actual code to reproduce problem.
