### ISSUE TITLE
Dividend Dates not showing up all of the time

### ISSUE THREAD

**Issue by dmichaels713** [ranaroussi/yfinance#984]
When using yf.Ticker(symbol), dividend dates are not showing up all of the time for stocks with dividends, for example MSFT or SRCE.

When this happens, the field ticker.info['lastDividendDate'] simply does not exist.  Furthermore, when this happens, ticker.actions does not have the correct list of Dividend dates.  Some are randomly missing.  This is a huge problem if you're using this module to scan for dividend stocks.  

While it does not happen 100% of the time, if you try running yf.Ticker(symbol) many times in a row for the same symbol, you will definitely get this error, so it's easy to replicate.

**Comment by ValueRaider** [comment]
> running yf.Ticker(symbol) many times in a row

Yahoo goes funny when you spam it.

**Comment by doktor99** [comment]
there is no question from my testing that @ValueRaider is correct. i'm working on code which autodetects these missing dividends. what's interesting is that the adjusted closing price calculations appear to be correct as-if the dividends were missing. at this point, i suspect redundant time-delayed calls to yfinance will be required to have sufficient certainty.

**Comment by ValueRaider** [comment]
Try yfinance-cache + rate limiter
