### ISSUE TITLE
The data for the minute interval is consistently "wrong". It rarely ever matches the historical data when you set intervals for 1 day / 1 hour etc... Is there a way to make the minute intervals more accurate?

### ISSUE THREAD

**Issue by cvjin741** [ranaroussi/yfinance#987]
The data for the minute interval is consistently "wrong". It rarely ever matches the historical data when you set intervals for 1 day / 1 hour etc... Is there a way to make the minute intervals more accurate? 

Also, how does it make sense that the data is not matching, when we're supposedly pulling from the same historical data set, but only changing the interval that it is being pulled from? 1 minute vs 1 hour vs 1 day

To clarify further: For example, when you look at the opening and closing price for a specific ticker, it will reflect what's on yahoo finance's historical data section. However, if you look at the data you pulled using 1 minute intervals for 9:29 AM, 9:30 AM, 9:31 AM  it will not match the opening price on the historical data. Same with closing price.... if you look at the 1 minute data for closing price at 4:29 PM, 4:30 PM, and 4:31 PM none of them will match. It only matches sometimes.... and it doesn't matter if you're using adj_close, close, high, or low. They are simply just wrong, which makes no sense to me, since it should be pulling from the same historical data set, no?

**Comment by ValueRaider** [comment]
Can you create a script to reproduce issue exactly, easier to see the difference. Then we can also cross-check against stock exchange.
