### ISSUE TITLE
Error: list index out of range

### ISSUE THREAD

**Issue by berzrekeley** [ranaroussi/yfinance#988]
I get an error (list index out of range) when I tried to use the functions

import yfinance as yf

ticker = 'FB'

balancesheet = get_balance_sheet(ticker)
income_statement = get_income_statement(ticker)
cash_flow = get_cash_flow(ticker)
analyst = get_analysts_info(ticker)

**Comment by berzrekeley** [comment]
This is the error that I get.

IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_19672/1026670729.py in <module>
----> 1 balancesheet = get_balance_sheet(ticker)
      2 income_statement = get_income_statement(ticker)
      3 cash_flow = get_cash_flow(ticker)
      4 analyst = get_analysts_info(ticker)

~\anaconda3\lib\site-packages\yahoo_fin\stock_info.py in get_balance_sheet(ticker, yearly)
    438 
    439 
--> 440     json_info = _parse_json(balance_sheet_site)
    441 
    442     try:

~\anaconda3\lib\site-packages\yahoo_fin\stock_info.py in _parse_json(url, headers)
    371     html = requests.get(url=url, headers = headers).text
    372 
--> 373     json_str = html.split('root.App.main =')[1].split(
    374         '(this)')[0].split(';\n}')[0].strip()
    375 

IndexError: list index out of range

**Comment by devfinwiz** [comment]
Refer this repository: https://github.com/devfinwiz/Stock_Screeners

**Comment by ValueRaider** [comment]
Ticker 'FB' doesn't exist.
