### ISSUE TITLE
Yahoo Finance Forex Daily Historical Close Price Discrepancy   

### ISSUE THREAD

**Issue by JamesPooleFX** [ranaroussi/yfinance#991]
Hi there, I’m in the process of learning to trade Forex, and am using Yahoo Finance/yfinance to retrieve currency OHLC historic rates.

For the most part it provides everything I need, however, when it comes to daily data (1d) Yahoo Finance seems to adjust the closing price back the opening price at the end of each daily trading bar (see https://yhoo.it/3kb4mUD). 

I appreciate this isn’t a yfinance issue per se, but I was wondering if anyone could shed any light on it, as I’ve been unable to determine this behaviour? Note, all other timeframes (e.g. 30m, 1h, 4h) don’t appear to suffer the same issue.

Thanks

**Comment by ValueRaider** [comment]
Disable `auto_adjust` (see readme). More info on how Yahoo adjusts: http://marubozu.blogspot.com/2006/09/how-yahoo-calculates-adjusted-closing.html

**Comment by Karlheinzniebuhr** [comment]
Found the same issue https://github.com/ranaroussi/yfinance/issues/1075

**Comment by ValueRaider** [comment]
See #1071
