### ISSUE TITLE
No data found for this date range, symbol may be delisted(July 26th,2022): But, it works again now

### ISSUE THREAD

**Issue by LeeChunley** [ranaroussi/yfinance#998]
I run yfiance codes, and it went well before!
Also, I checked the same Issues which other friends talked about. It is not helpful.
My codes as fellow:

StartDate="2022-05-16"
EndDate="2022-05-23"

SYMBOL="QQQ"
data=yf.Ticker(SYMBOL)

DATE_CHECK=data.history(interval="1m",start=StartDate,end=EndDate)

print(DATE_CHECK)
sys.exit(0)

Errors show as fellow:

- QQQ: No data found for this date range, symbol may be delisted
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume, date]
Index: []
[Finished in 2.1s]

Somebody to help me?

**Comment by Arrjaan** [comment]
Same problem, used to work but currently I am unable to fetch historical data.

**Comment by Arrjaan** [comment]
Update: I am using eventlet. Including these lines at the start of the document solved this problem for me:

import eventlet
eventlet.monkey_patch()

**Comment by LeeChunley** [comment]
> Update: I am using eventlet. Including these lines at the start of the document solved this problem for me:
> 
> import eventlet eventlet.monkey_patch()

Hi, Arrjaan,

**Comment by Arrjaan** [comment]
It seems the problem lies in your code, not in the yfinance package. If I run a separate file with just your code it works as intended. You might need to review the rest of your code to figure out why it is not working.

**Comment by LeeChunley** [comment]
> It seems the problem lies in your code, not in the yfinance package. If I run a separate file with just your code it works as intended. You might need to review the rest of your code to figure out why it is not working.

Thanks again!
I attach a photo of my all codes about this!

**Comment by lyj0209** [comment]
Hey I confronted the same problem and i suppose it is because Yahoo Finance can never be accessible in China mainland any more.

**Comment by LeeChunley** [comment]
> Hey I confronted the same problem and i suppose it is because Yahoo Finance can never be accessible in China mainland any more.

Hi, thanks!
You supposed? Did u get messages? U have proved it?

**Comment by lyj0209** [comment]
Yes when U visit the Yahoo Finance from China Mainland U will see the notification.



发自我的iPhone


------------------ Original ------------------
From: LeeS ***@***.***&gt;
Date: Wed,Jun 8,2022 0:06 PM
To: ranaroussi/yfinance ***@***.***&gt;
Cc: lyj0209 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [ranaroussi/yfinance] No data found for this date range, symbolmay be delisted(Jun 8th,2022) (Issue #998)





  
Hey I confronted the same problem and i suppose it is because Yahoo Finance can never be accessible in China mainland any more.
  
Hi, thanks!
 You supposed? Did u get messages? U have proved it?

**Comment by cecil0221** [comment]
Hi, I'm facing the same issue. Looks like it might be a problem in China Mainland. Even though I connect to a VPN using proxy mode, I still fetch nothing using yfinance and pandas-datareader.

I can browse Yahoo Finance with VPN but not working for Python libraries. Anyone has better ideas?

**Comment by LeeChunley** [comment]
Thanks Arrjaan, lyi0209, cecil0221!

**Comment by LeeChunley** [comment]
Hi, every one here!
1 minute data, it works again @ yfinance. I don't know way!
Thank for you all!

**Comment by alitrack** [comment]
@LeeChunley 
still need proxy, right?

**Comment by tyePhDCandy** [comment]
I'm from mainland, china. I understand yahoo finance could only be accessed by vpn.
So, I add proxy parameter to my code. But , still the error persists " No data found for this date range, symbol may be delisted"
```python
import pandas_datareader as web
import yfinance as yf
import datetime as datetime
data = yf.download("IBM", start="2022-04-10", end="2022-05-11", threads=False, proxy="http://127.0.0.1:7890")
print(data)
```
The output text is as follows.
```text
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- IBM: No data found for this date range, symbol may be delisted
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []
```

**Comment by ValueRaider** [comment]
This is a bug, proxy handling was broken in many places. Can you try branch `hotfix/proxy` and report back.

**Comment by dkdk-ddk** [comment]
@ValueRaider @tyePhDCandy 
The fixed branch seems to have solved this issue.
I checked the implementation, this was indeed caused by mssing `proxy` param in requests.get()

**Comment by tyePhDCandy** [comment]
thanks ! good news !  i will try it, when i have time.

**Comment by ValueRaider** [comment]
Can someone try `Ticker.isin` specifically, we're not sure it works with proxy #1399
